### ISSUE TITLE
刷完后直接报错, 跑作者的example也一样

### ISSUE THREAD

**Issue by mzF414** [xuelongqy/flutter_easyrefresh#10]
我的是flutter1.0版本, 夜神模拟器. 跑作者的example也一样...

**Comment by xuelongqy** [comment]
能贴出错误日志吗

**Comment by mzF414** [comment]
之前有报错日志, 后来没有了, 但是页面应该已经假死了, 下拉或者上拉都拉不动了

**Comment by xuelongqy** [comment]
没有日志我也很难帮到你啊。真机有试过吗？三方模拟器不稳定的因素会很多

**Comment by xuelongqy** [comment]
你加下QQ群吧

**Comment by xuelongqy** [comment]
这应该是flutter的问题，对第三方模拟器支持不好
