### ISSUE TITLE
在BasicPage中你的更新时间怎么来的？

### ISSUE THREAD

**Issue by IPOSDai** [xuelongqy/flutter_easyrefresh#101]
Widget getListView() => EasyRefresh(
    behavior: ScrollOverBehavior(),
    refreshHeader: ClassicsHeader (
      key: _easyRefreshKey,
      refreshText: "下拉刷新",
      refreshReadyText: "释放刷新",
      refreshingText: "刷新中...",
      refreshedText: "刷新完毕",
      moreInfo: "更新于",
      bgColor: Colors.transparent,
      textColor: Colors.black87,
      moreInfoColor: Colors.black54,
      showMore: true,
    ),
    child: ListView.builder(
      itemCount: widgets.length,
      itemBuilder: (BuildContext context, int index) {
        return getRow(index);
      },
    ),
    onRefresh: () async {
      await loadData();
    },
  );
这个没有时间，这个是自己添加的吗

**Comment by QQLaoMing** [comment]
同问

**Comment by xuelongqy** [comment]
包含%T会替换为时间
