### ISSUE TITLE
代码跑不起来  AlipayZeroSdk:1.1

### ISSUE THREAD

**Issue by wugj** [xuelongqy/flutter_easyrefresh#102]
> Could not resolve moe.feng:AlipayZeroSdk:1.1.
  Required by:
      project :app
   > Could not resolve moe.feng:AlipayZeroSdk:1.1.
      > Could not get resource 'http://repo.spring.io/libs-release/moe/feng/AlipayZeroSdk/1.1/AlipayZeroSdk-1.1.pom'.
         > Could not GET 'http://repo.spring.io/libs-release/moe/feng/AlipayZeroSdk/1.1/AlipayZeroSdk-1.1.pom'. Received status code 401 from server: Unauthorized
   > Could not resolve moe.feng:AlipayZeroSdk:1.1.
      > Could not get resource 'https://jitpack.io/moe/feng/AlipayZeroSdk/1.1/AlipayZeroSdk-1.1.pom'.
         > Could not GET 'https://jitpack.io/moe/feng/AlipayZeroSdk/1.1/AlipayZeroSdk-1.1.pom'.
            > Connect to jitpack.io:443 [jitpack.io/104.24.22.62, jitpack.io/104.24.23.62] failed: Connection timed out: connect

**Comment by wugj** [comment]
mistake

**Comment by xuelongqy** [comment]
v2版本已重构
