### ISSUE TITLE
ClassicsFooter 一直是展示 moMoreText

### ISSUE THREAD

**Issue by dingzuhua** [xuelongqy/flutter_easyrefresh#105]
LoadedText and noMoreText are set in ClassicsFooter, but the display is always noMoreText. How is this display controlled?

**Comment by serge66** [comment]
+1

**Comment by 982991084** [comment]
+1

**Comment by LsFern** [comment]
+1

**Comment by xuelongqy** [comment]
请了解异步原理。v2版本已重构
