### ISSUE TITLE
如果是嵌套在NestedScrollView中的话会出现滑动冲突问题

### ISSUE THREAD

**Issue by KarenKaKa** [xuelongqy/flutter_easyrefresh#11]

**Comment by xuelongqy** [comment]
你翻翻之前的Issues，有提到过这个

**Comment by xuelongqy** [comment]
出现冲突是因为NestedScrollView的child设置controller后，会导致分离控制，EasyRefresh需要使用controller去控制列表。不好意思之前那个Issues，被提问者删除了。你可以使用CustomScrollView去达到和NestedScrollView一样的效果，NestedScrollView的内部实现就是使用的CustomScrollView。你可以参考示例[SliverPage](https://github.com/xuelongqy/flutter_easyrefresh/blob/master/example/lib/page/sample/sliver_page.dart)

**Comment by KarenKaKa** [comment]
嗯嗯，抱歉刚看到，我已经用CustomScrollView解决了，谢谢！

**Comment by xuelongqy** [comment]
1.2.4已经可以支持NestedScrollView了，你可以参考示例[NestedScrollViewPage](https://github.com/xuelongqy/flutter_easyrefresh/blob/master/example/lib/page/sample/nested_scroll_view_page.dart)

**Comment by haolizi** [comment]
> 嗯嗯，抱歉刚看到，我已经用CustomScrollView解决了，谢谢！

老哥，你是怎么使用CustomScrollView嵌套TabBarView的？
