### ISSUE TITLE
有时会出现无法滑动的情况，你们遇到过吗？

### ISSUE THREAD

**Issue by blockmood** [xuelongqy/flutter_easyrefresh#112]

**Comment by king163** [comment]
我也遇到了 严格按照这个顺序就会出错 1、 enable下拉刷新 enable加载更多 然后disable下拉刷新，2、先下拉刷新一把（disable掉了） 然后在上拉加载更多（预期是enable的 结果也disable掉了） 3、最后enable下拉刷新 enable加载更多 结果都不成功了

**Comment by xuelongqy** [comment]
v2版本已重构
