### ISSUE TITLE
v2版本能不能给首次刷新加上

### ISSUE THREAD

**Issue by zhangruiyu** [xuelongqy/flutter_easyrefresh#116]
目前已经在用v2了 ,虽然刷新头没有,但是能用,但是firstrefresh 不加上 我这边逻辑就会和v2最终版的不一致

**Comment by xuelongqy** [comment]
会慢慢加的，v2还不成熟，不建议商用哈

**Comment by zhangruiyu** [comment]
目前不上线 要几个月呢  但是说能不能优先添加和这个功能  0-0因为这样 等你发布release版本后 我除了添加head样式 不需要再修改代码逻辑了

**Comment by xuelongqy** [comment]
好的，我会优先安排在日程上。基本原理基本实现了，后面就是扩展和样式了

**Comment by zhangruiyu** [comment]
谢谢老哥

**Comment by xuelongqy** [comment]
首次刷新已添加

**Comment by zhangruiyu** [comment]
![image](https://user-images.githubusercontent.com/10591822/61858726-3cb38b00-aef9-11e9-9a18-7809f514deee.png)
![image](https://user-images.githubusercontent.com/10591822/61858746-4b01a700-aef9-11e9-84ae-359011d7cb08.png)
其他页面没事,但是搭配了IndexedStack好像不行了  还有firstRefreshWidget虽然展示,但是说刷新结束后head会展示说完成
