### ISSUE TITLE
ClassicsHeaderState dispose销毁顺序错误

### ISSUE THREAD

**Issue by jasonrongdevelop** [xuelongqy/flutter_easyrefresh#118]
I/flutter (31833): ══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
I/flutter (31833): The following assertion was thrown while finalizing the widget tree:
I/flutter (31833): ClassicsHeaderState#85db1(tickers: tracking 2 tickers) was disposed with an active Ticker.
I/flutter (31833): ClassicsHeaderState created a Ticker via its TickerProviderStateMixin, but at the time dispose() was
I/flutter (31833): called on the mixin, that Ticker was still active. All Tickers must be disposed before calling
I/flutter (31833): super.dispose(). Tickers used by AnimationControllers should be disposed by calling dispose() on the
I/flutter (31833): AnimationController itself. Otherwise, the ticker will leak.
I/flutter (31833): The offending ticker was: _WidgetTicker(created by ClassicsHeaderState#85db1(lifecycle state:
I/flutter (31833): created, tickers: tracking 0 tickers))

```
 @override
  void dispose() {
    super.dispose();
    _readyController.dispose();
    _restoreController.dispose();
  }

```
AnimationControllers销毁应该在super.dispose之前

**Comment by xuelongqy** [comment]
v2版本已重构
