### ISSUE TITLE
集成刷新控件之后，滚动条消失了

### ISSUE THREAD

**Issue by leozhuo** [xuelongqy/flutter_easyrefresh#119]
没加载刷新控件前，滑动是有滚动条的，加载之后滚动条就消失了，你们有遇过吗`@override
  Widget buildPage(BuildContext context) {
    // TODO: implement buildPage
    // TODO: 添加滚动条
    return new EasyRefresh(
      refreshHeader: BallPulseHeader(key: _headerKey),
      refreshFooter: BallPulseFooter(key: _footerKey),
        child: Scrollbar(
            child: SingleChildScrollView(
                scrollDirection: Axis.vertical,
                child: Container(`

**Comment by xuelongqy** [comment]
请使用v2版本
