### ISSUE TITLE
Demo与模拟器的兼容问题, 只有第一次能下拉刷新

### ISSUE THREAD

**Issue by FreeLoopC** [xuelongqy/flutter_easyrefresh#12]
在夜神模拟器5.1上面运行demo, BasicPage只有第一次能下拉刷新, 真机上没有此现象.
以为代码有误, 鼓捣了半天, 发现了这个问题, 给后面的同志提个醒儿

**Comment by xuelongqy** [comment]
我只有使用自带的模拟器运行Flutter项目成功过。三方模拟器无法打开Flutter应用，不知道为什么

**Comment by xuelongqy** [comment]
这应该是flutter的问题，对第三方模拟器支持不好
