### ISSUE TITLE
RefreshCallback和系统的冲突了。

### ISSUE THREAD

**Issue by jendy2012** [xuelongqy/flutter_easyrefresh#120]
import 'package:flutter/material.dart';

Error: 'RefreshCallback' is imported from both 'package:flutter_easyrefresh/src/header/refresh_indicator.dart' and 'package:flutter/src/material/refresh_indicator.dart'.

当有空视图的时候。正常内容不显示 
空视图(当不为null时,只会显示空视图)
emptyWidget

new EasyRefresh(
          firstRefresh: false,
          header: TaurusHeader(),
          emptyWidget:new Text('测试'),
          onRefresh: () {
            
          },
          child:
          new Column(
            children: [],
          ),
        ),
之前不是自动判断没有加载到数据或者页面加载中才会显示空视图么？
现在要自己判断？

**Comment by xuelongqy** [comment]
v2版本已经重构，请查看相应示例，文档中已经说明。由于自动判断不友好，代码不规范会出现不准确。所以修改为为null时,只会显示空视图，设置为null就不会再显示了。冲突可以使用别名或者屏蔽的方式解决，下一个版本会进行修改

**Comment by xuelongqy** [comment]
v2.0.1已修复
