### ISSUE TITLE
v2问题

### ISSUE THREAD

**Issue by mcxinyu** [xuelongqy/flutter_easyrefresh#121]
使用全局 header 和 footer：
1、下拉刷新进程不会触发状态的改变，例如一直显示向下箭头和“下拉刷新”字样，正常情况下应该变成“释放刷新”。
2、有时又会变成下拉还没松手自动就刷新了。
3、下拉时系统必然报错：

> I/flutter ( 5756): Another exception was thrown: 'package:flutter/src/rendering/box.dart': Failed assertion: line 1692 pos 18: 'debugDoingThisResize || debugDoingThisLayout ||
I/flutter ( 5756): Another exception was thrown: 'package:flutter/src/rendering/box.dart': Failed assertion: line 1692 pos 18: 'debugDoingThisResize || debugDoingThisLayout ||
I/chatty  ( 5756): uid=10350(com.sxmd.tornado.host) Thread-7 identical 2 lines

4、加载更多的情况下，会 overflowed。
5、加载更多，当没有更多之后，无法在显示footer，同时 header 也无法触发刷新。

还没测试使用自定义 header 和 footer 的情况。

**Comment by mcxinyu** [comment]
以上有些问题可以在“swiper”demo 中得到复现

**Comment by xuelongqy** [comment]
Swiper示例中忘了加ScrollNotificationInterceptor，这是用来解决滚动冲突的

**Comment by xuelongqy** [comment]
3、4、5的问题暂时没发现，你可以提供一下你的示例代码

**Comment by mcxinyu** [comment]
好，我再找时间按demo试一下，有问题我再给下代码。问题先不关闭，3Q~

**Comment by xuelongqy** [comment]
第四点已修复，第五点可以参考基本示例的没有更多处理
