### ISSUE TITLE
EasyRefresh.custom 怎么放TabBarView

### ISSUE THREAD

**Issue by niugengyun** [xuelongqy/flutter_easyrefresh#124]
我的代码放上去之后，页面向下滚动时 tabbar没效果，能否给个demo

viewService.buildComponent('search'),  是一个SliverAppBar
![image](https://user-images.githubusercontent.com/4466086/62511685-69479b00-b847-11e9-829d-ddd90e48d932.png)

**Comment by xuelongqy** [comment]
使用SliverAppBar或者参考NestedScrollView示例
