### ISSUE TITLE
AB都有第一次刷新的页面，A跳B再返回A，就报错了。

### ISSUE THREAD

**Issue by bibi-Android** [xuelongqy/flutter_easyrefresh#126]
AB都有第一次刷新的页面，A跳B再返回A，就报错了。

**Comment by bibi-Android** [comment]
如果不要第一次刷新，就没有报错

**Comment by xuelongqy** [comment]
我这边测试了，没有问题。你看看是不是其他情况导致的，比如StreamBuilder的情况，以为已经不是初次数据。我很好奇的是为什么要把firstRefresh和StreamBuilder一起使用，这样不会出现冲突吗？毕竟都是用在初始情况下
