### ISSUE TITLE
Demo 无法运行

### ISSUE THREAD

**Issue by LeoDicaprio** [xuelongqy/flutter_easyrefresh#129]
`Compiler message:
file:///Users/newmac/Documents/Flutter/flutter_downloads/flutter/.pub-cache/hosted/pub.flutter-io.cn/flare_flutter-1.5.4/lib/flare.dart:1027:18: Error: The argument type 'Uint16List' can't be assigned to the
parameter type 'Int32List'.
 - 'Uint16List' is from 'dart:typed_data'.
 - 'Int32List' is from 'dart:typed_data'.
Try changing the type of the parameter, or casting the argument to 'Int32List'.
        indices: _indices, textureCoordinates: _uvBuffer);
                 ^
file:///Users/newmac/Documents/Flutter/flutter_downloads/flutter/.pub-cache/hosted/pub.flutter-io.cn/extended_nested_scroll_view-0.3.6/lib/src/nested_scroll_view_refresh_indicator.dart:373:24: Error: Method not
found: 'ErrorDescription'.
              context: ErrorDescription('when calling onRefresh'),
                       ^^^^^^^^^^^^^^^^
file:///Users/newmac/Documents/Flutter/flutter_downloads/flutter/.pub-cache/hosted/pub.flutter-io.cn/extended_nested_scroll_view-0.3.6/lib/src/nested_scroll_view_refresh_indicator.dart:373:24: Error: The method
'ErrorDescription' isn't defined for the class 'NestedScrollViewRefreshIndicatorState'.
 - 'NestedScrollViewRefreshIndicatorState' is from 'package:extended_nested_scroll_view/src/nested_scroll_view_refresh_indicator.dart'
 ('file:///Users/newmac/Documents/Flutter/flutter_downloads/flutter/.pub-cache/hosted/pub.flutter-io.cn/extended_nested_scroll_view-0.3.6/lib/src/nested_scroll_view_refresh_indicator.dart').
Try correcting the name to the name of an existing method, or defining a method named 'ErrorDescription'.
              context: ErrorDescription('when calling onRefresh'),
                       ^^^^^^^^^^^^^^^^
Compiler failed on /Users/newmac/Desktop/flutter_easyrefresh-2/example/lib/main.dart
Error launching application on iPhone Xʀ.`

**Comment by LeoDicaprio** [comment]
找到原因了，是因为我使用的是flutter一个测试版本，升级flutter就好了。但是升级之后，使用iOS模拟器也运行不了？请问是不支持模拟器吗？
error: Multiple commands produce '/Users/newmac/Desktop/flutter_easyrefresh-2/example/build/ios/Debug-iphonesimulator/Runner.app/Frameworks/Flutter.framework':
    1) Target 'Runner' has copy command from '/Users/newmac/Desktop/flutter_easyrefresh-2/example/ios/Flutter/Flutter.framework' to
    '/Users/newmac/Desktop/flutter_easyrefresh-2/example/build/ios/Debug-iphonesimulator/Runner.app/Frameworks/Flutter.framework'
    2) That command depends on command in Target 'Runner': script phase “[CP] Embed Pods Frameworks”
    warning: The use of Swift 3 @objc inference in Swift 4 mode is deprecated. Please address deprecated @objc inference warnings, test your code with “Use of deprecated Swift 3 @objc inference” logging enabled,
    and then disable inference by changing the "Swift 3 @objc Inference" build setting to "Default" for the "Runner" target. (in target 'Runner')
    warning: ignoring duplicated output file: '/Users/newmac/Desktop/flutter_easyrefresh-2/example/build/ios/Debug-iphonesimulator/Runner.app/Frameworks/Flutter.framework' in shell script build phase '[CP] Embed
    Pods Frameworks'. This warning represents an extremely serious project misconfiguration and will likely cause some shell scripts in your project to be skipped entirely, leading to other build failures or
    missing files in the build directory. This will be a hard error in the future. (in target 'Runner')
    note: Using new build systemnote: Planning buildnote: Constructing build description

**Comment by xuelongqy** [comment]
我也没测试过，理论来说不会出现这个问题吧

**Comment by LeoDicaprio** [comment]
@xuelongqy 还是我的问题，应该是因为我没有配置iOS账号的原因。我使用了安卓模拟器是可以运行的。可以使用flutter doctor检测下。给像我这样的新手小白提示下。
