### ISSUE TITLE
header和footer可否设计成widget类型

### ISSUE THREAD

**Issue by 2534290808** [xuelongqy/flutter_easyrefresh#132]
header和footer可否设计成widget类型?

**Comment by xuelongqy** [comment]
header和footer相当于widget的构造器。为何这样设计，肯定是做了最好的取舍。如果设计为widget就会跟v1一样使用变得复杂，逻辑更乱。快速自定义可以使用CustomHeader

**Comment by Ennotsubasa-ciyuanxiang** [comment]
最新版本根本没有CustomHeader这个东西了
