### ISSUE TITLE
onRefresh中使用RxDart发出请求

### ISSUE THREAD

**Issue by SeongBrave** [xuelongqy/flutter_easyrefresh#133]
onRefresh中使用RxDart发出请求，在这个方法中只管发出请求，然后我监听回调，然后再回调中再重置刷新状态，onRefresh不应该是一个异步方法，我只需要触发一下即可

**Comment by xuelongqy** [comment]
#### 4.控制加载和刷新完成
```dart
  EasyRefreshController _controller = EasyRefreshController();
  ....
  EasyRefresh(
	enableControlFinishRefresh: true,
	enableControlFinishLoad: true,
    ....
  );
  ....
  _controller.finishRefresh(success: true);
  _controller.finishLoad(success： true, noMore: false);
```

**Comment by SeongBrave** [comment]
import 'package:flutter/material.dart';
import 'package:flutter_easyrefresh/easy_refresh.dart';
import 'package:rxdart/rxdart.dart';

class QdPage extends StatefulWidget {
  @override
  _QdPageState createState() {
    return _QdPageState();
  }
}

class _QdPageState extends State<QdPage> {
  EasyRefreshController _controller;
  final refreshSubject = PublishSubject<int>();

  @override
  void initState() {
    super.initState();
    _controller = EasyRefreshController();
  }

  @override
  void dispose() {
    super.dispose();

    refreshSubject.close();
  }

  @override
  Widget build(BuildContext context) {
    refreshSubject.delay(Duration(seconds: 3)).listen((onData) {
      _controller.finishRefresh(success: true);
    });
    return Expanded(
      child: EasyRefresh(
        header: ClassicalHeader(),
        enableControlFinishRefresh: true,
        enableControlFinishLoad: true,
        controller: _controller,
        onRefresh: () {
          refreshSubject.add(12);
          return;
        },
        child: SingleChildScrollView(
          child: Column(
            children: <Widget>[
              Container(
                height: 350,
                color: Colors.red,
              ),
              FlatButton(
                child: Text('data'),
                onPressed: () {
                  _controller.callLoad();
                },
              ),
              Container(
                height: 150,
                color: Colors.blue,
              )
            ],
          ),
        ),
      ),
    );
  }
}

**Comment by xuelongqy** [comment]
一个是callLoad，一个是finishRefresh。当然没有作用啦

**Comment by SeongBrave** [comment]
```
import 'package:flutter/material.dart';
import 'package:flutter_easyrefresh/easy_refresh.dart';
import 'package:rxdart/rxdart.dart';

class QdPage extends StatefulWidget {
  @override
  _QdPageState createState() {
    return _QdPageState();
  }
}

class _QdPageState extends State<QdPage> {
  EasyRefreshController _controller;
  final refreshSubject = PublishSubject<int>();

  @override
  void initState() {
    super.initState();
    _controller = EasyRefreshController();
  }

  @override
  void dispose() {
    super.dispose();

    refreshSubject.close();
  }

  @override
  Widget build(BuildContext context) {
    refreshSubject.delay(Duration(seconds: 3)).listen((onData) {
      _controller.finishRefresh(success: true);
    });
    return Expanded(
      child: EasyRefresh(
        header: ClassicalHeader(),
        enableControlFinishRefresh: true,
        enableControlFinishLoad: true,
        controller: _controller,
        onRefresh: () {
          refreshSubject.add(12);
          return;
        },
        child: SingleChildScrollView(
          child: Column(
            children: <Widget>[
              Container(
                height: 350,
                color: Colors.red,
              ),
              Container(
                height: 150,
                color: Colors.blue,
              )
            ],
          ),
        ),
      ),
    );
  }
}

```

去了中间的那个，不用调用callload, 我下了的时候触发 网络请求，然后等网络请求回来了，再finishRefresh

**Comment by xuelongqy** [comment]
在build里面处理逻辑是不正确的。只需要在请求结束或者适当的时机调用finishRefresh即可。其他问题，请检验是否来源于flutter_easyrefresh框架

**Comment by SeongBrave** [comment]
其实我的问题很简单，我就是想在onRefresh 回调的时候触发送网络请求，但是您这款需要返回一个Future<void> 类型，不太清除我应该返回什么，我这边只是触发， rxDart我摸你网络请求，延时3秒执行重置刷新状态。您这边的demo都是通过onRefresh的回调自动做的重置刷新状态

**Comment by xuelongqy** [comment]
Future类型只是为了，在不需要控制结束的时候自动结束，并非强制使用await配合Future。就如你所说的，完全满足你的需求，只需要在请求结束或者适当的时机调用finishRefresh即可。

**Comment by SeongBrave** [comment]
```
 refreshSubject.delay(Duration(seconds: 3)).listen((onData) {
      _controller.finishRefresh(success: true);
    });
```
这块我延时了3秒，然后调用finishRefresh，但是现在不知道是我finishRefresh返回的有问题吗？还没等调用finishRefresh了就自动完成了刷新状态重置了
