### ISSUE TITLE
关于加载更多的问题

### ISSUE THREAD

**Issue by pomin** [xuelongqy/flutter_easyrefresh#135]
加载更多完成后，能否和下拉刷新一样设置回弹？

使用 Demo 中的 BasicPage，如果把 onLoad 的 setState 中 _count += 20 注释掉，界面就会停留在加载完成的状态，如果希望列表能滚动到底部，不出现Footer 应该怎么修改？

**Comment by xuelongqy** [comment]
将无限加载设置为false
