### ISSUE TITLE
no more data的时候, 怎么还在一直loading

### ISSUE THREAD

**Issue by iYoullloveGitHub** [xuelongqy/flutter_easyrefresh#137]
![093C9CB8F2F80A53CEBF533962A267E8](https://user-images.githubusercontent.com/23657712/63088409-72dbac00-bf87-11e9-9c70-8e7fc23ef0fb.jpg)

**Comment by xuelongqy** [comment]
可以提供一下你出错的示例代码吗？

**Comment by xuelongqy** [comment]
v2.0.3已修复
