### ISSUE TITLE
ClassicalFooter设置bgColor无效

### ISSUE THREAD

**Issue by shanzhenghan** [xuelongqy/flutter_easyrefresh#138]
ClassicalFooter设置bgColor无效，好像始终是透明色，  ClassicalHeader可以的

header: ClassicalHeader(
          bgColor: Colors.green,
          textColor: Colors.white,
          refreshText: "下拉刷新",
          refreshReadyText: "释放立即刷新",
          refreshingText: "正在刷新...",
          refreshedText: "刷新完成",
          refreshFailedText: "刷新失败",
          infoText: "上次更新: %T",
          infoColor: Colors.white,
        ),
        footer: ClassicalFooter(
          bgColor: Colors.green,
          textColor: Colors.white,
          loadText: "上拉加载",
          loadReadyText: "释放立即加载",
          loadingText: "正在加载...",
          loadedText: "加载完成",
          loadFailedText: "加载失败",
          noMoreText: "没有更多了",
          showInfo: false,
          enableInfiniteLoad: false,
        ),

还有个问题就是当列表数据未满一页的时候，上拉加载时    footer这一块的布局被底部的BottomNatigationBar挡住了

**Comment by xuelongqy** [comment]
下个版本将会修复。你也可以使用git的方式导入github最新的源码使用

**Comment by xuelongqy** [comment]
v2.0.3已修复
