### ISSUE TITLE
手指向下滑动时跳动

### ISSUE THREAD

**Issue by nihuajun1991** [xuelongqy/flutter_easyrefresh#139]
1.easyrefresh嵌套swiper,gridview,横向listview,wrap流式布局,这是我当前页面的层级关系;

异常:假如当前页面正处于wrap中第三行左右时,此时手指往下滑动,这时页面会突然向上跳动,并跳动至横向listview出现,有时会向上跳动至gridview出现,但只要这两个组件出现在屏幕上,滑动就不会出现问题. 只有从wrap第三行左右时往下滑动时才会出现这种情况.请问,这种问题怎么处理?

**Comment by xuelongqy** [comment]
请参考一下swiper相关，确认是否为手势冲突导致，如果是则参考示例中的手势拦截
