### ISSUE TITLE
resetRefreshState 和 resetLoadState 只处理了nomore 状态 没有处理 success状态

### ISSUE THREAD

**Issue by sven-xie** [xuelongqy/flutter_easyrefresh#141]
resetRefreshState 和 resetLoadState 只处理了nomore 状态 没有处理 success状态，在success 设置为false的情况下  状态没有办法恢复；
`// 恢复状态
  void resetRefreshState() {
    if (mounted) {
      setState(() {
        _noMore = false;
        refreshState = RefreshMode.inactive;
        hasSliverLayoutExtent = false;
      });
    }
  }

// 恢复状态
  void resetLoadState() {
    if (mounted) {
      setState(() {
        _noMore = false;
        loadState = LoadMode.inactive;
        hasSliverLayoutExtent = false;
      });
    }
  }`

**Comment by xuelongqy** [comment]
下个版本将会修复。你也可以使用git的方式导入github最新的源码进行测试

**Comment by xuelongqy** [comment]
v2.0.3已修复
