### ISSUE TITLE
已经finishLoad  ，但是no more data的时候,，旁边的图标还一直是loading

### ISSUE THREAD

**Issue by jahnli** [xuelongqy/flutter_easyrefresh#142]
![image](https://user-images.githubusercontent.com/20943608/63206940-c1588a00-c0f0-11e9-8884-2a738c9d3379.png)
![image](https://user-images.githubusercontent.com/20943608/63206941-ca495b80-c0f0-11e9-8a62-80e87893a530.png)

**Comment by xuelongqy** [comment]
v2.0.3已修复

**Comment by fantasy525** [comment]
> v2.0.3已修复

请问，如果不用控制器怎么触发no more呢？
