### ISSUE TITLE
更新到v2版本之后，上拉加载更多一直显示‘加载完成’

### ISSUE THREAD

**Issue by yinzhiqun** [xuelongqy/flutter_easyrefresh#143]
1.2.7版本正常
2.0.2和git最新版本有此问题

使用的ClassicalFooter，自动控制（未使用controller），不管上拉多高，一直都显示‘加载完成’，松手后会触发加载更多，但是动画一闪而过。

**Comment by xuelongqy** [comment]
如果有错误信息或者原因最好提供一下，以及你出现异常的示例代码。因为你遇到的问题可能别人都没遇到过，也许是用法问题，也许是其他问题或者框架问题。为了尽快解决你的问题，请提供更有用的信息。如果以后未出现此类问题，将会关掉这一条Issues。

**Comment by yinzhiqun** [comment]
代码大概是这样，child是一个ListView，onLoadMore直接 return Future.delayed(Duration(seconds: 2)); 界面表现是上拉不管多高，一直显示加载完成，松手后显示为‘正在加载’，但是没有悬停，缩回底部去了

![image](https://user-images.githubusercontent.com/24405130/63209514-68025200-c114-11e9-93db-1c3805953099.png)

**Comment by yinzhiqun** [comment]
并没有异常信息，我加群了，方便的话可以qq私聊，武汉-苦逼哥

**Comment by xuelongqy** [comment]
将footer的无限加载设置为false
