### ISSUE TITLE
用了之后 iOS 点击状态栏 不会触发 scroll to top 了

### ISSUE THREAD

**Issue by Takeroro** [xuelongqy/flutter_easyrefresh#147]
如题，普通的 listView 在 iOS 点击状态栏是可以自动触发列表的 scrollToTop 的，用 easyRefresh 包了一层之后就不行了。

**Comment by xuelongqy** [comment]
我这边用示例测试是可以触发的

**Comment by qky1412** [comment]
> 我这边用示例测试是可以触发的

[✓] Flutter (Channel unknown, v1.9.1+hotfix.7-pre.1, on Mac OS X 10.14.6 18G95,
    locale en-CN)
示例测试不行

**Comment by zinwalin** [comment]
iOS 点击状态栏 不会触发 scroll to top

[✓] Flutter (Channel stable, v1.17.1, on Mac OS X 10.15.4 19E287, locale en)

  @override
  Widget build(BuildContext context) {
    super.build(context);
    // if ( _isFirstLoad) return Scaffold(body: LoadingListPage());
    return Consumer<RecommendArticlesModel>(
        builder: (context, recommendArticlesModel, child) {
      return Scaffold(
        backgroundColor: Colors.white,
        body: EasyRefresh.custom(
          controller: _controller,
          scrollController: scrollController,
          header: BallPulseHeader(
              backgroundColor: Colours.app_bar_background_color),
          footer: ClassicalFooter(
            enableInfiniteLoad: true,
            showInfo: false,
          ),
          onRefresh: () async {
            _pageIndex = 0;
            Provider.of<RecommendArticlesModel>(context, listen: false)
                .refreshAllArticles(context);
            _controller.resetLoadState();
          },
          onLoad: () async {
            Provider.of<RecommendArticlesModel>(context, listen: false)
                .loadData(false, ++_pageIndex, context,
                    callBack: (success, noMore) async {
              _controller.finishLoad(success: success, noMore: noMore);
            });
          },
          slivers: <Widget>[
            SliverList(
              delegate: SliverChildBuilderDelegate(
                (context, index) {
                  // print(_articles.length);
                  ArticleEntity item = recommendArticlesModel.articles[index];
                  return ArticleListCommonItem(
                    article: item,
                    videoScrollController: videoScrollController,
                  );
                },
                childCount: recommendArticlesModel.articles.length,
              ),
            ),
          ],
        ),
      );
    });
  }
