### ISSUE TITLE
请问如何给webview添加下拉刷新

### ISSUE THREAD

**Issue by Creolophus** [xuelongqy/flutter_easyrefresh#148]
我们工程使用了webview_flutter 0.3.13
https://pub.dev/packages/webview_flutter
但是页面直接卡死，请问有解决方案吗

**Comment by xuelongqy** [comment]
webview是原生视图，而且自带滚动，你可以在webview外层加一个固定高度，但仅仅是作为列表中的一项。flutter没法给webview加上下拉刷新效果，只能在原生加。希望可以帮到你。
