### ISSUE TITLE
在添加了scrollController之后会导致NestScrollView的头部不会收起

### ISSUE THREAD

**Issue by luckysmg** [xuelongqy/flutter_easyrefresh#153]
在给EF添加了scrollController之后，原本往下滑应该会折叠头部，但是却没有，将scrollController删除后，能够正常的有折叠效果，我用的custom构造器

**Comment by xuelongqy** [comment]
NestScrollView的子组件添加ScrollController不会折叠的。EasyRefresh和NestScrollView使用同一个ScrollController就可以了
