### ISSUE TITLE
child能够支持PageView吗

### ISSUE THREAD

**Issue by chenxinfei2014** [xuelongqy/flutter_easyrefresh#155]

**Comment by xuelongqy** [comment]
就算支持 结果也不是你想要的。仅仅是对ScrollView操作，如果child不是的话，会把整个child包装成CustomScrollView。你可以没每一页添加一个EasyRefresh。最开始child为Widget是为了单组件的方便，结果却导致了滥用。希望你有时间可以看看源码，这是最直接，最有效的方法
