### ISSUE TITLE
NestedScrollView包裹EasyRefresh的问题

### ISSUE THREAD

**Issue by MrDreamCatcher** [xuelongqy/flutter_easyrefresh#157]
我使用一个没有Appbar的NestedScrollView在最外层，包裹一个EasyRefresh，下拉不松手，然后再上拉的时候每次都是NestedScrollView向上滚动，而EasyRefresh仍然保持原状态，我想实现类似于支付包首页的下拉效果，不松手上拉的时候改变的是EasyRefresh的状态，而不是最外层的NestedScrollView的状态。

**Comment by xuelongqy** [comment]
这是NestedScrollView的bug

**Comment by MrDreamCatcher** [comment]
> 这是NestedScrollView的bug

有解决方案吗？

**Comment by xuelongqy** [comment]
目前还没有。如果没有TabView多页的话，建议使用CustomScrollView

**Comment by MrDreamCatcher** [comment]
> 目前还没有。如果没有TabView多页的话，建议使用CustomScrollView

CustomScrollView里面能再嵌套一个EasyRefresh吗？我试了一下会报错。

**Comment by MrDreamCatcher** [comment]
> 目前还没有。如果没有TabView多页的话，建议使用CustomScrollView

CustomScrollView里面能再嵌套一个EasyRefresh吗？我试了一下会报错。

**Comment by MrDreamCatcher** [comment]
> 目前还没有。如果没有TabView多页的话，建议使用CustomScrollView

CustomScrollView里面能再嵌套一个EasyRefresh吗？我试了一下会报错。

**Comment by xuelongqy** [comment]
请看示例

**Comment by MrDreamCatcher** [comment]
> 请看示例

我们项目里想实现类似于支付宝首页的下拉刷新，从页面中间拉开刷新，整体布局可以向上滚动，可我在示例里面没有找到类似的效果。

**Comment by xuelongqy** [comment]
可以用Sliverappbar的源码修改为header前面的部分，设置headerIndex为1

**Comment by MrDreamCatcher** [comment]
> 可以用Sliverappbar的源码修改为header前面的部分，设置headerIndex为1

Sliverappbar的头部是划不上去的，我们的场景要求header要划上去的，你的意思是自定义SliverAppBar吗？貌似headerIndex只对SliverAppBar有作用。
