### ISSUE TITLE
关于NestedScrollView的疑问

### ISSUE THREAD

**Issue by Bedroome** [xuelongqy/flutter_easyrefresh#159]
请问我NestedScrollView的子组件是个滑动的组件，下拉刷新的时候拉的头部是子组件的，怎么样能拉到SliverAppBar

**Comment by xuelongqy** [comment]
用同一个scrollcontroller

**Comment by Bedroome** [comment]
NestedScrollView里的SliverAppBar和body里的滑动3个都用同一个？还是怎么样使用呀

**Comment by xuelongqy** [comment]
NestedScrollView EasyRefresh和body里面的ScrollController都用同一个
