### ISSUE TITLE
EasyRefresh无法包裹垂直滑动的PageView

### ISSUE THREAD

**Issue by StimeKe** [xuelongqy/flutter_easyrefresh#161]
如题，无法包裹垂直滑动的PageView，我是利用PageView做出抖音的效果，然后包裹这个，但是无法实现

**Comment by xuelongqy** [comment]
EasyRefresh内部是ScrollView结构，也可以理解为ListView。请结合适当的方式使用

**Comment by JDNew** [comment]
@StimeKe 请问你是怎么处理的？

**Comment by StimeKe** [comment]
> @StimeKe 请问你是怎么处理的？

我自己实现了一个，PageView没有用这个。
