### ISSUE TITLE
滚动加载更多时，当滚动快时触发加载更多后，加载结束时会触发列表往回滚动

### ISSUE THREAD

**Issue by fantasy525** [xuelongqy/flutter_easyrefresh#162]
```
flutter:1.7.8 hotfix4
 flutter_easyrefresh: 2.0.0
ios真机
```
![2019-09-16 14-11-13 2019-09-16 14_11_37](https://user-images.githubusercontent.com/22516157/64937200-ef65f100-d88b-11e9-9022-0a5a5a082a89.gif)

上面的gif显示滑到底部后开始加载更多，但是页面又往回滑动了一段距离，没有停在底部等待加载更多

**Comment by xuelongqy** [comment]
列表未填充是这样的。其他情况请检验你的代码，或者按照要求提出你的issue

**Comment by SpringerInFighting** [comment]
你最后怎么解决的

**Comment by xhp281** [comment]
等结果

**Comment by xuelongqy** [comment]
> 等结果

如果你也遇到这个问题，请提供一下实例代码

**Comment by xuelongqy** [comment]
请升级最新版本进行测试

**Comment by jujingyi0618** [comment]
> 请升级最新版本进行测试

最新版依然有这个问题，我的布局是NestedSCrollview结合body tab tabBarView,每个tabbarview中的列表上拉加载时会出现这个问题

**Comment by xuelongqy** [comment]
请参考NestedScrollView示例
