### ISSUE TITLE
ChatPage，第一屏从底部开始渲染问题

### ISSUE THREAD

**Issue by wapchief** [xuelongqy/flutter_easyrefresh#167]
如果将reverse设为ture，虽然可以实现IM聊天的效果，但是往往在消息少的时候，比如只有两条，按照这种实现方式，消息默认并不是出现在顶部，而是从底部开始渲染，当消息数量超过一屏的时候，看起来才正常。目前现在这种方式显然不太符合IM逻辑，所以，请问有没有其他解决办法？

**Comment by xuelongqy** [comment]
示例没有问题，这种方式也符合IM逻辑。应该是你把顺序用反了，reverse代表反向，意味着消息的顺序是反的。示例中可以加载更多，以及发消息，你可以试试看

**Comment by wapchief** [comment]
> 你说的不符合逻辑，应该是使用习惯问题

所以，有没有什么办法能保证在渲染第一屏的时候从上面开始渲染，现在如果使用了reverse，就相当于把底部当头部。但是不用的话，自己实现，下拉加载更多，每次添加一页数据，又没有那种平滑过度的效果

**Comment by yh4922** [comment]
我是 用 ScrollController  控制列表 在初始化的时候滑动到最低

**Comment by xuelongqy** [comment]
已实现此效果，不过不算特别友好，通过计算列表内容的高度使用不同的布局。请参考示例[ChatPage](https://github.com/xuelongqy/flutter_easyrefresh/blob/v2/example/lib/page/sample/chat.dart)
