### ISSUE TITLE
关于快速滑动列表导致onload重复调用

### ISSUE THREAD

**Issue by luckysmg** [xuelongqy/flutter_easyrefresh#168]
当以比较快的手速（或者说是相当快）的速度滑动列表到达底部时，onload方法可能会被执行两次，这对分页加载时候的逻辑是致命的，因为第一次请求还没回来，当前页面还没更新，然后就因为错误再次调用的onload方法再次请求了服务器数据，分页列表加载逻辑就会混乱，所以能否请大佬看一下并且希望能够修复这个问题

示例代码如下，看控制台的print的‘load’即可判断哦😂

`import 'package:flutter/material.dart';
import 'package:flutter/cupertino.dart';
import 'package:flutter_douban/widgets/common_widgets/refresh_footer.dart';
import 'package:flutter_easyrefresh/easy_refresh.dart';
import 'package:flutter_screenutil/flutter_screenutil.dart';

class TestPage extends StatefulWidget {
  @override
  _TestPageState createState() => _TestPageState();
}

class _TestPageState extends State<TestPage> {
  EasyRefreshController controller;

  @override
  void initState() {
    super.initState();
    controller = EasyRefreshController();
  }

  @override
  Widget build(BuildContext context) {
    print('build');
    return Scaffold(
        body: EasyRefresh.custom(
            enableControlFinishLoad: true,
            controller: controller,
            footer: RefreshFooter(),
            onLoad: () async {
              print('load');
              await Future.delayed((Duration(milliseconds: 1500)));
              controller.finishLoad();
            },
            slivers: [
          SliverFixedExtentList(
              delegate: SliverChildBuilderDelegate((context, index) {
                return Text('第$index个条目',
                    style: TextStyle(fontSize: ScreenUtil().setSp(28)));
              }, childCount: 200),
              itemExtent: 40)
        ]));
  }
}
`

**Comment by luckysmg** [comment]
希望就是在当前load方法还没执行完之前不能再次触发第二次load

**Comment by xuelongqy** [comment]
在触发加载或刷新后，是进行加锁的。理论来说不会出现你描述的问题，请您确认一下代码逻辑，以及是否为最新版本

**Comment by AbeiOS** [comment]
> 希望就是在当前load方法还没执行完之前不能再次触发第二次load

作者这个问题解决了吗？
