### ISSUE TITLE
上拉加载更多, 始终是 对勾  状态

### ISSUE THREAD

**Issue by zzdota** [xuelongqy/flutter_easyrefresh#169]
![image](https://user-images.githubusercontent.com/16704305/65753929-95deab80-e142-11e9-9dd1-469592c73597.png)
上面是当前版本信息;

发现了一个问题,上拉加载更多, 始终是 对勾  状态. 如下图;
如果是使用方式有问题,请指教.
![newpz-ejgss](https://user-images.githubusercontent.com/16704305/65755133-130b2000-e145-11e9-8b52-2fb5d85d1605.gif)

代码如下
![image](https://user-images.githubusercontent.com/16704305/65754522-ce32b980-e143-11e9-89eb-f960f96ad533.png)

第一次使用,很容易就集成 成功了,感谢作者! @xuelongqy

**Comment by fouthx** [comment]
我也是这个问题，只显示加载完成，没有其他状态

**Comment by zzdota** [comment]
> 我也是这个问题，只显示加载完成，没有其他状态

经过多次尝试,通过自定义footer,设置 enableInfiniteLoad: false 方能解决这个问题.
感谢作者!!!
![image](https://user-images.githubusercontent.com/16704305/68169007-a1c15700-ffa5-11e9-9308-a5bc34a32a87.png)

**Comment by xuelongqy** [comment]
由于异步事件太快或者没有延时，无限加载会在滚动到底部开始触发，所以直接就完成了，没有看到过程
