### ISSUE TITLE
能否增加下拉拖动的回调

### ISSUE THREAD

**Issue by hjlxy** [xuelongqy/flutter_easyrefresh#17]
您好，很喜欢这个组件包，有个需求，在下拉拖动的时候，进行一些操作，类似淘宝或京东的APP下拉的时候，隐藏AppBar，刷新完成后显示AppBar，现在在不改变源码的情况下，只能使用onRefresh方法

**Comment by xuelongqy** [comment]
1.2.0及以后版本 是支持的。请使用headerStatusChanged和footerStatusChanged，用于监听当前下拉或则上拉的状态

**Comment by hjlxy** [comment]
好的，谢谢
