### ISSUE TITLE
control调用callRefresh方法会先把flexibleSpace折叠起来再展开

### ISSUE THREAD

**Issue by taoyimin** [xuelongqy/flutter_easyrefresh#172]
[https://github.com/xuelongqy/flutter_easyrefresh/blob/v2/example/lib/page/sample/nested_scroll_view.dart](url)
在上面这个页面的flexibleSpace中我加了一个搜索按钮，并通过control调用callRefresh方法，发现flexibleSpace会先折叠起来再展开然后再显示更新的header，有什么办法能直接显示header而不是先折叠再展开吗？
`flexibleSpace: SingleChildScrollView(
                physics: NeverScrollableScrollPhysics(),
                child: Container(
                  padding: EdgeInsets.only(top: 80),
                  child: RaisedButton(onPressed: (){
                    _refreshController.callRefresh();
                  },child: Text('刷新'),),
                ),
              ),`

**Comment by xuelongqy** [comment]
这是Flutter列表的设计，以及EasyRefresh的原理是超出顶部才能刷新。所以是必然现象

**Comment by qcdys** [comment]
https://github.com/peng8350/flutter_pulltorefresh/issues/270?notification_referrer_id=MDE4Ok5vdGlmaWNhdGlvblRocmVhZDc4MzEyODk1NjoxNTQwMjk3Ng%3D%3D#issuecomment-661772366

这里修正了 与easyRefresh 现象一样 @xuelongqy

**Comment by xuelongqy** [comment]
> [peng8350/flutter_pulltorefresh#270](https://github.com/peng8350/flutter_pulltorefresh/issues/270)
> 
> 这里修正了 与easyRefresh 现象一样 @xuelongqy

感谢提醒，已修复，将会在下个版本发布
