### ISSUE TITLE
空布局和首次刷新同时使用有问题

### ISSUE THREAD

**Issue by joker-fu** [xuelongqy/flutter_easyrefresh#175]
@override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text(FlutterI18n.translate(context, 'emptyWidget')),
        backgroundColor: Colors.white,
      ),
      body: EasyRefresh.custom(
        firstRefresh: false,
        firstRefreshWidget: Center(
            child: SizedBox(
              height: 200.0,
              width: 300.0,
              child: Card(
                child: Column(
                  mainAxisAlignment: MainAxisAlignment.center,
                  crossAxisAlignment: CrossAxisAlignment.center,
                  children: <Widget>[
                    Container(
                      width: 50.0,
                      height: 50.0,
                      child: SpinKitFadingCube(
                        color: Theme.of(context).primaryColor,
                        size: 25.0,
                      ),
                    ),
                    Container(
                      child:
                      Text(FlutterI18n.translate(context, 'loading')),
                    )
                  ],
                ),
              ),
            )
        ),
        emptyWidget: _count == 0 ? Container(
          height: double.infinity,
          child: Column(
            mainAxisAlignment: MainAxisAlignment.center,
            crossAxisAlignment: CrossAxisAlignment.center,
            children: <Widget>[
              Expanded(child: SizedBox(), flex: 2,),
              SizedBox(
                width: 100.0,
                height: 100.0,
                child: Image.asset('assets/image/nodata.png'),
              ),
              Text(
                FlutterI18n.translate(context, 'noData'),
                style: TextStyle(fontSize: 16.0, color: Colors.grey[400]),
              ),
              Expanded(child: SizedBox(), flex: 3,),
            ],
          ),
        ): null,
        slivers: <Widget>[
          SliverList(
            delegate: SliverChildBuilderDelegate(
                  (context, index) {
                return SampleListItem();
              },
              childCount: _count,
            ),
          ),
        ],
        onRefresh: () async {
          await Future.delayed(Duration(seconds: 3), () {
            setState(() {
              _count = 0;
            });
          });
        },
        onLoad: () async {
          await Future.delayed(Duration(seconds: 2), () {
            setState(() {
              _count += 20;
            });
          });
        },
      ),
    );
  }

**Comment by dmskys** [comment]
我也遇到了这个问题

**Comment by dmskys** [comment]
我也遇到这个问题 
原因是EasyRefreshController refreshController = EasyRefreshController();
声明在StatefulWidget 中了
声明在State类中 解决了

**Comment by xuelongqy** [comment]
请详细描述一下你的问题。我试过同时使用没有问题，先会显示首次刷新视图，然后再显示空视图。需要注意的是，透明色会出现覆盖现象，这个需要你自己控制
