### ISSUE TITLE
firstRefresh 配合 provider 加载更多自动回滚顶部。

### ISSUE THREAD

**Issue by joker-fu** [xuelongqy/flutter_easyrefresh#176]
使用 flutter_easyrefresh: ^2.0.4

firstRefresh 配合 provider 使用第一次进入页面刷新加载正常，第二次进入页面加载完成后，会自动回滚顶部。 必须手动刷新一次才能正常。

另外加载成功后，列表会滚动一段距离，不知道什么原因。与上一个问题无关

**Comment by xuelongqy** [comment]
滚动是因为异步请求过快，列表缓冲未结束，这个我会研究一下解决方案。使用provider的话，请先验证你的逻辑，文字描述并不是还原问题的好方法

**Comment by xuelongqy** [comment]
firstRefresh 会触发自动滚动到顶部刷新操作
