### ISSUE TITLE
能否增加属性控制只显示下来刷新，屏蔽上拉加载的功能

### ISSUE THREAD

**Issue by hugochou** [xuelongqy/flutter_easyrefresh#18]
需要用到的场景例如：在没有更多数据时我只希望直接在底部显示“没有更多数据”等，而不希望用户每次上拉都出现上拉加载的动画。

**Comment by xuelongqy** [comment]
不设置loadMore 或者设置为null 即可

**Comment by hugochou** [comment]
是否还可以优化一下？如果loadMore设置为null时，iOS应该有上拉回弹效果，而不是像现在这样完全不能拉动

**Comment by xuelongqy** [comment]
你可以试试看，因该是屏蔽了iso的回弹效果的。你可以用三元运算符去设置loadMore

**Comment by xuelongqy** [comment]
使用ios的回弹效果 是会出现很多不可控现象的。所以没有办法加上。你也可以写一个空白的Footer去代替

**Comment by hugochou** [comment]
> 使用ios的回弹效果 是会出现很多不可控现象的。所以没有办法加上。你也可以写一个空白的Footer去代替

首先感谢你的回复。
你说的这个方法我之前试过，但是效果并不太好，因为使用的是定义好的动画，如果不改动内部动画效果，上拉回弹会有卡顿感觉，这样处理相当于隐藏了各种状态的图文显示，但是各个状态切换的动画延迟还是存在的。

**Comment by xuelongqy** [comment]
你提到的回弹效果已经实现了。但是遇到一点问题就是，如果在刷新过程中使用setState去改变EasyRefresh的属性时，例如loadMore，可能会出现异常。你可以加入QQ群554981921，一起讨论

**Comment by lionoggo** [comment]
@hugochou 你是如何实现没有更多数据时直接显示"没有更多数据提示的"?
