### ISSUE TITLE
添加空白页面之后，底部有间距

### ISSUE THREAD

**Issue by BeyoundFly** [xuelongqy/flutter_easyrefresh#181]
![image](https://user-images.githubusercontent.com/24197624/67268429-092bd100-f4e7-11e9-854c-e2e049834196.png)
![image](https://user-images.githubusercontent.com/24197624/67268507-3d06f680-f4e7-11e9-9359-22ba5615d11a.png)

class EmptyPageState extends State<EmptyPage> {
  // 总数
  int _count = 0;

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text(FlutterI18n.translate(context, 'emptyWidget')),
        backgroundColor: Colors.white,
      ),
      body: EasyRefresh.custom(
        emptyWidget: _count == 0 ? Container(
          color: Colors.red,
          height: double.infinity,
          child: Column(
            mainAxisAlignment: MainAxisAlignment.center,
            crossAxisAlignment: CrossAxisAlignment.center,
            children: <Widget>[
              Expanded(child: SizedBox(), flex: 2,),
              SizedBox(
                width: 100.0,
                height: 100.0,
                child: Image.asset('assets/image/nodata.png'),
              ),
              Text(
                FlutterI18n.translate(context, 'noData'),
                style: TextStyle(fontSize: 16.0, color: Colors.grey[400]),
              ),
              Expanded(child: SizedBox(), flex: 3,),
            ],
          ),
        ): null,
        slivers: <Widget>[
          SliverList(
            delegate: SliverChildBuilderDelegate(
                  (context, index) {
                return SampleListItem();
              },
              childCount: _count,
            ),
          ),
        ],
        onRefresh: () async {
          await Future.delayed(Duration(seconds: 2), () {
            setState(() {
              if(_count == 0) {
                _count = 20;
              } else {
                _count = 0;
              }
            });
          });
        },
        onLoad: () async {
          await Future.delayed(Duration(seconds: 2), () {
            setState(() {
              _count += 20;
            });
          });
        },
      ),
    );
  }
}

**Comment by xuelongqy** [comment]
你看看是不是安全区域的问题。SafeArea
