### ISSUE TITLE
发现只要使用了EasyRefresh并且添加onRefresh或者onLoad，会导致GPU一直再刷新

### ISSUE THREAD

**Issue by mengxin1995** [xuelongqy/flutter_easyrefresh#184]
复现路径：只要使用EasyRefresh并且添加了onRefresh或者onLoad属性，flutter attach你的应用，控制台输入P看他的GPU变化，会发现GPU和UI线程一直再刷新。

目前没有定位到刷新的原因，希望作者给予一下支持

**Comment by 1232209** [comment]
你好，我碰到了同样的问题！
经过测试发现，只要onRefresh不为null的话，就会一直刷新。这样导致的问题是占用cpu过高，直接飙到了10%。
但是我用作者的example发现又不会，只会在下拉的时候有刷新。是我哪里做错了嘛？
`Widget normalList(partition,fileTileModel){
    return EasyRefresh(
      enableControlFinishRefresh: true,
      enableControlFinishLoad: true,
      controller: _controller,
      scrollController: _scrollController,
      taskIndependence:false,
      onRefresh: () async{
        fetchAllDir(_currentDir).then((value){
          _controller.resetLoadState();
          _controller.finishRefresh();
        });

      },
      header: CustomHeader(headerBuilder: (BuildContext context,
          RefreshMode refreshState,
          double pulledExtent,
          double refreshTriggerPullDistance,
          double refreshIndicatorExtent,
          AxisDirection axisDirection,
          bool float,
          Duration completeDuration,
          bool enableInfiniteRefresh,
          bool success,
          bool noMore){
        return Stack(
          children: <Widget>[
            Positioned(
              bottom: 0.0,
              left: 0.0,
              right: 0.0,
              child: Lottie.asset("lib/Resource/animation/loading.json", width: 40, height: 40),
            ),
          ],
        );
      }),
      child: ListView.builder(
          itemCount: fileTileModel.length,
          itemBuilder: (context, index) {
            return ListTile(
              onTap: () {
                if (selectFileMode) {
                  setState(() {
                    if (_fileListTileModel
                        .listModel[index].selectFileType ==
                        SelectFileType.selected) {
                      _fileListTileModel.listModel[index].selectFileType =
                          SelectFileType.selecting;
                    } else {
                      _fileListTileModel.listModel[index].selectFileType =
                          SelectFileType.selected;
                    }

                    bottomBarEntryController.sink
                        .add({"fileListTileModel": _fileListTileModel});
                    appBarEntryController.sink
                        .add({"fileListTileModel": _fileListTileModel});
                  });
                } else {
                  if (fileTileModel[index].fileType == FileType.Dir) {
                    PathModel pathModel = PathModel(
                        fileTileModel[index].name,
                        "$_currentDir/${fileTileModel[index].name}");
                    var args = {
                      "pathModel":pathModel,
                      "capacityBarStreamController":capacityBarStreamController
                    };
                    Navigator.pushNamed(context, "FileListChild",
                        arguments: args);
                  }
                }
              },
              onLongPress: () {
                if (!selectFileMode) {
                  goSelectFileMode(index);
                }
              },
              leading: FileTypeJudge.put(
                  fileTileModel[index].name, fileTileModel[index].fileType),
              title: Text(
                fileTileModel[index].name,
                style: TextStyle(
                    color: Colors.black,
                    fontWeight: FontWeight.w600,
                    fontSize: 14),
                maxLines: 1,
                overflow: TextOverflow.ellipsis,
              ),
              subtitle: Text(
                  fileTileModel[index].updateDate.replaceAll(",", " ")),
              trailing:
              trailingList(fileTileModel[index].selectFileType, index),
            );
          }),
    );
  }`

**Comment by myron6520** [comment]
也遇到这个问题 貌似现在还没有被解决

**Comment by lanyuzx** [comment]
这个貌似是Lottie的问题 单独加载Lottie CPU也会飙升
