### ISSUE TITLE
偶尔下拉刷新失败

### ISSUE THREAD

**Issue by xy221150** [xuelongqy/flutter_easyrefresh#186]
EasyRefreshController触发刷新方法偶尔不起作用

**Comment by xy221150** [comment]
调用EasyRefreshController刷新方法次数多次就会有一次调用不成功

**Comment by xuelongqy** [comment]
刷新未结束之前，调用是无效的

**Comment by huangying1111** [comment]
> 刷新未结束之前，调用是无效的

怎么判断刷新结束没有 1.+ 有一个key可以判断升级后就不可用了

**Comment by xuelongqy** [comment]
需要自定义样式获取，可以直接复制样式源码添加连接器即可

**Comment by xuelongqy** [comment]
已添加通知器Header和Footer，将会在下一个版本发布

**Comment by xuelongqy** [comment]
已更新，请升级至2.0.5版本
