### ISSUE TITLE
LinkHeader和emptyWidge同时使用，不显示header

### ISSUE THREAD

**Issue by huangying1111** [xuelongqy/flutter_easyrefresh#189]
参考demo 写的LinkHeader
在slivers中新增
` SliverToBoxAdapter(
     child: CircleHeader(
         _headerNotifier,
      ),
   ),`

同时使用emptyWidget时，会出现下拉加载的图标没有显示，但数据正常获取的情况

**Comment by xuelongqy** [comment]
有检验过数据吗？

**Comment by huangying1111** [comment]
数据没有问题，我现在只能写在SliverList里判断数据为空的时候显示emptyWidget

**Comment by xuelongqy** [comment]
设置一下headerIndex就可以了，不设置的话整个列表都会显示空视图
