### ISSUE TITLE
Exception: type 'Container' is not a subtype of type 'RefreshHeader' in type cast

### ISSUE THREAD

**Issue by huzhiren** [xuelongqy/flutter_easyrefresh#19]
If you set onRefresh to null, but refreshHeader not null (in my case onRefresh is null in some condition), you got those exceptions :

type 'Container' is not a subtype of type 'RefreshHeader' in type cast
#0      EasyRefreshState.build (package:flutter_easyrefresh/src/refresher.dart:1099:56)
#1      StatefulElement.build (package:flutter/src/widgets/framework.dart:3809:27)

type 'Container' is not a subtype of type 'RefreshHeader' in type cast
#0      EasyRefreshState.build (package:flutter_easyrefresh/src/refresher.dart:1148:29)
#1      StatefulElement.build (package:flutter/src/widgets/framework.dart:3809:27)

I manually edit the source code in line 1099 to:
              widget.refreshHeader == null || !widget.refreshHeader.isFloat
                  ? header
                  : new Container(),

and line 1148 to:
            child: widget.refreshHeader != null &&
                    widget.refreshHeader.isFloat
                ? header
                : new Container(),
to get around this issue.

**Comment by xuelongqy** [comment]
Please refer to the property documentation and examples. Header and Footer are the specified types. If you need to customize, please refer to [CUSTOM_HEADER_FOOTER.md](https://github.com/xuelongqy/flutter_easyrefresh/blob/master/art/md/en/CUSTOM_HEADER_FOOTER.md) and [sliver_page.dart](https://github.com/xuelongqy/flutter_easyrefresh/blob/master/example/lib/page/sample/sliver_page.dart).

**Comment by huzhiren** [comment]
I don't think you got it.  I used the `ClassicsHeader` and `ClassicsFooter` right come down from this package.

**Comment by huzhiren** [comment]
`
			EasyRefresh(
				key: _easyRefreshKey,
				refreshHeader: ClassicsHeader(
					key: _headerKey,
					refreshText: strings.pullToRefresh,
					refreshReadyText: strings.releaseToRefresh,
					refreshingText: strings.refreshing,
					refreshedText: strings.refreshed,
					bgColor: Colors.transparent,
					textColor: Colors.black87,
				),
				refreshFooter: ClassicsFooter(
					key: _footerKey,
					loadText: strings.pushToLoad,
					loadReadyText: strings.releaseToLoad,
					loadingText: strings.loading,
					loadedText: strings.loaded,
					noMoreText: strings.noMore,
					bgColor: Colors.transparent,
					textColor: Colors.black87,
				),
				onRefresh: tabs[tabIndex].onRefresh,
				loadMore: tabs[tabIndex].onLoadMore,
				autoControl: true,
				child: CustomScrollView(...)

`

**Comment by xuelongqy** [comment]
Ok, I got it. I will fix it as soon as possible.

**Comment by huzhiren** [comment]
The fix can be found here: [PR#20](https://github.com/xuelongqy/flutter_easyrefresh/pull/20)

**Comment by xuelongqy** [comment]
Thank you. [1.2.2](https://pub.dartlang.org/packages/flutter_easyrefresh) fixed
