### ISSUE TITLE
I can't see loaded text when using setState.

### ISSUE THREAD

**Issue by leishuai** [xuelongqy/flutter_easyrefresh#191]
When delete setState inside onLoad callback, I can see loaded text display at the bottom of the list view. But when there is setState,no loaded text displayed.  When debugging , I found load state was immediately set to inactive where there is setState.

My code is like this:
EasyRefresh buildListView(Widget listView) {
    return EasyRefresh(
      controller: _refreshController,
      enableControlFinishRefresh: false,
      enableControlFinishLoad: false,
      footer: ClassicalFooter(
        enableInfiniteLoad: false,
        loadText: S.of(context).pushToLoad,
        loadReadyText: S.of(context).releaseToLoad,
        loadingText: S.of(context).loading,
        loadedText: S.of(context).loaded,
        noMoreText: S.of(context).noMore,
        showInfo: false,
//        triggerDistance: 50.0,
        completeDuration: Duration(milliseconds: 200),
      ),
      child: listView != null ? listView : _buildListView(),
      onLoad: supportLoadMore ? (){
        return Future.delayed(const Duration(milliseconds: 500), () async {
          if (await onListViewLoadMore()) {
            setState(() {});
          }
        });
      } : null,
    );

**Comment by xuelongqy** [comment]
Footer has no float parameter, it is always the last
