### ISSUE TITLE
NestedScrollerView开启控制加载和刷新完成，刷新和加载停止不了

### ISSUE THREAD

**Issue by sisychen** [xuelongqy/flutter_easyrefresh#192]
EasyRefresh(
                enableControlFinishRefresh: true,
                enableControlFinishLoad: true,
                child: ListView.builder(
                  padding: EdgeInsets.all(0.0),
                  itemBuilder: (context, index) {
                    return SampleListItem();
                  },
                  itemCount: _listCount,
                ),
                onRefresh: () async {
                  await Future.delayed(Duration(seconds: 2), () {
                    _refreshController.finishRefresh();
                    setState(() {
                      _listCount = 20;
                    });
                  });
                },
                onLoad: () async {
                  await Future.delayed(Duration(seconds: 2), () {
                    _refreshController.finishLoad();
                    setState(() {
                      _listCount += 10;
                    });
                  });
                },
              )

**Comment by Adgeros** [comment]
同样问题

**Comment by JDNew** [comment]
我是间歇性的，断点跟到有调用到finishRefresh方法，但就是一些显示loading的状态。

**Comment by xuelongqy** [comment]
你没有在EasyRefresh中设置controller
