### ISSUE TITLE
为什么每次自动刷新都会报错？

### ISSUE THREAD

**Issue by MuZiLee** [xuelongqy/flutter_easyrefresh#196]
![image](https://user-images.githubusercontent.com/7467318/69496578-7da2c700-0f0e-11ea-9715-791d048a13f6.png)
![image](https://user-images.githubusercontent.com/7467318/69496583-9317f100-0f0e-11ea-8303-92c2a56b90d6.png)
我的聊天页面，每次自动刷新都报错。不只是这一个页面，所有的自动刷新都出现这种情况。请问为什么？

**Comment by xuelongqy** [comment]
请检验你的代码，无误后按照要求提出问题。不然我也无法帮助你

**Comment by MuZiLee** [comment]
代码是复制例子的。不需要了，我自己封装了一套
