### ISSUE TITLE
首次自动刷新，数据只有一页，finishLoad(noMore: true)不生效，但是下拉刷新却生效.

### ISSUE THREAD

**Issue by LCJ-MinYa** [xuelongqy/flutter_easyrefresh#197]

**Comment by xuelongqy** [comment]
请阅读文档，了解参数含义

**Comment by taozidada** [comment]
@xuelongqy 真的有这个问题， 我也出现了，我有必现的方法，条件也不算苛刻。版本flutter_easyrefresh: ^2.0.4，iOS模拟器12.4 iPhone xs max。前提，不通过下拉刷新先获得一页数据，第二页通过上拉加载，成功后设置_refreshController.finishLoad(noMore: true); 此时的nomore是不生效的！！！
具体例子：
假如服务端有22个数据，我采用pageSize = x的方式分页获取
1、x=20，不下拉 手动获取一页数据，上拉1次直到无数据noMore: true，不生效
2、x=20，下拉获取一页数据，上拉1次直到无数据noMore: true，生效
3、x=5，不下拉手动获取一页数据，上拉4次直到无数据，设置noMore: true，生效
4、x=10，不下拉手动获取一页数据，上拉2次直到无数据，设置noMore: true，生效
5、x=12，不下拉手动获取一页数据，上拉1次直到无数据，设置noMore: true，不生效
实验的几次只改了x的值，代码没有任何改动。
造成这个bug的步骤应该就是不下拉刷新的情况下，第一次调用上拉并且设置noMore: true，就会不生效，麻烦大佬看一下，谢谢

**Comment by xuelongqy** [comment]
> @xuelongqy 真的有这个问题， 我也出现了，我有必现的方法，条件也不算苛刻。版本flutter_easyrefresh: ^2.0.4，iOS模拟器12.4 iPhone xs max。前提，不通过下拉刷新先获得一页数据，第二页通过上拉加载，成功后设置_refreshController.finishLoad(noMore: true); 此时的nomore是不生效的！！！
> 具体例子：
> 假如服务端有22个数据，我采用pageSize = x的方式分页获取
> 1、x=20，不下拉 手动获取一页数据，上拉1次直到无数据noMore: true，不生效
> 2、x=20，下拉获取一页数据，上拉1次直到无数据noMore: true，生效
> 3、x=5，不下拉手动获取一页数据，上拉4次直到无数据，设置noMore: true，生效
> 4、x=10，不下拉手动获取一页数据，上拉2次直到无数据，设置noMore: true，生效
> 5、x=12，不下拉手动获取一页数据，上拉1次直到无数据，设置noMore: true，不生效
> 实验的几次只改了x的值，代码没有任何改动。
> 造成这个bug的步骤应该就是不下拉刷新的情况下，第一次调用上拉并且设置noMore: true，就会不生效，麻烦大佬看一下，谢谢

新版本发布了，能否再测试一下呢？如果还是有问题，可以提供一个示例吗？

**Comment by taozidada** [comment]
我发现我也复现不了，当时出问题的是2.0.4，我现在切到2.0.4也没发现这个问题，暂时关闭吧。
