### ISSUE TITLE
刷新启动之后页面dispose 动画报错

### ISSUE THREAD

**Issue by qylshy** [xuelongqy/flutter_easyrefresh#199]
[ERROR:flutter/lib/ui/ui_dart_state.cc(148)] Unhandled Exception: 'package:flutter/src/animation/animation_controller.dart': Failed assertion: line 508 pos 7: '_ticker != null': AnimationController.animateTo() called after AnimationController.dispose()
E/flutter ( 4086): AnimationController methods should not be used after calling dispose.
E/flutter ( 4086): #0      _AssertionError._doThrowNew (dart:core-patch/errors_patch.dart:40:39)
E/flutter ( 4086): #1      _AssertionError._throwNew (dart:core-patch/errors_patch.dart:36:5)
E/flutter ( 4086): #2      AnimationController.animateTo (package:flutter/src/animation/animation_controller.dart:508:7)
E/flutter ( 4086): #3      MaterialHeaderWidgetState.refreshFinish=.<anonymous closure> (package:flutter_easyrefresh/material_header.dart:146:28)
E/flutter ( 4086): #4      new Future.delayed.<anonymous closure> (dart:async/future.dart:316:39)
E/flutter ( 4086): #5      _rootRun (dart:async/zone.dart:1120:38)
E/flutter ( 4086): #6      _CustomZone.run (dart:async/zone.dart:1021:19)
E/flutter ( 4086): #7      _CustomZone.runGuarded (dart:async/zone.dart:923:7)
E/flutter ( 4086): #8      _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:963:23)
E/flutter ( 4086): #9      _rootRun (dart:async/zone.dart:1124:13)
E/flutter ( 4086): #10     _CustomZone.run (dart:async/zone.dart:1021:19)
E/flutter ( 4086): #11     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:947:23)
E/flutter ( 4086): #12     Timer._createTimer.<anonymous closure> (dart:async-patch/timer_patch.dart:21:15)
E/flutter ( 4086): #13     _Timer._runTimers (dart:isolate-patch/timer_impl.dart:382:19)
E/flutter ( 4086): #14     _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:416:5)
E/flutter ( 4086): #15     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:172:12)

源代码：
![image](https://user-images.githubusercontent.com/5379447/69776169-19198d80-11d6-11ea-87dd-9c150d51cc0e.png)

**Comment by xuelongqy** [comment]
已修复，将会在下一个版本中发布

**Comment by xuelongqy** [comment]
已更新，请升级至2.0.5版本
