### ISSUE TITLE
提两点使用中的问题

### ISSUE THREAD

**Issue by cv0cv0** [xuelongqy/flutter_easyrefresh#203]
1、No More 左边的图标去不掉
2、没有适配全面屏

**Comment by xuelongqy** [comment]
感谢你的建议
1、可自行定义Footer，默认样式不一定适用于每一个项目，这也是框架实现自定义样式的意义
2、全面屏的适配不属于框架的考虑范围，需要自行适配

**Comment by xuelongqy** [comment]
全面屏已经可以使用padding参数
