### ISSUE TITLE
flutter run时compiler错误

### ISSUE THREAD

**Issue by ahai0831** [xuelongqy/flutter_easyrefresh#205]
步骤复现：
下载压缩包并解压，
在主目录中执行flutter pub get
进入example目录，执行flutter run 
报错信息如下：
Launching lib/main.dart on iPhone 8 in debug mode...

Compiler message:
file:///Users/zhaoztcorp.21cn.com/.pub-cache/hosted/pub.flutter-io.cn/flare_flut
ter-1.5.4/lib/flare.dart:585:14: Error: The method 'FlutterActor.makeShapeNode'
has fewer positional arguments than those of overridden method
'Actor.makeShapeNode'.
  ActorShape makeShapeNode() {
             ^
file:///Users/zhaoztcorp.21cn.com/.pub-cache/hosted/pub.flutter-io.cn/flare_dart
-1.4.9/lib/actor.dart:68:14: Context: This is the overridden method
('makeShapeNode').
  ActorShape makeShapeNode(ActorShape source) {
             ^
lib/page/sample/sample.dart:184:15: Error: Getter not found: 'kDebugMode'.
              kDebugMode ? ListItem(
              ^^^^^^^^^^
lib/page/sample/sample.dart:184:15: Error: The getter 'kDebugMode' isn't defined
for the class '_SamplePageState'.
 - '_SamplePageState' is from 'package:example/page/sample/sample.dart'
 ('lib/page/sample/sample.dart').
Try correcting the name to the name of an existing getter, or defining a getter
or field named 'kDebugMode'.
              kDebugMode ? ListItem(
              ^^^^^^^^^^
file:///Users/zhaoztcorp.21cn.com/.pub-cache/hosted/pub.flutter-io.cn/extended_n
ested_scroll_view-0.3.8/lib/src/nested_scroll_view_refresh_indicator.dart:373:24
: Error: Method not found: 'ErrorDescription'.
              context: ErrorDescription('when calling onRefresh'),
                       ^^^^^^^^^^^^^^^^
file:///Users/zhaoztcorp.21cn.com/.pub-cache/hosted/pub.flutter-io.cn/extended_n
ested_scroll_view-0.3.8/lib/src/nested_scroll_view_refresh_indicator.dart:373:24
: Error: The method 'ErrorDescription' isn't defined for the class
'NestedScrollViewRefreshIndicatorState'.
 - 'NestedScrollViewRefreshIndicatorState' is from
 'package:extended_nested_scroll_view/src/nested_scroll_view_refresh_indicator.d
 art'
 ('file:///Users/zhaoztcorp.21cn.com/.pub-cache/hosted/pub.flutter-io.cn/extende
 d_nested_scroll_view-0.3.8/lib/src/nested_scroll_view_refresh_indicator.dart').
Try correcting the name to the name of an existing method, or defining a method
named 'ErrorDescription'.
              context: ErrorDescription('when calling onRefresh'),
                       ^^^^^^^^^^^^^^^^
file:///Users/zhaoztcorp.21cn.com/.pub-cache/hosted/pub.flutter-io.cn/flare_flut
ter-1.5.4/lib/flare.dart:1027:18: Error: The argument type 'Uint16List' can't be
assigned to the parameter type 'Int32List'.
 - 'Uint16List' is from 'dart:typed_data'.
 - 'Int32List' is from 'dart:typed_data'.
Try changing the type of the parameter, or casting the argument to 'Int32List'.
        indices: _indices, textureCoordinates: _uvBuffer);
                 ^
Compiler failed on
/Users/zhaoztcorp.21cn.com/Downloads/flutter_easyrefresh-2/example/lib/main.dart
Error launching application on iPhone 8.

![image](https://user-images.githubusercontent.com/29880468/69946666-0f21c280-1527-11ea-8e4a-bdd008173ea7.png)
![image](https://user-images.githubusercontent.com/29880468/69946701-1ea10b80-1527-11ea-899b-2b49969a684d.png)

**Comment by ahai0831** [comment]
并且在项目中有错误：
``
![image](https://user-images.githubusercontent.com/29880468/69946616-ec8fa980-1526-11ea-8829-7ac6bcfb50f7.png)

**Comment by ahai0831** [comment]
是否跟flutter 版本有关系呢？ 我的当前flutter doctor
![image](https://user-images.githubusercontent.com/29880468/69946945-91aa8200-1527-11ea-9c3a-188af59cccdb.png)

**Comment by xuelongqy** [comment]
请检验flutter版本以及项目依赖库
