### ISSUE TITLE
下拉提示

### ISSUE THREAD

**Issue by dyjmlf** [xuelongqy/flutter_easyrefresh#206]
我已经修改refreshText 文字为 ‘下拉刷新’， 但是下拉的时候，刚出来的还是 ‘Pull to refresh’，等到拉倒一定长度后才变成 ‘下拉刷新’ ， 怎么样设置才能不显示 ‘Pull to refresh’？

**Comment by dyjmlf** [comment]
还有 refreshingText 也已经设置为 ‘刷新中’， 但是松手的瞬间还是显示 ‘Refreshing...’， 然后变成 ‘刷新中’，是我哪里少设置了配置么？

**Comment by xuelongqy** [comment]
请参考示例的设置
