### ISSUE TITLE
自定义Footer中的Widget不能响应事件

### ISSUE THREAD

**Issue by ioshc** [xuelongqy/flutter_easyrefresh#207]
class WooplusFooter extends Footer {

  final VoidCallback onTap;

  WooplusFooter({
    this.onTap,
    completeDuration = const Duration(seconds: 1),
    bool enableHapticFeedback = false,
    bool enableInfiniteLoad = true,
  }): super(
    float: true,
    extent: 78.0,
    triggerDistance: 88.0,
    completeDuration: completeDuration == null
      ? Duration(milliseconds: 300,)
      : completeDuration + Duration(milliseconds: 300,),
    enableHapticFeedback: enableHapticFeedback,
    enableInfiniteLoad: enableInfiniteLoad,
  );

  @override
  Widget contentBuilder(BuildContext context, LoadMode loadState,
    double pulledExtent, double loadTriggerPullDistance,
    double loadIndicatorExtent, AxisDirection axisDirection,
    bool float, Duration completeDuration, bool enableInfiniteLoad,
    bool success, bool noMore) {

    return !noMore
      ? Container(child: buildLoading(context), alignment: Alignment.center,)
      :
    FlatButton(
      onPressed: () {
        print('onPressed');
      },
      child: Text('点我点我'),
    );
  }
}

点击按钮没有点击效果，里面的onPressed函数也不会执行

**Comment by xuelongqy** [comment]
最新源码已支持手势，将在下一个版本发布

**Comment by ioshc** [comment]
请问什么时候可以发布新版支持手势？
或者请问修改当前版本的什么地方可以支持手势，我们近期会发版，所以希望能尽快解决这个问题。谢谢

**Comment by xuelongqy** [comment]
已更新，请升级至2.0.5版本
