### ISSUE TITLE
上拉加载 报错的话 好像没有显示loadFailedText

### ISSUE THREAD

**Issue by FullChargeComplete** [xuelongqy/flutter_easyrefresh#211]

**Comment by ZhuSiSheng** [comment]
![WechatIMG1](https://user-images.githubusercontent.com/35139593/70375487-4209f300-1939-11ea-96a4-a9bb0611b7cc.jpeg)
![WechatIMG2](https://user-images.githubusercontent.com/35139593/70375488-4209f300-1939-11ea-8f8f-aafab123f94a.jpeg)

**Comment by xuelongqy** [comment]
需要使用EasrRefreshController控制哦

**Comment by FullChargeComplete** [comment]
已经用了 EasyRefreshController 做控制了 还是报错了

**Comment by FullChargeComplete** [comment]
EasyRefreshController _controller = EasyRefreshController();


 _controller.finishLoad(success: false,noMore: false);

不知道这样调用对不对  谢谢大佬

**Comment by xuelongqy** [comment]
测试过没有问题，你应该是没有把在EasyRefresh中设置controller参数吧

**Comment by FullChargeComplete** [comment]
大佬 你好 我是这样设置了下  ClassicalFooter

具体代码
import 'package:flutter_easyrefresh/easy_refresh.dart';

loadMoreFoot(){
  return ClassicalFooter(
                    loadText: '上拉加载更多',
                    loadReadyText: '释放加载',
                    loadingText: '加载中···',
                    loadedText: '加载完成',
                    loadFailedText: '加载失败',
                    noMoreText: '没有更多了',
                    infoText: '上次上拉 %T'
                  );
}



 EasyRefresh(
                  header: refreshHader(),
                  footer: loadMoreFoot(),
                  emptyWidget:screenData.tabData['demand']['list'].length==0? emptyWidget():null,
                  controller: _controller,

**Comment by xuelongqy** [comment]
不好意思，之前没考虑到无限加载的情况。问题已修复，将会在下一个版本发布

**Comment by xuelongqy** [comment]
已修复，请更新至2.0.6

**Comment by FullChargeComplete** [comment]
辛苦大佬 @xuelongqy
