### ISSUE TITLE
在NestedScrollView下给EasyRefresh设置firstRefresh:true会出现问题

### ISSUE THREAD

**Issue by LvJson** [xuelongqy/flutter_easyrefresh#213]
在有NestedScrollView且firstRefresh为true的情况下，我不给EasyRefresh设置scrollController时，整个界面会向上顶一下才刷新，如果给EasyRefresh设置scrollController则会出现头部被固定，无法滑动的情况。原因应该是scrollController的设置影响了NestedScrollView对内部滑动的控制，求解决。

**Comment by xuelongqy** [comment]
对于NestedScrollView的问题，目前基本都无解，不推荐使用

**Comment by xuelongqy** [comment]
不使用TabBarView的组合，建议使用CustomScrollView
