### ISSUE TITLE
希望可以真正配置回弹效果

### ISSUE THREAD

**Issue by hidetag** [xuelongqy/flutter_easyrefresh#215]
- 虽说目前提供了类似 api，但这属于治标不治本？关闭回弹后，上拉下拉的功能也就失效了
- 回弹效果来自于 iOS，但实际上根据需求，有的并不需要回弹效果
- 所以希望能真正放开回弹效果的配置，顶部的非回弹效果同原生纸墨设计的效果，底部非回弹效果同普通非回弹

**Comment by xuelongqy** [comment]
EasyRefresh的原理正是来自于回弹效果计算偏移量，如果找到更好的方案可以一起研究
