### ISSUE TITLE
上拉加载，调用controller.finishLoad方法，加载依然无法停止

### ISSUE THREAD

**Issue by Ian0903** [xuelongqy/flutter_easyrefresh#216]
上拉加载时，无论调用controller.finishLoad(succes:true)还是controller.finishLoad(succes:fasle)时，都无法让加载停止，EasyRefresh里已经加入了controller。

**Comment by xuelongqy** [comment]
描述不明确，无法找到问题。请按照要求提出issue

**Comment by Ian0903** [comment]
无网络状态下，上拉加载时，调用controller.finishLoad(success:false)方法，加载的footer动画不停止。

**Comment by Ian0903** [comment]
onLoad: () async {
          bool result = await Future.delayed(Duration(seconds: 2), () {
            //模拟网络请求
            return false;
          });
          _controller.finishLoad(success: result);
        },


加载动画不停止

**Comment by Ian0903** [comment]
更新了2.0.6版后，第一次上拉加载能手动停止了，但第二次再上拉加载时又无法停止。

样例代码：
onLoad: () async {
bool result = await Future.delayed(Duration(seconds: 2), () {
//模拟网络请求
return false;
});
            easyRefreshController.resetLoadState();
            easyRefreshController.finishLoad(success: result);
},

**Comment by xuelongqy** [comment]
最新版本还有问题吗？resetLoadState在没有使用没有更多数据的时候，尽量不要使用
