### ISSUE TITLE
Error type 'String' is not a subtype of type 'bool'

### ISSUE THREAD

**Issue by fuyucn** [xuelongqy/flutter_easyrefresh#217]
Seems for new flutter version 1.12.13, got error "type 'String' is not a subtype of type 'bool'" when set header and footer text.

Error is when checking if text is 'null'

``` 
String get _refreshText {
    return widget.classicalHeader.refreshText ??
            GlobalEasyRefreshLocalizations.of(context) == null
        ? _localizations.pullToRefresh
        : GlobalEasyRefreshLocalizations.of(context).pullToRefresh;
  }
```

**Comment by Khan0z** [comment]
String get _loadText {
    return widget.classicalFooter.loadText ??
            GlobalEasyRefreshLocalizations.of(context) == null


Same problem

**Comment by a642815311** [comment]
I also encountered this problem, please developers to solve it quickly, my boss is going to fire me,Pity the weak and helpless Chinese coder.

**Comment by xuelongqy** [comment]
v2.0.7 fixed it

**Comment by FullChargeComplete** [comment]
大佬升级2.0.7 报错
Compiler message:
/Applications/flutter/.pub-cache/hosted/pub.flutter-io.cn/flutter_easyrefresh-2.0.7/lib/src/header/refresh_indicator.dart:541:10:
Error: The method 'findAncestorStateOfType' isn't defined for the class 'BuildContext'.
 - 'BuildContext' is from 'package:flutter/src/widgets/framework.dart'
 ('/Applications/flutter/packages/flutter/lib/src/widgets/framework.dart').
Try correcting the name to the name of an existing method, or defining a method named 'findAncestorStateOfType'.
        .findAncestorStateOfType<_EasyRefreshSliverRefreshControlState>();
         ^^^^^^^^^^^^^^^^^^^^^^^
/Applications/flutter/.pub-cache/hosted/pub.flutter-io.cn/flutter_easyrefresh-2.0.7/lib/src/footer/load_indicator.dart:519:17:
Error: The method 'findAncestorStateOfType' isn't defined for the class 'BuildContext'.
 - 'BuildContext' is from 'package:flutter/src/widgets/framework.dart'
 ('/Applications/flutter/packages/flutter/lib/src/widgets/framework.dart').
Try correcting the name to the name of an existing method, or defining a method named 'fi

**Comment by yayxs** [comment]
是的 有遇到同样的问题
The following assertion was thrown building ClassicalHeaderWidget(dirty, state:
I/flutter ( 8920): ClassicalHeaderWidgetState#da85b(tickers: tracking 3 tickers)):
I/flutter ( 8920): type 'String' is not a subtype of type 'bool'
I/flutter ( 8920):
I/flutter ( 8920): Either the assertion indicates an error in the framework itself, or we should provide substantially
I/flutter ( 8920): more information in this error message to help you determine and fix the underlying cause.
I/flutter ( 8920): In either case, please report this assertion by filing a bug on GitHub:
I/flutter ( 8920):   https://github.com/flutter/flutter/issues/new?template=BUG.md

**Comment by xuelongqy** [comment]
> s

请升级版本
