### ISSUE TITLE
用2.0.7版本出现的问题

### ISSUE THREAD

**Issue by wangfeigit** [xuelongqy/flutter_easyrefresh#220]
用2.0.7版本出现的问题：
Compiler message:
/D:/flutter/flutter_windows/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_easyrefresh-2.0.7/lib/src/header/refresh_indicator.dart:541:10: Error: The method 'findAncestorStateOfType' isn't defined for the class 'BuildContext'.
 - 'BuildContext' is from 'package:flutter/src/widgets/framework.dart' ('/D:/flutter/flutter_windows/flutter/packages/flutter/lib/src/widgets/framework.dart').
Try correcting the name to the name of an existing method, or defining a method named 'findAncestorStateOfType'.
        .findAncestorStateOfType<_EasyRefreshSliverRefreshControlState>();
         ^^^^^^^^^^^^^^^^^^^^^^^
/D:/flutter/flutter_windows/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_easyrefresh-2.0.7/lib/src/footer/load_indicator.dart:519:17: Error: The method 'findAncestorStateOfType' isn't defined for the class 'BuildContext'.
 - 'BuildContext' is from 'package:flutter/src/widgets/framework.dart' ('/D:/flutter/flutter_windows/flutter/packages/flutter/lib/src/widgets/framework.dart').
Try correcting the name to the name of an existing method, or defining a method named 'findAncestorStateOfType'.
        context.findAncestorStateOfType<_EasyRefreshSliverLoadControlState>();
                ^^^^^^^^^^^^^^^^^^^^^^^
Compiler failed on D:\flutter_project\flutter_app\lib\main.dart
Finished with error: Gradle task assembleDebug failed with exit code 1

**Comment by xuelongqy** [comment]
请升级Flutter1.12.13

**Comment by xuelongqy** [comment]
已做兼容 请升级至2.0.8版本
