### ISSUE TITLE
./../flutter/.pub-cache/hosted/pub.dartlang.org/flutter_easyrefresh-2.0.7/lib/src/header/refresh_indicator.dart:541:10: Error: The method 'findAncestorStateOfType' isn't defined for the class 'BuildContext'.  - 'BuildContext' is from 'package:flutter/src/widgets/framework.dart' ('../../flutter/packages/flutter/lib/src/widgets/framework.dart'). Try correcting the name to the name of an existing method, or defining a method named 'findAncestorStateOfType'.         .findAncestorStateOfType<_EasyRefreshSliverRefreshControlState>();          ^^^^^^^^^^^^^^^^^^^^^^^

### ISSUE THREAD

**Issue by MrWangYc** [xuelongqy/flutter_easyrefresh#221]
mac 上项目一直报这个错误，请问要如何处理
./../flutter/.pub-cache/hosted/pub.dartlang.org/flutter_easyrefresh-2.0.7/lib/src/header/refresh_indicator.dart:541:10: Error: The method 'findAncestorStateOfType' isn't defined for the class 'BuildContext'.
 - 'BuildContext' is from 'package:flutter/src/widgets/framework.dart' ('../../flutter/packages/flutter/lib/src/widgets/framework.dart').
Try correcting the name to the name of an existing method, or defining a method named 'findAncestorStateOfType'.
        .findAncestorStateOfType<_EasyRefreshSliverRefreshControlState>();
         ^^^^^^^^^^^^^^^^^^^^^^^

**Comment by xuelongqy** [comment]
请升级至2.0.8版本

**Comment by yayxs** [comment]
Because flutter_easyrefresh_demo2 depends on flutter_easyrefresh ^2.0.8 which doesn't match any versions, version solving failed.
