### ISSUE TITLE
同时使用首次刷新、下拉刷新、上拉加载，会造成请求后拿到数据  header再次显示,使用finishRefresh无法关闭

### ISSUE THREAD

**Issue by liuchouchou0728** [xuelongqy/flutter_easyrefresh#225]
代码：
class OrderList extends StatefulWidget {
  const OrderList({
    Key key,
    this.flag,
    this.controller,
    this.projectTypeFlag,
    this.projectId,
    this.keyword,
    this.status,
    this.localStatus,
    this.isFirstLoad,
    this.isEmpty,
    this.onRefresh,
    this.onLoadMore,
    this.orderList,
    this.orderStatusMap,
  }) : super(key: key);

  final String flag;
  final EasyRefreshController controller;
  final String projectTypeFlag;
  final int projectId;
  final String keyword;
  final int status;
  final int localStatus;
  final bool isFirstLoad;
  final bool isEmpty;
  final RefreshCallback onRefresh;
  final LoadMoreCallback onLoadMore;
  final List<OrderListDataData> orderList;
  final List<OrderStatusOptionData> orderStatusMap;

  @override
  _OrderListState createState() => _OrderListState();
}

typedef RefreshCallback = Future<void> Function();
typedef LoadMoreCallback = Future<void> Function();

class _OrderListState extends State<OrderList> {
  @override
  Widget build(BuildContext context) {
    return EasyRefresh(
      controller: widget.controller,
      enableControlFinishRefresh: true,
      enableControlFinishLoad: true,
      child: ListView.builder(
        padding: EdgeInsets.all(0.0),
        itemCount: widget.orderList.length ?? 0,
        itemBuilder: (context, index) {
          var data = widget.orderList[index] ?? null;
          return Container(
            child: OrderCard(
              data: data,
              orderStatusMap: widget.orderStatusMap,
            ),
          );
        },
      ),
      onRefresh: () async {
        await widget.onRefresh();
      },
      onLoad: () async {
        await widget.onLoadMore();
      },
      firstRefresh: widget.isFirstLoad,
      firstRefreshWidget: widget.isFirstLoad
          ? Container(
              width: double.infinity,
              height: double.infinity,
              child: Center(
                child: Column(
                  mainAxisAlignment: MainAxisAlignment.center,
                  crossAxisAlignment: CrossAxisAlignment.center,
                  children: <Widget>[
                    Container(
                      width: 50,
                      child: LoadingIndicator(
                        indicatorType: Indicator.ballPulse,
                        color: Colours.app_main,
                      ),
                    ),
                    Container(
                      child: Text('数据加载中...'),
                    )
                  ],
                ),
              ),
            )
          : null,
      emptyWidget: widget.isEmpty
          ? Container(
              width: double.infinity,
              height: double.infinity,
              child: Center(
                child: Column(
                  mainAxisAlignment: MainAxisAlignment.center,
                  crossAxisAlignment: CrossAxisAlignment.center,
                  children: <Widget>[
                    Container(
                      child: Text(
                        '暂无数据!',
                        style: TextStyle(
                          color: Colours.text_gray,
                          fontSize: Dimens.dp18,
                        ),
                      ),
                    )
                  ],
                ),
              ),
            )
          : null,
      header: ClassicalHeader(
        refreshText: "下拉刷新",
        refreshReadyText: "松开刷新",
        refreshingText: "刷新中",
        refreshedText: "刷新完成",
        refreshFailedText: "刷新失败",
        showInfo: false,
      ),
      footer: ClassicalFooter(
        loadText: "上拉加载",
        loadReadyText: "松开加载",
        loadingText: "加载中",
        loadedText: "加载完成",
        loadFailedText: "加载失败",
        noMoreText: "没有更多了",
        showInfo: false,
      ),
    );
  }
}

**Comment by xuelongqy** [comment]
enableControlFinish请都设置为false，使用前请参考文档
