### ISSUE TITLE
调用callRefresh，没有效果

### ISSUE THREAD

**Issue by li-xiaojun** [xuelongqy/flutter_easyrefresh#229]
![image](https://user-images.githubusercontent.com/4426715/71662373-3836ac80-2d8c-11ea-897e-95f2b7a726ef.png)
![image](https://user-images.githubusercontent.com/4426715/71662381-4389d800-2d8c-11ea-8c11-6835eeac2fe9.png)
![image](https://user-images.githubusercontent.com/4426715/71662483-98c5e980-2d8c-11ea-8a22-76b32a0c08a4.png)

吐司会弹出，确定代码执行了。
我的需求是第一次进入页面的时候，调用刷新方法开始刷新。
尝试过将firstRefresh和emptyWdiget都注释掉还是不行。
而且firstWdiget相关配置一直不生效。
Flutter 版本 1.12  macOs。

**Comment by xuelongqy** [comment]
我不确定你的问题出在哪里，但是我觉得你是想设置默认样式吧？如果是这样，设置defaultHeader和defaultFooter即可，汉化最新版也有提供，请参考文档。不推荐使用static去创建Widget
