### ISSUE TITLE
easyrefresh为什么不能嵌套在布局空间如ListView或者Column中

### ISSUE THREAD

**Issue by Kyou-sha-Belle-House** [xuelongqy/flutter_easyrefresh#230]
经过尝试，我发现Easyrefresh不能嵌套在任何布局控件中，难道说刷新组件必须是顶级的可视组件么？这显然是不合理的，代码如下
Column(
                children: <Widget>[
                ...
                Containe(位置A)
                ...
                 Container(
                    child: EasyRefresh.custom(
                      header: BallPulseHeader(),
                      footer: BallPulseFooter(),
                      onRefresh: () async { },
                      onLoad: () async { },
                      slivers: <Widget>[ ],
                    ),
                  ),
                ],
              ),
这样的代码就因为EasyRefresh外层有Column而无法使用，但是实际需求是，我需要在位置A放某些控件，请问作者，如何解决

**Comment by xuelongqy** [comment]
因为列表为无限长，请补充flutter基础知识
