### ISSUE TITLE
loadmore完成之后，footer依然显示

### ISSUE THREAD

**Issue by javavaan** [xuelongqy/flutter_easyrefresh#231]
加载更多完成会后，footer为啥没消失

`controller: _controller,
              onLoad: () async {
                await Future.delayed(Duration(seconds: 2), () {
                  setState(() {
                    hotProducts.add(RecommendProductDes(
                        'http://pic1.win4000.com/wallpaper/8/543797494cbb2.jpg',
                        '1999999',
                        "222"));
//                    hotProducts.clear();
                    _controller.finishLoad(noMore: false,success: true);
                  });
                });
              },
              enableControlFinishLoad: false,
            );`

**Comment by xuelongqy** [comment]
请关闭无限加载

**Comment by sym233** [comment]
> 请关闭无限加载

finishLoad(nomore: true)之后，即使enableInfinteLoad: false, footer也不收回，是feature吗
