### ISSUE TITLE
noMore 设为 true 上拉依然可以加载

### ISSUE THREAD

**Issue by cv0cv0** [xuelongqy/flutter_easyrefresh#232]
要再上拉一次再请求一次接口才会显示没有数据。

**Comment by xuelongqy** [comment]
如果测试示例没有问题，请检验您代码的逻辑

**Comment by cv0cv0** [comment]
@xuelongqy 我是这样用的：
<img width="443" alt="image" src="https://user-images.githubusercontent.com/18623780/72120559-4cce0280-3393-11ea-8d1c-55bdeab858e9.png">
<img width="575" alt="image" src="https://user-images.githubusercontent.com/18623780/72120593-67a07700-3393-11ea-927d-6c5ba1ee2114.png">
第一次请求成功 noMore 其实已经为 true 了，但是需要再上拉一次才行。

**Comment by xuelongqy** [comment]
试试将setState放到前面呢？刷新和加载同是只会执行一个操作，你可以用一个参数来判断当前操作是刷新还是加载

**Comment by cv0cv0** [comment]
> 试试将setState放到前面呢？刷新和加载同是只会执行一个操作，你可以用一个参数来判断当前操作是刷新还是加载

还是一样。

**Comment by seekcx** [comment]
+1，一样的问题。

其实感觉 nomore 完全可以作为一个属性，直接用 state 来控制，为什么要加一个 controller 呢？

**Comment by xuelongqy** [comment]
> +1，一样的问题。
> 
> 其实感觉 nomore 完全可以作为一个属性，直接用 state 来控制，为什么要加一个 controller 呢？

错误的方式，不采纳。具体原因可参考源码
