### ISSUE TITLE
使用bloc作为数据层之后出现动画不理想化

### ISSUE THREAD

**Issue by tom0gao** [xuelongqy/flutter_easyrefresh#236]
BlocProvider(
      create: (BuildContext context) {
        _homeProductListBlocBloc = HomeProductListBlocBloc(
            cancelToken: cancelToken,
            productService: productService,
            categoryLevel1: int.parse(widget.categoryListItemBean.id));
        return _homeProductListBlocBloc..add(Fetch());
      },
      child: BlocBuilder<HomeProductListBlocBloc, HomeProductListBlocState>(
          builder: (context, state) {
        return BlocListener<HomeProductListBlocBloc, HomeProductListBlocState>(
            listener: (context, state) {
              if (state is LoadedHomeProductListBlocState) {
//如果我在 下面的refresh回调方法中 手动等待5秒 在这里网络请求完成后(只花了三秒) 手动关闭 下拉状态不会消失
                finishEasyRefresh(noMore: state.hasReachedMax);
              }
            },
            child: GRefresh(
              controller: easyRefreshController,
              emptyWidget: state is InitialHomeProductListBlocState ||
                      (state is LoadedHomeProductListBlocState &&
                          state.list.length == 0)
                  ? EmptyView(
                      type: 'product',
                      isLoadComplete:
                          !(state is InitialHomeProductListBlocState),
                    )
                  : null,
              onRefresh: () async {
//这里如果不等待 会直接关闭下拉状态
                _homeProductListBlocBloc.add(Fetch());
              },
              onLoad: () async {
                _homeProductListBlocBloc.add(Fetch(isRefresh: false));
              },
              child: Padding(
                padding: EdgeInsets.symmetric(horizontal: 16),
                child: Wrap(
                  spacing: 8,
                  runSpacing: 16,
                  children: state is LoadedHomeProductListBlocState
                      ? state.list
                          .map((item) => ProductItemVertical(
                                data: item,
                              ))
                          .toList()
                      : [],
                ),
              ),
            ));
      })

**Comment by lionoggo** [comment]
> BlocProvider(
> create: (BuildContext context) {
> _homeProductListBlocBloc = HomeProductListBlocBloc(
> cancelToken: cancelToken,
> productService: productService,
> categoryLevel1: int.parse(widget.categoryListItemBean.id));
> return _homeProductListBlocBloc..add(Fetch());
> },
> child: BlocBuilder<HomeProductListBlocBloc, HomeProductListBlocState>(
> builder: (context, state) {
> return BlocListener<HomeProductListBlocBloc, HomeProductListBlocState>(
> listener: (context, state) {
> if (state is LoadedHomeProductListBlocState) {
> //如果我在 下面的refresh回调方法中 手动等待5秒 在这里网络请求完成后(只花了三秒) 手动关闭 下拉状态不会消失
> finishEasyRefresh(noMore: state.hasReachedMax);
> }
> },
> child: GRefresh(
> controller: easyRefreshController,
> emptyWidget: state is InitialHomeProductListBlocState ||
> (state is LoadedHomeProductListBlocState &&
> state.list.length == 0)
> ? EmptyView(
> type: 'product',
> isLoadComplete:
> !(state is InitialHomeProductListBlocState),
> )
> : null,
> onRefresh: () async {
> //这里如果不等待 会直接关闭下拉状态
> _homeProductListBlocBloc.add(Fetch());
> },
> onLoad: () async {
> _homeProductListBlocBloc.add(Fetch(isRefresh: false));
> },
> child: Padding(
> padding: EdgeInsets.symmetric(horizontal: 16),
> child: Wrap(
> spacing: 8,
> runSpacing: 16,
> children: state is LoadedHomeProductListBlocState
> ? state.list
> .map((item) => ProductItemVertical(
> data: item,
> ))
> .toList()
> : [],
> ),
> ),
> ));
> })

在使用bloc时,可以主动控制刷新操作和结束.比如在发出event的时候通知刷新开始,在收到state时候通知刷新结束
