### ISSUE TITLE
1.2.3 版本下拉刷新报错

### ISSUE THREAD

**Issue by Zhengyangma** [xuelongqy/flutter_easyrefresh#24]
错误信息：trying to call updateHeight() of null

**Comment by xuelongqy** [comment]
能说一下，在什么情况下发生的错误吗？或者贴上使用示例的代码

**Comment by Zhengyangma** [comment]
onRefresh的代码和loadMore回调的代码是一样的。
升上1.2.3后loadmore就报错了（onRefresh 没有问题），我现在用的是降过版本的1.1.0。
代码没有变动过，但loadmore的时候不报updateHeight()的错误。
###
`EasyRefresh(
       `refreshHeader: ClassicsHeader(
        bgColor: Colors.lightBlue[700],
        key: widget.erHeaderKey,
      ),
      refreshFooter: ClassicsFooter(
        bgColor: Colors.lightBlue[700],
        key: widget.erFooterKey,
        noMoreText: 'Finished',
      ),
      onRefresh: () async { await loadMoreList();
          return; },
      loadMore: () async {
          await loadMoreList();
          return;
      }
)`

**Comment by Zhengyangma** [comment]
下拉之后松开手，触发读取更多的回调函数就会报错。

**Comment by xuelongqy** [comment]
那可能是flutter版本的问题，有时间我研究一下

**Comment by xuelongqy** [comment]
我试了flutter 1.2.1没有问题。Demo运行报错吗？能给我一个简单的示例吗，我找找问题

**Comment by Zhengyangma** [comment]
> 我试了flutter 1.2.1没有问题。Demo运行报错吗？能给我一个简单的示例吗，我找找问题

我用的是CustomScrollView, 也许和新的那位同学的PR有关，你要不看下那个PR。

代码不太方便给示例。 Sorry。= =

**Comment by xuelongqy** [comment]
1.2.5已解决
