### ISSUE TITLE
在TabBarView里包裹EasyRefresh的BUG

### ISSUE THREAD

**Issue by leeewh** [xuelongqy/flutter_easyrefresh#240]
flutter的TabBarView没有预加载功能，所以每个tabview第一次被切换到的时候才会渲染。

现在的问题是，比如我有5个tabview,里面全部包裹了一个EasyRefresh。当我从第一个tabview切换到第二个的时候，第一个tabview里的EasyRefresh会执行一遍下拉动画（仅仅是动画，没有触发OnRefresh）。我设置了firstRefresh为true。

**Comment by xuelongqy** [comment]
这不是Bug，你可以研究一下Flutter源码，为什么会有这个现象。设置ScrollController即可

**Comment by leeewh** [comment]
> 这不是Bug，你可以研究一下Flutter源码，为什么会有这个现象。设置ScrollController即可

谢谢！
