### ISSUE TITLE
EasyRefresh.builder中怎么使用emptyWidget、firstRefreshWidget

### ISSUE THREAD

**Issue by lulu116** [xuelongqy/flutter_easyrefresh#243]
EasyRefresh.builder({
    key,
    this.controller,
    this.onRefresh,
    this.onLoad,
    this.enableControlFinishRefresh = false,
    this.enableControlFinishLoad = false,
    this.taskIndependence = false,
    this.scrollController,
    this.header,
    this.footer,
    this.firstRefresh,
    this.topBouncing = true,
    this.bottomBouncing = true,
    @required this.builder,
  })  : this.scrollDirection = null,
        this.reverse = null,
        this.child = null,
        this.primary = null,
        this.shrinkWrap = null,
        this.center = null,
        this.anchor = null,
        this.cacheExtent = null,
        this.slivers = null,
        this.semanticChildCount = null,
        this.dragStartBehavior = null,
        this.headerIndex = null,
        this.firstRefreshWidget = null,
        this.emptyWidget = null;

**Comment by xuelongqy** [comment]
builder是最灵活的，你可以参照源码自行添加
