### ISSUE TITLE
'RefreshHeaderState'.dart(non_type_as_type_argument)

### ISSUE THREAD

**Issue by Mr-Cai** [xuelongqy/flutter_easyrefresh#246]
RefreshHeaderState 1.2.7 正常使用, 更新至2.0.8后类缺失，不知道该替换成什么？原来的写法是
GlobalKey<RefreshHeaderState> _headerKey1

**Comment by shabake** [comment]
一样的问题 
 
GlobalKey<RefreshHeaderState>  _key = new  GlobalKey<RefreshHeaderState>();

报错
