### ISSUE TITLE
滑动时发生回滚

### ISSUE THREAD

**Issue by jujingyi0618** [xuelongqy/flutter_easyrefresh#247]
代码
return Scaffold(
      appBar: AppBar(title: Text('demo')),
      body: EasyRefresh(
          child: ListView.builder(
            physics: NeverScrollableScrollPhysics(),
            itemCount: 105,
            itemBuilder: (context, index) {
              return ListTile(title: Text('$index'));
            },
          ),
          onLoad: () async{
            print('load');
          },
        )
    );
我录了个视频
http://gfoxcdn.gfoxsoft.net/my/q3.mp4

**Comment by jujingyi0618** [comment]
按住屏幕向上拉或向下拉 然后松开 发生这种现象

**Comment by xuelongqy** [comment]
估计是模拟器的问题，真机应该没问题。你试试看呢

**Comment by jujingyi0618** [comment]
我测试了 直接使用listview 在模拟器回滚严重，在真机上正常。
套用EasyRefresh后，模拟器回滚严重，真机 有时候 有轻微的回滚 大约在1厘米之内

**Comment by xiejibiao** [comment]
这个问题我也遇到了，请问您解决了吗？
