### ISSUE TITLE
NoSuchMethodError: The method '>' was called on null

### ISSUE THREAD

**Issue by CatEatFishs** [xuelongqy/flutter_easyrefresh#25]
你好，我1.2.4版本还是出现这个问题，我在曾经的issues 中看到过，但是我还是出现这个问题，
`new EasyRefresh(
        key: _easyRefreshKey,
        refreshHeader: MaterialHeader(
          key: _headerKey,
        ),
        refreshFooter: MaterialFooter(
          key: _footerKey,
        ),
        child:
        CustomScrollView(
          slivers: <Widget>[
            SliverList(
              delegate: SliverChildBuilderDelegate(
                    (BuildContext context, int index) {
                  return OrganizationItem(
                      index: index, followButtonHidden: true, item: list[index]);
                },
                childCount: list==null ? 0 : list.length,
              ),
            )
          ],
        ),
        onRefresh: () async {
          await new Future.delayed(const Duration(seconds: 1), () {
            list.clear();
            this.isShowLoading=false;
            isMore=true;
            pageNum='1';
            followListRequest(studentId, pageNum, pageSize);
          });
        },
        loadMore: () async {
          await new Future.delayed(const Duration(seconds: 1), () {
            if(isMore){
              this.isShowLoading=false;
              pageNum=(int.parse(pageNum)+1).toString();
//              followListRequest(studentId, pageNum, pageSize);
            }else{
              Alert.toast(context, '已加载完全部' ,
                  position: ToastPosition.center, duration: ToastDuration.short);
            }
          });
        },
      ),`
这是我的代码，上拉加载就报错NoSuchMethodError: The method '>' was called on null，麻烦解决一下

**Comment by jiangyue2780** [comment]
+1

**Comment by xuelongqy** [comment]
可以定位一下错误吗？因为我没有遇到过这个情况。我的猜想是否在body.semanticChildCount > this._itemCount的判断出错？

**Comment by xuelongqy** [comment]
或者给我一个简单运行的示例

**Comment by xuelongqy** [comment]
1.2.5已解决
