### ISSUE TITLE
1.12.13+hotfix.7  无法下拉刷新

### ISSUE THREAD

**Issue by moxc** [xuelongqy/flutter_easyrefresh#250]
firstRefreshWidget 与 emptyWidget 不为null时出现

**Comment by yjouyang** [comment]
Same Problem

**Comment by yjouyang** [comment]
求fix

**Comment by galaxybruce** [comment]
_taskNotifier.addListener(() {
      // 监听首次刷新是否结束
      if (_enableFirstRefresh && !_taskNotifier.value.refreshing) {
        _scrollerController.jumpTo(0.0);
        setState(() {
          _enableFirstRefresh = false;
        });
      }
    });

这里个监听没执行，_enableFirstRefresh永远是true

**Comment by xuelongqy** [comment]
2.1.0已修复
