### ISSUE TITLE
IOS GlobalEasyRefreshLocalizations failed

### ISSUE THREAD

**Issue by virskor** [xuelongqy/flutter_easyrefresh#252]
current easy refresh version: 2.0.9
flutter: latest stable channel
device: ios
> A GlobalEasyRefreshLocalizations delegate that supports the zh_Hans_BR locale was not found.
You will see this issue by switching your  IOS device's location. try Taiwan or HK etc.

IOS: 13

**Comment by virskor** [comment]
```dart
MaterialApp(
        localizationsDelegates: const [
          GlobalCupertinoLocalizations.delegate,
          GlobalMaterialLocalizations.delegate,
          GlobalWidgetsLocalizations.delegate,
          GlobalEasyRefreshLocalizations.delegate,
        ],
)
```

**Comment by xuelongqy** [comment]
Currently only Chinese and English are supported. You can set the language you need in Header and Footer
