### ISSUE TITLE
怎么显示头部刷新状态，又不触发刷新事件？

### ISSUE THREAD

**Issue by JakeWoki** [xuelongqy/flutter_easyrefresh#254]
主动显示刷新动画，但不触发相应事件，类似google的SwipeRefreshLayout的方法setRefreshing（android）

**Comment by xuelongqy** [comment]
结合EasyRefreshController，事件会触发，但是可以不处理

**Comment by JakeWoki** [comment]
但是手动下拉刷新时，是需要触发事件的，使用EasyRefreshController的callRefresh做不到

**Comment by xuelongqy** [comment]
我认为通过代码控制就可以了，无非是多一些类似if的判断。试试NotificationHeader呢

**Comment by JakeWoki** [comment]
增加RefreshMode refreshState属性的改变不是更好吗？

**Comment by xuelongqy** [comment]
个人需求，不在框架的考虑范围内，请谅解
