### ISSUE TITLE
指定firstRefreshWidget ，首次加载完，不能再执行下拉刷新

### ISSUE THREAD

**Issue by xilibro** [xuelongqy/flutter_easyrefresh#256]
EasyRefresh.custom 设置了 firstRefresh 为 true之后，不能执行下拉刷新了。。
前两天还可以的。
现在下载的demo也不能执行。
iPhone 6 Plus  12.4.5
刚升级了flutter（升级前也是不可以的 1.12+）
[✓] Flutter (Channel dev, v1.15.3, on Mac OS X 10.14.6 18G103, locale zh-Hans-CN)
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
[✓] Xcode - develop for iOS and macOS (Xcode 11.3)
[✓] Android Studio (version 3.5)
[✓] IntelliJ IDEA Ultimate Edition (version 2017.3.5)
[✓] Connected device (2 available)

**Comment by xilibro** [comment]
刚刚实验了一下，是指定了firstRefreshWidget的缘故。注释掉以后，下拉刷新可用。希望能解决一下。

**Comment by dexcell** [comment]
I have same issue.

**Comment by xuelongqy** [comment]
2.1.0已修复
