### ISSUE TITLE
下拉刷新  和  上拉刷新那个提示文字怎么改成中文呀?

### ISSUE THREAD

**Issue by xiaowang1314** [xuelongqy/flutter_easyrefresh#257]

**Comment by Exclusive-gfj** [comment]
请问有解决这个问题吗? 能否告知一下

**Comment by evansherry** [comment]
同问。麻烦大佬答复下@xuelongqy 
这个多语言配置使用GeneratedLocalizationsDelegate是写死的不支持扩展。
i18n插件bug比较多，建议更换i10n

**Comment by xiaowang1314** [comment]
```
import 'dart:async';

import 'package:flutter/material.dart';
import 'package:flutter_easyrefresh/easy_refresh.dart';

class StoreResaleAnalyze extends StatefulWidget {
  @override
  _StoreResaleAnalyzeState createState() {
    // TODO: implement createState
    return _StoreResaleAnalyzeState();
  }
}

class _StoreResaleAnalyzeState extends State<StoreResaleAnalyze> {
  EasyRefreshController _controller = EasyRefreshController();
  @override
  Widget build(BuildContext context) {
    // TODO: implement build
    return Scaffold(
      appBar: AppBar(
        title: Text('门店零售统计分析'),
      ),
      body: EasyRefresh(
        controller: _controller,
        enableControlFinishRefresh: true,
        enableControlFinishLoad: true,
        firstRefresh: true,
        header: ClassicalHeader(
          refreshText: "下拉刷新",
          refreshReadyText: "松开后开始刷新",
          refreshingText: "正在刷新...",
          refreshedText: "刷新完成",
          bgColor: Colors.transparent,
          textColor: Colors.black87,
        ),
        footer: ClassicalFooter(
          loadText: "上拉加载更多",
          loadReadyText: "松开后开始加载",
          loadingText: "正在加载...",
          loadedText: "加载完成",
          noMoreText: "没有更多内容了",
          bgColor: Colors.transparent,
          textColor: Colors.black87,
        ),
        child: ListView(
          children: <Widget>[
            Text('data'),
          ],
        ),
        onRefresh: () async {
          print('onRefresh');
          Timer(Duration(seconds: 2), () {
            print('2秒 onRefresh cd');
            _controller.finishRefresh(success: true);
          });
        },
        onLoad: () async {
          print('onLoad');
          Timer(Duration(seconds: 2), () {
            print('2秒 onLoad cd');
            _controller.finishLoad(success: true, noMore: false);
          });
        },
      ),
    );
  }
}

```
@Exclusive-gfj @evansherry 看了源码可以这样配置

**Comment by evansherry** [comment]
@xiaowang1314 你这是demo吗。ClassicalHeader过于丑陋，现在没出设计只能将就使用，
我的实现和你一个意思。
作者想通过多语言来实现，本来是没什么问题的，锅在于i18n那个插件。

```
class DefaultHeader extends ClassicalHeader{
  final BuildContext context;
  
  DefaultHeader(this.context): super();
  
  @override
  String get refreshText => S.of(context).pullToRefresh;

  @override
  String get refreshedText => S.of(context).refreshed;

  @override
  String get refreshReadyText => S.of(context).releaseToRefresh;

  @override
  String get refreshingText => S.of(context).refreshing;

  @override
  String get refreshFailedText => S.of(context).refreshFailed;

  @override
  String get infoText => S.of(context).updateAt;
  
  @override
  Color get infoColor => FanColors.color_9B9B9B;
}
```

**Comment by xiaowang1314** [comment]
@evansherry 是的

**Comment by xuelongqy** [comment]
文档中的国际化，不能使用吗？example项目运行没有问题的，可以参考一下呢？

**Comment by Exclusive-gfj** [comment]
@xuelongqy 按照文档中配置了，就是不显示。example 项目里面是直接之定义了，那是不是组件的国际化支持有问题呢？

**Comment by xuelongqy** [comment]
国际化将会在下一个版本删除，原因是太过鸡肋，没有实用价值。请自定义国际化

**Comment by yy1234** [comment]
> ```
> import 'dart:async';
> 
> import 'package:flutter/material.dart';
> import 'package:flutter_easyrefresh/easy_refresh.dart';
> 
> class StoreResaleAnalyze extends StatefulWidget {
>   @override
>   _StoreResaleAnalyzeState createState() {
>     // TODO: implement createState
>     return _StoreResaleAnalyzeState();
>   }
> }
> 
> class _StoreResaleAnalyzeState extends State<StoreResaleAnalyze> {
>   EasyRefreshController _controller = EasyRefreshController();
>   @override
>   Widget build(BuildContext context) {
>     // TODO: implement build
>     return Scaffold(
>       appBar: AppBar(
>         title: Text('门店零售统计分析'),
>       ),
>       body: EasyRefresh(
>         controller: _controller,
>         enableControlFinishRefresh: true,
>         enableControlFinishLoad: true,
>         firstRefresh: true,
>         header: ClassicalHeader(
>           refreshText: "下拉刷新",
>           refreshReadyText: "松开后开始刷新",
>           refreshingText: "正在刷新...",
>           refreshedText: "刷新完成",
>           bgColor: Colors.transparent,
>           textColor: Colors.black87,
>         ),
>         footer: ClassicalFooter(
>           loadText: "上拉加载更多",
>           loadReadyText: "松开后开始加载",
>           loadingText: "正在加载...",
>           loadedText: "加载完成",
>           noMoreText: "没有更多内容了",
>           bgColor: Colors.transparent,
>           textColor: Colors.black87,
>         ),
>         child: ListView(
>           children: <Widget>[
>             Text('data'),
>           ],
>         ),
>         onRefresh: () async {
>           print('onRefresh');
>           Timer(Duration(seconds: 2), () {
>             print('2秒 onRefresh cd');
>             _controller.finishRefresh(success: true);
>           });
>         },
>         onLoad: () async {
>           print('onLoad');
>           Timer(Duration(seconds: 2), () {
>             print('2秒 onLoad cd');
>             _controller.finishLoad(success: true, noMore: false);
>           });
>         },
>       ),
>     );
>   }
> }
> ```
> 
> @Exclusive-gfj @evansherry 看了源码可以这样配置

 // 设置EasyRefresh的默认样式
    EasyRefresh.defaultHeader =  ClassicalHeader(
      refreshText: "下拉刷新",
      refreshReadyText: "松开后开始刷新",
      refreshingText: "正在刷新...",
      refreshedText: "刷新完成",
      bgColor: Colors.transparent,
      textColor: Colors.black87,
      infoText: '更新于 %T',
    );
    EasyRefresh.defaultFooter = ClassicalFooter(
      loadText: "上拉加载更多",
      loadReadyText: "松开后开始加载",
      loadingText: "正在加载...",
      loadedText: "加载完成",
      noMoreText: "没有更多内容了",
      bgColor: Colors.transparent,
      textColor: Colors.black87,
      infoText: '更新于 %T'
    );

可以加个时间

**Comment by zhujiahong** [comment]
为啥我example 项目跑起来也是英文。。。

**Comment by peakerWu** [comment]
【infoText: '更新于 %T'】  大佬，这个%T为啥可以表示时间
