### ISSUE TITLE
可以开发一个类似下拉进入淘宝二楼的功能吗？

### ISSUE THREAD

**Issue by 2534290808** [xuelongqy/flutter_easyrefresh#26]
可以开发一个类似下拉进入淘宝二楼的功能吗？

**Comment by xuelongqy** [comment]
你可以参考示例[SliverPage](https://github.com/xuelongqy/flutter_easyrefresh/blob/master/example/lib/page/sample/sliver_page.dart)，理论可以通过下拉监听去做任何事情

**Comment by xuelongqy** [comment]
二楼示例已添加，[SecondFloorPage ](https://github.com/xuelongqy/flutter_easyrefresh/blob/master/example/lib/page/sample/second_floor_page.dart)。可以下载[Demo](https://github.com/xuelongqy/flutter_easyrefresh/raw/master/art/pkg/EasyRefresh.apk)进行尝试
