### ISSUE TITLE
不支持自定义滚动组件

### ISSUE THREAD

**Issue by wtus** [xuelongqy/flutter_easyrefresh#260]
version： flutter_easyrefresh:2.1.0
描述：
不支持 如  [scrollable_positioned_list](https://github.com/google/flutter.widgets/tree/master/lib/src/scrollable_positioned_list) ,[indexed_list_view](https://github.com/marcglasberg/indexed_list_view), 等自定义滚动组件，请在文档说明相关支持方法

**Comment by xuelongqy** [comment]
EasyRefresh，本身即为滚动组件，如需嵌套，提供slivers支持即可

**Comment by gaoyong06** [comment]
> version： flutter_easyrefresh:2.1.0
> 描述：
> 不支持 如 [scrollable_positioned_list](https://github.com/google/flutter.widgets/tree/master/lib/src/scrollable_positioned_list) ,[indexed_list_view](https://github.com/marcglasberg/indexed_list_view), 等自定义滚动组件，请在文档说明相关支持方法

您好，请问你这个是怎么解决了，我也遇到这个问题，不知如何处理？
