### ISSUE TITLE
键盘弹出后再显示EmptyView，然后再收起键盘，EmptyView保持被压缩状态无法返回填充状态 

### ISSUE THREAD

**Issue by moxc** [xuelongqy/flutter_easyrefresh#261]
Flutter : v1.12.13+hotfix.8

**Comment by xuelongqy** [comment]
请使用最新版本。提交issue前，请在issue上搜索一下呢？

**Comment by moxc** [comment]
2.1.0 2.0.9 在v1.12.13 + hotfix.8都有这个问题 忘了写版本了

**Comment by xuelongqy** [comment]
首先说明一下吧，这并不是EasyRefresh的bug，如果还有这个问题呢，说明目前无法在框架层面取解决。提供一个解决办法吧，在渲染的第一帧后弹出软键盘，TextField的话设置焦点即可，使用WidgetsBinding.instance.addPostFrameCallback，在initState中注册回调

**Comment by moxc** [comment]
谢谢哈
