### ISSUE TITLE
provide a callback function when noMore is true, or display `no more data` in the `footer`

### ISSUE THREAD

**Issue by jpainam** [xuelongqy/flutter_easyrefresh#262]
Hi, i would like to display a snackbar or a notification when noMore is  true,
using `_refreshController.finishRefreshCallBack = _finishCallBack` with
```dart
_finishCallBack({bool success, bool noMore}) {
    if (noMore) {
      print("no more data");
    }
    if (!success) {
      print("Something happend");
    }
  }
```
didn't work.
How can I achieved this. I would to display Text('no more data') on the footer when there no more data to load

**Comment by xuelongqy** [comment]
Use EasyRefreshController

**Comment by jpainam** [comment]
`_refreshController` is of type `EasyRefreshController`. Can you show how to do that with `EasyRefreshController`. Because that's what I was using and try to override the `finishRefreshCallBack`
