### ISSUE TITLE
FLMarqueeLabel 和 easy_refresh 事件冲突

### ISSUE THREAD

**Issue by IvanYue** [xuelongqy/flutter_easyrefresh#264]
FLMarqueeLabel内容滚动的时候，easy_refresh刷新和上拉加载不会响应。

import 'package:flutter_easyrefresh/easy_refresh.dart';
import 'package:flui/flui.dart';

class CategoryPage extends StatefulWidget {
  CategoryPage({Key key}) : super(key: key);
  @override
  _CategoryPageState createState() => _CategoryPageState();
}

class _CategoryPageState extends State<CategoryPage> {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(title: Text('分类')),
      body: EasyRefresh(
        child: ListView(
          children: <Widget>[
            FLMarqueeLabel(
              text: 'Notice: FLUI is a widget kit for Google Flutter',
              style: TextStyle(color: Colors.blueAccent, fontSize: 16),
              velocity: 1,
              space: 150,
              loop: true,
            )
          ],
        ),
        onRefresh: () {},
        onLoad: () {},
      ),
    );
  }
}

**Comment by xuelongqy** [comment]
请参考Swiper示例，避免滚动冲突
