### ISSUE TITLE
对下拉刷新的提个建议

### ISSUE THREAD

**Issue by gaoyong06** [xuelongqy/flutter_easyrefresh#267]
`
ClassicalFooter(
              /// 提示加载文字
              loadText: '正在加载',

              /// 准备加载文字
              loadReadyText: '正在加载',

              /// 正在加载文字
              loadingText: '正在加载',

              /// 加载完成文字
              loadedText: null,

              /// 加载失败文字
              loadFailedText: '网络出现错误,请稍后再试',

              /// 没有更多文字
              noMoreText: "没有更多数据了",
              showInfo: false,
              bgColor: Colors.transparent,
              textColor: QzoneColors.textGray,
            )

`

把这些 loadText， loadReadyText.... loadFailedText 都换成Widget, 这样开发者，就可以自行根据需要“定制”， 这样就容易很多，现在这个跑个demo可以，实际用的话，还是有点麻烦，重写ClassicalFooter 感觉也没多大必要，

例如我现在觉得默认的字号太大了，想改小，没法改，
想把那个loading 的动画，改成CupertinoActivityIndicator() 也是没法改

所以作者可以把这些以widget的方式，开放处理，把现在的实现也保留，但是做成default, 这样就便利很多了

**Comment by xuelongqy** [comment]
考虑过，但兼容成本过高所以不采纳。最好的是自行实现，默认样式没法适应所有场景

**Comment by gaoyong06** [comment]
> 考虑过，但兼容成本过高所以不采纳。最好的是自行实现，默认样式没法适应所有场景

ok, 明白

**Comment by qcks** [comment]
没有“没有更多”功能，👋👋

**Comment by xuelongqy** [comment]
> 没有“没有更多”功能，👋👋

请认真阅读文档
