### ISSUE TITLE
分组的ListView问题

### ISSUE THREAD

**Issue by gaoyong06** [xuelongqy/flutter_easyrefresh#268]
遇到一个分组的ListView的问题
场景类似：微信->通讯录 这样的List
有个吸顶的头部：A..B...C...D

这样，也用了第三方的库：
flutter_sticky_header
https://github.com/letsar/flutter_sticky_header

这个能和 flutter_easyrefresh 配合使用嘛？ 研究了半天，没有找到方法？
或者，flutter_easyrefresh  是否，可以处理此类需求

**Comment by xuelongqy** [comment]
flutter_easyrefresh内部使用了CustomScrollView，你可以研究一下。如果使用CustomScrollView没有问题，flutter_easyrefresh应该问题不大

**Comment by lionoggo** [comment]
> 遇到一个分组的ListView的问题
> 场景类似：微信->通讯录 这样的List
> 有个吸顶的头部：A..B...C...D
> 
> 这样，也用了第三方的库：
> flutter_sticky_header
> https://github.com/letsar/flutter_sticky_header
> 
> 这个能和 flutter_easyrefresh 配合使用嘛？ 研究了半天，没有找到方法？
> 或者，flutter_easyrefresh 是否，可以处理此类需求

可以配合使用

**Comment by gaoyong06** [comment]
> > 遇到一个分组的ListView的问题
> > 场景类似：微信->通讯录 这样的List
> > 有个吸顶的头部：A..B...C...D
> > 这样，也用了第三方的库：
> > flutter_sticky_header
> > https://github.com/letsar/flutter_sticky_header
> > 这个能和 flutter_easyrefresh 配合使用嘛？ 研究了半天，没有找到方法？
> > 或者，flutter_easyrefresh 是否，可以处理此类需求
> 
> 可以配合使用

大概怎么个思路，或者有没有示例代码之类，感谢

**Comment by xuelongqy** [comment]
使用EasyRefresh.custom即可
