### ISSUE TITLE
关于黑夜模式适配问题

### ISSUE THREAD

**Issue by qcdys** [xuelongqy/flutter_easyrefresh#269]
@xuelongqy  
你好，很感谢你开发出这么好的插件
在这里我想提两点优化建议
1、在黑夜模式下，冲上云霄Header并未适配， 希望作者可以适配一下(建议取appBar的背景色 这样可以无缝结合)
2、冲上云霄Header的completeDuration希望可以做成参数传入 ， 1秒有点漫长

再次感谢作者 期待你的回复

**Comment by xuelongqy** [comment]
v2.1.1已添加，冲上云霄添加自定义背景色。夜间模式由于Flutter1.9不支持，所以暂不适配
