### ISSUE TITLE
SliverGeometry is not valid: The "layoutExtent" exceeds the "paintExtent".

### ISSUE THREAD

**Issue by 594904020** [xuelongqy/flutter_easyrefresh#271]
快速滑动的时候偶尔出现出错（There are occasional mistakes when sliding fast）

SliverGeometry is not valid: The "layoutExtent" exceeds the "paintExtent".

**Comment by xuelongqy** [comment]
最新版本有这个问题吗？

**Comment by genius1212** [comment]
是的，尤其是，上拉加载了几页之后，猛然下拉，就会出现这个问题，，直接出发下拉刷新，UI也会中间一片空白，像是卡帧了一样

**Comment by genius1212** [comment]
════════ Exception caught by rendering library ═════════════════════════════════════════════════════
The following assertion was thrown during performLayout():
SliverGeometry is not valid: The "layoutExtent" exceeds the "paintExtent".

The paintExtent is 0.0, but the layoutExtent is 130.0.
The RenderSliver that returned the offending geometry was: _RenderEasyRefreshSliverRefresh#1e7e0 relayoutBoundary=up1 NEEDS-PAINT
...  needs compositing
...  parentData: paintOffset=Offset(0.0, 888.1) (can use size)
...  constraints: SliverConstraints(AxisDirection.down, GrowthDirection.forward, ScrollDirection.forward, scrollOffset: 0.0, remainingPaintExtent: 0.0, overlap: -773.4, crossAxisExtent: 375.0, crossAxisDirection: AxisDirection.right, viewportMainAxisExtent: 505.0, remainingCacheExtent: 0.0, cacheOrigin: 0.0)
...  geometry: SliverGeometry(scrollExtent: 130.0, hidden, paintOrigin: -773.4, layoutExtent: 130.0, maxPaintExtent: 903.4, cacheExtent: 130.0)
...    scrollExtent: 130.0
...    hidden
...    paintOrigin: -773.4
...    layoutExtent: 130.0
...    maxPaintExtent: 903.4
...    cacheExtent: 130.0
The relevant error-causing widget was: 
  EasyRefresh file:///Users/novo/Desktop/novo/lib/page/home/home_page.dart:293:12
When the exception was thrown, this was the stack: 
#0      SliverGeometry.debugAssertIsValid.<anonymous closure>.verify (package:flutter/src/rendering/sliver.dart:718:9)
#1      SliverGeometry.debugAssertIsValid.<anonymous closure> (package:flutter/src/rendering/sliver.dart:735:15)
#2      SliverGeometry.debugAssertIsValid (package:flutter/src/rendering/sliver.dart:757:6)
#3      RenderSliver.debugAssertDoesMeetConstraints (package:flutter/src/rendering/sliver.dart:1212:21)
#4      RenderObject.layout.<anonymous closure> (package:flutter/src/rendering/object.dart:1770:9)
...
The following RenderObject was being processed when the exception was fired: _RenderEasyRefreshSliverRefresh#1e7e0 relayoutBoundary=up1 NEEDS-PAINT
...  needs compositing
...  parentData: paintOffset=Offset(0.0, 888.1) (can use size)
...  constraints: SliverConstraints(AxisDirection.down, GrowthDirection.forward, ScrollDirection.forward, scrollOffset: 0.0, remainingPaintExtent: 0.0, overlap: -773.4, crossAxisExtent: 375.0, crossAxisDirection: AxisDirection.right, viewportMainAxisExtent: 505.0, remainingCacheExtent: 0.0, cacheOrigin: 0.0)
...  geometry: SliverGeometry(scrollExtent: 130.0, hidden, paintOrigin: -773.4, layoutExtent: 130.0, maxPaintExtent: 903.4, cacheExtent: 130.0)
...    scrollExtent: 130.0
...    hidden
...    paintOrigin: -773.4
...    layoutExtent: 130.0
...    maxPaintExtent: 903.4
...    cacheExtent: 130.0
RenderObject: _RenderEasyRefreshSliverRefresh#1e7e0 relayoutBoundary=up1 NEEDS-PAINT
  needs compositing
  parentData: paintOffset=Offset(0.0, 888.1) (can use size)
  constraints: SliverConstraints(AxisDirection.down, GrowthDirection.forward, ScrollDirection.forward, scrollOffset: 0.0, remainingPaintExtent: 0.0, overlap: -773.4, crossAxisExtent: 375.0, crossAxisDirection: AxisDirection.right, viewportMainAxisExtent: 505.0, remainingCacheExtent: 0.0, cacheOrigin: 0.0)
  geometry: SliverGeometry(scrollExtent: 130.0, hidden, paintOrigin: -773.4, layoutExtent: 130.0, maxPaintExtent: 903.4, cacheExtent: 130.0)
    scrollExtent: 130.0
    hidden
    paintOrigin: -773.4
    layoutExtent: 130.0
    maxPaintExtent: 903.4
    cacheExtent: 130.0
...  child: _RenderLayoutBuilder#0c895 relayoutBoundary=up2 NEEDS-PAINT
...    needs compositing
...    parentData: paintOffset=Offset(0.0, 0.0) (can use size)
...    constraints: BoxConstraints(w=375.0, 0.0<=h<=903.4)
...    size: Size(375.0, 903.4)
...    child: RenderConstrainedBox#cfb47 relayoutBoundary=up3 NEEDS-PAINT
...      needs compositing
...      parentData: offset=Offset(0.0, 0.0) (can use size)
...      constraints: BoxConstraints(w=375.0, 0.0<=h<=903.4)
...      size: Size(375.0, 903.4)
...      additionalConstraints: BoxConstraints(w=Infinity, h=903.4)
...      child: RenderStack#e8ca4 NEEDS-PAINT
...        needs compositing
...        parentData: <none> (can use size)
...        constraints: BoxConstraints(w=375.0, h=903.4)
...        size: Size(375.0, 903.4)
...        alignment: AlignmentDirectional.topStart
...        textDirection: ltr
...        fit: loose
...        overflow: clip
...        child 1: RenderConstrainedBox#ecfc6 relayoutBoundary=up1 NEEDS-PAINT
...          parentData: top=26.0; left=-60.0; offset=Offset(-60.0, 26.0) (can use size)
...          constraints: BoxConstraints(unconstrained)
...          size: Size(60.0, 20.0)
...          additionalConstraints: BoxConstraints(w=60.0, h=20.0)
...        child 2: RenderConstrainedBox#33321 relayoutBoundary=up1 NEEDS-PAINT
...          parentData: top=52.0; left=-60.0; offset=Offset(-60.0, 52.0) (can use size)
...          constraints: BoxConstraints(unconstrained)
...          size: Size(60.0, 20.0)
...          additionalConstraints: BoxConstraints(w=60.0, h=20.0)
...        child 3: RenderConstrainedBox#e5f51 relayoutBoundary=up1 NEEDS-PAINT
...          parentData: top=86.7; left=-60.0; offset=Offset(-60.0, 86.7) (can use size)
...          constraints: BoxConstraints(unconstrained)
...          size: Size(60.0, 20.0)
...          additionalConstraints: BoxConstraints(w=60.0, h=20.0)
...        child 4: _RenderScrollSemantics#acead relayoutBoundary=up1 NEEDS-PAINT
...          needs compositing
...          parentData: not positioned; offset=Offset(0.0, 0.0) (can use size)
...          constraints: BoxConstraints(0.0<=w<=375.0, 0.0<=h<=903.4)
...          semantic boundary
...          size: Size(375.0, 903.4)

**Comment by myNameispiaofei** [comment]
相同的问题+1

**Comment by xiaschina** [comment]
有解决办法吗

**Comment by gitspringcould** [comment]
同问

**Comment by xujixiao** [comment]
请问这个问题怎么解决的

**Comment by liufei01** [comment]
有解决方案吗？

**Comment by weiweilidd01** [comment]
+1 ，使用了NestedScrollView + SliverPersistentHeader 就报错了，

**Comment by ilgnefz** [comment]
是使用**SliverPersistentHeader**时，设置的内容小于自定义的**delegate**中设置的最小高度

**Comment by ilgnefz** [comment]
使用**SliverPersistentHeader**时，设置的内容小于自定义的**delegate**中设置的最小高度，在自定义的**delegate**中写死它的高度就行了

**Comment by houziruinb87** [comment]
> 使用**SliverPersistentHeader**时，设置的内容小于自定义的**delegate**中设置的最小高度，在自定义的**delegate**中写死它的高度就行了

正解!

**Comment by houziruinb87** [comment]
> +1 ，使用了NestedScrollView + SliverPersistentHeader 就报错了，

使用SliverPersistentHeader时，设置的内容小于自定义的delegate中设置的最小高度，在自定义的delegate中写死它的高度就行了
