### ISSUE TITLE
数据不满一屏，加载更多还是无法卡住

### ISSUE THREAD

**Issue by MingForce** [xuelongqy/flutter_easyrefresh#277]
好像这几个刷新框架都有这个问题。数据不满一屏，下面的加载更多，无法停留

**Comment by xuelongqy** [comment]
停住不会很奇怪吗？中间会空出一大截

**Comment by MingForce** [comment]
> 停住不会很奇怪吗？中间会空出一大截

不是一直停住，是刷新的时候停住，刷新结束后隐藏，就如满屏的时候一样的刷新效果。现在是不满屏时，一上拉，就消失了，没有停留。

**Comment by xuelongqy** [comment]
目前在此框架的层面，没有办法。如果你发现好的解决方案可以在此留言，分享出来。不过我觉得更好的方案是规范接口，并每次分页拿足够多的数据
