### ISSUE TITLE
列表中加入marquee库控件，下拉刷新无效

### ISSUE THREAD

**Issue by gzqreder** [xuelongqy/flutter_easyrefresh#278]
Marquee控件中有用到ScrollController，怀疑是ScrollController冲突，请问如何解决这个问题

可以在basic.dart文件的 return SampleListItem 上添加以下代码重现。
> 
                    if (0 == index) {
                      return Container(
                        height: 40,
                        child: Marquee(
                          text:
                              "fdsfsfsdfsdfsfsfsdfsdfsdfsfsdfdsfsdfsdfsfsfsdfdsfsdfs",
                          blankSpace: 120,
                          style: TextStyle(fontSize: 14),
                        ),
                      );
                    }

**Comment by xuelongqy** [comment]
请参考Readme中，Swiper示例，解决滚动冲突
