### ISSUE TITLE
使用fish-redux刷新数据会自动跳转到头部

### ISSUE THREAD

**Issue by chenkb730** [xuelongqy/flutter_easyrefresh#279]
使用fish-redux adapter去更新数据的时候,上拉刷新添加数据源会自动回弹到顶部,请问有解决办法吗

**Comment by xuelongqy** [comment]
是滚动到顶部还是重新创建了列表呢？

**Comment by chenkb730** [comment]
> 是滚动到顶部还是重新创建了列表呢？

是直接滚到到顶部上去了,我使用其他的方法去刷新或者用另外刷新组件尝试是没有问题的,adapter的item数据也是clone的数据.

**Comment by xuelongqy** [comment]
试试设置一个ScrollController呢
