### ISSUE TITLE
用EasyRefreshController控制加载更多加载完成会不消失

### ISSUE THREAD

**Issue by git-maven** [xuelongqy/flutter_easyrefresh#280]
![1587347706334](https://user-images.githubusercontent.com/45022397/79706799-07539680-82ed-11ea-8fe5-9ca900158385.jpg)
如图所示

已经调用了easyRefreshController.finishLoad(noMore: value);

**Comment by xuelongqy** [comment]
两种方法，没有更多后： 1.去掉无限加载 2.将onLoad设置为null
