### ISSUE TITLE
Error on line 1, column 7 of ../../../.pub-cache/hosted/pub.dartlang.org/url_launcher_web-0.1.1+1/pubspec.yaml: "name" field doesn't match expected name "url_launcher_web".    ╷  1 │ name: logo_web    │       ^^^^^^^^    ╵ pub upgrade failed (65;   ╵)

### ISSUE THREAD

**Issue by zhangtianai** [xuelongqy/flutter_easyrefresh#282]
Error on line 1, column 7 of ../../../.pub-cache/hosted/pub.dartlang.org/url_launcher_web-0.1.1+1/pubspec.yaml: "name" field doesn't match expected name "url_launcher_web".

  ╷

1 │ name: logo_web

  │       ^^^^^^^^

  ╵
pub upgrade failed (65;   ╵)

**Comment by xuelongqy** [comment]
这貌似并不是框架的问题。如果你想测试web的示例，请使用flutter_dev的最新版本
