### ISSUE TITLE
使用TabBarView开启firstRefresh同时设置firstRefreshWidget有问题

### ISSUE THREAD

**Issue by 415593725** [xuelongqy/flutter_easyrefresh#285]
TabBar+TabBarView，TabBarView里面使用EasyRefresh设置firstRefresh=true,自定义了firstRefreshWidget。从第一页左滑到第二页时，第一页发生了下拉刷新的动画，不过没有触发第一页的刷新，但左右滑动切换页面时稍微慢一点，这个下拉动画及其明细。

**Comment by xuelongqy** [comment]
为列表添加不同的ScrollController
