### ISSUE TITLE
为什么下拉没有松手也会导致刷新

### ISSUE THREAD

**Issue by nbwzlyd** [xuelongqy/flutter_easyrefresh#288]
不是松手再出发刷新么？
return new EasyRefresh(
      onRefresh: _onRefresh,
      onLoad: _onLoad,
      child: ListView.builder(
        itemBuilder: (BuildContext ctx, int index) {
          if (index == 0) {
            return HomeBannerWidget(bannerBean);
          }
          return ContentWidget(contentEntity, index - 1);
        },
        shrinkWrap: true,
        itemCount: _getItemCount(),
      ),
    );

///-----------------
Future<Null> _onRefresh() async {
    _getItemData(page++,false);
  }

**Comment by xuelongqy** [comment]
确定一下是否有滚动冲突呢？如果有，请参考swiper的示例
