### ISSUE TITLE
关于显示文字国际化显示中文的问题，

### ISSUE THREAD

**Issue by ymwm-lxl** [xuelongqy/flutter_easyrefresh#292]
关闭了那么多关于怎么显示中文的问题，但是看到作者都说让去查阅文档，请问文档哪里有呢？首页相关的下边这个部分是怎么用的呢？可以详细一点么？

添加国际化支持
import 'package:flutter_easyrefresh/easy_refresh.dart';
....
  /// 如果没有您当前的语言支持
  /// 您可以使用strings_en.arb进行翻译并命名为strings_{languageCode}_{countryCode}.arb
  /// 然后进行Pull requests
  new MaterialApp(
    localizationsDelegates: [
      GlobalEasyRefreshLocalizations.delegate,
      ....
    ],
    supportedLocales: [
        Locale('en', ''),
        Locale('zh', 'CN'),
        ....
    ]
    ....
  )

**Comment by xuelongqy** [comment]
国际化不再维护，请自行在样式中设置文字

**Comment by IOCloudFly** [comment]
能否告诉下怎么在样式里设置中文吗。

**Comment by bigmili** [comment]
也没文档，怎么设置😂
