### ISSUE TITLE
custom footer gesturedetector onTap not working

### ISSUE THREAD

**Issue by XiaNaLee** [xuelongqy/flutter_easyrefresh#297]
继承footer实现，但是onTap没有响应 

@override
  Widget build(BuildContext context) {
    return new GestureDetector(
      onTap: () {log.('log');},
      child: new Row(
        crossAxisAlignment: CrossAxisAlignment.center,
        mainAxisAlignment: MainAxisAlignment.center,
        children: _buildContent(),
      ),
    );
  }

**Comment by xuelongqy** [comment]
这个问题应该有解决过，使用的是哪个版本呢？或者检验是否为布局或者手势冲突
