### ISSUE TITLE
怎么让语言显示中文？

### ISSUE THREAD

**Issue by brave1024** [xuelongqy/flutter_easyrefresh#299]
App已按说明设置支持国际化，但就是识别不了中文，一直显示英文，请问要怎么处理？

**Comment by xuelongqy** [comment]
下个版本会去掉国际化。支持中文在样式参数设置对应文字即可。可以参考示例

**Comment by wangqilinqqq** [comment]
`dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter`

` new MaterialApp(
    localizationsDelegates: [
      GlobalEasyRefreshLocalizations.delegate,
      ....
    ],
    supportedLocales: [
        Locale('en', ''),
        Locale('zh', 'CN'),
        ....
    ]
    ....
  )`
