### ISSUE TITLE
第一次上拉加载更多后需要上拉多次才会触发第二次上拉手势加载

### ISSUE THREAD

**Issue by kangshifu** [xuelongqy/flutter_easyrefresh#3]
复现步骤:
 1.第一次上拉进行加载更多
 2.加载完成后再上拉，上拉的手势无效，就是整个列表不会随手势的上拉而上拉加载更多，不知道是不是手势冲突被拦截了

**Comment by xuelongqy** [comment]
V1.0.2已修复
