### ISSUE TITLE
NotificationListener 无效

### ISSUE THREAD

**Issue by sqixin** [xuelongqy/flutter_easyrefresh#30]
我的 NotificationListener  里面用的是 其他Refresh插件，监听有效，我用这个插件后 NotificationListener 监听不起作用了，不知道你有没有遇到。

**Comment by xuelongqy** [comment]
是的，将会在下个版本进行修改。如果你需要的话，可以下载源码修改refresher.dart中NotificationListener return false，开启滑动事件的冒泡

**Comment by sqixin** [comment]
好的。谢谢，改成false确实可以了。你既然默认是true，我改成false应该不会有其他影响吧。

**Comment by xuelongqy** [comment]
不会有影响的

**Comment by xuelongqy** [comment]
1.2.6已修复
