### ISSUE TITLE
上拉加载一些使用过后的反馈

### ISSUE THREAD

**Issue by s949492225** [xuelongqy/flutter_easyrefresh#300]
通常大家可能会定制一个比较个性的下拉刷新,这点easyrefresh做的很好.
但是对于上拉加载更多,这个就相对来说个性化的比较少了.
这里举一些通常模式下上拉加载的考虑的问题:
1.上拉加载其实并不是上拉,而是页面滑到底了,就开始显示加载中了,此时是并不需要持续上拉释放来触发刷新,这点和下拉刷新区别很大,并且上拉一般不会再有那种弹性的缩放效果.
2.通常上拉的加载的ui很简单,如果有个比较大众化的一般都能接受.
3.一般来说没有数据了,底部会有显示一个没有更多数据的指示条在底部
4.加载更多数据失败了,底部显示一个加载失败的条,体验好的会有重试按钮在底部.
5.失败和没有更多数据的情况下,底部的条是不会消失的,会一直在

安卓的pay商店中列表的加载逻辑目前是这样的,如果有意可以参考一下.
希望作者把这个库搞成flutter列表的最有名的库

**Comment by s949492225** [comment]
另外发现上拉加载里,footer里_refreshState没有发现加载结束的状态

**Comment by qcks** [comment]
没有“没有更多”这个功能；放弃使用

**Comment by Yang-Xiao-Ming** [comment]
> 没有“没有更多”这个功能；放弃使用

这个功能，可以自定义的，如下：
 footer: CustomFooter(
          enableInfiniteLoad: true,
          extent: 44.0,
          triggerDistance: 44.0,
          footerBuilder: (context,
              loadState,
              pulledExtent,
              loadTriggerPullDistance,
              loadIndicatorExtent,
              axisDirection,
              float,
              completeDuration,
              enableInfiniteLoad,
              success,
              noMore) {
            return Stack(
              children: <Widget>[
                Positioned(
                  bottom: 0.0,
                  left: 0.0,
                  right: 0.0,
                  child: Container(
                    height: 44.0,
                    color: Colors.red,
                    alignment: Alignment.center,
                    child: isLast ? Text('没有更多') : Image.asset('images/image_loading2.gif'),
                  ),
                ),
              ],
            );
          }),

**Comment by Yang-Xiao-Ming** [comment]
“没有更多”这个功能，可以自己定义一下，如下：
footer: CustomFooter(
    enableInfiniteLoad: true,
    extent: 44.0,
    triggerDistance: 44.0,
    footerBuilder: (context,
        loadState,
        pulledExtent,
        loadTriggerPullDistance,
        loadIndicatorExtent,
        axisDirection,
        float,
        completeDuration,
        enableInfiniteLoad,
        success,
        noMore) {
      return Stack(
        children: <Widget>[
          Positioned(
            bottom: 0.0,
            left: 0.0,
            right: 0.0,
            child: Container(
              height: 44.0,
              color: Colors.red,
              alignment: Alignment.center,
              child: isLast ? Text('没有更多') : Image.asset('images/image_loading2.gif'),
            ),
          ),
        ],
      );
    }),

**Comment by xuelongqy** [comment]
你所说的，目前应该都支持。可参考文档进行设置

**Comment by kamike** [comment]
这个建议提的好，不知道作者有没有可能改下默认就是这种体验
