### ISSUE TITLE
loadmore，快速滑动时，新数据已经加载成功，页面显示，频繁出现反向回弹滚动。

### ISSUE THREAD

**Issue by ldhlfzysys** [xuelongqy/flutter_easyrefresh#301]
如题

**Comment by ldhlfzysys** [comment]
loadmore如果速度非常快完成。BouncingScrollSimulation触发回弹效果会执行，但此时list已经更新了数据。

**Comment by ldhlfzysys** [comment]
官方demo  basic页面，把loadmore延迟设置为700ms可以稳定复现

**Comment by ldhlfzysys** [comment]
尝试在处理滚动时，添加判断列表长度变化的逻辑，可以防止这一问题出现。

**Comment by xuelongqy** [comment]
可添加请求延时

**Comment by ldhlfzysys** [comment]
修改scroll_physics解决了

**Comment by xuelongqy** [comment]
看不少人提到这个问题，我尝试在下个版本添加防止回弹吧

**Comment by hao-feng** [comment]
@xuelongqy 请教一下，在最新的版本中，我通过设置hitOver和infiniteHitOver使列表在滑动到底部的时候拥有和iOS一致的回弹效果。
然后遇到了和这个issue描述相同的问题。有什么方法可以在内容加载成功，高度变高后停止原来的回弹动画吗。
这也可能是一个回弹动画位置计算的问题，因为在发生上述情况后，最终停止滑动的位置是比原内容高度更小的地方（理论上及时回弹动画正常完成，那回弹结束后的位置也应该是原始内容的底部）
