### ISSUE TITLE
当Easyrefresh在父组件为TabBar的时候, 并且TabBar是多个, 可滚动的条件下, 点击相差三四个tab的情况下会报错

### ISSUE THREAD

**Issue by 2673542667** [xuelongqy/flutter_easyrefresh#302]
════════ Exception caught by scheduler library ═════════════════════════════════════════════════════
The following NoSuchMethodError was thrown during a scheduler callback:
The method 'dependOnInheritedWidgetOfExactType' was called on null.
Receiver: null
Tried calling: dependOnInheritedWidgetOfExactType<PrimaryScrollController>()

When the exception was thrown, this was the stack: 
#0      Object.noSuchMethod (dart:core-patch/object_patch.dart:53:5)
#1      PrimaryScrollController.of (package:flutter/src/widgets/primary_scroll_controller.dart:49:52)
#2      _EasyRefreshState._scrollerController (package:flutter_easyrefresh/src/refresher.dart:241:33)
#3      _EasyRefreshState.callRefresh (package:flutter_easyrefresh/src/refresher.dart:306:9)
#4      _EasyRefreshState.initState.<anonymous closure> (package:flutter_easyrefresh/src/refresher.dart:275:9)
...
════════════════════════════════════════════════════════════════════════════════════════════════════

**Comment by xuelongqy** [comment]
为每个EasyRefresh设置不同的ScrollController即可，最好做一下Tab页保活，在回调中判断一下生命周期

**Comment by 2673542667** [comment]
> 为每个EasyRefresh设置不同的ScrollController即可，最好做一下Tab页保活，在回调中判断一下生命周期

谢谢
