### ISSUE TITLE
设置header，下拉刷新时，header和内容之间会出现一条线

### ISSUE THREAD

**Issue by zyang008** [xuelongqy/flutter_easyrefresh#305]
1.页面背景色设置蓝色；
2.header背景色和内容的背景均为白色（header与内容之间未设置分割线）；
3.手指下拉时（未释放），可以看到内容与header之间有条蓝色的线
![device-2020-06-02-100043](https://user-images.githubusercontent.com/65108875/83471812-3fd3bc00-a4b8-11ea-8907-710b9b29c7a5.png)
![device-2020-06-02-100128](https://user-images.githubusercontent.com/65108875/83471815-419d7f80-a4b8-11ea-8bce-9b3a42d32fd7.png)

**Comment by xuelongqy** [comment]
这是flutter一直以来的问题，建议使用特殊布局处理 多0.5即可

**Comment by zyang008** [comment]
特殊布局？是header使用特殊布局吗还是其他方式，不是很明白，还望指导指导，感谢：）

**Comment by zyang008** [comment]
> 这是flutter一直以来的问题，建议使用特殊布局处理 多0.5即可

**Comment by yiwuyu** [comment]
@zyang008 请问特殊布局解决了吗= - =

**Comment by f2yu** [comment]
在负坐标中加个控件处理背景色即可
