### ISSUE TITLE
firstRefresh 与 firstRefreshWidget 使用的问题

### ISSUE THREAD

**Issue by gaoyong06** [xuelongqy/flutter_easyrefresh#307]
阅读了文档和代码还有demo基本搞明白了这两个的使用，但是在我使用的时候遇到了和实际情况不符的问题，麻烦作者大大看看是我哪里没搞对

这里面有这么几个概念下面是我的理解：
**onRefresh**: 是否开启刷新
**firstRefresh**：是否开启首次刷新
**firstRefreshWidget**：开启刷新(onRefresh != null) 且开启首次刷新（firstRefresh=true）时，首次刷新时显示的widget

我用demo执行的时候没有问题。
但我目前业务实际情况是这样， onRefresh 里面赋值的是一个Future 的方法
伪代码是：

    ...
    //下拉刷新
    Future<void> _onRefresh() async {
       _loadData(.....);
    }
    ...

这个_onRefresh 中的 _loadData 方法里面会异步调用一个http api获取数据，得到响应结果后执行 setState刷新页面数据

使用的时候是这样，
伪代码是：

    ...
    onRefresh: _onRefresh,
    firstRefresh: true,
    firstRefreshWidget: Column(
        mainAxisAlignment: MainAxisAlignment.start,
        children: <Widget>[
          SizedBox(
            height: Dimens.gapDp8,
          ),
          Loading()
        ]),
    ...
    
如果上面这样使用的话firstRefreshWidget一直不会显示。

但是如果和demo里面一样，增加一个延迟执行
例如下面这样，
伪代码是：

    ...
    //下面增加了延迟执行
    onRefresh: () async { 
      await Future.delayed(Duration(seconds:2), () {
        _onRefresh();
      });
    },
    firstRefresh: true,
    firstRefreshWidget: Column(
        mainAxisAlignment: MainAxisAlignment.start,
        children: <Widget>[
          SizedBox(
            height: Dimens.gapDp8,
          ),
          Loading()
        ]),
    ...

此时firstRefreshWidget就会显示，问题是：现实场景里面这个延迟执行不能加，加了只会让用户等待的时间更久

请问这个该如何处理？

[文中提到的demo](https://github.com/xuelongqy/flutter_easyrefresh/blob/9a0d05cef52573be77938c4bed7a19c3fa8a4c33/example/lib/page/sample/first_refresh.dart)

**Comment by xuelongqy** [comment]
了解一下dart的Future作用，或者启用主动控制，请查看文档

**Comment by gaoyong06** [comment]
> 了解一下dart的Future作用，或者启用主动控制，请查看文档

哪个文档里面有【主动控制】的相关说明，在补充提示一下，还是不太明白从哪里查阅，项目写文档基本都看了，demo的代码看了一大部分，没找到和我这种情况这个相关的

**Comment by gaoyong06** [comment]
@xuelongqy 看到麻烦回复一下
