### ISSUE TITLE
firstRefresh设置不生效

### ISSUE THREAD

**Issue by lzhAndroid** [xuelongqy/flutter_easyrefresh#309]
EasyRefresh.custom(
            firstRefresh: true,
            firstRefreshWidget: Container(),
            header: MaterialHeader(
                valueColor: AlwaysStoppedAnimation<Color>(Theme.of(context).accentColor),
                backgroundColor: Colors.white),
            footer: MaterialFooter(
                valueColor: AlwaysStoppedAnimation<Color>(Theme.of(context).accentColor),
                backgroundColor: Colors.white),
            enableControlFinishRefresh: true,
            enableControlFinishLoad: true,
            onRefresh: _onRefresh,
            onLoad: _onLoad,
            controller: controller,
            slivers: slivers,
          )

设置firstRefresh后，scrollControl为空，return掉了。

**Comment by xuelongqy** [comment]
请参考示例
