### ISSUE TITLE
scrollController没有调用？

### ISSUE THREAD

**Issue by caihua** [xuelongqy/flutter_easyrefresh#31]
https://github.com/xuelongqy/flutter_easyrefresh/blob/03ce507092b3ee1236b8c6ce8832b5beeb008de8/lib/src/refresher.dart#L1201
https://github.com/xuelongqy/flutter_easyrefresh/blob/03ce507092b3ee1236b8c6ce8832b5beeb008de8/lib/src/refresher.dart#L1202
https://github.com/xuelongqy/flutter_easyrefresh/blob/03ce507092b3ee1236b8c6ce8832b5beeb008de8/lib/src/refresher.dart#L1203

这个地方如果外层传入了 scrollController，就变成null了，外层 scrollController无法监听到滚动事件。

**Comment by xuelongqy** [comment]
outerController是用来兼容NestedScrollView的，一般情况下不用设置。如果需要的话，请在ListView里面设置，会自动获取

**Comment by xuelongqy** [comment]
我会将这个问题写在 常见问题 文档中
