### ISSUE TITLE
child里边嵌套timer轮播listview onRefresh()失效

### ISSUE THREAD

**Issue by abc123james** [xuelongqy/flutter_easyrefresh#310]
body: Container(
          child: EasyRefresh(
            footer: MaterialFooter(),
            onRefresh: () async { },
            child:
            SingleChildScrollView(
              scrollDirection: Axis.vertical,
              child: Container(
                padding: EdgeInsets.only(left: 16.0, right: 16.0),
                child: Column(
                    crossAxisAlignment: CrossAxisAlignment.center,
                    children: <Widget>[
                      **notes,**//这是一个timer定时触发的listView消息滚动条
                   ....
                    ]),
              ),
            ),

          ),
        ));

**Comment by xuelongqy** [comment]
添加滚动通知拦截即可，请参考Swiper示例
