### ISSUE TITLE
刷新问题

### ISSUE THREAD

**Issue by Exclusive-gfj** [xuelongqy/flutter_easyrefresh#313]
列表在刷新成功头部还未收起时，立马再点击刷新列表会导致页面数据不会变，需要要重新再触发一下刷新数据才会改变

**Comment by xuelongqy** [comment]
好的，下个版本会修复

**Comment by davidjonse** [comment]
我现在也发现了这个问题，暂时解决的方式是在请求的时候sleep 1秒，这样可以降低出现这个问题的概率

**Comment by xuelongqy** [comment]
已修复，将会在下个版本发布
