### ISSUE TITLE
finishLoad 后 footer不会自定隐藏

### ISSUE THREAD

**Issue by Tonigt** [xuelongqy/flutter_easyrefresh#314]

**Comment by xuelongqy** [comment]
关闭无限加载即可。提问前请先阅读文档以及之前的issue，可以解决你的大部分疑惑

**Comment by Tonigt** [comment]
好的 &nbsp;谢谢



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "KnoYo"<notifications@github.com&gt;; 
发送时间: 2020年6月18日(星期四) 凌晨0:26
收件人: "xuelongqy/flutter_easyrefresh"<flutter_easyrefresh@noreply.github.com&gt;; 
抄送: "lonely"<1984701289@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [xuelongqy/flutter_easyrefresh] finishLoad 后 footer不会自定隐藏 (#314)





 
关闭无限加载即可。提问前请先阅读文档以及之前的issue，可以解决你的大部分疑惑
