### ISSUE TITLE
ios上拉加载更多的时候，手机总是要震动1次

### ISSUE THREAD

**Issue by gaoyong06** [xuelongqy/flutter_easyrefresh#316]
版本：13.4.1
型号：iPhone Xs Max

上拉加载更多的时候，总是要震动1次，这个可以关闭嘛？，或者在哪里设置？

**Comment by xuelongqy** [comment]
为何不看文档呢？

**Comment by hbshun** [comment]
感谢大佬开发的插件！不好意思 只找到了在自定义header和footer的时候有enableHapticFeedback选项，我只用到了简单的列表，不能设置这个选项。请赐教
EasyRefresh(
  onRefresh: updateData,
  controller: _refreshController,
  child: ListView(children: []),
)

**Comment by WingCH** [comment]
EasyRefresh 默认Header 是 `ClassicalHeader()`

你可以overwire 

```dart
EasyRefresh(
    header: ClassicalHeader(
       enableHapticFeedback: false
     ),
),
```
