### ISSUE TITLE
调用callRefresh会导致TabBarView里面的每个View都滚动到头部

### ISSUE THREAD

**Issue by bitjjj** [xuelongqy/flutter_easyrefresh#321]
前提：TabBarView里的每一项ListView都没有定义自己的scrollcontroller。
EasyRefresh(
       controller: easyController,
        child: ListView.builder(
          itemCount: reportList.length,
          itemBuilder: (context, index){
            return ...;
          }
        ),
      )
那么在任意一个View里面调用easyController.callRefresh();会导致所有tab里面的listview都滚动到头部。

原因：

void callRefresh({Duration duration = const Duration(milliseconds: 300)}) {
    // ignore: invalid_use_of_protected_member
    if (_scrollerController == null || _scrollerController.positions.isEmpty)
      return;
    _callRefreshNotifier.value = true;
    _scrollerController
        .animateTo(0.0, duration: duration, curve: Curves.linear)
        .whenComplete(() {
      _scrollerController.animateTo(
          -(_header.triggerDistance + EasyRefresh.callOverExtent),
          duration: Duration(milliseconds: 100),
          curve: Curves.linear);
    });
  }
上述代码在get _scrollerController的时候会使用PrimaryScrollController.of(context)得到scrollcontroller，那么调用animateTo的代码是：
final List<Future<void>> animations = List<Future<void>>(_positions.length);
    for (int i = 0; i < _positions.length; i += 1)
      animations[i] = _positions[i].animateTo(offset, duration: duration, curve: curve);
    return Future.wait<void>(animations).then<void>((List<void> _) => null);
这里面会循环遍历保存的positions，都会设置到头部。这样操作，就有问题了。

在给listview加上自己的scrollcontroller以后就好了
ListView.builder(
          controller: scrollController,
          itemCount: reportList.length,
          itemBuilder: (context, index){
            return getCard(reportList[index]);
          }
        )

**Comment by xuelongqy** [comment]
是的，看起来你已经提到解决方案了。这应该不算是问题，是Flutter的设计就是这样。不设置Scrollcontroller时，会共用默认的

**Comment by bitjjj** [comment]
我觉得应该在文档中做出提示，因为scrollcontroller并不是必须添加的。一旦包含了listview的widget应用AutomaticKeepAliveClientMixin只初始化一次，在其他tab中调用callRefresh就换干扰滚动条位置，这种行为真的很奇怪。

**Comment by lsfern** [comment]
其实设置为null也是可以的。确实会有此问题
