### ISSUE TITLE
国际化问题

### ISSUE THREAD

**Issue by AXinger** [xuelongqy/flutter_easyrefresh#323]
咨询个问题,我在用 GlobalEasyRefreshLocalizations.delegate, 一直不显示中文,我运行example 也是不显示中文, 有遇到这样情况吗??   

在我的页面 能取值
![34D1FD04A463B45488A71DE05E435F3B](https://user-images.githubusercontent.com/18339649/85965421-40943b00-b9ef-11ea-811d-6566f5aa03ee.jpg)

但是在组件中,就是取null
![10844C10DE92868D55C71C88323885BA](https://user-images.githubusercontent.com/18339649/85965379-180c4100-b9ef-11ea-95f8-a6f47a3defab.jpg)

**Comment by xuelongqy** [comment]
库自带的国际化已经废弃了，请自行使用国际化设置需要显示的文本内容
