### ISSUE TITLE
添加onload，onload完成后如果数据总高度超过了屏幕高度，footer不会隐藏

### ISSUE THREAD

**Issue by liaoyu1992** [xuelongqy/flutter_easyrefresh#326]
下方的footer会一直显示，不会回弹收回
![IMG_20200701_161814](https://user-images.githubusercontent.com/6285162/86221864-0aee7e00-bbb8-11ea-91ce-39abc6f3d8f1.png)

**Comment by xuelongqy** [comment]
关闭无限加载呢？

**Comment by liaoyu1992** [comment]
关闭无限加载footer会回弹回去，不过感觉footer的状态变化不对，我用的ClassicalFooter，在加载完成时，先变为拉动加载，再变为加载完成，再回弹收回，应该之间变为加载完成才对。
