### ISSUE TITLE
上拉加载，调用controller.finishLoad方法，加载无法消失已是最新版本2.1.1

### ISSUE THREAD

**Issue by wozhizhizhi** [xuelongqy/flutter_easyrefresh#329]
EasyRefresh(
      header: MaterialHeader(),
      footer: MaterialFooter(),
      controller: _controller,
      enableControlFinishLoad: true,
      onRefresh: _handleRefresh,
      onLoad: _loadMoreData,
      child: ListView.builder(
        padding: EdgeInsets.only(top: 20),
        itemBuilder: (context, index) {
          return _listItemWidget(index);
        },
        itemCount: _list.length,
      ),
    )

if (bookTypeListModel.data.list == null ||
              bookTypeListModel.data.list == []) {
            List<BookData> list = [];
            _list.addAll(list);
            _controller.finishLoad(noMore: true,success: true);
          }

**Comment by xuelongqy** [comment]
无限加载的情况下,onmore是不会消失的。可以设置onload为null，或者关闭无限加载
