### ISSUE TITLE
have u ever try CupertinoSliverRefreshControl in cupertino?

### ISSUE THREAD

**Issue by Mericusta** [xuelongqy/flutter_easyrefresh#33]
`CustomScrollView(
    slivers: <Widget>[
        CupertinoSliverNavigationBar(
        backgroundColor: Color.fromRGBO(110, 90, 160, 1.0),
        middle: Container(height: 0, width: 0),
        largeTitle: IconButton(
            color: Colors.white,
            alignment: Alignment.centerLeft,
            icon: Icon(Icons.menu),
            onPressed: () {},
        ),
        previousPageTitle: 'Cupertino',
        ),
        CupertinoSliverRefreshControl(
        refreshTriggerPullDistance: 120.0,
        refreshIndicatorExtent: 120.0,
        builder: ...,
        onRefresh: () {
            return Future<void>.delayed(const Duration(seconds: 5))
            ..then<void>((_) {
                if (mounted) {
                    setState(() => repopulateList());
                }
            });
        },
        ),
    ],
)`

**Comment by xuelongqy** [comment]
Yes, I have used.SpaceHeader is transplanted from [space_reload](https://github.com/2d-inc/Flare-Flutter/blob/master/example/space_reload/lib/refresh_control.dart). EasyRefresh can do the same as CupertinoSliverRefreshControl.

**Comment by Mericusta** [comment]
I tried, that's cool!
