### ISSUE TITLE
使用此插件后, iOS Flutter客户端无法点击状态栏滚动列表到顶部

### ISSUE THREAD

**Issue by zinwalin** [xuelongqy/flutter_easyrefresh#330]
Flutter自带的列表类组件, scrollController如果是默认的,或直接声明为 ScrollController controller = PrimaryScrollController.of(context);  在iOS上默认是可以点击状态栏滚动到顶部. 

但是所有使用EasyRefresh插件的页面默认都不支持这个功能,   闲鱼App iOS端的搜索界面也不支持这个功能,他们的做法是添加一个浮动的按钮来实现滚动列表到顶部. 

有没有什么思路可以帮忙解决这个问题?  项目里大量使用了EasyRefresh组件 .

**Comment by xuelongqy** [comment]
之前的issue有提到过，貌似是不设置ScrollController即可
