### ISSUE TITLE
有没有footerIndex的效果呢？ 我想要footer后面还有一个占位，因为bottomTabBar遮挡住一部分内容了

### ISSUE THREAD

**Issue by LemonBabyluo** [xuelongqy/flutter_easyrefresh#332]

**Comment by xuelongqy** [comment]
为何不自定义footer呢？

**Comment by LemonBabyluo** [comment]
> 为何不自定义footer呢？
我就是自定义的，但是怎么设置都没有用，撑不起来，有什么好的解决办法吗？

**Comment by xuelongqy** [comment]
> > 为何不自定义footer呢？
> > 我就是自定义的，但是怎么设置都没有用，撑不起来，有什么好的解决办法吗？

设置底部空白高度为bottomTabBar的高度呢？

**Comment by medz** [comment]
@xuelongqy 
![image](https://user-images.githubusercontent.com/5564821/88923156-d5ff4500-d2a3-11ea-9ea9-112490a09874.png)
不行的～试过了，内容高度被撑上去了，但是加载器还是被 bottomAppBar 挡住！还会导致内容距离底部变成了设置的空白！

其实 floater 解决方法就是包含一个 SafeArea 就能解决！

**Comment by medz** [comment]
![image](https://user-images.githubusercontent.com/5564821/88925098-aa318e80-d2a6-11ea-909a-309cf38f24c0.png)

不管咋个设置，都这个鬼样子。上面红框是 floater 的 extent 高度，下面红框是依旧跑到 bottomAppBar 后面去了！

作者可以试下 Scaffold 组建设置 extendBody = true 然后就这个鬼样子了！但是以为是使用的自定义 bottomAppBar 所以成了这个样子。准确得说 Scaffold 设置 extendBody = true 就这个样子，我里面的组建设置了SafeArea的，所以不会被 bottomAppBar 遮挡，但是 floater 没有 SafeArea 所以导致被遮挡了

**Comment by medz** [comment]
> > > 为何不自定义footer呢？
> > > 我就是自定义的，但是怎么设置都没有用，撑不起来，有什么好的解决办法吗？
> 
> 设置底部空白高度为bottomTabBar的高度呢？

设置底部空白高度为 bottomTabBar 高度也没用，只会把实际内容往上撑。

**Comment by xuelongqy** [comment]
> > > > 为何不自定义footer呢？
> > > > 我就是自定义的，但是怎么设置都没有用，撑不起来，有什么好的解决办法吗？
> > 
> > 设置底部空白高度为bottomTabBar的高度呢？
> 
> 设置底部空白高度为 bottomTabBar 高度也没用，只会把实际内容往上撑。

我的意思是在自定义footer的地步

**Comment by xuelongqy** [comment]
这个问题不可能通过这个框架的层面来解决

**Comment by medz** [comment]
> 这个问题不可能通过这个框架的层面来解决

其实给 footer 增加 SafeArea 组建就能解决，先这样吧～

**Comment by xuelongqy** [comment]
@medz @LemonBabyluo footer添加了safeArea和padding参数，可以使用git的方式引入框架，看看是否满足你们的需求。
```yaml
dependencies:
  flutter_easyrefresh:
    git:
      url: git://github.com/xuelongqy/flutter_easyrefresh.git
```

**Comment by xuelongqy** [comment]
v2.1.5 Footer已添加safeArea和padding支持

**Comment by LemonBabyluo** [comment]
> v2.1.5 Footer已添加safeArea和padding支持

这个很好的解决了我的问题，非常感谢~

**Comment by islinjj** [comment]
我使用的是easy_refresh: 3.4.0，是取消了padding这个属性了吗？

**Comment by islinjj** [comment]
我使用的是easy_refresh: 3.4.0，是取消了padding这个属性了吗？
