### ISSUE TITLE
刷新动画时长 completeDuration 属性能否设置成可配置?

### ISSUE THREAD

**Issue by CN-CJ** [xuelongqy/flutter_easyrefresh#336]
目前自定义的Header是可以控制刷新动画时长的 属性名为 completeDuration ; 但是默认的Header这个属性是写死的1秒; 实际测试的时候感觉这个时间有点长了,调整了一下感觉700毫秒的话动画更自然一点,所以建议能不能让这个属性在默认Header和Footer也可以配置

**Comment by xuelongqy** [comment]
ClassicalHeader是有的，其他样式请自行修改源码
