### ISSUE TITLE
当第一页数据只有2条的时候无法显示 没有更多数据

### ISSUE THREAD

**Issue by lifuqing** [xuelongqy/flutter_easyrefresh#337]
1、当第一页数据只有2条的时候无法显示 没有更多数据，
2、不满第一页上拉之后 也无法露出没有更多数据并停留展示

**Comment by xuelongqy** [comment]
v2.1.4已修复

**Comment by medz** [comment]
> v2.1.4已修复

刚更新到 2.1.4 版本，粗心呀大哥，修复这个问题导致了新问题。。。
