### ISSUE TITLE
The method 'objectRuntimeType' isn't defined

### ISSUE THREAD

**Issue by wanderingGuy** [xuelongqy/flutter_easyrefresh#338]
自动升级2.1.2版本后，提示找不到objectRuntimeType方法：

Compiler message:
.flutterw/cache/.pub-cache/hosted/http%2558%2547%2547dart-pub.byted.org/flutter_easyrefresh-2.1.2/lib/src/behavior/scroll_behavior.dart:14:24: Error: The method 'objectRuntimeType' isn't defined for the class 'EmptyOverScrollScrollBehavior'.
 - 'EmptyOverScrollScrollBehavior' is from 'package:flutter_easyrefresh/src/behavior/scroll_behavior.dart' ('.flutterw/cache/.pub-cache/hosted/http%2558%2547%2547dart-pub.byted.org/flutter_easyrefresh-2.1.2/lib/src/behavior/scroll_behavior.dart').
Try correcting the name to the name of an existing method, or defining a method named 'objectRuntimeType'.
  String toString() => objectRuntimeType(this, 'EmptyScrollBehavior');
                       ^^^^^^^^^^^^^^^^^

本地使用Flutter 1.12.13 版本，dart 2.7.0，应该是还不支持这个语法吧？大佬考虑兼容下。

**Comment by xuelongqy** [comment]
v2.1.3已修复
