### ISSUE TITLE
请问为什么2.1.2去掉了多语言支持

### ISSUE THREAD

**Issue by LeeYawei** [xuelongqy/flutter_easyrefresh#343]
如题，GlobalEasyRefreshLocalizations没了

**Comment by xuelongqy** [comment]
因为没必要了，整合和维护都不方便，还会增加框架体积。直接设置语言其实会更好

**Comment by zinwalin** [comment]
> 因为没必要了，整合和维护都不方便，还会增加框架体积。开发者直接设置语言其实会更好

写个示例吧.

**Comment by xuelongqy** [comment]
> > 因为没必要了，整合和维护都不方便，还会增加框架体积。开发者直接设置语言其实会更好
> 
> 写个示例吧.

示例代码都是有的啊，请见常见问题
