### ISSUE TITLE
如何在初始化时先异步获取数据，然后再放入EasyRefresh布局下

### ISSUE THREAD

**Issue by libinwalan** [xuelongqy/flutter_easyrefresh#344]
老大，我现在出来的效果是需要手动refresh来获取异步数据才能显示数据。
怎么做到进入界面后 先异步获取数据加入EasyRefresh 下的child去呢。
解决方案一：先跳转之前获取数据传递到EasyRefresh界面。但是我想在当前EasyRefresh去异步获取后再显示。请问应该怎么设计呢？谢谢

**Comment by xuelongqy** [comment]
首次刷新能满足需求吗？

**Comment by libinwalan** [comment]
老大，不能解决。因为这个场景下 在进入当前页面、回退到当前页面 都要刷新。不仅仅是首次刷新
这个场景应该比较常用，建议老大可以考虑加入

**Comment by xuelongqy** [comment]
我觉这不是当前框架应该做的事情，需要你自己进行监听。路由跳转是一个Future，可以用then监听回退到当前页面

**Comment by libinwalan** [comment]
嗯  好像可以用futurebuilder来实现。我试试。谢谢
