### ISSUE TITLE
如何滑动到底部不自动加载更多，而是再次手动上拉加载更多

### ISSUE THREAD

**Issue by wangxiongtao** [xuelongqy/flutter_easyrefresh#345]

**Comment by xuelongqy** [comment]
取消无限加载即可，你可以使用在demo里面了解所有的功能

**Comment by wangxiongtao** [comment]
谢谢，之前再demo找了半天 好像没找到
------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "xuelongqy/flutter_easyrefresh"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年8月5日(星期三) 下午4:37
收件人:&nbsp;"xuelongqy/flutter_easyrefresh"<flutter_easyrefresh@noreply.github.com&gt;;
抄送:&nbsp;"晓梦千年"<1220577523@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [xuelongqy/flutter_easyrefresh] 如何滑动到底部不自动加载更多，而是再次手动上拉加载更多 (#345)





 
取消无限加载即可，你可以使用在demo里面了解所有的功能

**Comment by xuelongqy** [comment]
ClassicFooter中设置enableInfiniteLoad
