### ISSUE TITLE
下拉刷新时滚动距离监听有误

### ISSUE THREAD

**Issue by shelby-yao** [xuelongqy/flutter_easyrefresh#347]
在下拉刷新的时候监听该值_scrollController.position.pixels，在拉出默认触发区70的时候会发生pixels偏移60也就是一个extent的高度，请问是否可以规避该问题，因为我这里需要在下拉时时刻监听下拉高度以做背景拉伸

**Comment by xuelongqy** [comment]
因为需要固定header的高度，不然会列表失去焦点，会完全弹回，监听滚动距离的换需要配合Header或者Footer的状态一起

**Comment by shelby-yao** [comment]
> 因为需要固定header的高度，不然会列表失去焦点，会完全弹回，监听滚动距离的话需要配合Header或者Footer的状态一起

请问那个拉出触发区的header状态是什么，怎么获取？

**Comment by xuelongqy** [comment]
> > 因为需要固定header的高度，不然会列表失去焦点，会完全弹回，监听滚动距离的话需要配合Header或者Footer的状态一起
> 
> 请问那个拉出触发区的header状态是什么，怎么获取？

请查看文档和示例

**Comment by shelby-yao** [comment]
> > > 因为需要固定header的高度，不然会列表失去焦点，会完全弹回，监听滚动距离的话需要配合Header或者Footer的状态一起
> > 
> > 
> > 请问那个拉出触发区的header状态是什么，怎么获取？
> 
> 请查看文档和示例

可是监听NotificationHeader 的    LinkHeaderNotifier下拉时
一直都是 RefreshMode.drag这个状态，并没有在触发距离达到那一瞬间改变为其他状态

**Comment by shelby-yao** [comment]
就是箭头从下转上的那一瞬间

**Comment by xuelongqy** [comment]
可以使用NotificationHeader，监听高度。详情参考：[#366](https://github.com/xuelongqy/flutter_easyrefresh/issues/366)
