### ISSUE TITLE
iOS平台，默认情况下点击状态栏可以滚动到最顶部吗？

### ISSUE THREAD

**Issue by z234009184** [xuelongqy/flutter_easyrefresh#35]
iOS平台，默认情况下点击状态栏可以滚动到最顶部吗？是不是需要单独处理

**Comment by xuelongqy** [comment]
我没有试过，估计是没有的。你需要自己设置ScrollController去滚动到顶部

**Comment by z234009184** [comment]
好的

**Comment by zinwalin** [comment]
默认是可以的,  只要scrollController用的是PrimaryScrollController.of(context)
