### ISSUE TITLE
下拉刷新后，再次上拉加载更多，只能加载到一页

### ISSUE THREAD

**Issue by rankyangel2014** [xuelongqy/flutter_easyrefresh#350]
![image](https://user-images.githubusercontent.com/8031724/89898846-fcae6b80-dc13-11ea-9706-ab3a2714f23f.png)

**Comment by xuelongqy** [comment]
我觉得很可能是你代码逻辑的问题，请参考示例

**Comment by Fengxiangmei** [comment]
具体表现为先下拉一下，然后上拉，回到顶部下拉，然后再上拉就无法更新要加载的数据了。

**Comment by Fengxiangmei** [comment]
换了个pull_to_refresh，一切都正常了，这个控件可能还是有问题的。

**Comment by xuelongqy** [comment]
2.1.6已修复
