### ISSUE TITLE
ValueNotifier<TaskState> was used after being disposed

### ISSUE THREAD

**Issue by JanusKun** [xuelongqy/flutter_easyrefresh#352]
您好，感谢项目开源。项目里使用了您的这个开源列表刷新库，很不错。
**项目背景**：项目中现在用的状态管理框架是Provider，版本4.3.2。项目目前是混合开发，框架用的是flutte boost.版本1.17.1.这是项目背景.
**问题描述**：不过刚升级了版本到2.1.5.去掉之前2.1.1版本国际化代码，改用demo中现用的这种方式。2.1.1版本使用没什么问题。升级后，项目第一次请求数据没有问题，再次请求其他数据会报以下崩溃错误信息。
`Unhandled Exception: A ValueNotifier<TaskState> was used after being disposed.
    Once you have called dispose() on a ValueNotifier<TaskState>, it can no longer be used.
    #0      ChangeNotifier._debugAssertNotDisposed.<anonymous closure> (package:flutter/src/foundation/change_notifier.dart:106:9)
    #1      ChangeNotifier._debugAssertNotDisposed (package:flutter/src/foundation/change_notifier.dart:112:6)
    #2      ChangeNotifier.notifyListeners (package:flutter/src/foundation/change_notifier.dart:201:12)
    #3      ValueNotifier.value= (package:flutter/src/foundation/change_notifier.dart:274:5)
    #4      _EasyRefreshSliverLoadControlState.finishLoad (package:flutter_easyrefresh/src/footer/load_indicator.dart:635:25)
    #5      EasyRefreshController.finishLoad (package:flutter_easyrefresh/src/refresher.dart:652:25)
    #6      RefreshListViewModel.reload (package:ischool/provider1/view_model.dart:172:23)
    <asynchronous suspension>
    #7      RefreshListViewModel.refresh (package:ischool/provider1/view_model.dart:155:11)
    #8      _ActivistEvaluationListPageState.initState (package:ischool/modules/party/activist/page/activist_evaluation_list.dart:37:15)
    #9      StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:4640:58)
    #10     ComponentElement.mount (package:flutter/src/widgets/framework.dart:4476:5)
    #11     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3446:14)
    #12     Element.updateChild (package:flutter/src/widgets/framework.dart:3214:18)
    #13     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5830:14)
    #14     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3446:14)
    #15     Element.updateChild (package:flutter/src/widgets/framework.dart:3214:18)
    #16     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4527:16)
    #17     Element.rebuild (package:flutter/src/widgets/framework.dart:4218:5)
    #18     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4481:5)
    #19     ComponentElement.mount (package:flutter/src/widgets/framework.dart:4476:5)
    #20     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3446:14)
    #21     Element.updateChild (package:flutter/src/widgets/framework.dart:3214:18)
    #22     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5830:14)
    #23     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3446:14)
    #24     Element.updateChild (package:flutter/src/widgets/framework.dart:3214:18)
    #25     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5830:14)
    #26     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3446:14)
    #27     Element.updateChild (package:flutter/src/widgets/framework.dart:3214:18)
    #28     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4527:16)
    #29     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4675:11)
    #30     Element.rebuild (package:flutter/src/widgets/framework.dart:4218:5)
    #31     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4481:5)
    #32     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:4666:11)
    #33     ComponentElement.mount (package:flutter/src/widgets/framework.dart:4476:5)
    #34     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3446:14)
    #35     Element.updateChild (package:flutter/src/widgets/framework.dart:3214:18)
    #36     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5830:14)
    #37     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3446:14)
    #38     Element.updateChild (package:flutter/src/widgets/framework.dart:3214:18)
    #39     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5830:14)
    #40     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3446:14)
    #41     Element.updateChild (package:flutter/src/widgets/framework.dart:3214:18)
    #42     ComponentElement.performR`

**Comment by xuelongqy** [comment]
好的，我会尽快排查问题

**Comment by JanusKun** [comment]
> 好的，我会尽快排查问题

好的 感谢~~~~

**Comment by xuelongqy** [comment]
我目前无法确认你的问题。你可否帮忙看看是否在refresher.dart中有过一次dispose方法调用呢？

**Comment by JanusKun** [comment]
> 我目前无法确认你的问题。你可否帮忙看看是否在refresher.dart中有过一次dispose方法调用呢？
以下是对ChangeNotifier的一些封装。
class ViewModel with ChangeNotifier {
  /// 当前界面状态
  ViewState get state => _viewState;

  bool get isLoading => state == ViewState.loading;

  bool get isUpdate => state == ViewState.update;
  ........
  ........
}
/// 列表ViewModel 无上拉下拉刷新
abstract class ListViewModel<T> extends ViewModel {
  List<T> list = [];

  @override
  void request({bool init = true}) async {
    refresh(init: init);
  }

  /// 数据刷新
  /// 初始化界面 init = true, 如果界面已经存在,数据需要刷新 init = false
  Future<void> refresh({bool init = true}) async {
    if (init) {
      list.clear();
      setLoading();
    } else {
      setUpdate();
    }
    List<T> data = await loadData();
    list.clear();
    list.addAll(data);
    list.isEmpty ? setEmpty() : setSuccess();
  }

  ///实现接口  加载数据
  Future<List<T>> loadData();
}

/// 列表ViewModel 上拉下拉刷新
abstract class RefreshListViewModel<T> extends ViewModel {
  int page = 0;
  List<T> list = [];

  RefreshController refreshController = RefreshController();

  @override
  void request({bool init = true}) async {
    refresh(init: init);
  }

  /// 数据刷新
  /// 初始化界面 init = true, 如果界面已经存在,数据需要刷新 init = false(比如下拉刷新)
  Future<void> refresh({bool init = true}) async {
    if (init) {
      list.clear();
      setLoading(loading: false);
    } else {
      setUpdate();
    }
    await reload(true);
  }

  /// 上拉加载更多
  Future<void> loadMore() async {
    setUpdate();
    await reload(false);
  }

  /// 更新数据
  Future<void> reload(bool reload) async {
    reload ? page = 0 : page++;
    ListData data = await loadData();
    if (reload) {
      list.clear();
    }
    list.addAll(data.content.map((e) => formJson(e)).toList());
    refreshController.finishLoad(success: true, noMore: data.last);
    list.isEmpty ? setEmpty() : setSuccess();
  }

  ///实现接口  加载数据
  Future<ListData> loadData();

  ///实现接口  json to model
  T formJson(Map<String, dynamic> json);

  @override
  void dispose() {
    super.dispose();
    refreshController.dispose();
  }
}

**Comment by JanusKun** [comment]
> 我目前无法确认你的问题。你可否帮忙看看是否在refresher.dart中有过一次dispose方法调用呢？

> 以下是代码里的一些封装
`class ViewModel with ChangeNotifier {
  /// 当前界面状态
  ViewState get state => _viewState;

  bool get isLoading => state == ViewState.loading;
  ............
}`
`/// 列表ViewModel 上拉下拉刷新
abstract class RefreshListViewModel<T> extends ViewModel {
int page = 0;
  List<T> list = [];
  /// 继承自EasyRefreshController
  RefreshController refreshController = RefreshController();
@override
  void request({bool init = true}) async {
    refresh(init: init);
  }
  /// 数据刷新
  /// 初始化界面 init = true, 如果界面已经存在,数据需要刷新 init = false(比如下拉刷新)
  Future<void> refresh({bool init = true}) async {
    if (init) {
      list.clear();
      setLoading(loading: false);
    } else {
      setUpdate();
    }
    await reload(true);
  }

  /// 上拉加载更多
  Future<void> loadMore() async {
    setUpdate();
    await reload(false);
  }

  /// 更新数据
  Future<void> reload(bool reload) async {
    reload ? page = 0 : page++;
    ListData data = await loadData();
    if (reload) {
      list.clear();
    }
    list.addAll(data.content.map((e) => formJson(e)).toList());
    refreshController.finishLoad(success: true, noMore: data.last);
    list.isEmpty ? setEmpty() : setSuccess();
  }

  ///实现接口  加载数据
  Future<ListData> loadData();

  ///实现接口  json to model
  T formJson(Map<String, dynamic> json);

  @override
  void dispose() {
    super.dispose();
    refreshController.dispose();
  }
}`

**Comment by JanusKun** [comment]
> 我目前无法确认你的问题。你可否帮忙看看是否在refresher.dart中有过一次dispose方法调用呢？

目前仍使用的是2.1.1版本，代码没变动。正常使用中。

**Comment by henryneu** [comment]
我也是遇到这个问题，我是结合自定义TabBar使用的，在TabBar切换时，会报这个错误，但是在切换后，再下拉刷新就没问题了，目前没定位到问题，大家有遇到的话，可以指点一下

**Comment by 387587243** [comment]
我也是遇到这个问题，状态管理用的fish_redux，页面用了模拟的TabBar，也是切换Tab的时候会报错，刷新和加载都不报错

**Comment by henryneu** [comment]
> 我也是遇到这个问题，我是结合自定义TabBar使用的，在TabBar切换时，会报这个错误，但是在切换后，再下拉刷新就没问题了，目前没定位到问题，大家有遇到的话，可以指点一下

我换了一个思路，做了TabBar下对应列表页的状态保活，为每一个列表页单独设置了一个EasyRefreshController，就不再报这个错误了，具体原因我还不太清楚，不过问题解决了

**Comment by xuelongqy** [comment]
> > 我也是遇到这个问题，我是结合自定义TabBar使用的，在TabBar切换时，会报这个错误，但是在切换后，再下拉刷新就没问题了，目前没定位到问题，大家有遇到的话，可以指点一下
> 
> 我换了一个思路，做了TabBar下对应列表页的状态保活，为每一个列表页单独设置了一个EasyRefreshController，就不再报这个错误了，具体原因我还不太清楚，不过问题解决了

我觉得应该与生命周期的控制有关，多个tab页切换会出现先构建然后马上销毁

**Comment by xuelongqy** [comment]
请尝试2.1.6版本

**Comment by jiouloucse** [comment]
> 我也是遇到这个问题，状态管理用的fish_redux，页面用了模拟的TabBar，也是切换Tab的时候会报错，刷新和加载都不
请问您解决了吗 我没有使用tabview 用的fish——redux 也出现了这个问题

**Comment by xuelongqy** [comment]
> > 我也是遇到这个问题，状态管理用的fish_redux，页面用了模拟的TabBar，也是切换Tab的时候会报错，刷新和加载都不
> > 请问您解决了吗 我没有使用tabview 用的fish——redux 也出现了这个问题

将在下个版本修复 [issues#382](https://github.com/xuelongqy/flutter_easyrefresh/issues/382)

**Comment by xuelongqy** [comment]
v2.1.7已修复

**Comment by JunnanLee** [comment]
使用的 2.1.8 在多个tab 中使用下拉刷新报错 A ValueNotifier<TaskState> was used after being disposed.
页面有三个tab ，中间的那个多下拉几次就会报错

**Comment by xiongcaichang** [comment]
@xuelongqy  嗯嗯，最新版本出现了。

**Comment by RunningTheSnail** [comment]
> 使用的 2.1.8 在多个tab 中使用下拉刷新报错 A ValueNotifier was used after being disposed.
> 页面有三个tab ，中间的那个多下拉几次就会报错

后面你们是怎么解决的。

**Comment by chaochaox1990** [comment]
add+1

**Comment by Ronadlo7** [comment]
就是在多个tab中使用会出现，关键还不是每次都出现，

**Comment by linkjd** [comment]
maybe no EasyRefresh after you switch tab, like this:
this._list.length > 0 ? EasyRefresh() : Text("no data")

**Comment by clycheng2015** [comment]
最新版本2.2.1下拉刷新时也触发了这个问题，每次下拉都提示！

**Comment by AlianOL** [comment]
> 最新版本2.2.1下拉刷新时也触发了这个问题，每次下拉都提示！

我也在2.2.1遇到了这个问题，我是搜索完之后调用频繁了会出现这个问题，不知道能不能做个防护
