### ISSUE TITLE
最新版的  flutter_easyrefresh: ^2.1.5

### ISSUE THREAD

**Issue by LWTFLH** [xuelongqy/flutter_easyrefresh#353]
无法本地化，之前有 GlobalEasyRefreshLocalizations.delegate, 这个类，升级后没有了，报错，模拟器已经是中文了，刷新插件还是英文提示，请问是怎么回事。

**Comment by xuelongqy** [comment]
非常抱歉，自带的国际化已经取消了。文档已修改，请查考
