### ISSUE TITLE
下拉刷新不会结束，上拉加载是正常的  

### ISSUE THREAD

**Issue by 623034345** [xuelongqy/flutter_easyrefresh#355]
![image](https://user-images.githubusercontent.com/21259873/91676971-002e7600-eb74-11ea-947b-1f08ec1e3839.png)

数据返回后 调用了如下三个方法：
            _controller.resetLoadState();
            _controller.finishLoad();
            _controller.finishRefresh(noMore: false);
这时候发现上拉加载正常  但是下拉刷新的时候不会结束，奇怪的是上拉加载一次再执行下拉刷新就正常了，但是再次下拉刷新的时候 仍然不正常
![image](https://user-images.githubusercontent.com/21259873/91677082-4f74a680-eb74-11ea-9e4c-fb90f5f8ab7f.png)
经过断点调试发现  这个finishRefreshCallBack 打印是null  所以判断无法进入  但是我下拉刷新完全按照demo 的写法  不应该有这种问题

**Comment by YangJ0720** [comment]
下拉刷新的时候，快速滑动到底部上拉加载更多，会导致上拉加载直接显示加载完毕（实际上并没有执行上拉加载的操作）

**Comment by 623034345** [comment]
我这个是直接下拉刷新就不会结束  一直转圈 
 _controller.resetLoadState();
_controller.finishLoad();
_controller.finishRefresh(noMore: false);
这三个方法都调用了 还是不结束  打断点是因为这个finishRefreshCallBack ==null 导致的  不知道为什么

**Comment by xuelongqy** [comment]
2.1.6已修复

**Comment by KimiSet** [comment]
下拉刷新的时候，快速滑动到底部上拉加载更多，会导致上拉加载直接显示加载完毕（实际上并没有执行上拉加载的操作）------该问题修复了吗？
