### ISSUE TITLE
下拉刷新触发释放刷新的瞬间 滚动距离突然降低

### ISSUE THREAD

**Issue by DNetORM** [xuelongqy/flutter_easyrefresh#356]
下拉刷新，触发释放刷新的瞬间，滚动距离突然改变的问题
/flutter (14999): -74.36527863705543
I/flutter (14999): -74.5683254756061
I/flutter (14999): -14.816614387387148
I/flutter (14999): -15.064706045164924
I/flutter (14999): -15.312600683940893
如果界面里有浮动的元素，依赖这个滚动距离 scrollController.position.pixels，就会导致这个元素突然向上跃进了60个像素。

**Comment by DNetORM** [comment]
我的建议是 让滚动距离平滑的过度，不要出现断崖式改变

**Comment by DNetORM** [comment]
可以上extent高度一秒内逐渐降低，就可以了，不要瞬间将高度变为0

**Comment by xuelongqy** [comment]
可以使用NotificationHeader，监听高度。详情参考：[#366](https://github.com/xuelongqy/flutter_easyrefresh/issues/366)
