### ISSUE TITLE
国际化问题

### ISSUE THREAD

**Issue by zjxhdlj** [xuelongqy/flutter_easyrefresh#358]
import 'package:flutter_easyrefresh/easy_refresh.dart';

同时添加了localizationsDelegates: [
        GlobalEasyRefreshLocalizations.delegate,
]

还是会报错The getter 'GlobalEasyRefreshLocalizations' isn't defined for the class '_MyAppState'

**Comment by xuelongqy** [comment]
不再提供自带国际化，请查看文档
