### ISSUE TITLE
iOS 滚动到第第二页偏下的位置, 点击滚动视图里面的Widget事件, 会触发onLoading事件

### ISSUE THREAD

**Issue by CarlXu1008** [xuelongqy/flutter_easyrefresh#360]
iOS 滚动到第第二页偏下的位置, 点击滚动视图里面的Widget事件, 会触发onLoading事件,  导致跳转到下一页之后, 返回会出现页面自己滚动的情况. 

另外还有一个崩溃问题:  出现异常。
FlutterError (EasyRefreshPhysics.applyBoundaryConditions returned invalid overscroll value.
The method was called to consider a change from 3167.0749646616514 to 3068.6683588088713, which is a delta of -98.4 units. However, it returned an overscroll of 182.4 units, which has a greater magnitude than the delta. The applyBoundaryConditions method is only supposed to reduce the possible range of movement, not increase it.
The scroll extents are 0.0 .. 2886.229001499251, and the viewport dimension is 606.0.)

**Comment by xuelongqy** [comment]
请尝试2.1.6版本
