### ISSUE TITLE
当slivers里的SliverList换成SliverGrid后，firstRefresh功能就失效了

### ISSUE THREAD

**Issue by wvvw12** [xuelongqy/flutter_easyrefresh#361]
作者您好，首先十分感谢您分享的flutter_easyrefresh插件。

我根据用例使用第二种方式“ EasyRefresh.custom() ”建立首次刷新的功能时，其中的 “ slivers: ” 里的 “ SliverList ” 控件换成了 “ SliverGrid ” 后，firstRefresh 功能就失效了。

由于自己是flutter新手，没能力去查明该问题的出现；
如果是自己使用方式问题，麻烦您指明一下。

再次感谢您的贡献

**Comment by wvvw12** [comment]
不好意思，忘了放上代码。

`import 'package:flutter/material.dart';
import 'package:flutter_easyrefresh/easy_refresh.dart';

class RecommendPage extends StatefulWidget {
  RecommendPage({Key key}) : super(key: key);

  @override
  _RecommendPageState createState() => _RecommendPageState();
}

class _RecommendPageState extends State<RecommendPage> {
  final List<String> _imgList = const [
    "https://ss3.bdstatic.com/70cFv8Sh_Q1YnxGkpoWK1HF6hhy/it/u=3941201315,3164925962&fm=26&gp=0.jpg",
    "https://timgsa.baidu.com/timg?image&quality=80&size=b9999_10000&sec=1590429306894&di=66063b73daae38b0298474e905bafa96&imgtype=0&src=http%3A%2F%2F04.imgmini.eastday.com%2Fmobile%2F20180811%2F20180811144208_2a720b08e4862cc5804dd6cf96a95c52_1.jpeg",
    "https://timgsa.baidu.com/timg?image&quality=80&size=b9999_10000&sec=1590429306894&di=dd69ae3caa0a411d137af8b1f20f5147&imgtype=0&src=http%3A%2F%2Fb-ssl.duitang.com%2Fuploads%2Fitem%2F201701%2F28%2F20170128151037_mxjyh.jpeg",
    "https://timgsa.baidu.com/timg?image&quality=80&size=b9999_10000&sec=1590429306894&di=9acb5f4ceb10d85defc7c10e91d76c4d&imgtype=0&src=http%3A%2F%2Fn.sinaimg.cn%2Fsinacn%2Fw580h739%2F20180313%2F626b-fyscsmv0233314.jpg",
    "https://timgsa.baidu.com/timg?image&quality=80&size=b9999_10000&sec=1590429306894&di=769b1cecaffe7d5e33a253a08214d07f&imgtype=0&src=http%3A%2F%2Fp0.meituan.net%2Fwedding%2F959d3f92597f8478f4b77584402c3a87189171.jpg",
    "https://timgsa.baidu.com/timg?image&quality=80&size=b9999_10000&sec=1590429306894&di=2bfb110fd58e448e2342cd5197869dbb&imgtype=0&src=http%3A%2F%2Fhbimg.b0.upaiyun.com%2F46b3d51eef67a9d927661c09c48c42e83aeeb7611f933e-7xqzCT_fw658",
    "https://timgsa.baidu.com/timg?image&quality=80&size=b9999_10000&sec=1590429306892&di=4c4812c0960547347d50f4ba16aa9f30&imgtype=0&src=http%3A%2F%2Fimg1.gtimg.com%2Fxian%2Fpics%2Fhv1%2F50%2F47%2F2136%2F138905435.jpg",
    "https://timgsa.baidu.com/timg?image&quality=80&size=b9999_10000&sec=1590429306892&di=466c820f2693def553ece7d795955a32&imgtype=0&src=http%3A%2F%2Fimg.mp.itc.cn%2Fupload%2F20170607%2F7764479087a945ab9494729c9ee4558a_th.jpg",
    "https://timgsa.baidu.com/timg?image&quality=80&size=b9999_10000&sec=1590429306891&di=962be1d46ab259dd9036bedb0146b682&imgtype=0&src=http%3A%2F%2F00.minipic.eastday.com%2F20161107%2F20161107143034_82e40f3bfb3a355f310dce3c94c190b1_15.jpeg",
    "https://timgsa.baidu.com/timg?image&quality=80&size=b9999_10000&sec=1590429306890&di=009162b16e86e80b17f8281a7a3b151c&imgtype=0&src=http%3A%2F%2Fqimg.hxnews.com%2F2017%2F0922%2F1506066594443.jpg",
    "https://timgsa.baidu.com/timg?image&quality=80&size=b9999_10000&sec=1590429306890&di=d1d7aa45ee93abf75bd8dcb7bcd3b07e&imgtype=0&src=http%3A%2F%2F5b0988e595225.cdn.sohucs.com%2Fq_70%2Cc_zoom%2Cw_640%2Fimages%2F20180716%2F4e0332e8f1bb406085e2926c63b61b64.jpeg",
    'https://timgsa.baidu.com/timg?image&quality=80&size=b9999_10000&sec=1590429306926&di=d7cb954c27674bd98ac714ffc17ccdd6&imgtype=0&src=http%3A%2F%2F00.minipic.eastday.com%2F20170210%2F20170210165256_18cc9cf7204413fa79a1617c55dd44b7_3.jpeg',
    'https://timgsa.baidu.com/timg?image&quality=80&size=b9999_10000&sec=1590429306926&di=4968137b9cd7bff87c7a10a0b146f593&imgtype=0&src=http%3A%2F%2Fb-ssl.duitang.com%2Fuploads%2Fitem%2F201710%2F31%2F20171031091430_XvTw4.jpeg'
  ];

  int _count = 0;

  @override
  Widget build(BuildContext context) {
    return EasyRefresh.custom(
      firstRefresh: true,
      firstRefreshWidget: Container(
        width: double.infinity,
        height: double.infinity,
        child: Center(
          child: SizedBox(
            height: 200.0,
            width: 300.0,
            child: Card(
              child: Column(
                mainAxisAlignment: MainAxisAlignment.center,
                crossAxisAlignment: CrossAxisAlignment.center,
                children: <Widget>[
                  Container(
                    width: 150.0,
                    height: 50.0,
                    child: Text("加载中..."),
                  ),
                ],
              ),
            ),
          ),
        ),
      ),

      slivers: <Widget>[
        // SliverList(
        //   delegate: SliverChildBuilderDelegate(
        //     (context, index) {
        //       int i = index > 12 ? (index % 12) : index;
        //       return Card(
        //         child: Image.network(_imgList[i]),
        //       );
        //     },
        //     childCount: _count,
        //   ),
        // ),

        SliverGrid(
          delegate: SliverChildBuilderDelegate(
            (BuildContext context, int index) {
              int i = index > 12 ? (index % 12) : index;
              return Card(
                child: Image.network(_imgList[i]),
              );
            },
            childCount: _count,
          ),
          gridDelegate: SliverGridDelegateWithFixedCrossAxisCount(
            crossAxisCount: 2,
            childAspectRatio: 2 / 3,
          ),
        ),
      ],

      onRefresh: () async {
        await Future.delayed(
          Duration(seconds: 2),
          () {
            if (mounted) {
              setState(
                () {
                  _count = 19;
                },
              );
            }
          },
        );
      },

      onLoad: () async {
        await Future.delayed(
          Duration(seconds: 2),
          () {
            if (mounted) {
              setState(
                () {
                  _count += 19;
                },
              );
            }
          },
        );
      },
    );
  }
}`

**Comment by xuelongqy** [comment]
请参考[issue#195](https://github.com/xuelongqy/flutter_easyrefresh/issues/195)，请勿重复提交issue。如果有用麻烦关一下issue。
