### ISSUE TITLE
tab切换时，重置了noMore

### ISSUE THREAD

**Issue by bayun2** [xuelongqy/flutter_easyrefresh#364]
页面 Tab 布局基于 DefaultTabController + TabBarView，第一个 tab 已经通过设置 controller.finishLoad(success: true, noMore: true); footer可以显示 noMore的文案了。tab 切换到第二个 view（任意内容） 再切回来，noMore 被重置成了 false
已经设置了页面 AutomaticKeepAliveClientMixin 相关
也设置了 widget 的 key

**Comment by bayun2** [comment]
改成像官网的 demo 一样，使用 IndexedStack 可以规避 DefaultTabController + TabBarView 产生的状态重置的 bug

**Comment by xuelongqy** [comment]
这是因为页面没有保活的原因，状态被重置了

**Comment by bayun2** [comment]
并不是，上面已经提到设置了页面保活的，DefaultTabController + TabBarView 可以必现该 bug

**Comment by xuelongqy** [comment]
> 并不是，上面已经提到设置了页面保活的，DefaultTabController + TabBarView 可以必现该 bug

是这个原因吗？[flutter AutomaticKeepAliveClientMixin不起作用？](https://www.jianshu.com/p/03e4e5df826a)

**Comment by bayun2** [comment]
加了的，我写过demo，剔除了业务，用一个最纯静的也会有问题的
