### ISSUE TITLE
EasyRefresh嵌套NestedScrollView使用，下拉刷新和上拉加载都失效了

### ISSUE THREAD

**Issue by Luffys6** [xuelongqy/flutter_easyrefresh#369]
EasyRefresh嵌套NestedScrollView使用，下拉刷新和上拉加载都失效了

**Comment by xuelongqy** [comment]
请参考示例

**Comment by kaijiemu** [comment]
> 请参考示例

看了示例，里面是，NestedScrollView包裹了EasyRefresh，但我的需求想EasyRefresh，包裹NestedScrollView可以吗

**Comment by kaijiemu** [comment]
> EasyRefresh嵌套NestedScrollView使用，下拉刷新和上拉加载都失效了

大佬，我也遇到这个问题，你解决了吗

**Comment by smart005** [comment]
哪位大佬解决了啊分享一下

**Comment by Luffys6** [comment]
> 哪位大佬解决了啊分享一下

不知道咋解决

**Comment by Luffys6** [comment]
@xuelongqy

**Comment by kaijiemu** [comment]
咨询了作者大佬，说暂时无法解决

**Comment by Luffys6** [comment]
> 咨询了作者大佬，说暂时无法解决

好的
