### ISSUE TITLE
Flutter v1.22.0 版本 安装refresh2.1.5版本出错

### ISSUE THREAD

**Issue by LeoDicaprio** [xuelongqy/flutter_easyrefresh#373]
flutter pub get
Running "flutter pub get" in new_shop...                        
Because flutter_easyrefresh >=2.0.6 depends on cupertino_icons ^0.1.3 and new_shop depends on cupertino_icons ^1.0.0, flutter_easyrefresh >=2.0.6 is forbidden.

So, because new_shop depends on flutter_easyrefresh ^2.1.5, version solving failed.

是因为 cupertino_icons: ^1.0.0 的版本是1.0.0
做下适配？

**Comment by WingCH** [comment]
同問！

**Comment by xuelongqy** [comment]
下个版本将会去掉cupertino_icons依赖

**Comment by xuelongqy** [comment]
2.1.6已修复
