### ISSUE TITLE
上拉加载更多网络请求失败不会自己结束

### ISSUE THREAD

**Issue by git-maven** [xuelongqy/flutter_easyrefresh#374]
在网络请求失败时候我进行的操作：
refreshController.resetLoadState();
refreshController.resetRefreshState();
refreshController.finishRefresh();
refreshController.finishLoad(noMore: !hasMore);

当网络请求失败，列表不进行增加的时候，上拉加载就会卡住不动

**Comment by git-maven** [comment]
![Uploading 1602399049242.jpg…]()

**Comment by git-maven** [comment]
![1602399049242](https://user-images.githubusercontent.com/45022397/95672473-a2119b80-0bd3-11eb-96f8-d2ad8c551c3b.jpg)

**Comment by git-maven** [comment]
使用了你的example，上拉加载的时候只要列表不增加，就会卡在LoadCompleted，不能自己收叠

**Comment by xuelongqy** [comment]
使用主动控制，可以设置加载失败的

**Comment by xuelongqy** [comment]
关闭无限加载既可
