### ISSUE TITLE
使用主动控制，可以设置加载失败的

### ISSUE THREAD

**Issue by git-maven** [xuelongqy/flutter_easyrefresh#376]
使用主动控制，可以设置加载失败的

_Originally posted by @xuelongqy in https://github.com/xuelongqy/flutter_easyrefresh/issues/374#issuecomment-706897300_

这边测试过设置加载失败还是会占用一层footer，如果想要加载失败不显示footer，直接恢复未进行上拉加载的状态，要如何设置呢？

**Comment by xuelongqy** [comment]
关闭无限加载
