### ISSUE TITLE
Footer behind BottomAppBar

### ISSUE THREAD

**Issue by BPHvZ** [xuelongqy/flutter_easyrefresh#38]
When using a BottomAppBar the Footer is behind the BottomAppBar on loading new data

**Comment by xuelongqy** [comment]
You can use bottomNavigationBar or ConnectorHeader. Such as [CupertinoPage](https://github.com/xuelongqy/flutter_easyrefresh/blob/master/example/lib/page/sample/cupertino_page.dart)
