### ISSUE TITLE
ios首次加载bug

### ISSUE THREAD

**Issue by dmskys** [xuelongqy/flutter_easyrefresh#383]
════════ Exception caught by foundation library ════════════════════════════════════════════════════
The following assertion was thrown while dispatching notifications for ValueNotifier<TaskState>:
setState() or markNeedsBuild() called during build.

This EasyRefresh widget cannot be marked as needing to build because the framework is already in the process of building widgets.  A widget can be marked as needing to be built during the build phase only if one of its ancestors is currently building. This exception is allowed because the framework builds parent widgets before children, which means a dirty descendant will always be built. Otherwise, the framework might not visit this widget during this build phase.
The widget on which setState() or markNeedsBuild() was called was: EasyRefresh
  state: _EasyRefreshState#1df6f
The widget which was currently being built when the offending call was made was: LayoutBuilder
  renderObject: _RenderLayoutBuilder#fb71b relayoutBoundary=up2 NEEDS-PAINT
When the exception was thrown, this was the stack: 
#0      Element.markNeedsBuild.<anonymous closure> (package:flutter/src/widgets/framework.dart:4292:11)
#1      Element.markNeedsBuild (package:flutter/src/widgets/framework.dart:4307:6)
#2      State.setState (package:flutter/src/widgets/framework.dart:1264:14)
#3      _EasyRefreshState.initState.<anonymous closure> (package:flutter_easyrefresh/src/refresher.dart:286:9)
#4      ChangeNotifier.notifyListeners (package:flutter/src/foundation/change_notifier.dart:226:25)
...
The ValueNotifier<TaskState> sending notification was: ValueNotifier<TaskState>#ae821(Instance of 'TaskState')
════════════════════════════════════════════════════════════════════════════════════════════════════

**Comment by xuelongqy** [comment]
非常感谢，将在下个版本修复 [issues#382](https://github.com/xuelongqy/flutter_easyrefresh/issues/382)

**Comment by xuelongqy** [comment]
v2.1.7已修复
