### ISSUE TITLE
NestedScrollViewPage例子里给ListView和GridView添加PageStorageKey无效

### ISSUE THREAD

**Issue by JDNew** [xuelongqy/flutter_easyrefresh#384]
如题，我想切换tab的时候，两个列表还各自记录上一次的滚动位置，我就给ListView和GridView各自加了PageStorageKey，但还是没有效果。

如果我给ListView和GridView的外面加上Scaffold，此时再设置PageStorageKey就有效，但就达不到上滑列表头部能折叠的效果。

**Comment by xuelongqy** [comment]
请看示例

**Comment by JDNew** [comment]
@xuelongqy 你好，发现在一些机子上，左边ListView滚动，切换右边GridView tab的时候，会导致GridView上移少许部分。

**Comment by xuelongqy** [comment]
> @xuelongqy 你好，发现在一些机子上，左边ListView滚动，切换右边GridView tab的时候，会导致GridView上移少许部分。

请参考示例

**Comment by henryneu** [comment]
> @xuelongqy 你好，发现在一些机子上，左边ListView滚动，切换右边GridView tab的时候，会导致GridView上移少许部分。

这个确实是的，我也发现了，你可以看一下我提的pull requests，我改了一下，现在每一个tab下面的列表都是互不影响了，这是我们测试给我提的bug
