### ISSUE TITLE
使用GridView时下拉刷新不回弹，ListView时正常

### ISSUE THREAD

**Issue by shifengbin** [xuelongqy/flutter_easyrefresh#388]
![image](https://user-images.githubusercontent.com/14366712/98329011-223feb00-2032-11eb-8538-7cd43e4da7f5.png)

**Comment by xuelongqy** [comment]
原因未知，GridView请勿让数据不满一屏，不满一屏可屏蔽上拉加载。请参考[issue#195](https://github.com/xuelongqy/flutter_easyrefresh/issues/195)

**Comment by shifengbin** [comment]
和我外层用PageView有关吗？我的数据是满一屏的，拉到下面的时候load状态就一直存在

**Comment by shifengbin** [comment]
问题找到了，是setState时更新状态方式不正确导致的
