### ISSUE TITLE
NestedScrollView demo刚拉下来就进界面就报错

### ISSUE THREAD

**Issue by AsFreeBird** [xuelongqy/flutter_easyrefresh#391]
The following _CastError was thrown building _NestedScrollViewCustomScrollView(scrollDirection: vertical, _NestedScrollController#7b114(outer, no clients), ClampingScrollPhysics -> ClampingScrollPhysics):
Null check operator used on a null value，新手谅解

**Comment by onewilk** [comment]
![image](https://user-images.githubusercontent.com/6149582/99947828-8218ee80-2db3-11eb-97c9-949341a9f0ca.png)

**Comment by xuelongqy** [comment]
v2.1.7已修复
