### ISSUE TITLE
EmptyWidget底部空白问题

### ISSUE THREAD

**Issue by sooYo** [xuelongqy/flutter_easyrefresh#393]
**列表从有数据状态经过下拉刷新进入空数据状态时，空白页的底部会出现Header高度的空白。**

##### 1.1 页面
```
class _MyHomePageState extends State<MyHomePage> {
  final _colors = [];

  @override
  Widget build(BuildContext context) {
    final listView = ListView(
      children: <Widget>[
        ..._colors.map((e) => Container(color: e, height: 180)),
      ],
    );

    final emptyView = _colors.length != 0 ? null : TestEmptyView();

    return Scaffold(
      body: EasyRefresh(
        emptyWidget: emptyView,
        onRefresh: _onRefresh,
        child: listView,
      ),
    );
  }

  Future<void> _onRefresh() async {
    await Future.delayed(Duration(seconds: 1));
    setState(() {
      if (_colors.isEmpty) {
        _colors.addAll([
          Colors.greenAccent,
          Colors.blueAccent,
          Colors.amber,
          Colors.purpleAccent,
        ]);
      } else {
        _colors.clear();
      }
    });
  }
}
```
##### 1.2 空白页
```
class TestEmptyView extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Container(
      color: Colors.teal,
      child: Center(
        child: Text('This is empty view'),
      ),
    );
  }
}
```

##### 2.1 初始状态
<img src="https://user-images.githubusercontent.com/1388305/99046494-c515dd80-25cd-11eb-8f17-1e094de0a388.png"  height=350 width=200/> 

##### 2.2 加载后有数据
<img src="https://user-images.githubusercontent.com/1388305/99046697-1625d180-25ce-11eb-950c-1e59d287f68d.png" height=350 width=200/>

##### 2.3 再次下拉得到空数据，空白页底部出现空白
<img src="https://user-images.githubusercontent.com/1388305/99046778-38b7ea80-25ce-11eb-847c-614253362e91.png" height=350 width=200/>

#### 3. 版本
1. Flutter (Channel stable, 1.22.1, on Mac OS X 10.15.7 19H15, locale zh-Hans-CN)
2. flutter_easyrefresh: version: "2.1.6"

**Comment by xuelongqy** [comment]
EmptyWidget只是为了方便而添加，不能保证占满剩余高度。苛刻条件下，请使用条件片段和高度计算自行实现空视图
