### ISSUE TITLE
使用EasyRefresh.custom方式传入自定义的footer 上拉加载报错

### ISSUE THREAD

**Issue by zjh12580** [xuelongqy/flutter_easyrefresh#395]
════════ Exception caught by foundation library ════════════════════════════════
The following assertion was thrown while dispatching notifications for ValueNotifier<TaskState>:
setState() or markNeedsBuild() called during build.

This EasyRefreshSliverRefreshControl widget cannot be marked as needing to build because the framework is already in the process of building widgets.  A widget can be marked as needing to be built during the build phase only if one of its ancestors is currently building. This exception is allowed because the framework builds parent widgets before children, which means a dirty descendant will always be built. Otherwise, the framework might not visit this widget during this build phase.
The widget on which setState() or markNeedsBuild() was called was: EasyRefreshSliverRefreshControl
    state: _EasyRefreshSliverRefreshControlState#27162
The widget which was currently being built when the offending call was made was: LayoutBuilder
    renderObject: _RenderLayoutBuilder#04a56 relayoutBoundary=up3 NEEDS-PAINT
When the exception was thrown, this was the stack
#0      Element.markNeedsBuild.<anonymous closure>
package:flutter/…/widgets/framework.dart:4292
#1      Element.markNeedsBuild
package:flutter/…/widgets/framework.dart:4307
#2      State.setState
package:flutter/…/widgets/framework.dart:1264
#3      _EasyRefreshSliverRefreshControlState.initState.<anonymous closure>
package:flutter_easyrefresh/…/header/refresh_indicator.dart:634
#4      ChangeNotifier.notifyListeners
package:flutter/…/foundation/change_notifier.dart:226
...
The ValueNotifier<TaskState> sending notification was: ValueNotifier<TaskState>#43198(Instance of 'TaskState')
════════════════════════════════════════════════════════════════════════════════

**Comment by zjh12580** [comment]
版本是2.1.6

**Comment by xuelongqy** [comment]
v2.1.7已修复
