### ISSUE TITLE
iOS端当滑动到顶部和底部的时候，没有回弹效果

### ISSUE THREAD

**Issue by MrReN** [xuelongqy/flutter_easyrefresh#40]
感谢您提供的刷新库，iOS端当滑动到顶部和底部的时候，没有回弹效果，看起来就像一下子就停下来了，很僵硬，滑动控件我使用的是CustomScrollView。不知道您是否解决了这个问题。请教了

**Comment by xuelongqy** [comment]
为了统一 所有平台都是一样的效果。如果你觉得ios没有回弹的话，你应该去运行一下Demo，也许你能找到答案
