### ISSUE TITLE
不须要下拉刷新，关闭回弹效果无效

### ISSUE THREAD

**Issue by zboboan** [xuelongqy/flutter_easyrefresh#400]
在 EasyRefresh.custom 下 onRefresh: null，topBouncing:false, ， 关闭回弹效果，但是无效，请问一下在不须要下拉刷新的时候要怎么关闭回弹

**Comment by xuelongqy** [comment]
顶部回弹(Header的overScroll属性优先，且onRefresh和header都为null时生效)

**Comment by zboboan** [comment]
> 
> 
> 顶部回弹(Header的overScroll属性优先，且onRefresh和header都为null时生效)

原来如此，谢谢
