### ISSUE TITLE
setState() or markNeedsBuild() called during build.

### ISSUE THREAD

**Issue by 2673542667** [xuelongqy/flutter_easyrefresh#405]
当组件挂载，并第一次自动下拉刷新的时候，会出现这个错误，使用TabBar，多页面，来回切换就会触发这个报错，有没有大佬给我指点一二

### This EasyRefresh widget cannot be marked as needing to build because the framework is already in the process of building widgets.  A widget can be marked as needing to be built during the build phase only if one of its ancestors is currently building. This exception is allowed because the framework builds parent widgets before children, which means a dirty descendant will always be built. Otherwise, the framework might not visit this widget during this build phase.
The widget on which setState() or markNeedsBuild() was called was: EasyRefresh
  state: _EasyRefreshState#1d515
The widget which was currently being built when the offending call was made was: LayoutBuilder
  renderObject: _RenderLayoutBuilder#4d5ba relayoutBoundary=up2
When the exception was thrown, this was the stack: 
#0      Element.markNeedsBuild.<anonymous closure> (package:flutter/src/widgets/framework.dart:4292:11)
#1      Element.markNeedsBuild (package:flutter/src/widgets/framework.dart:4307:6)
#2      State.setState (package:flutter/src/widgets/framework.dart:1264:14)
#3      _EasyRefreshState.initState.<anonymous closure> (package:flutter_easyrefresh/src/refresher.dart:286:9)
#4      ChangeNotifier.notifyListeners (package:flutter/src/foundation/change_notifier.dart:226:25)
...

**Comment by xuelongqy** [comment]
v2.1.7已修复

**Comment by 2673542667** [comment]
谢谢

**Comment by ismanong** [comment]
数据不到一屏幕也会报这个错
