### ISSUE TITLE
关于iOS上拉下拉优化问题

### ISSUE THREAD

**Issue by MrReN** [xuelongqy/flutter_easyrefresh#41]
我加上了behavior属性，他在iOS端看起来有点奇怪，不知道您发觉没有，他会突然跳一下.这种情况下发生在了下拉和上拉后，界面开始减速时，当界面滑动速度很慢，而又刚好到达顶端时，刷新动画，会突然加速，然后返回。如果快速上下拉动的话，动画效果看不出来。我认为是您在做动画时，控制动画时间的原因，动画时间过短造成的。我会尝试修改源码，也希望您能给个反馈

**Comment by MrReN** [comment]
我看了您的源码，请教下，为什么要限制滚动,在refresher.dart文件中
 if (widget.limitScroll) {
        _scrollPhysics = _neverScrollableScrollPhysics;
      } else {
        _scrollPhysics = RefreshAlwaysScrollPhysics(
//            scrollOverListener: _getScrollOverListener(),
            headerPullBackRecord: false,
            footerPullBackRecord: false);
      }

**Comment by xuelongqy** [comment]
limitScroll参数的意思是，刷新过程中不允许列表滚动。由于EasyRefresh的实现原理以及Flutter的一些原因，目前只能通过速度模拟回弹，所以回弹不是那么完善，如果你也感兴趣的话，我们可以一起研究

**Comment by xuelongqy** [comment]
v2版本已重构
