### ISSUE TITLE
CustomScrollView+EasyRefresh.builder Firstrefresh无效

### ISSUE THREAD

**Issue by growtechgit** [xuelongqy/flutter_easyrefresh#410]
CustomScrollView+EasyRefresh.builder Firstrefresh无效
页面首次加载的时候无法正常调用 onrefresh方法
代码结构如下：
请指正：
return new Scaffold(
            backgroundColor: Colours.pageBackgroundcolor, //分割线
            body: 
EasyRefresh.builder(
              onRefresh: () async {
                await mybloc.GetProfileData(AppVars.getinstance().usrID);
              },
              onLoad: null,
              firstRefresh: true,
              enableControlFinishRefresh: false,
              bottomBouncing: false,
              controller: _refreshController,
              header:
                  ClassicalHeader(), //ClassicalHeader(), //MaterialHeader(), //SpaceHeader(),
              builder: (context, physics, header, footer) {
                return new CustomScrollView(
                  controller: _scrollController,
                  physics: physics,
                  slivers: <Widget>[
                    SliverAppBar(),
                    header,
                    SliverList(),]

**Comment by xuelongqy** [comment]
EasyRefresh.builder Firstrefresh无效，后续会在文档中说明。使用EasyRefresh.custom即可，内部使用CustomScrollView实现
