### ISSUE TITLE
NoSuchMethodError: The method '>' was called on null

### ISSUE THREAD

**Issue by wutiaorong** [xuelongqy/flutter_easyrefresh#411]
调用callRefresh会出现这种问题。用的是2.1.7。可以帮忙看下吗
crash_exception_name => NoSuchMethodError
crash_message => NoSuchMethodError: The method '>' was called on null. Receiver: null Tried calling: >()
crash_thread_tag => ScrollPosition._updateSemanticActions$ScrollPosition.notifyListeners$ScrollPosition.forcePixels$ScrollPositionWithSingleContext.jumpTo$

#0 ScrollPosition._updateSemanticActions (package:flutter/src/widgets/scroll_position.dart:472)
#1 ScrollPosition.notifyListeners (package:flutter/src/widgets/scroll_position.dart:809)
#2 ScrollPosition.forcePixels (package:flutter/src/widgets/scroll_position.dart:346)
#3 ScrollPositionWithSingleContext.jumpTo (package:flutter/src/widgets/scroll_position_with_single_context.dart:202)
#4 ScrollPositionWithSingleContext.animateTo (package:flutter/src/widgets/scroll_position_with_single_context.dart:181)
#5 ScrollController.animateTo (package:flutter/src/widgets/scroll_controller.dart:159)
#6 _EasyRefreshState.callRefresh (package:flutter_easyrefresh/src/refresher.dart:368)
#7 EasyRefreshController.callRefresh (package:flutter_easyrefresh/src/refresher.dart:621)

**Comment by xuelongqy** [comment]
试试看2.1.8呢

**Comment by wutiaorong** [comment]
> 试试看2.1.8呢

我试试看

**Comment by xuelongqy** [comment]
v3已发布，也许问题得到解决。如果问题依然存在，请重新打开
