### ISSUE TITLE
使用 Tabar + TabBarView 有报错

### ISSUE THREAD

**Issue by marscj** [xuelongqy/flutter_easyrefresh#416]
使用 Tabar + TabBarView 有报错

The method 'dependOnInheritedWidgetOfExactType' was called on null.
Receiver: null
Tried calling: dependOnInheritedWidgetOfExactType<PrimaryScrollController>()

从页面1 直接切换到 页面3 就会报错， 
目前使用了 tabbar + pageview 替代 找了很久才发现这个原因

**Comment by xuelongqy** [comment]
请贴上报错代码示例，谢谢

**Comment by xuelongqy** [comment]
v3已发布，也许问题得到解决。如果问题依然存在，请重新打开
