### ISSUE TITLE
header显示在最上层

### ISSUE THREAD

**Issue by henghadawang** [xuelongqy/flutter_easyrefresh#417]
1.当数据不足一屏时，拖拽控件header会出现在其他控件的上面，超过一屏时不会出现此问题。
2.代码是基于2.1.8版本demo改的

https://user-images.githubusercontent.com/13497905/103630172-4493ad80-4f7c-11eb-9a08-e34280618041.mp4

**Comment by henghadawang** [comment]
@xuelongqy

**Comment by xuelongqy** [comment]
目前无法解决，有什么使用场景吗？既然要下拉刷新，为什么需要覆盖在列表上方？

**Comment by henghadawang** [comment]
> 目前无法解决，有什么使用场景吗？既然要下拉刷新，为什么需要覆盖在列表上方？

上面是筛选卡，比如按到访时间排序，到访次数排序等，有什么思路吗？多谢多谢

**Comment by xuelongqy** [comment]
我觉得临时的解决办法，把列表顶下去。如果筛选卡需要显示隐藏的话，可以做一个向下滑动的动画呢

**Comment by henghadawang** [comment]
> 我觉得临时的解决办法，把列表顶下去。如果筛选卡需要显示隐藏的话，可以做一个向下滑动的动画呢

好的，这个跟产品商量下，多谢。这个后续版本能考虑修复吗？

**Comment by Yuanqiumei** [comment]
页面的都写在child里面吗？可以试试float

**Comment by xuelongqy** [comment]
v3已发布，也许问题得到解决。如果问题依然存在，请重新打开
