### ISSUE TITLE
需要帮助 1.刷新之后同时在footer提示no more; 2.callRefresh不想滚动到顶部

### ISSUE THREAD

**Issue by lan2000** [xuelongqy/flutter_easyrefresh#418]
大佬好，我有些疑问想请教：
第一个想知道，设置footer: ClassicalFooter() ，如果finishRefresh(success: true, noMore: false)刷新完成后，同时设置“上拉加载”没有更多数据，怎么让“no more” footer显示出来呢。我在刷新之后尝试调用controller.finishLoad(success: true, noMore: true);但是它并没显示。

第二个是，设置header: MaterialHeader()，手动controller().callRefresh()触发刷新，它会自动滚动顶部进行刷新，怎么让它不滚动顶部呢，直接显示MaterialHeader进行刷新呢。

谢谢，麻烦大佬了！

**Comment by lan2000** [comment]
回来看看~~
继续等待答案

**Comment by xuelongqy** [comment]
v3 Notifier.animateToOffset 也许可以帮助到你。v3已发布，请及时更新。如果问题依然存在，请重新打开

**Comment by saviourdog** [comment]
@lan2000 靓仔解决了没
