### ISSUE TITLE
快速滑到顶部，条目点击手势会失效大概2秒

### ISSUE THREAD

**Issue by lan2000** [xuelongqy/flutter_easyrefresh#420]
列表滑到下面，在快速滑到顶部。这个时候SliverToBoxAdapter里面的InkWell点击事件无效，水波纹也没有。大概过2秒，点击就恢复了。

代码如下，很：

@override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text('MyInfoMainPage'),
      ),
      body: Container(
        child: EasyRefresh.custom(
          footer: ClassicalFooter(showInfo: false,completeDuration:null,enableHapticFeedback:false),
          header: MaterialHeader(completeDuration:null),
          firstRefresh: true,
          onRefresh:() async{
            print("--------------onRefresh--");
          },
          onLoad: ()async{},
          slivers: [
            SliverToBoxAdapter(
              child: SizedBox(
                height: 40,
                child: Container(),
              ),
            ),
            SliverToBoxAdapter(
              child: SizedBox(
                height: 40,
                child: InkWell(
                  onTapDown: (_){
                    print("--------------onTapDown--");
                  },
                  onTap: (){
                    print("--------点击------InkWell--");//这里的点击会失效
                  },
                  child: Text('aaaaaaaaaa',style: TextStyle(fontSize: 33),),
                ),
              ),
            ),
            SliverGrid(
                delegate: SliverChildBuilderDelegate(
                      (BuildContext context, int index) {
                    return Container(
                      height: 20,
                      padding: EdgeInsets.only(left: 8, right: 8),
                      child: Text('SliverGrid'),
                    );
                  },
                  childCount: 220,
                ),
                gridDelegate: SliverGridDelegateWithMaxCrossAxisExtent(
                  maxCrossAxisExtent: 200,
                  childAspectRatio: 5,
                )),
          ],
        ),
      ),
    );
  }

**Comment by lan2000** [comment]
应该和physics有关

**Comment by lan2000** [comment]
能否添加EasyRefreshPhysics的配置，某些情况防止滚动超出边界，不用回弹的效果。

**Comment by xuelongqy** [comment]
v3已发布，也许问题得到解决。如果问题依然存在，请重新打开
