### ISSUE TITLE
背景色与下拉设置背景色不一致时会出现背景色的细条

### ISSUE THREAD

**Issue by Yuanqiumei** [xuelongqy/flutter_easyrefresh#421]

**Comment by xuelongqy** [comment]
这是Flutter普遍存在的问题，要解决只能使用类溢出布局方式填平缝隙

**Comment by Yuanqiumei** [comment]
> 这是Flutter普遍存在的问题，要解决只能使用类溢出布局方式填平缝隙

是使用EasyRefresh时背景色设置造成的，代码如下，大佬有什么好方法可以解决吗
Scaffold(
      appBar: AppBar(
        title: Text(widget.title),
        backgroundColor: Colors.transparent,
        actions: <Widget>[
          IconButton(
            icon: Icon(Icons.menu),
            onPressed: () => showModalBottomSheet(
              context: context,
              builder: (context) {
                return _buildModalMenu();
              },
            ),
          )
        ],
      ),
      backgroundColor: Colors.transparent,
      body: Stack(
        children: <Widget>[
          // 页面数据 - 下拉刷新
          Column(
            children: <Widget>[
              Container(
                height: 56.0 + MediaQuery.of(context).padding.top,
              ),

              Expanded(
                child: Container(
//                    color: Color(0xFF2372FF),
                  child: EasyRefresh(
                    enableControlFinishRefresh: false,
                    enableControlFinishLoad: true,
                    taskIndependence: false,
                    header: ClassicalHeader(
                      refreshText: '',
                      refreshedText: '刷新完成',
                      refreshingText: '正在刷新数据中...',
                      refreshReadyText: '正在刷新数据中...',
                      infoText: '最后更新，今天 %T',
                      textColor: Colors.red,
                      infoColor: Colors.red,
                      bgColor: Color(0xFF2372FF),
                    ),
                    footer: ClassicalFooter(
                      loadText: '',
                      loadReadyText: '',
                      loadingText: '',
                      loadedText: '',
                      loadFailedText: '',
                      noMoreText: '',
                      infoText: '',
                    ),
                    child: SingleChildScrollView(
                      child: Column(
                        children: [
                          // 个人信息
                          this._userInfo,
                        ],
                      ),
                    ),
                    onRefresh: () async {
                      //开始加载更多
                    },
                  ),
                ),
              )
            ],
          ),

          // 自定义头部
          this._generateAppBar,

        ],
      )
)


// 生成顶部导航
  Widget get _generateAppBar {
    return Container(
      width: MediaQuery.of(context).size.width,
      height: 56.0 + MediaQuery.of(context).padding.top,
      padding: EdgeInsets.only(left: 15.0, right: 15.0, top: MediaQuery.of(context).padding.top),
      alignment: Alignment.center,
      decoration: BoxDecoration(
//        gradient: LinearGradient(
//          begin: Alignment.topCenter, end: Alignment.bottomCenter,
//        ),
        color: Color(0xFF2372FF)
      ),
      child: Row(
        mainAxisAlignment: MainAxisAlignment.spaceBetween,
        crossAxisAlignment: CrossAxisAlignment.center,
        children: <Widget>[
          // 搜索输入框 -> 搜索页面
          Expanded(
            child: GestureDetector(
              onTap: () => Navigator.of(context).pushNamed('/search'),
              child: Container(
                height: 32.0,
                width: MediaQuery.of(context).size.width * 0.80,
                alignment: Alignment.center,
                padding: EdgeInsets.only(left: 10.0, right: 10.0),
                decoration: BoxDecoration(
                    color: Colors.white,
                    borderRadius: BorderRadius.circular(30.0)
                ),
                child: Row(
                  crossAxisAlignment: CrossAxisAlignment.center,
                  children: <Widget>[
                    Icon(Icons.search, color: Colors.red,size: 20.0,),
                    SizedBox(width: 3.0),
                    Text('搜索', style: TextStyle(fontSize: 14.0, color: Colors.red))
                  ],
                ),
              ),
            ),
          ),

          // 个人消息
          GestureDetector(
            onTap: (){
              Navigator.of(context).pushNamed('/friendList',arguments: {
                'type': 1, // 首页进入
              });
            },
            behavior: HitTestBehavior.opaque,
            child: Container(
              width: 40.0,
              alignment: Alignment.centerRight,
              child: Image.network('https://fbk-static.oss-cn-shanghai.aliyuncs.com/suifutong/app/images/home/home_right_logo.png',width: 20.0,height: 20.0,),
            ),
          )
        ],
      ),
    );
  }

  Widget get _userInfo {
    return Container(
      child: Stack(
        children: [
          // 背景图
          Container(
            width: MediaQuery.of(context).size.width,
            height: 140,
            decoration: BoxDecoration(
              image: DecorationImage(
                image: NetworkImage("https://fbk-static.oss-cn-shanghai.aliyuncs.com/suifutong/app/images/image/top_bg.png"), fit: BoxFit.cover,
              ),
            ),
          ),

          // 用户信息
          Positioned(
            top: 10.0,
            left: 15.0,
            child: Row(
              children: <Widget>[
                Container(
                  margin: EdgeInsets.only(right: 15.0),
                  child: Image.network("https://fbk-static.oss-cn-shanghai.aliyuncs.com/suifutong/app/images/my/mine_logo.png", width: 60.0, height: 56.0),
                ),
                Column(
                  crossAxisAlignment: CrossAxisAlignment.start,
                  children: <Widget>[
                    Container(
                      child: Text('早上好', style: TextStyle(color: Colors.white)),
                    ),
                  ],
                ),
              ],
            ),
          ),

          // 查询账户
          Positioned(
            bottom: 28.0,
            left: 15.0,
            child: GestureDetector(
              onTap: () => Navigator.of(context).pushNamed('/userRecord'),
              child: Container(
                alignment: Alignment.center,
                padding: EdgeInsets.only(left: 8.0, right: 8.0, top: 3.0,bottom: 3.0),
                decoration: BoxDecoration(
                    color: Colors.white,
                    borderRadius: BorderRadius.circular(30.0)
                ),
                child: Row(
                  crossAxisAlignment: CrossAxisAlignment.center,
                  children: <Widget>[
                    SizedBox(width: 2.0),
                    Text('查询账户', style: TextStyle(fontSize: 12.0, color: Theme.of(context).primaryColor))
                  ],
                ),
              ),
            ),
          ),

          Positioned(
            bottom: 0,
            width: MediaQuery.of(context).size.width,
            child: Container(
              height: 6.0,
              decoration: BoxDecoration(
                  color: Colors.red,
                  borderRadius: BorderRadius.only(
                    topLeft: Radius.circular(48.0),
                    topRight: Radius.circular(48.0),
                  )
              ),
            ),
          )
        ],
      ),
    );
  }

**Comment by xuelongqy** [comment]
之前有类似的issue可以找找。Flutter中两个组件不相连就可能会出现这种

**Comment by Yuanqiumei** [comment]
> 前有类似的issue可以找找

没有类似的问题

**Comment by Yuanqiumei** [comment]
非常规解决问题，将页面背景色修改成下拉加载的背景色，每个模块特殊处理，如果有大佬有更好的方法欢迎讨论

**Comment by xuelongqy** [comment]
https://github.com/xuelongqy/flutter_easy_refresh/issues/547

**Comment by xuelongqy** [comment]
v3已发布，请及时更新
