### ISSUE TITLE
下拉刷新第一、二次可以正常刷新，后面无法正常刷新，移植卡在释放刷新，版本2.1.7，设置如下

### ISSUE THREAD

**Issue by androidneter** [xuelongqy/flutter_easyrefresh#423]
_controller.finishRefresh(noMore: true);
_controller.finishLoad(noMore: true);
_controller.resetRefreshState();

**Comment by xuelongqy** [comment]
升级到2.1.8测试呢？

**Comment by Zhaimm** [comment]
请问这个问题解决了吗？ 我升级到2.1.8同样有问题

**Comment by wangdenkun** [comment]
![image](https://user-images.githubusercontent.com/13745166/106692796-1f906a00-6610-11eb-9689-255af02e317f.png)
2.1.8版本 不调用resetRefreshState就可以了

**Comment by xuelongqy** [comment]
v3已发布，也许问题得到解决。如果问题依然存在，请重新打开
