### ISSUE TITLE
使用2.1.7版本依然出现A ValueNotifier<TaskState> was used after being disposed.

### ISSUE THREAD

**Issue by q296494327** [xuelongqy/flutter_easyrefresh#427]
E/flutter ( 6952): [ERROR:flutter/lib/ui/ui_dart_state.cc(177)] Unhandled Exception: A ValueNotifier<TaskState> was used after being disposed.
E/flutter ( 6952): Once you have called dispose() on a ValueNotifier<TaskState>, it can no longer be used.
E/flutter ( 6952): #0      ChangeNotifier._debugAssertNotDisposed.<anonymous closure> (package:flutter/src/foundation/change_notifier.dart:117:9)
E/flutter ( 6952): #1      ChangeNotifier._debugAssertNotDisposed (package:flutter/src/foundation/change_notifier.dart:123:6)
E/flutter ( 6952): #2      ChangeNotifier.notifyListeners (package:flutter/src/foundation/change_notifier.dart:217:12)
E/flutter ( 6952): #3      ValueNotifier.value= (package:flutter/src/foundation/change_notifier.dart:292:5)
E/flutter ( 6952): #4      _EasyRefreshSliverLoadControlState.finishLoad (package:flutter_easyrefresh/src/footer/load_indicator.dart:636:25)
E/flutter ( 6952): #5      EasyRefreshController.finishLoad (package:flutter_easyrefresh/src/refresher.dart:652:25)
E/flutter ( 6952): #6      _SubCategoryGoodsState._requestGetCategoryGoods.<anonymous closure> (package:flutter_app/app/pages/category/category_tab_page/widget/sub_category_goods.dart:167:26)
E/flutter ( 6952): #7      _rootRunUnary (dart:async/zone.dart:1198:47)
E/flutter ( 6952): #8      _CustomZone.runUnary (dart:async/zone.dart:1100:19)
E/flutter ( 6952): #9      _FutureListener.handleError (dart:async/future_impl.dart:160:20)
E/flutter ( 6952): #10     Future._propagateToListeners.handleError (dart:async/future_impl.dart:708:47)
E/flutter ( 6952): #11     Future._propagateToListeners (dart:async/future_impl.dart:729:24)
E/flutter ( 6952): #12     Future._completeWithValue (dart:async/future_impl.dart:529:5)
E/flutter ( 6952): #13     _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:40:15)
E/flutter ( 6952): #14     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:311:13)
E/flutter ( 6952): #15     CategoryTabModel.getCategoryGoodsData (package:flutter_app/app/pages/category/category_tab_page/category_tab_model.dart)
E/flutter ( 6952): <asynchronous suspension>
E/flutter ( 6952): #16     _SubCategoryGoodsState._requestGetCategoryGoods (package:flutter_app/app/pages/category/category_tab_page/widget/sub_category_goods.dart:146:24)
E/flutter ( 6952): #17     _SubCategoryGoodsState.onEventBus (package:flutter_app/app/pages/category/category_tab_page/widget/sub_category_goods.dart:49:9)
E/flutter ( 6952): #18     BaseState.initState.<anonymous closure> (package:flutter_app/app/pages/base/base_state.dart:50:9)
E/flutter ( 6952): #19     _rootRunUnary (dart:async/zone.dart:1198:47)
E/flutter ( 6952): #20     _CustomZone.runUnary (dart:async/zone.dart:1100:19)
E/flutter ( 6952): #21     _CustomZone.runUnaryGuarded (dart:async/zone.dart:1005:7)
E/flutter ( 6952): #22     CastStreamSubscription._onData (dart:_internal/async_cast.dart:85:11)
E/flutter ( 6952): #23     _rootRunUnary (dart:async/zone.dart:1198:47)
E/flutter ( 6952): #24     _CustomZone.runUnary (dart:async/zone.dart:1100:19)
E/flutter ( 6952): #25     _CustomZone.runUnaryGuarded (dart:async/zone.dart:1005:7)
E/flutter ( 6952): #26     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:357:11)
E/flutter ( 6952): #27     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:285:7)
E/flutter ( 6952): #28     _ForwardingStreamSubscription._add (dart:async/stream_pipe.dart:127:11)
E/flutter ( 6952): #29     _WhereStream._handleData (dart:async/stream_pipe.dart:199:12)
E/flutter ( 6952): #30     _ForwardingStreamSubscription._handleData (dart:async/stream_pipe.dart:157:13)
E/flutter ( 6952): #31     _rootRunUnary (dart:async/zone.dart:1198:47)
E/flutter ( 6952): #32     _CustomZone.runUnary (dart:async/zone.dart:1100:19)
E/flutter ( 6952): #33     _CustomZone.runUnaryGuarded (dart:async/zone.dart:1005:7)
E/flutter ( 6952): #34     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:357:11)
E/flutter ( 6952): #35     _DelayedData.perform (dart:async/stream_impl.dart:611:14)
E/flutter ( 6952): #36     _StreamImplEvents.handleNext (dart:async/stream_impl.dart:730:11)
E/flutter ( 6952): #37     _PendingEvents.schedule.<anonymous closure> (dart:async/stream_impl.dart:687:7)
E/flutter ( 6952): #38     _rootRun (dart:async/zone.dart:1182:47)
E/flutter ( 6952): #39     _CustomZone.run (dart:async/zone.dart:1093:19)
E/flutter ( 6952): #40     _CustomZone.runGuarded (dart:async/zone.dart:997:7)
E/flutter ( 6952): #41     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1037:23)
E/flutter ( 6952): #42     _rootRun (dart:async/zone.dart:1190:13)
E/flutter ( 6952): #43     _CustomZone.run (dart:async/zone.dart:1093:19)
E/flutter ( 6952): #44     _CustomZone.runGuarded (dart:async/zone.dart:997:7)
E/flutter ( 6952): #45     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1037:23)
E/flutter ( 6952): #46     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
E/flutter ( 6952): #47     _s

**这是在多tab共用一个刷新列表时出现的问题,在2.1.1版本没有任何问题,之后的每个版本直到2.1.8都这样**

断点走到下方注释的位置报错: 

 ///请求获取分类下的商品
  void _requestGetCategoryGoods(String categoryId, String categorySubId) {
    CategoryTabModel().getCategoryGoodsData(categoryId, categorySubId, currentIndex).then((val) {
      pageStateController.showSuccess();
      if (val == null) {
        val = List<CategoryGoodsData>();
      }
      if (currentIndex == 1 && val.isEmpty) {
        pageStateController.showEmpty();
      }

      setState(() {
        if (currentIndex == 1) {
          refreshController?.resetLoadState();
          mDatas.clear();
        }
        mDatas.addAll(val);
        currentIndex++;
      });
      //在此处报错
      refreshController?.finishRefresh(success: true);
      refreshController?.finishLoad(success: true, noMore: val.isEmpty);
    }).catchError((error) {
      pageStateController.showError(error.message);
      refreshController?.finishLoad(success: false);
      Utils.showToast(error.message);
    });
  }

**Comment by SilentSword2020** [comment]
显示布局可能的原因：出现没有列表数据或网络错误，从widget tree中删除easyRefresh,显示一个错误或无数据的布局，
解决方法：通过easyrefresh的emptyWidget的来显示一个错误或无数据的布局，

出现上面的错误就是因为：easyrefresh被从从widget tree中删除了，refreshController没有用了

**Comment by q296494327** [comment]
这个错误存在于flutter练手项目,目前新项目尽量避免了多个tab操作同一个easyrefresh

**Comment by S-WangZi** [comment]
问题的原因 @SilentSword2020  说的很清楚
原easyrefresh被移除后，refreshController的绑定状态并未清除，再次使用refreshController就会报错。
作者提供了refreshController清空状态的函数：refreshController.dispose();

**Comment by chaochaox1990** [comment]
> 问题的原因 @SilentSword2020 说的很清楚
> 原easyrefresh被移除后，refreshController的绑定状态并未清除，再次使用refreshController就会报错。
> 作者提供了refreshController清空状态的函数：refreshController.dispose();

you save my day.Thanks . Your answer very clear

**Comment by xuelongqy** [comment]
v3已发布，也许问题得到解决。如果问题依然存在，请重新打开
