### ISSUE TITLE
EasyRefresh包裹NestedScrollView，NestedScrollView都不显示了，变成空白

### ISSUE THREAD

**Issue by kaijiemu** [xuelongqy/flutter_easyrefresh#429]
![image](https://user-images.githubusercontent.com/13444779/106459892-81948680-64cd-11eb-81a1-1dfe43dc4bb5.png)

return Container(
        child: Scaffold(
            backgroundColor: ThemeUtil.getWhiteColor(),
            body: EasyRefresh(
              controller: _refreshController,
              header: RefreshUtil.getRefreshHeader(),
              footer: RefreshUtil.getRefreshFooter(),
              onRefresh: () async {
                return await _taViewMode.refreshData();
              },
              onLoad: true
                  ? () async {
                      _taViewModel.loadMore();
                    }
                  : null,
              child: NestedScrollView(
                  headerSliverBuilder: (context, innerScrolled) => <Widget>[

**Comment by kaijiemu** [comment]
`return Container(
child: Scaffold(
backgroundColor: ThemeUtil.getWhiteColor(),
body: EasyRefresh(
controller: _refreshController,
header: RefreshUtil.getRefreshHeader(),
footer: RefreshUtil.getRefreshFooter(),
onRefresh: () async {
return await _taViewMode.refreshData();
},
onLoad: true
? () async {
_taViewModel.loadMore();
}
: null,
child: NestedScrollView(
headerSliverBuilder: (context, innerScrolled) => [`

**Comment by kaijiemu** [comment]
大佬，有交流学习群可以加吗

**Comment by xuelongqy** [comment]
翻看之前的issue，就知道不支持包裹NestedScrollView了。原理复杂，目前无计划支持

**Comment by xuelongqy** [comment]
v3已发布，也许问题得到解决。如果问题依然存在，请重新打开
