### ISSUE TITLE
如何在refresh后的，设置底部的noMore为true

### ISSUE THREAD

**Issue by peak77** [xuelongqy/flutter_easyrefresh#433]
想要的效果：refresh后list个数小于20，底部的noMore就显示出来。我的做法：refresh后，设置finishLoad 的noMore:true，但是noMore的文字在底部需要向上滑才能看到。

**Comment by youmu178** [comment]
自己滚一下？

**Comment by xuelongqy** [comment]
多次有人提及。为何这样实现，因为很多样式，是有背景和动画的。不满时直接放到列表后会特别奇怪

**Comment by lan2000** [comment]
> 想要的效果：refresh后list个数小于20，底部的noMore就显示出来。我的做法：refresh后，设置finishLoad 的noMore:true，但是noMore的文字在底部需要向上滑才能看到。

我也遇到这个问题，请问您这边当前是如何解决的呢

**Comment by peak77** [comment]
> > 想要的效果：refresh后list个数小于20，底部的noMore就显示出来。我的做法：refresh后，设置finishLoad 的noMore:true，但是noMore的文字在底部需要向上滑才能看到。
> 
> 我也遇到这个问题，请问您这边当前是如何解决的呢

**Comment by peak77** [comment]
> > > 想要的效果：refresh后list个数小于20，底部的noMore就显示出来。我的做法：refresh后，设置finishLoad 的noMore:true，但是noMore的文字在底部需要向上滑才能看到。
> > 
> > 
> > 我也遇到这个问题，请问您这边当前是如何解决的呢

没解决，但是又请求了一下，第一次请求完又请求了一次。

**Comment by xuelongqy** [comment]
v3已发布，也许问题得到解决。如果问题依然存在，请重新打开
