### ISSUE TITLE
嵌套在Column里会报错，无法运行

### ISSUE THREAD

**Issue by andfaraway** [xuelongqy/flutter_easyrefresh#434]
return Scaffold(
      body: Column(
        children: [
          Text('easyTest'),
          EasyRefresh(
            onRefresh: (){
               return Future.delayed(Duration(seconds: 1));
            },
            child: ListView.separated(
                shrinkWrap: true,
                itemBuilder: (context, i) {
                  return ListTile(
                    title: Text('test $i'),
                  );
                },
                separatorBuilder: (context, i) {
                  return Divider();
                },
                itemCount: 5),
          )
        ],
      ),
    );

报错如下：
The following assertion was thrown during performResize():
Vertical viewport was given unbounded height.

Viewports expand in the scrolling direction to fill their container. In this case, a vertical viewport was given an unlimited amount of vertical space in which to expand. This situation typically happens when a scrollable widget is nested inside another scrollable widget.

If this widget is always nested in a scrollable widget there is no need to use a viewport because there will always be enough vertical space for the children. In this case, consider using a Column instead. Otherwise, consider using the "shrinkWrap" property (or a ShrinkWrappingViewport) to size the height of the viewport to the sum of the heights of its children.

若是使用系统的RefreshIndicator则没有问题

**Comment by C1oudust** [comment]
Column里面嵌套的EasyRefresh需要用Expanded包裹

**Comment by andfaraway** [comment]
> Column里面嵌套的EasyRefresh需要用Expanded包裹

解决了，感谢
