### ISSUE TITLE
Null safety support

### ISSUE THREAD

**Issue by laiiihz** [xuelongqy/flutter_easyrefresh#435]
请问有支持空安全的计划吗

**Comment by vance-liu** [comment]
@xuelongqy 如果作者没空，需要提供帮助的话，可以@我

**Comment by roselifeye** [comment]
@vance-liu 可以添加null-safety然后pub吗？谢谢

**Comment by vance-liu** [comment]
这几天内晚上有时间改完，并且把实例升级，再提个pr。或许有人更快提了也说不定。

**Comment by roselifeye** [comment]
好的，谢谢😃

**Comment by momtboy** [comment]
@vance-liu 空安全有进展了嘛？着急用

**Comment by vance-liu** [comment]
@momtboy 你可以先试试这个分支[null_safety](https://github.com/vance-liu/flutter_easyrefresh/tree/null_safety)，具体我还没详细测试过，抱歉。

**Comment by momtboy** [comment]
@vance-liu 空安全的版本不打算发布到pub嘛？？

**Comment by xuelongqy** [comment]
不好意思，最近事情比较多。会在近期支持

**Comment by cipchk** [comment]
+1，急用。

**Comment by xuelongqy** [comment]
v2.2.0已支持
