### ISSUE TITLE
Flutter statble 2.0.0   运行项目到 Chrome报错

### ISSUE THREAD

**Issue by gionchat** [xuelongqy/flutter_easyrefresh#436]
![image](https://user-images.githubusercontent.com/58280808/109903001-2d501280-7cd6-11eb-964d-2f6cc90ea2ea.png)

**Comment by laiiihz** [comment]
应该是`extended_nested_scroll_view`的问题，参考[extended_nested_scroll_view#61](https://github.com/fluttercandies/extended_nested_scroll_view/issues/61)

**Comment by gionchat** [comment]
多谢
