### ISSUE TITLE
easyrefresh头部添加一个SliverPersistentHeader，数据为空，下面emptyWidget遮挡头部PersistentHeader

### ISSUE THREAD

**Issue by lan2000** [xuelongqy/flutter_easyrefresh#439]
列表头部放一个轮播，或者筛选、排序栏。
数据为空的时候，如果不显示emptyWidget,则页面显示空白，也看不到列表底部的“没有更多”提示，需要向上滑动，才能看到“没有更多”提示。
如果数据为空的时候显示emptyWidget，则列表头部的轮播会被遮挡。

怎么实现无需滚动也能看到“没有更多”的提示呢？

**Comment by xuelongqy** [comment]
多次有人提及，后续会考虑

**Comment by lan2000** [comment]
------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年3月18日(星期四) 下午5:41
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [xuelongqy/flutter_easyrefresh] easyrefresh头部添加一个SliverPersistentHeader，数据为空，下面emptyWidget遮挡头部PersistentHeader (#439)





 
多次有人提及，后续会考虑

**Comment by xuelongqy** [comment]
v3已发布，也许问题得到解决。如果问题依然存在，请重新打开
