### ISSUE TITLE
刘海屏要适配下啊...

### ISSUE THREAD

**Issue by zhangruiyu** [xuelongqy/flutter_easyrefresh#44]
库很好用...已经集成啦 ....希望我们上线前能用上新版本0-0期待大佬

**Comment by xuelongqy** [comment]
刘海屏 需要自己适配啊，老哥。可以处理的。ios那个示例就是处理了刘海屏的，你可以看看

**Comment by tjswk2008** [comment]
> 刘海屏 需要自己适配啊，老哥。可以处理的。ios那个示例就是处理了刘海屏的，你可以看看

不好意思，请问一下例子在哪呢？

**Comment by JDNew** [comment]
请问这个刘海屏是怎么适配的？
