### ISSUE TITLE
一点点小建议

### ISSUE THREAD

**Issue by FirePrayer** [xuelongqy/flutter_easyrefresh#440]
这个组件很不错,但是有些细节能调整下就更完美了.

1.统一上拉下拉刷新状态,状态其实还可以去掉一个.
2.不用在_EasyRefreshSliverLoad里面判断CustomScrollView剩余的空间,直接在slivers后面添加一个SliverFillRemaining.
3.可以把刷新和加载写弄在header和footer里面
4.可以在_RenderEasyRefreshSliverLoad加个加载完成的回弹动画.

**Comment by xuelongqy** [comment]
非常感谢。v3已发布，请及时更新
