### ISSUE TITLE
用tab+tabView或者tab+PageView这中组合，每个页面都用到了EasyRefresh，在某个页面下拉刷新的时候，每个页面的下拉刷新都响应了

### ISSUE THREAD

**Issue by xieyang94** [xuelongqy/flutter_easyrefresh#441]
用tab+tabView或者tab+PageView这中组合，每个页面都用到了EasyRefresh，在某个页面下拉刷新的时候，每个页面的下拉刷新都响应了，是用法错误还是本身就存在这种问题，请指教

**Comment by xuelongqy** [comment]
这个问题被提及无数次，请参考之前的issue
