### ISSUE TITLE
# Null check operator used on a null value

### ISSUE THREAD

**Issue by xieyuhai** [xuelongqy/flutter_easyrefresh#442]
![image](https://user-images.githubusercontent.com/15424550/110732166-95ff3800-825e-11eb-8d90-a8cae8063727.png)

#0 ChangeNotifier.notifyListeners (package:flutter/src/foundation/change_notifier.dart:218)
--
0 # Null check operator used on a null value
1 #1 ValueNotifier.value= (package:flutter/src/foundation/change_notifier.dart:292)
2 #2 _RenderEasyRefreshSliverLoad.performLayout (package:flutter_easyrefresh/src/footer/load_indicator.dart:183)

**Comment by xieyuhai** [comment]
当前使用版本v2.1.8

**Comment by xuelongqy** [comment]
请使用v2.2.1
