### ISSUE TITLE
EasyRefresh offset异常

### ISSUE THREAD

**Issue by SionChen** [xuelongqy/flutter_easyrefresh#445]
下拉的时候 当`hasSliverLayoutExtent`为true的时候`offset`为0异常。
就像这样当下拉高度达到`triggerDistance`高度的时候`offset`会再次从0开始递减。
这样会影响我们的一些监听滑动`offset`的业务
应该是防止回弹操作引起的异常
下面是示例demo对于`offset`监听的异常展示图
![example](https://user-images.githubusercontent.com/14322899/110920390-48ff8c80-8358-11eb-8aa1-a6b72cf02312.gif)

**Comment by xuelongqy** [comment]
请参考之前的issue，可使用监听器LinkHeader去监听Header的高度
