### ISSUE TITLE
自动加载好像无效啊

### ISSUE THREAD

**Issue by yuzhiqiang1993** [xuelongqy/flutter_easyrefresh#45]
autoLoad设置为true也没有自动加载，还是需要手动上拉才会加载

**Comment by yuzhiqiang1993** [comment]
哦，我理解的自动加载可能个该库不太一样，我理解的自动加载是快到底部的时候就去加载数据，无需手动上来加载.....

**Comment by xuelongqy** [comment]
可以这样做，使用ScrollController监听快滑到底部的时候，触发加载

**Comment by xuelongqy** [comment]
v2版本已重构
