### ISSUE TITLE
SliverGeometry is not valid: The "layoutExtent" exceeds the "paintExtent".

### ISSUE THREAD

**Issue by HyBLF** [xuelongqy/flutter_easyrefresh#451]
上拉加载多页快速下拉就会有瞬间显示空白然后正常显示，控制台打印下面的错；demo必现
The following assertion was thrown during performLayout():
SliverGeometry is not valid: The "layoutExtent" exceeds the "paintExtent".

The paintExtent is 0.0, but the layoutExtent is 60.0.
The RenderSliver that returned the offending geometry was: _RenderEasyRefreshSliverRefresh#aa027 relayoutBoundary=up1 NEEDS-PAINT
...  parentData: paintOffset=Offset(0.0, 669.7) (can use size)
...  constraints: SliverConstraints(AxisDirection.down, GrowthDirection.forward, ScrollDirection.forward, scrollOffset: 0.0, remainingPaintExtent: 0.0, overlap: -611.2, crossAxisExtent: 360.0, crossAxisDirection: AxisDirection.right, viewportMainAxisExtent: 564.0, remainingCacheExtent: 202.8, cacheOrigin: 0.0)
...  geometry: SliverGeometry(scrollExtent: 60.0, hidden, paintOrigin: -611.2, layoutExtent: 60.0, maxPaintExtent: 671.2, cacheExtent: 60.0)
...    scrollExtent: 60.0
...    hidden
...    paintOrigin: -611.2
...    layoutExtent: 60.0
...    maxPaintExtent: 671.2
...    cacheExtent: 60.0
The relevant error-causing widget was: 
  _EasyRefreshSliverRefresh file:///Users/xx/Documents/project/Flutter/flutter_easyrefresh/lib/src/header/refresh_indicator.dart:872:12
When the exception was thrown, this was the stack: 
#0      SliverGeometry.debugAssertIsValid.<anonymous closure>.verify (package:flutter/src/rendering/sliver.dart:713:9)
#1      SliverGeometry.debugAssertIsValid.<anonymous closure> (package:flutter/src/rendering/sliver.dart:730:15)
#2      SliverGeometry.debugAssertIsValid (package:flutter/src/rendering/sliver.dart:752:6)
#3      RenderSliver.debugAssertDoesMeetConstraints (package:flutter/src/rendering/sliver.dart:1207:22)
#4      RenderObject.layout.<anonymous closure> (package:flutter/src/rendering/object.dart:1780:9)
...
The following RenderObject was being processed when the exception was fired: _RenderEasyRefreshSliverRefresh#aa027 relayoutBoundary=up1 NEEDS-PAINT
...  parentData: paintOffset=Offset(0.0, 669.7) (can use size)
...  constraints: SliverConstraints(AxisDirection.down, GrowthDirection.forward, ScrollDirection.forward, scrollOffset: 0.0, remainingPaintExtent: 0.0, overlap: -611.2, crossAxisExtent: 360.0, crossAxisDirection: AxisDirection.right, viewportMainAxisExtent: 564.0, remainingCacheExtent: 202.8, cacheOrigin: 0.0)
...  geometry: SliverGeometry(scrollExtent: 60.0, hidden, paintOrigin: -611.2, layoutExtent: 60.0, maxPaintExtent: 671.2, cacheExtent: 60.0)
...    scrollExtent: 60.0
...    hidden
...    paintOrigin: -611.2
...    layoutExtent: 60.0
...    maxPaintExtent: 671.2
...    cacheExtent: 60.0
RenderObject: _RenderEasyRefreshSliverRefresh#aa027 relayoutBoundary=up1 NEEDS-PAINT
  parentData: paintOffset=Offset(0.0, 669.7) (can use size)
  constraints: SliverConstraints(AxisDirection.down, GrowthDirection.forward, ScrollDirection.forward, scrollOffset: 0.0, remainingPaintExtent: 0.0, overlap: -611.2, crossAxisExtent: 360.0, crossAxisDirection: AxisDirection.right, viewportMainAxisExtent: 564.0, remainingCacheExtent: 202.8, cacheOrigin: 0.0)
  geometry: SliverGeometry(scrollExtent: 60.0, hidden, paintOrigin: -611.2, layoutExtent: 60.0, maxPaintExtent: 671.2, cacheExtent: 60.0)
    scrollExtent: 60.0
    hidden
    paintOrigin: -611.2
    layoutExtent: 60.0
    maxPaintExtent: 671.2
    cacheExtent: 60.0
...  child: _RenderLayoutBuilder#d5d28 relayoutBoundary=up2 NEEDS-PAINT
...    parentData: paintOffset=Offset(0.0, 0.0) (can use size)
...    constraints: BoxConstraints(w=360.0, 0.0<=h<=671.2)
...    size: Size(360.0, 671.2)
...    child: RenderStack#c9977 relayoutBoundary=up3 NEEDS-PAINT
...      parentData: offset=Offset(0.0, 0.0) (can use size)
...      constraints: BoxConstraints(w=360.0, 0.0<=h<=671.2)
...      size: Size(360.0, 671.2)
...      alignment: AlignmentDirectional.topStart
...      textDirection: ltr
...      fit: loose
...      child 1: RenderConstrainedBox#3c65e relayoutBoundary=up4 NEEDS-PAINT
...        parentData: right=0.0; bottom=0.0; left=0.0; offset=Offset(0.0, 0.0) (can use size)
...        constraints: BoxConstraints(w=360.0, 0.0<=h<=Infinity)
...        size: Size(360.0, 671.2)
...        additionalConstraints: BoxConstraints(w=Infinity, h=671.2)
...        child: _RenderColoredBox#fb2a4 NEEDS-PAINT
...          parentData: <none> (can use size)
...          constraints: BoxConstraints(w=360.0, h=671.2)
...          size: Size(360.0, 671.2)
...          behavior: opaque

**Comment by radoslaw-sz** [comment]
Google brought me here - I am not a user of this plugin, but for your information I have the same problem with my custom code - when sliverPersisentHeader uses animation controller, it happens sometimes that sliverPersistentHeader is painted with different value than it was defined (layoutextent as defined value, while paintExtent what animation controller says).
Maybe it is even flutter bug.

**Comment by radoslaw-sz** [comment]
It has been raised in official flutter issues: https://github.com/flutter/flutter/issues/78748

**Comment by you-zuo** [comment]
我也遇到这个问题了，有什么办法可以解决吗

**Comment by xuelongqy** [comment]
v3已发布，也许问题得到解决。如果问题依然存在，请重新打开
