### ISSUE TITLE
刷新没完成前上拉加载出现加载不动的问题需要上滑一下才可以继续加载

### ISSUE THREAD

**Issue by PillarChen** [xuelongqy/flutter_easyrefresh#455]
下拉刷新后没结束刷新前,列表若是快速滑动到底部了等刷新完了数据后再上拉加载会出现拉不动的问题(footer显示的空白,列表数据需要满足超过一屏,若是再次下滑到footer处于可见范围之外再次上拉加载就好了)

**Comment by xuelongqy** [comment]
这是因为footer有刷新完成的延时。部分footer样式，在完成后显示空白。请验证

**Comment by OctMon** [comment]
我也遇到同样的问题

**Comment by xuelongqy** [comment]
v3已发布，也许问题得到解决。如果问题依然存在，请重新打开
