### ISSUE TITLE
嵌套在NestedScrollView中会出现滑动冲突问题

### ISSUE THREAD

**Issue by LiangMengGu** [xuelongqy/flutter_easyrefresh#456]
使用了 NestedScrollView 
body 中使用的 tabview 
给每个tabview 的 EasyRefresh 设置了额外的 scrollController 
会出现 和 sliver 滑动冲突 分离的问题

**Comment by good-good-study** [comment]
作者貌似已经解决了这个问题了。用的是 extended_nested_scroll_view嵌套的 EasyRefresh。我测试过了，问题不大
[https://pub.dev/packages/extended_nested_scroll_view/versions/3.0.0-non-null-safety/example](url)

**Comment by ztqup666** [comment]
> 作者貌似已经解决了这个问题了。用的是 extended_nested_scroll_view嵌套的 EasyRefresh。我测试过了，问题不大
> [https://pub.dev/packages/extended_nested_scroll_view/versions/3.0.0-non-null-safety/example](url)

代码中的例子有bug，在头部未折叠的时候上滑，偶现抖动，且概率不小，请问有解决办法吗

**Comment by xuelongqy** [comment]
v3已发布，也许问题得到解决。如果问题依然存在，请重新打开
