### ISSUE TITLE
V2.2.0  Null check operator used on a null value

### ISSUE THREAD

**Issue by HongxiangShe** [xuelongqy/flutter_easyrefresh#457]
2.2.0版本
```
 if (_enableFirstRefresh) {
      _firstRefreshHeader = FirstRefreshHeader(widget.firstRefreshWidget!);
      SchedulerBinding.instance!.addPostFrameCallback((Duration timestamp) {
        callRefresh();
      });
    }
```
当开启firstRefresh后,  widget.firstRefreshWidget! 这里会因为把null强制非空而报错, 建议不用‘!’, 除非你非常非常确定他非null值

**Comment by wh8817221** [comment]
我也有同样的问题，作者改一下吧

**Comment by sobriver** [comment]
我也是

**Comment by xuelongqy** [comment]
v2.2.1已修复

**Comment by aldaspan** [comment]
I have updated flutter_easyrefresh to v2.2.1 and the problem still exists.
`../../FlutterDev/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_easyrefresh-2.2.1/lib/src/header/refresh_indicator.dart:200:30: Warning: Operand of null-aware operation '!' has type 'SchedulerBinding' which excludes null.
 - 'SchedulerBinding' is from 'package:flutter/src/scheduler/binding.dart' ('../../FlutterDev/flutter/packages/flutter/lib/src/scheduler/binding.dart').
        if (SchedulerBinding.instance!.schedulerPhase == SchedulerPhase.idle) {
                             ^
../../FlutterDev/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_easyrefresh-2.2.1/lib/src/header/refresh_indicator.dart:203:28: Warning: Operand of null-aware operation '!' has type 'SchedulerBinding' which excludes null.
 - 'SchedulerBinding' is from 'package:flutter/src/scheduler/binding.dart' ('../../FlutterDev/flutter/packages/flutter/lib/src/scheduler/binding.dart').
          SchedulerBinding.instance!.addPostFrameCallback((Duration timestamp) {
                           ^
../../FlutterDev/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_easyrefresh-2.2.1/lib/src/header/refresh_indicator.dart:675:24: Warning: Operand of null-aware operation '!' has type 'SchedulerBinding' which excludes null.
 - 'SchedulerBinding' is from 'package:flutter/src/scheduler/binding.dart' ('../../FlutterDev/flutter/packages/flutter/lib/src/scheduler/binding.dart').
      SchedulerBinding.instance!.addPostFrameCallback((Duration timestamp) {
                       ^
../../FlutterDev/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_easyrefresh-2.2.1/lib/src/header/refresh_indicator.dart:718:28: Warning: Operand of null-aware operation '!' has type 'SchedulerBinding' which excludes null.
 - 'SchedulerBinding' is from 'package:flutter/src/scheduler/binding.dart' ('../../FlutterDev/flutter/packages/flutter/lib/src/scheduler/binding.dart').
      if (SchedulerBinding.instance!.schedulerPhase == SchedulerPhase.idle) {
                           ^
../../FlutterDev/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_easyrefresh-2.2.1/lib/src/header/refresh_indicator.dart:721:26: Warning: Operand of null-aware operation '!' has type 'SchedulerBinding' which excludes null.
 - 'SchedulerBinding' is from 'package:flutter/src/scheduler/binding.dart' ('../../FlutterDev/flutter/packages/flutter/lib/src/scheduler/binding.dart').
        SchedulerBinding.instance!.addPostFrameCallback((Duration timestamp) {
                         ^
../../FlutterDev/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_easyrefresh-2.2.1/lib/src/header/refresh_indicator.dart:766:30: Warning: Operand of null-aware operation '!' has type 'SchedulerBinding' which excludes null.
 - 'SchedulerBinding' is from 'package:flutter/src/scheduler/binding.dart' ('../../FlutterDev/flutter/packages/flutter/lib/src/scheduler/binding.dart').
            SchedulerBinding.instance!
                             ^
../../FlutterDev/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_easyrefresh-2.2.1/lib/src/header/refresh_indicator.dart:774:28: Warning: Operand of null-aware operation '!' has type 'SchedulerBinding' which excludes null.
 - 'SchedulerBinding' is from 'package:flutter/src/scheduler/binding.dart' ('../../FlutterDev/flutter/packages/flutter/lib/src/scheduler/binding.dart').
          SchedulerBinding.instance!.addPostFrameCallback((Duration timestamp) {
                           ^
../../FlutterDev/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_easyrefresh-2.2.1/lib/src/header/refresh_indicator.dart:788:32: Warning: Operand of null-aware operation '!' has type 'SchedulerBinding' which excludes null.
 - 'SchedulerBinding' is from 'package:flutter/src/scheduler/binding.dart' ('../../FlutterDev/flutter/packages/flutter/lib/src/scheduler/binding.dart').
              SchedulerBinding.instance!
                               ^
../../FlutterDev/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_easyrefresh-2.2.1/lib/src/header/header.dart:235:22: Warning: Operand of null-aware operation '!' has type 'SchedulerBinding' which excludes null.
 - 'SchedulerBinding' is from 'package:flutter/src/scheduler/binding.dart' ('../../FlutterDev/flutter/packages/flutter/lib/src/scheduler/binding.dart').
    SchedulerBinding.instance!.addPostFrameCallback((Duration timestamp) {
                     ^
../../FlutterDev/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_easyrefresh-2.2.1/lib/src/footer/footer.dart:244:22: Warning: Operand of null-aware operation '!' has type 'SchedulerBinding' which excludes null.
 - 'SchedulerBinding' is from 'package:flutter/src/scheduler/binding.dart' ('../../FlutterDev/flutter/packages/flutter/lib/src/scheduler/binding.dart').
    SchedulerBinding.instance!.addPostFrameCallback((Duration timestamp) {
                     ^
../../FlutterDev/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_easyrefresh-2.2.1/lib/src/footer/load_indicator.dart:198:30: Warning: Operand of null-aware operation '!' has type 'SchedulerBinding' which excludes null.
 - 'SchedulerBinding' is from 'package:flutter/src/scheduler/binding.dart' ('../../FlutterDev/flutter/packages/flutter/lib/src/scheduler/binding.dart').
        if (SchedulerBinding.instance!.schedulerPhase == SchedulerPhase.idle) {
                             ^
../../FlutterDev/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_easyrefresh-2.2.1/lib/src/footer/load_indicator.dart:201:28: Warning: Operand of null-aware operation '!' has type 'SchedulerBinding' which excludes null.
 - 'SchedulerBinding' is from 'package:flutter/src/scheduler/binding.dart' ('../../FlutterDev/flutter/packages/flutter/lib/src/scheduler/binding.dart').
          SchedulerBinding.instance!.addPostFrameCallback((Duration timestamp) {
                           ^
../../FlutterDev/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_easyrefresh-2.2.1/lib/src/footer/load_indicator.dart:596:24: Warning: Operand of null-aware operation '!' has type 'SchedulerBinding' which excludes null.
 - 'SchedulerBinding' is from 'package:flutter/src/scheduler/binding.dart' ('../../FlutterDev/flutter/packages/flutter/lib/src/scheduler/binding.dart').
      SchedulerBinding.instance!.addPostFrameCallback((Duration timestamp) {
                       ^
../../FlutterDev/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_easyrefresh-2.2.1/lib/src/footer/load_indicator.dart:663:24: Warning: Operand of null-aware operation '!' has type 'SchedulerBinding' which excludes null.
 - 'SchedulerBinding' is from 'package:flutter/src/scheduler/binding.dart' ('../../FlutterDev/flutter/packages/flutter/lib/src/scheduler/binding.dart').
      SchedulerBinding.instance!.addPostFrameCallback((Duration timestamp) {
                       ^
../../FlutterDev/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_easyrefresh-2.2.1/lib/src/footer/load_indicator.dart:705:28: Warning: Operand of null-aware operation '!' has type 'SchedulerBinding' which excludes null.
 - 'SchedulerBinding' is from 'package:flutter/src/scheduler/binding.dart' ('../../FlutterDev/flutter/packages/flutter/lib/src/scheduler/binding.dart').
      if (SchedulerBinding.instance!.schedulerPhase == SchedulerPhase.idle) {
                           ^
../../FlutterDev/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_easyrefresh-2.2.1/lib/src/footer/load_indicator.dart:708:26: Warning: Operand of null-aware operation '!' has type 'SchedulerBinding' which excludes null.
 - 'SchedulerBinding' is from 'package:flutter/src/scheduler/binding.dart' ('../../FlutterDev/flutter/packages/flutter/lib/src/scheduler/binding.dart').
        SchedulerBinding.instance!.addPostFrameCallback((Duration timestamp) {
                         ^
../../FlutterDev/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_easyrefresh-2.2.1/lib/src/footer/load_indicator.dart:751:30: Warning: Operand of null-aware operation '!' has type 'SchedulerBinding' which excludes null.
 - 'SchedulerBinding' is from 'package:flutter/src/scheduler/binding.dart' ('../../FlutterDev/flutter/packages/flutter/lib/src/scheduler/binding.dart').
            SchedulerBinding.instance!
                             ^
../../FlutterDev/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_easyrefresh-2.2.1/lib/src/footer/load_indicator.dart:759:28: Warning: Operand of null-aware operation '!' has type 'SchedulerBinding' which excludes null.
 - 'SchedulerBinding' is from 'package:flutter/src/scheduler/binding.dart' ('../../FlutterDev/flutter/packages/flutter/lib/src/scheduler/binding.dart').
          SchedulerBinding.instance!.addPostFrameCallback((Duration timestamp) {
                           ^
../../FlutterDev/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_easyrefresh-2.2.1/lib/src/footer/load_indicator.dart:770:32: Warning: Operand of null-aware operation '!' has type 'SchedulerBinding' which excludes null.
 - 'SchedulerBinding' is from 'package:flutter/src/scheduler/binding.dart' ('../../FlutterDev/flutter/packages/flutter/lib/src/scheduler/binding.dart').
              SchedulerBinding.instance!
                               ^
../../FlutterDev/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_easyrefresh-2.2.1/lib/src/refresher.dart:293:24: Warning: Operand of null-aware operation '!' has type 'SchedulerBinding' which excludes null.
 - 'SchedulerBinding' is from 'package:flutter/src/scheduler/binding.dart' ('../../FlutterDev/flutter/packages/flutter/lib/src/scheduler/binding.dart').
      SchedulerBinding.instance!.addPostFrameCallback((Duration timestamp) {
                       ^`
