### ISSUE TITLE
首次刷新有个bug

### ISSUE THREAD

**Issue by SJJ-dot** [xuelongqy/flutter_easyrefresh#458]
```
  /// 首次刷新
  final bool firstRefresh;

  /// 首次刷新组件
  /// 不设置时使用header
  final Widget? firstRefreshWidget;

// 判断是否开启首次刷新
    _enableFirstRefresh = widget.firstRefresh;
    if (_enableFirstRefresh) {
      _firstRefreshHeader = FirstRefreshHeader(widget.firstRefreshWidget!);
      SchedulerBinding.instance!.addPostFrameCallback((Duration timestamp) {
        callRefresh();
      });
    }
```

上面说了不设置用header，使用的时候用了！！！！

**Comment by yg7001** [comment]
我使用时，设置了首次刷新，下来刷新就失效了

**Comment by wh8817221** [comment]
我的设置firstRefresh= true会报错

**Comment by SJJ-dot** [comment]
> 我使用时，设置了首次刷新，下来刷新就失效了

我练手的项目，发现有bug就没用这个属性了

**Comment by SJJ-dot** [comment]
> 我的设置firstRefresh= true会报错

是的就是这个错误

**Comment by wh8817221** [comment]
我是关闭了首次刷新, 使用了下面的方法解决的：
SchedulerBinding.instance!.addPostFrameCallback((Duration timestamp) {
      Timer(Duration(milliseconds: 200), () {
        _controller.callRefresh();
      });
    });

**Comment by wh8817221** [comment]
> > 我的设置firstRefresh= true会报错
> 
> 是的就是这个错误

你可以用我下面的方法试试，我这边是没问题的

**Comment by SJJ-dot** [comment]
> 你可以用我下面的方法试试，我这边是没问题的

我做着玩的。不行也没关系๑乛◡乛๑

>

**Comment by xuelongqy** [comment]
v2.2.1已修复
