### ISSUE TITLE
能否支持沉浸式状态栏颜色渐变？

### ISSUE THREAD

**Issue by my6521** [xuelongqy/flutter_easyrefresh#46]
目前监听headerHeightChanged事件没问题，但footerHeightChanged事件只有到达底部才能触发。有些功能就实现不了

**Comment by xuelongqy** [comment]
这个，你可能需要使用ScrollController去操作

**Comment by my6521** [comment]
能把控件内部的ScrollController暴漏出来吗？

**Comment by xuelongqy** [comment]
这个你自己设置就可以了

**Comment by my6521** [comment]
你是指的outcontroller属性吗？

**Comment by xuelongqy** [comment]
ScrollView不是可以设置controller吗？

**Comment by my6521** [comment]
我再试下，谢谢你的耐心回复

**Comment by my6521** [comment]
你好，测试了下scrollView上的controller是可以的，但是下拉的时候监听的offset的永远是0。headerHeightChanged虽然可以实现，但总显得不是很好的方式。

**Comment by xuelongqy** [comment]
是的 这是EasyRefresh的实现原理，你可以结合两者一起使用

**Comment by raindy29** [comment]
沒有 ScrollController.addListener 方法，請問 TOP 回頂端要怎麼實現呢?

**Comment by xuelongqy** [comment]
v2版本已重构
