### ISSUE TITLE
在flutter_easyrefresh: ^2.2.0中 onload 方法执行了两次 ；

### ISSUE THREAD

**Issue by TakahashiAiko** [xuelongqy/flutter_easyrefresh#460]
在flutter_easyrefresh: ^2.2.0中 我将EasyRefresh配合getx使用 ； onLoad: homePageController.upLoading,
upLoading 方法走了两次 ； 导致page连续 ++ ；
测试表现为 ： 上提动作触底时触发一次 ； 松开回弹触发一次 ；

**Comment by hYRamos** [comment]
同样遇到，2.2.1，pageSize占不满全屏时，出现该问题

**Comment by supermebing** [comment]
同样遇到该问题

**Comment by HaHaHaHaHaHaHaaaaaa** [comment]
同样问题，onload两次，首次时页面未全屏。

**Comment by weifucheng1102** [comment]
footer 添加       enableInfiniteLoad: false



footer :ClassicalFooter(
      enableInfiniteLoad: false,
    )

**Comment by xuelongqy** [comment]
v3已发布，也许问题得到解决。如果问题依然存在，请重新打开
