### ISSUE TITLE
easyrefresh_2.1.8版本，当列表加载出多页后，急速往上滑动到列表顶部，会自动触发下拉加载，这时很容易触发一个error，截图如下，望大佬可以看看如何修复，

### ISSUE THREAD

**Issue by wcy0312808** [xuelongqy/flutter_easyrefresh#465]
![图片](https://user-images.githubusercontent.com/23207025/114806305-1c1b1b00-9dd7-11eb-96dc-93b0c2ad8f84.png)

**Comment by wcy0312808** [comment]
使用您提供的demo，同样会遇到这样的问题

**Comment by hw20101101** [comment]
这是个重复的问题，可参考下面两个 issues ：

https://github.com/xuelongqy/flutter_easyrefresh/issues/451

https://github.com/flutter/flutter/issues/78748

**Comment by xuelongqy** [comment]
v3已发布，也许问题得到解决。如果问题依然存在，请重新打开
