### ISSUE TITLE
旧版本迁移问题

### ISSUE THREAD

**Issue by zxcvbnm3057** [xuelongqy/flutter_easyrefresh#466]
旧版本更新到最新版后代码报错autoLoad refreshHeader refreshFooter 未定义

**Comment by zxcvbnm3057** [comment]
经核对与 flutter_easyrefresh/art/md/cn/PROPERTY.md 中写法一致，属性被弃用了吗，应该怎么修改呢

**Comment by xuelongqy** [comment]
请看文档，无限加载
