### ISSUE TITLE
下拉刷新不会结束  一直转圈

### ISSUE THREAD

**Issue by xieyezi** [xuelongqy/flutter_easyrefresh#467]
下拉刷新不会结束  一直转圈 
  _controller.resetLoadState();
  _controller.finishRefresh();
这两个个方法都调用了 还是不结束  打断点是因为这个finishRefreshCallBack ==null 导致的  不知道为什么

代码如下：
```dart
 if (res.results.length >= 0) {
      if (mounted) {
        setState(() {
          _totalCount = res.count;
          _infoList = res.results;
        });
        _controller.resetLoadState();
        _controller.finishRefresh();
      }
    }
```

![image](https://user-images.githubusercontent.com/16821989/115008206-6dadcd80-9edd-11eb-8b84-591bb48e8117.png)

flutter_easyrefresh: v2.1.8
flutter: 1.22.4

_Originally posted by @623034345 in https://github.com/xuelongqy/flutter_easyrefresh/issues/355#issuecomment-692612828_

**Comment by laiiihz** [comment]
是不是忘记初始化EasyRefreshController了😂

**Comment by xieyezi** [comment]
> 是不是忘记初始化EasyRefreshController了😂
@laiiihz 
确认已经初始化过了，目前已经替换为其他插件

**Comment by helloworld10010** [comment]
> > 是不是忘记初始化EasyRefreshController了😂
> > @laiiihz
> > 确认已经初始化过了，目前已经替换为其他插件

同样的问题。
`class HomePage extends StatefulWidget {
  static final sName = "home";

  @override
  _HomePageState createState() => _HomePageState();
}

class _HomePageState extends State<HomePage> {

  late DataBean? _dataBean;

  late TooltipBehavior _tooltipBehavior;
  late EasyRefreshController _controller;

  @override
  void initState() {
    super.initState();
    _tooltipBehavior = TooltipBehavior(enable: true,header: '',canShowMarker: true);
    _dataBean = DataBean();
    _controller = EasyRefreshController();
    // _controller.callRefresh(duration: Duration(seconds: 1));

  }

  @override
  Widget build(BuildContext context) {
    return Stack(
      children: [
        Column(
          mainAxisSize: MainAxisSize.max,
          mainAxisAlignment: MainAxisAlignment.start,
          children: <Widget>[
            Image(
              image: AssetImage("asset/icon_orange_bg.png"),
              fit: BoxFit.fitWidth,),
            Expanded(
              child: Container(
                color: Colors.white,
              ),
              flex: 1,
            )
          ],
        ),
        Scaffold(
          backgroundColor: Colors.transparent,
          appBar: AppBar(title: Text("首页"),centerTitle: true,elevation: 0,backgroundColor: Colors.transparent,),
          body: EasyRefresh(
            controller: _controller,
            enableControlFinishRefresh: true,
            firstRefresh: true,
            header: MaterialHeader(),
            onRefresh: () async {
              await _statNewBossFirstPage().then((value){
                setState(() {
                  _dataBean = value;
                });
                _controller.finishRefresh();
              }
              );

            },
            child: Column(
              children: <Widget>[
                Padding(
                  padding: const EdgeInsets.all(8.0),
                  child: Card(
                    clipBehavior: Clip.antiAlias,
                    elevation: 10,
                    shape: RoundedRectangleBorder(
                      borderRadius: BorderRadius.only(topLeft: Radius.circular(20),topRight: Radius.circular(20)),
                    ),
                    child: CheLiangTongJiWidget(_dataBean),
                  ),
                ),
                Padding(
                  padding: const EdgeInsets.symmetric(horizontal: 8),
                  child: Row(
                    children: <Widget>[
                      Expanded(child: YingShouOrYingFuTongJiWidget(_dataBean,YingShouOrYingFuTongJiWidget.YINGSHOU),flex: 1,),
                      Expanded(child: YingShouOrYingFuTongJiWidget(_dataBean,YingShouOrYingFuTongJiWidget.YINGFU),flex: 1,)
                    ],
                  ),
                ),
                Padding(
                  padding: const EdgeInsets.all(8.0),
                  child: Row(
                    mainAxisAlignment: MainAxisAlignment.start,
                    children: <Widget>[
                      Image.asset("asset/icon_yunying_zhuangkuang_tongji.png"),
                      Padding(
                        padding: const EdgeInsets.symmetric(horizontal: 8),
                        child: Text(
                          "运营状况统计",
                          style: Theme.of(context).textTheme.subtitle1,
                        ),
                      )
                    ],
                    crossAxisAlignment: CrossAxisAlignment.center,
                    textBaseline: TextBaseline.alphabetic,
                  ),
                ),
                _buildTypesSplineChart()
              ],
            ),
          ),
        )
      ],
    );
  }

  SfCartesianChart _buildTypesSplineChart() {
    return SfCartesianChart(
      legend: Legend(
          isVisible: true),
      plotAreaBorderWidth: 0,
      title: ChartTitle(text: '运营情况统计'),
      primaryXAxis: NumericAxis(
        majorGridLines: MajorGridLines(width: 0),
        interval: 1,
      ),
      primaryYAxis: NumericAxis(
          labelFormat: '{value}%',
          minimum: -0.1,
          maximum: 0.3,
          interval: 0.1,
          majorTickLines: MajorTickLines(size: 0)),
      series: _getSplineTypesSeries(),
      tooltipBehavior: _tooltipBehavior,
    );
  }

  List<SplineSeries<ChartData, num>> _getSplineTypesSeries() {
    final List<ChartData> chartData = <ChartData>[
      ChartData(1, 0.05),
      ChartData(2, 0),
      ChartData(3, 0.03),
      ChartData(4, 0),
      ChartData(5, 0.04),
      ChartData(6, 0.02),
      ChartData(7, -0.01),
      ChartData(8, 0.01),
      ChartData(9, -0.08),
      ChartData(10, -0.02),
      ChartData(11, 0.03),
      ChartData(12, 0.05),
    ];
    final List<ChartData> chartData2 = <ChartData>[
      ChartData(1, 0.03),
      ChartData(2, 0.04),
      ChartData(3, 0.03),
      ChartData(4, 0),
      ChartData(5, 0.04),
      ChartData(6, 0.04),
      ChartData(7, -0.01),
      ChartData(8, 0.01),
      ChartData(9, 0.3),
      ChartData(10, -0.02),
      ChartData(11, 0.04),
    ];
    return <SplineSeries<ChartData, num>>[
      SplineSeries<ChartData, num>(
        /// To set the spline type here.
          splineType: SplineType.natural,
          dataSource: chartData,
          name: "利润",
          xValueMapper: (ChartData sales, _) => sales.x,
          yValueMapper: (ChartData sales, _) => sales.y,
          width: 2),
      SplineSeries<ChartData, num>(
        /// To set the spline type here.
          splineType: SplineType.natural,
          dataSource: chartData2,
          name: "费用",
          xValueMapper: (ChartData sales, _) => sales.x,
          yValueMapper: (ChartData sales, _) => sales.y,
          width: 2),
    ];
  }

  Future<DataBean?> _statNewBossFirstPage() async {
    var result = await httpManager.netFetch(Address.statNewBossFirstPage);
    if(result?.result??false){
      var dataBean = RootBean.fromJsonMap(json.decode(result?.data));
      return dataBean.data;
    } else {
      Fluttertoast.showToast(msg: "网络错误..");
    }
    _controller.finishRefresh(success: true);
  }

  @override
  void dispose() {
    _controller.dispose();
  }
}`

**Comment by helloworld10010** [comment]
> 是不是忘记初始化EasyRefreshController了😂

同样的问题。
```
class _HomePageState extends State<HomePage> {

  late DataBean? _dataBean;

  late TooltipBehavior _tooltipBehavior;
  late EasyRefreshController _controller;

  @override
  void initState() {
    super.initState();
    _tooltipBehavior = TooltipBehavior(enable: true,header: '',canShowMarker: true);
    _dataBean = DataBean();
    _controller = EasyRefreshController();
    // _controller.callRefresh(duration: Duration(seconds: 1));

  }

  @override
  Widget build(BuildContext context) {
    return Stack(
      children: [
        Column(
          mainAxisSize: MainAxisSize.max,
          mainAxisAlignment: MainAxisAlignment.start,
          children: <Widget>[
            Image(
              image: AssetImage("asset/icon_orange_bg.png"),
              fit: BoxFit.fitWidth,),
            Expanded(
              child: Container(
                color: Colors.white,
              ),
              flex: 1,
            )
          ],
        ),
        Scaffold(
          backgroundColor: Colors.transparent,
          appBar: AppBar(title: Text("首页"),centerTitle: true,elevation: 0,backgroundColor: Colors.transparent,),
          body: EasyRefresh(
            controller: _controller,
            enableControlFinishRefresh: true,
            firstRefresh: true,
            header: MaterialHeader(),
            onRefresh: () async {
              await _statNewBossFirstPage().then((value){
                setState(() {
                  _dataBean = value;
                });
                _controller.finishRefresh();
              }
              );

            },
            child: Column(
              children: <Widget>[
                Padding(
                  padding: const EdgeInsets.all(8.0),
                  child: Card(
                    clipBehavior: Clip.antiAlias,
                    elevation: 10,
                    shape: RoundedRectangleBorder(
                      borderRadius: BorderRadius.only(topLeft: Radius.circular(20),topRight: Radius.circular(20)),
                    ),
                    child: CheLiangTongJiWidget(_dataBean),
                  ),
                ),
                Padding(
                  padding: const EdgeInsets.symmetric(horizontal: 8),
                  child: Row(
                    children: <Widget>[
                      Expanded(child: YingShouOrYingFuTongJiWidget(_dataBean,YingShouOrYingFuTongJiWidget.YINGSHOU),flex: 1,),
                      Expanded(child: YingShouOrYingFuTongJiWidget(_dataBean,YingShouOrYingFuTongJiWidget.YINGFU),flex: 1,)
                    ],
                  ),
                ),
                Padding(
                  padding: const EdgeInsets.all(8.0),
                  child: Row(
                    mainAxisAlignment: MainAxisAlignment.start,
                    children: <Widget>[
                      Image.asset("asset/icon_yunying_zhuangkuang_tongji.png"),
                      Padding(
                        padding: const EdgeInsets.symmetric(horizontal: 8),
                        child: Text(
                          "运营状况统计",
                          style: Theme.of(context).textTheme.subtitle1,
                        ),
                      )
                    ],
                    crossAxisAlignment: CrossAxisAlignment.center,
                    textBaseline: TextBaseline.alphabetic,
                  ),
                ),
                _buildTypesSplineChart()
              ],
            ),
          ),
        )
      ],
    );
  }

  SfCartesianChart _buildTypesSplineChart() {
    return SfCartesianChart(
      legend: Legend(
          isVisible: true),
      plotAreaBorderWidth: 0,
      title: ChartTitle(text: '运营情况统计'),
      primaryXAxis: NumericAxis(
        majorGridLines: MajorGridLines(width: 0),
        interval: 1,
      ),
      primaryYAxis: NumericAxis(
          labelFormat: '{value}%',
          minimum: -0.1,
          maximum: 0.3,
          interval: 0.1,
          majorTickLines: MajorTickLines(size: 0)),
      series: _getSplineTypesSeries(),
      tooltipBehavior: _tooltipBehavior,
    );
  }

  List<SplineSeries<ChartData, num>> _getSplineTypesSeries() {
    final List<ChartData> chartData = <ChartData>[
      ChartData(1, 0.05),
      ChartData(2, 0),
      ChartData(3, 0.03),
      ChartData(4, 0),
      ChartData(5, 0.04),
      ChartData(6, 0.02),
      ChartData(7, -0.01),
      ChartData(8, 0.01),
      ChartData(9, -0.08),
      ChartData(10, -0.02),
      ChartData(11, 0.03),
      ChartData(12, 0.05),
    ];
    final List<ChartData> chartData2 = <ChartData>[
      ChartData(1, 0.03),
      ChartData(2, 0.04),
      ChartData(3, 0.03),
      ChartData(4, 0),
      ChartData(5, 0.04),
      ChartData(6, 0.04),
      ChartData(7, -0.01),
      ChartData(8, 0.01),
      ChartData(9, 0.3),
      ChartData(10, -0.02),
      ChartData(11, 0.04),
    ];
    return <SplineSeries<ChartData, num>>[
      SplineSeries<ChartData, num>(
        /// To set the spline type here.
          splineType: SplineType.natural,
          dataSource: chartData,
          name: "利润",
          xValueMapper: (ChartData sales, _) => sales.x,
          yValueMapper: (ChartData sales, _) => sales.y,
          width: 2),
      SplineSeries<ChartData, num>(
        /// To set the spline type here.
          splineType: SplineType.natural,
          dataSource: chartData2,
          name: "费用",
          xValueMapper: (ChartData sales, _) => sales.x,
          yValueMapper: (ChartData sales, _) => sales.y,
          width: 2),
    ];
  }

  Future<DataBean?> _statNewBossFirstPage() async {
    var result = await httpManager.netFetch(Address.statNewBossFirstPage);
    if(result?.result??false){
      var dataBean = RootBean.fromJsonMap(json.decode(result?.data));
      return dataBean.data;
    } else {
      Fluttertoast.showToast(msg: "网络错误..");
    }
    _controller.finishRefresh(success: true);
  }

  @override
  void dispose() {
    _controller.dispose();
  }
}```

**Comment by helloworld10010** [comment]
> > 是不是忘记初始化EasyRefreshController了😂
> > @laiiihz
> > 确认已经初始化过了，目前已经替换为其他插件

我出现了同样的问题，发现是数据转换报错了，后边的finishrefresh没走到，你可以试试不用你自己的代码，直接
`
Future.delay(Durtion(secons 3)(){
   controller.finishRefresh();
})
`测试
