### ISSUE TITLE
設定CustomScrollView屬性center後無法觸發onRefresh和無法顯示header

### ISSUE THREAD

**Issue by WingCH** [xuelongqy/flutter_easyrefresh#469]
我的場境：
假設現在是在第二分頁，下拉加載上一頁(第一頁)，上拉加載下一頁(第三頁),
我找到教學是使用`CustomScrollView -> center key` 來做類似的效果
1. https://dartpad.dartlang.org/c3b9b03925cdaaf88c1b8fe78a3b96b0
2. https://dartpad.dartlang.org/38a9320bb8edd30af3c8543c24df8a21

> https://github.com/flutter/flutter/issues/21541

根據上面的教學我嘗試使用`flutter_easyrefresh` 實現,
在example (`https://github.com/xuelongqy/flutter_easyrefresh/blob/v2/example/lib/page/sample/swiper.dart`), 在`CustomScrollView`  和 `SliverList` 加入 center key 會無法觸發onRefresh和無法顯示header

```dart
class SwiperPageState extends State<SwiperPage> {
  // 条目总数
  int _count = 20;

  @override
  Widget build(BuildContext context) {
    const Key centerKey = ValueKey('second-sliver-list'); // <-----

    return Scaffold(
      body: EasyRefresh.builder(
        builder: (context, physics, header, footer) {
          return CustomScrollView(
            center: centerKey, // <-----
            physics: physics,
            slivers: <Widget>[
              SliverAppBar(
                expandedHeight: 100.0,
                pinned: true,
                backgroundColor: Colors.white,
                flexibleSpace: FlexibleSpaceBar(
                  centerTitle: false,
                  title: Text('Swiper'),
                ),
              ),
              header,
              SliverList(
                key: centerKey, // <-----
                delegate: SliverChildListDelegate([
                  Container(
                    height: 210.0,
...
```
## 正常情況

https://user-images.githubusercontent.com/19588517/115420129-77149e00-a22d-11eb-8fab-3768d15e5913.mp4

## 加入centerKey 後

https://user-images.githubusercontent.com/19588517/115420147-7845cb00-a22d-11eb-8d1c-ffec73e53f04.mp4

求指教!

**Comment by xuelongqy** [comment]
v3已发布，也许问题得到解决。如果问题依然存在，请重新打开
