### ISSUE TITLE
能否添加一个加载更多失败后，点击重试的功能？

### ISSUE THREAD

**Issue by magic0908** [xuelongqy/flutter_easyrefresh#473]
感谢作者提供的开源库，不过我在使用的时候遇到一个问题。

通常的列表页，加载更多数据的时候，可能有网络问题啥的，加载失败，这时候点击底部不会触发重新加载功能，能否添加上？

**Comment by xuelongqy** [comment]
v3已发布，默认样式可自定义widget，请及时更新
