### ISSUE TITLE
如下模式 无法下拉刷新 上拉加载

### ISSUE THREAD

**Issue by chinajuns** [xuelongqy/flutter_easyrefresh#474]
如题，其中已替换builder,custom,都出现bug
Column(
          mainAxisSize: MainAxisSize.min,
          children: [
            Container(
              height: 55.0,
              decoration: BoxDecoration(
                  color: Colors.white,
              ),
            ),
            Expanded(
              child: LayoutBuilder(builder: (_,constraints){
                return Container(
                  child: EasyRefresh(
                    child:  ListView.builder(itemBuilder: (_,int f){
                         return _buildGoodsItem(model: _goods[f]);
                     },itemCount: _goods.length,shrinkWrap: true,);,
                    onRefresh: ()async{
                      this.loadGoods();
                    },
                    onLoad: ()async{
                      this.loadNextPage();
                    },
                    header: FLPulseHeader(),
                    footer: FLPulseFooter(),
                  ),
                );
              },),
            ),
            Container(
              height:44.0,
              decoration: BoxDecoration(
                  color: Colors.white,
              ),
            )
          ],
        )

**Comment by xuelongqy** [comment]
v3已发布，也许问题得到解决。如果问题依然存在，请重新打开
