### ISSUE TITLE
Refresh Indicator & Over scroll on Top of the Page (Outer scroller) - (When using NestedScrollView - TabView- CustomScrollView)

### ISSUE THREAD

**Issue by yasinarik** [xuelongqy/flutter_easyrefresh#477]
## @xuelongqy Hi, thanks for creating this package. 

I have a problem too. I want `refresh indicator` & `over scroll` to occur at the top of the NestedScrollView. (top of the page, outer scroller, **not** in between the tab buttons and inner scroller)

Can you achieve this?

### Here are some issues opened by me:
Please have a look at them if you have time because you seem to have the skills to implement new solutions.
[Issue at Flutter repo](https://github.com/flutter/flutter/issues/82150)
[Issue at ExtendedNestedScrollView repo](https://github.com/fluttercandies/extended_nested_scroll_view/issues/72)

### This is opened by someone else for your package. 
Is this related? I couldn't find the example you mentioned :(
#386

**Comment by krmao** [comment]
anything about this?

**Comment by xuelongqy** [comment]
v3 has been released, please update in time. If the problem persists, please reopen
