### ISSUE TITLE
一个小小建议

### ISSUE THREAD

**Issue by xyxiaosang** [xuelongqy/flutter_easyrefresh#478]
经典的header和Footer（ClassicalFooter和ClassicalHeader）建议：
1、前面的图标颜色是否可以单独设置与字体颜色区分
2、加载完成的图标是否可以更改或者取消显示

**Comment by lan2000** [comment]
同意，特别是第二点

**Comment by lan2000** [comment]
同意，特别是第二点

**Comment by xuelongqy** [comment]
v3已发布，请及时更新
