### ISSUE TITLE
在监听下拉刷新时，滑动距离偶会有异常

### ISSUE THREAD

**Issue by YinHAHA** [xuelongqy/flutter_easyrefresh#479]
![image](https://user-images.githubusercontent.com/21334507/118255258-9cb85e80-b4de-11eb-8e97-2fc65e6eff74.png)
使用NotificationListener监听EasyRefresh.custom的滑动距离，会出现使用scrollNotification.metrics.pixels打印的距离，有异常数据，正常情况下拉打印负值，等松开手，滑动距离应该是逐渐趋近0，停止后变成0，但是打印出来的数据，会突然冒出几个正数，导致影响了业务逻辑

**Comment by YinHAHA** [comment]
以上对应版本是2.1.8

**Comment by xuelongqy** [comment]
请查看之前的issue，使用NotificationHeader

**Comment by YinHAHA** [comment]
我不是要监听头部下拉距离，我需要监听的是上拉的距离，根据上拉的距离做标题栏透明度显示的效果，如果下拉距离显示正值，会做透明度计算，如果是负值，则透明的是0，标题栏不显示，按理说下拉刷新，直至下拉刷新完成，这个滑动距离都是负值，透明度都是0，不用显示标题栏，但是会发现下拉的时候，距离显示会变成正值，就如上面日志显示。
