### ISSUE TITLE
在监听上拉距离时，发现下拉刷新时距离偶会有异常

### ISSUE THREAD

**Issue by YinHAHA** [xuelongqy/flutter_easyrefresh#480]
使用NotificationListener监听EasyRefresh.custom的滑动距离，会出现使用scrollNotification.metrics.pixels打印的距离，
我需要监听的是上拉的距离，根据上拉的距离做标题栏透明度显示的效果，如果下拉距离显示正值，会做透明度计算，如果是负值，则透明的是0，标题栏不显示，按理说下拉刷新，直至下拉刷新完成，这个滑动距离都是负值，透明度都是0，不用显示标题栏，但是会发现下拉的时候，距离显示会变成正值，就如下日志显示。
![image](https://user-images.githubusercontent.com/21334507/118626425-7441a480-b7fd-11eb-9a8c-cde6ce406c80.png)

**Comment by xiaoshuimao** [comment]
```dart
 EasyRefresh.custom(
          onRefresh: onRefresh,
          scrollController: _scrollController,
          ......
)
```
![image](https://user-images.githubusercontent.com/6658087/120739054-773dd400-c523-11eb-8ce8-1de57df7d4a0.png)

我的情况是： 如果使用了下拉刷新onRefresh，    _scrollController.offset的也会想出现同样的情况。在出现释放刷新的状态下， _scrollController.offset 回复为 0。

如果不使用onRefresh下拉刷新， _scrollController.offset是正常的。

**Comment by choykarl** [comment]
我也是，下拉到开始刷新的那一瞬间，会突然变成0

**Comment by choykarl** [comment]
@YinHAHA @w567675 可以给header传一个LinkHeaderNotifier对象，然后监听它的pulledExtent

**Comment by xuelongqy** [comment]
v3已发布，请及时更新
