### ISSUE TITLE
GridView 和 EasyRefresh 的 footer

### ISSUE THREAD

**Issue by HZHAndroid** [xuelongqy/flutter_easyrefresh#481]
在 GridView  中使用，没有数据的时候，出现以下问题：
1、导致 GridView 的高度没有撑起（没有数据的时候）；
2、GridView 第一次显示，出现短暂的 footer 在中间；
3、假如 GridView 没有数据，则 footer 一直显示在屏幕中间；

如图：
![QQ截图20210524151742](https://user-images.githubusercontent.com/7828091/119311103-3a601a80-bca3-11eb-90f8-7b6b0345408c.png)

**Comment by xuelongqy** [comment]
v3已发布，也许问题得到解决。如果问题依然存在，请重新打开
