### ISSUE TITLE
GridView  和  EasyRefresh 的 header

### ISSUE THREAD

**Issue by HZHAndroid** [xuelongqy/flutter_easyrefresh#482]
当 GridView  和 EasyRefresh 一起使用的时候，会导致在上拉加载更多之后，出现 header 不可见的情况；
我的页面只有一页数据，也就是一页数据，就无法加载更多了。
操作如下：
第一步：切换到歌手页面，数据加载出来之后，下拉，可以看到控件：
![1](https://user-images.githubusercontent.com/7828091/119311947-4ef0e280-bca4-11eb-91ec-fca9e8c4ee0d.png)
第二步：刷新完成之后，滚动到底部看到没有更多数据页面，如图：
![112](https://user-images.githubusercontent.com/7828091/119312033-66c86680-bca4-11eb-966e-86eb021fd873.png)
第三步：重新滚回头部，下拉刷新，头部不见了，如图：
![333](https://user-images.githubusercontent.com/7828091/119312123-852e6200-bca4-11eb-86da-b5dba29de350.png)

这里有些时候也会把底部的没有更多数据放到了顶部；
我测试了一下，只要把 

  /// 任务独立(刷新和加载状态独立)
  final bool taskIndependence;
这个属性设置为 true，就没有问题；

**Comment by xuelongqy** [comment]
v3已发布，也许问题得到解决。如果问题依然存在，请重新打开
