### ISSUE TITLE
使用easyRefresh，刷新成功后设置noMore为true，列表顶部留白

### ISSUE THREAD

**Issue by tzt1994** [xuelongqy/flutter_easyrefresh#483]
这是我的代码
![image](https://user-images.githubusercontent.com/15625580/121144963-0e32c500-c871-11eb-80f7-7450755932cf.png)

请求代码
![image](https://user-images.githubusercontent.com/15625580/121145060-29053980-c871-11eb-8f80-5989195a1432.png)

刷新成功后，设置nomore为true，列表顶部留白
![image](https://user-images.githubusercontent.com/15625580/121145282-5eaa2280-c871-11eb-9aec-c798ca2d7887.png)

**Comment by xuelongqy** [comment]
v3已发布，也许问题得到解决。如果问题依然存在，请重新打开
