### ISSUE TITLE
设置enableInfiniteLoad关闭回弹效果后，下拉刷新导致footer不显示

### ISSUE THREAD

**Issue by cherrybiu** [xuelongqy/flutter_easyrefresh#484]
发生条件：设置enableInfiniteLoad为true关闭回弹效果，在数据量超过一屏且数据加载完毕
出现问题：首次进来footer正常显示‘没有更多了’,但是只要操作了下拉刷新并设置noMore为true，此时滚动到下方footer没有任何提示显示。此时点击编辑器进行一次setState又显示正常，或者把回弹效果打开，即enableInfiniteLoad设为false，下拉刷新也会正常显示
推断：关闭回弹效果后，进行一次刷新，然后滑动到底部，此时没有触发footer的contentBuilder方法，所以无法渲染footer的widget。点击一次setState, 就可以走进contentBuilder方法，此时渲染成功。或者打开回弹效果后，下滑到底部，也会自动触发footer的contentBuilder方法，所以渲染也正常。

所以这里的算不算是一个bug， 无法回弹即无法主动触发到底部footer方法，那应该如何实现关闭回弹的效果下同时让footer的提示也显示呢

**Comment by BatterMan-Li** [comment]
我也碰到同样的问题，请问这个问题解决了吗？

**Comment by xuelongqy** [comment]
v3已发布，也许问题得到解决。如果问题依然存在，请重新打开
