### ISSUE TITLE
引用插件报错

### ISSUE THREAD

**Issue by happy-sw** [xuelongqy/flutter_easyrefresh#487]
报错如下：
======== Exception caught by foundation library ====================================================
The following assertion was thrown while dispatching notifications for ValueNotifier<TaskState>:
setState() or markNeedsBuild() called during build.

This EasyRefresh widget cannot be marked as needing to build because the framework is already in the process of building widgets.  A widget can be marked as needing to be built during the build phase only if one of its ancestors is currently building. This exception is allowed because the framework builds parent widgets before children, which means a dirty descendant will always be built. Otherwise, the framework might not visit this widget during this build phase.
The widget on which setState() or markNeedsBuild() was called was: EasyRefresh
  dependencies: [PrimaryScrollController]
  state: _EasyRefreshState#5d52b
The widget which was currently being built when the offending call was made was: LayoutBuilder
  renderObject: _RenderLayoutBuilder#987c1 relayoutBoundary=up2
When the exception was thrown, this was the stack: 
#0      Element.markNeedsBuild.<anonymous closure> (package:flutter/src/widgets/framework.dart:4138:11)
#1      Element.markNeedsBuild (package:flutter/src/widgets/framework.dart:4153:6)
#2      State.setState (package:flutter/src/widgets/framework.dart:1287:15)
#3      _EasyRefreshState.initState.<anonymous closure> (package:flutter_easyrefresh/src/refresher.dart:282:9)
#4      ChangeNotifier.notifyListeners (package:flutter/src/foundation/change_notifier.dart:243:25)
...
The ValueNotifier<TaskState> sending notification was: ValueNotifier<TaskState>#60f56(Instance of 'TaskState')

这是什么情况

**Comment by xuelongqy** [comment]
v3已发布，也许问题得到解决。如果问题依然存在，请重新打开
