### ISSUE TITLE
finishLoad nomore设置为true,footer显示不正常  version: 2.1.8

### ISSUE THREAD

**Issue by SeeyouYsen** [xuelongqy/flutter_easyrefresh#489]
第一次刷新之后,设置finishLoad nomore设置为true,footter显示正常,
然后 resetLoadState 再刷新一次,finishLoad nomore设置为true,footer就不显示了
`refreshController.resetLoadState();`
  ` List<T> list = await loadData(pageParams: {'Page': pageIndex, 'PageSize': pageSize});`
      `refreshController.finishRefresh();`
     ` refreshController.finishLoad(noMore: list.length < pageSize);`

**Comment by g707175425** [comment]
我也是这问题

**Comment by xuelongqy** [comment]
v3已发布，也许问题得到解决。如果问题依然存在，请重新打开
