### ISSUE TITLE
SecondFloorPage多次拖动后有可能引起异常，直至应用崩溃

### ISSUE THREAD

**Issue by linenlin01** [xuelongqy/flutter_easyrefresh#49]
Launching lib\flutter_easyrefresh\secondfloor\main.dart on Android SDK built for x86 in debug mode...
Initializing gradle...
Resolving dependencies...
Running Gradle task 'assembleDebug'...
Built build\app\outputs\apk\debug\app-debug.apk.
Syncing files to device Android SDK built for x86...
D/        ( 7277): HostConnection::get() New Host Connection established 0xe9b525c0, tid 7297
D/EGL_emulation( 7277): eglMakeCurrent: 0xed95f640: ver 2 0 (tinfo 0xe9b4bda0)
I/flutter ( 7277): ══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
I/flutter ( 7277): The following assertion was thrown building Container(constraints: BoxConstraints(w=Infinity,
I/flutter ( 7277): h=-12.4; NOT NORMALIZED), dirty):
I/flutter ( 7277): BoxConstraints has a negative minimum height.
I/flutter ( 7277): The offending constraints were:
I/flutter ( 7277):   BoxConstraints(w=Infinity, h=-12.4; NOT NORMALIZED)
I/flutter ( 7277): 
I/flutter ( 7277): When the exception was thrown, this was the stack:
I/flutter ( 7277): #0      BoxConstraints.debugAssertIsValid.<anonymous closure>.throwError (package:flutter/src/rendering/box.dart:504:9)
I/flutter ( 7277): #1      BoxConstraints.debugAssertIsValid.<anonymous closure> (package:flutter/src/rendering/box.dart:534:19)
I/flutter ( 7277): #2      BoxConstraints.debugAssertIsValid (package:flutter/src/rendering/box.dart:551:6)
I/flutter ( 7277): #3      new ConstrainedBox (package:flutter/src/widgets/basic.dart:1969:27)
I/flutter ( 7277): #4      Container.build (package:flutter/src/widgets/container.dart:381:17)
I/flutter ( 7277): #5      StatelessElement.build (package:flutter/src/widgets/framework.dart:3789:28)
I/flutter ( 7277): #6      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3736:15)
I/flutter ( 7277): #7      Element.rebuild (package:flutter/src/widgets/framework.dart:3559:5)
I/flutter ( 7277): #8      StatelessElement.update (package:flutter/src/widgets/framework.dart:3796:5)
I/flutter ( 7277): #9      Element.updateChild (package:flutter/src/widgets/framework.dart:2748:15)
I/flutter ( 7277): #10     RenderObjectElement.updateChildren (package:flutter/src/widgets/framework.dart:4601:32)
I/flutter ( 7277): #11     MultiChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4992:17)
I/flutter ( 7277): #12     Element.updateChild (package:flutter/src/widgets/framework.dart:2748:15)
I/flutter ( 7277): #13     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3747:16)
I/flutter ( 7277): #14     Element.rebuild (package:flutter/src/widgets/framework.dart:3559:5)
I/flutter ( 7277): #15     ProxyElement.update (package:flutter/src/widgets/framework.dart:4006:5)
I/flutter ( 7277): #16     Element.updateChild (package:flutter/src/widgets/framework.dart:2748:15)
I/flutter ( 7277): #17     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3747:16)
I/flutter ( 7277): #18     Element.rebuild (package:flutter/src/widgets/framework.dart:3559:5)
I/flutter ( 7277): #19     ProxyElement.update (package:flutter/src/widgets/framework.dart:4006:5)
I/flutter ( 7277): #20     Element.updateChild (package:flutter/src/widgets/framework.dart:2748:15)
I/flutter ( 7277): #21     RenderObjectElement.updateChildren (package:flutter/src/widgets/framework.dart:4601:32)
I/flutter ( 7277): #22     MultiChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4992:17)
I/flutter ( 7277): #23     Element.updateChild (package:flutter/src/widgets/framework.dart:2748:15)
I/flutter ( 7277): #24     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3747:16)
I/flutter ( 7277): #25     Element.rebuild (package:flutter/src/widgets/framework.dart:3559:5)
I/flutter ( 7277): #26     StatefulElement.update (package:flutter/src/widgets/framework.dart:3894:5)
I/flutter ( 7277): #27     Element.updateChild (package:flutter/src/widgets/framework.dart:2748:15)
I/flutter ( 7277): #28     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3747:16)
I/flutter ( 7277): #29     Element.rebuild (package:flutter/src/widgets/framework.dart:3559:5)
I/flutter ( 7277): #30     ProxyElement.update (package:flutter/src/widgets/framework.dart:4006:5)
I/flutter ( 7277): #31     Element.updateChild (package:flutter/src/widgets/framework.dart:2748:15)
I/flutter ( 7277): #32     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3747:16)
I/flutter ( 7277): #33     Element.rebuild (package:flutter/src/widgets/framework.dart:3559:5)
I/flutter ( 7277): #34     StatefulElement.update (package:flutter/src/widgets/framework.dart:3894:5)
I/flutter ( 7277): #35     Element.updateChild (package:flutter/src/widgets/framework.dart:2748:15)
I/flutter ( 7277): #36     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4883:14)
I/flutter ( 7277): #37     Element.updateChild (package:flutter/src/widgets/framework.dart:2748:15)
I/flutter ( 7277): #38     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3747:16)
I/flutter ( 7277): #39     Element.rebuild (package:flutter/src/widgets/framework.dart:3559:5)
I/flutter ( 7277): #40     StatelessElement.update (package:flutter/src/widgets/framework.dart:3796:5)
I/flutter ( 7277): #41     Element.updateChild (package:flutter/src/widgets/framework.dart:2748:15)
I/flutter ( 7277): #42     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4883:14)
I/flutter ( 7277): #43     Element.updateChild (package:flutter/src/widgets/framework.dart:2748:15)
I/flutter ( 7277): #44     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3747:16)
I/flutter ( 7277): #45     Element.rebuild (package:flutter/src/widgets/framework.dart:3559:5)
I/flutter ( 7277): #46     StatefulElement.update (package:flutter/src/widgets/framework.dart:3894:5)
I/flutter ( 7277): #47     Element.updateChild (package:flutter/src/widgets/framework.dart:2748:15)
I/flutter ( 7277): #48     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3747:16)
I/flutter ( 7277): #49     Element.rebuild (package:flutter/src/widgets/framework.dart:3559:5)
I/flutter ( 7277): #50     StatefulElement.update (package:flutter/src/widgets/framework.dart:3894:5)
I/flutter ( 7277): #51     Element.updateChild (package:flutter/src/widgets/framework.dart:2748:15)
I/flutter ( 7277): #52     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3747:16)
I/flutter ( 7277): #53     Element.rebuild (package:flutter/src/widgets/framework.dart:3559:5)
I/flutter ( 7277): #54     ProxyElement.update (package:flutter/src/widgets/framework.dart:4006:5)
I/flutter ( 7277): #55     Element.updateChild (package:flutter/src/widgets/framework.dart:2748:15)
I/flutter ( 7277): #56     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3747:16)
I/flutter ( 7277): #57     Element.rebuild (package:flutter/src/widgets/framework.dart:3559:5)
I/flutter ( 7277): #58     ProxyElement.update (package:flutter/src/widgets/framework.dart:4006:5)
I/flutter ( 7277): #59     Element.updateChild (package:flutter/src/widgets/framework.dart:2748:15)
I/flutter ( 7277): #60     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3747:16)
I/flutter ( 7277): #61     Element.rebuild (package:flutter/src/widgets/framework.dart:3559:5)
I/flutter ( 7277): #62     StatefulElement.update (package:flutter/src/widgets/framework.dart:3894:5)
I/flutter ( 7277): #63     Element.updateChild (package:flutter/src/widgets/framework.dart:2748:15)
I/flutter ( 7277): #64     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3747:16)
I/flutter ( 7277): #65     Element.rebuild (package:flutter/src/widgets/framework.dart:3559:5)
I/flutter ( 7277): #66     BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2273:33)
I/flutter ( 7277): #67     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding&RendererBinding&WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:700:20)
I/flutter ( 7277): #68     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding&RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:268:5)
I/flutter ( 7277): #69     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:988:15)
I/flutter ( 7277): #70     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:928:9)
I/flutter ( 7277): #71     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:840:5)
I/flutter ( 7277): #75     _invoke (dart:ui/hooks.dart:209:10)
I/flutter ( 7277): #76     _drawFrame (dart:ui/hooks.dart:168:3)
I/flutter ( 7277): (elided 3 frames from package dart:async)
I/flutter ( 7277): ════════════════════════════════════════════════════════════════════════════════════════════════════
I/flutter ( 7277): Another exception was thrown: A RenderFlex overflowed by 99317 pixels on the bottom.
I/flutter ( 7277): Another exception was thrown: BoxConstraints has a negative minimum height.

![image](https://user-images.githubusercontent.com/19919981/54172095-dd0f9280-44b7-11e9-8689-d38e69ec675e.png)

**Comment by xuelongqy** [comment]
可能是_headerHeight为负值导致的，加个是否小于0的判断应该就可以了
