### ISSUE TITLE
easyrefresh嵌套listview，如何实现listview滑动到底部后继续滑动可以上拉加载

### ISSUE THREAD

**Issue by liziliang123** [xuelongqy/flutter_easyrefresh#490]
easyrefresh嵌套listview，如何实现listview滑动到底部后继续滑动可以上拉加载，现在的情况是必须滑动listview外面的部分才可以触发上拉加载，如何实现在listview内部滑动时触发上拉加载？

**Comment by xuelongqy** [comment]
v3已发布，也许问题得到解决。如果问题依然存在，请重新打开
