### ISSUE TITLE
The method 'markNeedsBuild' was called on null 

### ISSUE THREAD

**Issue by yixiaolunhui** [xuelongqy/flutter_easyrefresh#491]
load_indicator.dart in _EasyRefreshSliverLoadControlState.initState.<fn> at line 618 within flutter_easyrefresh  

load_indicator中618行
 // 监听是否触发刷新
    widget.taskNotifier.addListener(() {
      if (widget.taskNotifier.value.refreshing && !widget.taskIndependence) {
        setState(() {});
      }
    });

没有判断mounted  最好所有地方setState（）地方都判断下，抛出了很多这样的bug

**Comment by xuelongqy** [comment]
v3已发布，也许问题得到解决。如果问题依然存在，请重新打开
