### ISSUE TITLE
EasyRefresh.custom，设置shrinkWrap: true, 下拉刷新时，有头部不跟手的问题

### ISSUE THREAD

**Issue by lizhuoyuan** [xuelongqy/flutter_easyrefresh#493]
看起来像是卡顿
换成EasyRefresh就可以了。 去掉`shrinkWrap: true,`也正常了
<del>另外这3种使用方式，请问 哪种是更加推荐常用的呢？</del> 看源码更推荐custom

**Comment by xuelongqy** [comment]
v3已发布，也许问题得到解决。如果问题依然存在，请重新打开
