### ISSUE TITLE
header 支持 lottie 动画吗？

### ISSUE THREAD

**Issue by loveNoodles** [xuelongqy/flutter_easyrefresh#495]
header 支持 lottie 动画吗？

**Comment by houziruinb87** [comment]
支持

**Comment by xuelongqy** [comment]
支持的哈。v3已发布，请及时更新

**Comment by AngelBo** [comment]
你好 请问怎么使用呀  有案例吗 作者

**Comment by AngelBo** [comment]
你好 请问怎么使用呀 有案例lottie结合easyRefresh吗 作者

**Comment by xuelongqy** [comment]
> 你好 请问怎么使用呀 有案例lottie结合easyRefresh吗 作者

参考styles中的样式进行定义即可

**Comment by AngelBo** [comment]
改了几个没改成功  style里面全部是rive的controller
