### ISSUE TITLE
底部回弹问题

### ISSUE THREAD

**Issue by youmu178** [xuelongqy/flutter_easyrefresh#496]
请问一下，我想不足10条的时候，不开启上拉加载，也不回弹，也不显示noMore的样式？
_refreshController.finishLoad(success: false, noMore: true);
 onLoad: () => null
这样还是有回调，并把noMore 样式也展示了

**Comment by xuelongqy** [comment]
v3已发布，也许问题得到解决。如果问题依然存在，请重新打开
