### ISSUE TITLE
EasyRefreshPhysics.applyBoundaryConditions returned invalid overscroll value.

### ISSUE THREAD

**Issue by FLEasy** [xuelongqy/flutter_easyrefresh#499]
使用firstRefresh 第一次进入页面 会抛出这个异常

======== Exception caught by animation library =====================================================
The following assertion was thrown while notifying listeners for AnimationController:
EasyRefreshPhysics.applyBoundaryConditions returned invalid overscroll value.

The method was called to consider a change from 19.285951702427987 to 11.609774639312807, which is a delta of -7.7 units. However, it returned an overscroll of 11.6 units, which has a greater magnitude than the delta. The applyBoundaryConditions method is only supposed to reduce the possible range of movement, not increase it.
The scroll extents are 0.0 .. 0.0, and the viewport dimension is 731.0533333333333.
When the exception was thrown, this was the stack: 
#0      ScrollPosition.applyBoundaryConditions.<anonymous closure> (package:flutter/src/widgets/scroll_position.dart:477:9)
#1      ScrollPosition.applyBoundaryConditions (package:flutter/src/widgets/scroll_position.dart:489:6)
#2      ScrollPosition.setPixels (package:flutter/src/widgets/scroll_position.dart:259:33)
#3      ScrollPositionWithSingleContext.setPixels (package:flutter/src/widgets/scroll_position_with_single_context.dart:82:18)
#4      BallisticScrollActivity.applyMoveTo (package:flutter/src/widgets/scroll_activity.dart:566:21)
...
The AnimationController notifying listeners was: AnimationController#4a13d(▶ 11.610; for BallisticScrollActivity)
====================================================================================================

**Comment by 5115191** [comment]
extended.NestedScrollView嵌套出现同样的问题

**Comment by xuelongqy** [comment]
v3已发布，也许问题得到解决。如果问题依然存在，请重新打开
