### ISSUE TITLE
autoLoad与loadMore 冲突

### ISSUE THREAD

**Issue by huclengyue** [xuelongqy/flutter_easyrefresh#5]
设置`autoLoad: true,`同时设置`loadMore:null`
这时候滑动到底部，UI界面就会卡主，同时报错:
![33c0b654f323475596a8e8e32218517b](https://user-images.githubusercontent.com/9107717/50438154-ae0d6a00-0927-11e9-8e37-c99455e49c8b.jpg)

**Comment by xuelongqy** [comment]
v1.0.7已解决
