### ISSUE TITLE
NestedScrollView+TabBarView里，滑动过程中，偶尔会出现界面卡死的问题

### ISSUE THREAD

**Issue by caihua** [xuelongqy/flutter_easyrefresh#50]
loadMore: () async {
        print("loadMore $this");
        setState(() {
          for (var i = 0; i < 10; i++) {
            strGrid.addAll(addStrGrid);
          }
        });
 },
我将延时去掉，
列表有大量数据的时候，快速滑动，来回切换tab，偶尔会出现界面不响应的问题。
复现较为困难，偶尔会出现，一旦出现就不停打印出错信息，手指在屏幕上滑动会导致报错信息打印。
怀疑和https://github.com/flutter/flutter/issues/14452 这个问题有关。
打印日志如下：

flutter: loadMore _NestedScrollViewPageState#384a5(ticker inactive)
flutter: loadMore _NestedScrollViewPageState#384a5(ticker inactive)
flutter: ══╡ EXCEPTION CAUGHT BY GESTURE ╞═══════════════════════════════════════════════════════════════════
flutter: The following assertion was thrown while handling a gesture:
flutter: 'package:flutter/src/widgets/scrollable.dart': Failed assertion: line 490 pos 12: '_hold == null':
flutter: is not true.
flutter:
flutter: Either the assertion indicates an error in the framework itself, or we should provide substantially
flutter: more information in this error message to help you determine and fix the underlying cause.
flutter: In either case, please report this assertion by filing a bug on GitHub:
flutter:   https://github.com/flutter/flutter/issues/new?template=BUG.md
flutter:
flutter: When the exception was thrown, this was the stack:
flutter: #2      ScrollableState._handleDragStart 
flutter: #3      DragGestureRecognizer.acceptGesture.<anonymous closure> 
flutter: #4      GestureRecognizer.invokeCallback 
flutter: #5      DragGestureRecognizer.acceptGesture 
flutter: #6      GestureArenaManager._resolveInFavorOf 
flutter: #7      GestureArenaManager._resolve 
flutter: #8      GestureArenaEntry.resolve 
flutter: #9      OneSequenceGestureRecognizer.resolve 
flutter: #10     DragGestureRecognizer.handleEvent 
flutter: #11     PointerRouter._dispatch 
flutter: #12     PointerRouter.route 
flutter: #13     _WidgetsFlutterBinding&BindingBase&GestureBinding.handleEvent 
flutter: #14     _WidgetsFlutterBinding&BindingBase&GestureBinding.dispatchEvent 
flutter: #15     _WidgetsFlutterBinding&BindingBase&GestureBinding._handlePointerEvent 
flutter: #16     _WidgetsFlutterBinding&BindingBase&GestureBinding._flushPointerEventQueue 
flutter: #17     _WidgetsFlutterBinding&BindingBase&GestureBinding._handlePointerDataPacket 
flutter: #21     _invoke1 (dart:ui/hooks.dart:230:10)
flutter: #22     _dispatchPointerDataPacket (dart:ui/hooks.dart:151:5)
flutter: (elided 5 frames from class _AssertionError and package dart:async)
flutter:
flutter: Handler: onStart
flutter: Recognizer:
flutter:   VerticalDragGestureRecognizer#e09ac(start behavior: start)
flutter: ════════════════════════════════════════════════════════════════════════════════════════════════════
flutter: Another exception was thrown: 'package:flutter/src/widgets/scrollable.dart': Failed assertion: line 495 pos 12: '_hold == null || _drag == null': is not true.
flutter: Another exception was thrown: 'package:flutter/src/widgets/scrollable.dart': Failed assertion: line 495 pos 12: '_hold == null || _drag == null': is not true.
flutter: Another exception was thrown: 'package:flutter/src/widgets/scrollable.dart': Failed assertion: line 495 pos 12: '_hold == null || _drag == null': is not true.
flutter: Another exception was thrown: 'package:flutter/src/widgets/scrollable.dart': Failed assertion: line 495 pos 12: '_hold == null || _drag == null': is not true.
flutter: Another exception was thrown: 'package:flutter/src/widgets/scrollable.dart': Failed assertion: line 495 pos 12: '_hold == null || _drag == null': is not true.
flutter: Another exception was thrown: 'package:flutter/src/widgets/scrollable.dart': Failed assertion: line 495 pos 12: '_hold == null || _drag == null': is not true.
flutter: Another exception was thrown: 'package:flutter/src/widgets/scrollable.dart': Failed assertion: line 501 pos 12: '_hold == null || _drag == null': is not true.
flutter: loadMore _NestedScrollViewPageState#384a5(ticker inactive)
flutter: Another exception was thrown: 'package:flutter/src/widgets/scrollable.dart': Failed assertion: line 478 pos 12: '_drag == null': is not true.
flutter: Another exception was thrown: 'package:flutter/src/widgets/scrollable.dart': Failed assertion: line 487 pos 12: '_drag == null': is not true.
flutter: Another exception was thrown: 'package:flutter/src/widgets/scrollable.dart': Failed assertion: line 495 pos 12: '_hold == null || _drag == null': is not true.
flutter: Another exception was thrown: 'package:flutter/src/widgets/scrollable.dart': Failed assertion: line 495 pos 12: '_hold == null || _drag == null': is not true.
flutter: Another exception was thrown: 'package:flutter/src/widgets/scrollable.dart': Failed assertion: line 495 pos 12: '_hold == null || _drag == null': is not true.
flutter: Another exception was thrown: 'package:flutter/src/widgets/scrollable.dart': Failed assertion: line 495 pos 12: '_hold == null || _drag == null': is not true.
flutter: Another exception was thrown: 'package:flutter/src/widgets/scrollable.dart': Failed assertion: line 495 pos 12: '_hold == null || _drag == null': is not true.
flutter: Another exception was thrown: 'package:flutter/src/widgets/scrollable.dart': Failed assertion: line 501 pos 12: '_hold == null || _drag == null': is not true.
flutter: Another exception was thrown: 'package:flutter/src/widgets/scrollable.dart': Failed assertion: line 478 pos 12: '_drag == null': is not true.
flutter: Another exception was thrown: 'package:flutter/src/widgets/scrollable.dart': Failed assertion: line 487 pos 12: '_drag == null': is not true.
flutter: Another exception was thrown: 'package:flutter/src/widgets/scrollable.dart': Failed assertion: line 495 pos 12: '_hold == null || _drag == null': is not true.
flutter: Another exception was thrown: 'package:flutter/src/widgets/scrollable.dart': Failed assertion: line 495 pos 12: '_hold == null || _drag == null': is not true.
flutter: Another exception was thrown: 'package:flutter/src/widgets/scrollable.dart': Failed assertion: line 495 pos 12: '_hold == null || _drag == null': is not true.
flutter: Another exception was thrown: 'package:flutter/src/widgets/scrollable.dart': Failed assertion: line 495 pos 12: '_hold == null || _drag == null': is not true.
flutter: Another exception was thrown: 'package:flutter/src/widgets/scrollable.dart': Failed assertion: line 495 pos 12: '_hold == null || _drag == null': is not true.
flutter: Another exception was thrown: 'package:flutter/src/widgets/scrollable.dart': Failed assertion: line 495 pos 12: '_hold == null || _drag == null': is not true.
flutter: Another exception was thrown: 'package:flutter/src/widgets/scrollable.dart': Failed assertion: line 495 pos 12: '_hold == null || _drag == null': is not true.
flutter: Another exception was thrown: 'package:flutter/src/widgets/scrollable.dart': Failed assertion: line 495 pos 12: '_hold == null || _drag == null': is not true.
flutter: Another exception was thrown: 'package:flutter/src/widgets/scrollable.dart': Failed assertion: line 501 pos 12: '_hold == null || _drag == null': is not true.
flutter: Another exception was thrown: 'package:flutter/src/widgets/scrollable.dart': Failed assertion: line 478 pos 12: '_drag == null': is not true.
flutter: Another exception was thrown: 'package:flutter/src/widgets/scrollable.dart': Failed assertion: line 487 pos 12: '_drag == null': is not true.
flutter: Another exception was thrown: 'package:flutter/src/widgets/scrollable.dart': Failed assertion: line 495 pos 12: '_hold == null || _drag == null': is not true.
flutter: Another exception was thrown: 'package:flutter/src/widgets/scrollable.dart': Failed assertion: line 495 pos 12: '_hold == null || _drag == null': is not true.
flutter: Another exception was thrown: 'package:flutter/src/widgets/scrollable.dart': Failed assertion: line 495 pos 12: '_hold == null || _drag == null': is not true.
flutter: Another exception was thrown: 'package:flutter/src/widgets/scrollable.dart': Failed assertion: line 495 pos 12: '_hold == null || _drag == null': is not true.
flutter: Another exception was thrown: 'package:flutter/src/widgets/scrollable.dart': Failed assertion: line 495 pos 12: '_hold == null || _drag == null': is not true.
flutter: Another exception was thrown: 'package:flutter/src/widgets/scrollable.dart': Failed assertion: line 495 pos 12: '_hold == null || _drag == null': is not true.
flutter: Another exception was thrown: 'package:flutter/src/widgets/scrollable.dart': Failed assertion: line 501 pos 12: '_hold == null || _drag == null': is not true.
flutter: Another exception was thrown: 'package:flutter/src/widgets/scrollable.dart': Failed assertion: line 478 pos 12: '_drag == null': is not true.
flutter: Another exception was thrown: 'package:flutter/src/widgets/scrollable.dart': Failed assertion: line 487 pos 12: '_drag == null': is not true.
flutter: Another exception was thrown: 'package:flutter/src/widgets/scrollable.dart': Failed assertion: line 495 pos 12: '_hold == null || _drag == null': is not true.
flutter: Another exception was thrown: 'package:flutter/src/widgets/scrollable.dart': Failed assertion: line 495 pos 12: '_hold == null || _drag == null': is not true.
flutter: Another exception was thrown: 'package:flutter/src/widgets/scrollable.dart': Failed assertion: line 495 pos 12: '_hold == null || _drag == null': is not true.
flutter: Another exception was thrown: 'package:flutter/src/widgets/scrollable.dart': Failed assertion: line 495 pos 12: '_hold == null || _drag == null': is not true.
flutter: Another exception was thrown: 'package:flutter/src/widgets/scrollable.dart': Failed assertion: line 495 pos 12: '_hold == null || _drag == null': is not true.
flutter: Another exception was thrown: 'package:flutter/src/widgets/scrollable.dart': Failed assertion: line 495 pos 12: '_hold == null || _drag == null': is not true.
flutter: Another exception was thrown: 'package:flutter/src/widgets/scrollable.dart': Failed assertion: line 495 pos 12: '_hold == null || _drag == null': is not true.
flutter: Another exception was thrown: 'package:flutter/src/widgets/scrollable.dart': Failed assertion: line 501 pos 12: '_hold == null || _drag == null': is not true.
flutter: Another exception was thrown: 'package:flutter/src/widgets/scrollable.dart': Failed assertion: line 478 pos 12: '_drag == null': is not true.
flutter: Another exception was thrown: 'package:flutter/src/widgets/scrollable.dart': Failed assertion: line 487 pos 12: '_drag == null': is not true.
flutter: Another exception was thrown: 'package:flutter/src/widgets/scrollable.dart': Failed assertion: line 495 pos 12: '_hold == null || _drag == null': is not true.
flutter: Another exception was thrown: 'package:flutter/src/widgets/scrollable.dart': Failed assertion: line 495 pos 12: '_hold == null || _drag == null': is not true.
flutter: Another exception was thrown: 'package:flutter/src/widgets/scrollable.dart': Failed assertion: line 501 pos 12: '_hold == null || _drag == null': is not true.
flutter: Another exception was thrown: 'package:flutter/src/widgets/scrollable.dart': Failed assertion: line 478 pos 12: '_drag == null': is not true.
flutter: Another exception was thrown: 'package:flutter/src/widgets/scrollable.dart': Failed assertion: line 487 pos 12: '_drag == null': is not true.
flutter: Another exception was thrown: 'package:flutter/src/widgets/scrollable.dart': Failed assertion: line 495 pos 12: '_hold == null || _drag == null': is not true.
flutter: Another exception was thrown: 'package:flutter/src/widgets/scrollable.dart': Failed assertion: line 495 pos 12: '_hold == null || _drag == null': is not true.
flutter: Another exception was thrown: 'package:flutter/src/widgets/scrollable.dart': Failed assertion: line 495 pos 12: '_hold == null || _drag == null': is not true.
flutter: Another exception was thrown: 'package:flutter/src/widgets/scrollable.dart': Failed assertion: line 495 pos 12: '_hold == null || _drag == null': is not true.
flutter: Another exception was thrown: 'package:flutter/src/widgets/scrollable.dart': Failed assertion: line 495 pos 12: '_hold == null || _drag == null': is not true.
flutter: Another exception was thrown: 'package:flutter/src/widgets/scrollable.dart': Failed assertion: line 495 pos 12: '_hold == null || _drag == null': is not true.
flutter: Another exception was thrown: 'package:flutter/src/widgets/scrollable.dart': Failed assertion: line 501 pos 12: '_hold == null || _drag == null': is not true.
flutter: Another exception was thrown: 'package:flutter/src/widgets/scrollable.dart': Failed assertion: line 478 pos 12: '_drag == null': is not true.
flutter: Another exception was thrown: 'package:flutter/src/widgets/scrollable.dart': Failed assertion: line 487 pos 12: '_drag == null': is not true.
flutter: Another exception was thrown: 'package:flutter/src/widgets/scrollable.dart': Failed assertion: line 495 pos 12: '_hold == null || _drag == null': is not true.
flutter: Another exception was thrown: 'package:flutter/src/widgets/scrollable.dart': Failed assertion: line 495 pos 12: '_hold == null || _drag == null': is not true.
flutter: Another exception was thrown: 'package:flutter/src/widgets/scrollable.dart': Failed assertion: line 495 pos 12: '_hold == null || _drag == null': is not true.
flutter: Another exception was thrown: 'package:flutter/src/widgets/scrollable.dart': Failed assertion: line 495 pos 12: '_hold == null || _drag == null': is not true.
flutter: Another exception was thrown: 'package:flutter/src/widgets/scrollable.dart': Failed assertion: line 495 pos 12: '_hold == null || _drag == null': is not true.
flutter: Another exception was thrown: 'package:flutter/src/widgets/scrollable.dart': Failed assertion: line 495 pos 12: '_hold == null || _drag == null': is not true.
flutter: Another exception was thrown: 'package:flutter/src/widgets/scrollable.dart': Failed assertion: line 495 pos 12: '_hold == null || _drag == null': is not true.
flutter: Another exception was thrown: 'package:flutter/src/widgets/scrollable.dart': Failed assertion: line 495 pos 12: '_hold == null || _drag == null': is not true.
flutter: Another exception was thrown: 'package:flutter/src/widgets/scrollable.dart': Failed assertion: line 495 pos 12: '_hold == null || _drag == null': is not true.
flutter: Another exception was thrown: 'package:flutter/src/widgets/scrollable.dart': Failed assertion: line 495 pos 12: '_hold == null || _drag == null': is not true.
flutter: Another exception was thrown: 'package:flutter/src/widgets/scrollable.dart': Failed assertion: line 501 pos 12: '_hold == null || _drag == null': is not true.
flutter: Another exception was thrown: 'package:flutter/src/widgets/scrollable.dart': Failed assertion: line 478 pos 12: '_drag == null': is not true.
flutter: Another exception was thrown: 'package:flutter/src/widgets/scrollable.dart': Failed assertion: line 487 pos 12: '_drag == null': is not true.
flutter: Another exception was thrown: 'package:flutter/src/widgets/scrollable.dart': Failed assertion: line 495 pos 12: '_hold == null || _drag == null': is not true.
flutter: Another exception was thrown: 'package:flutter/src/widgets/scrollable.dart': Failed assertion: line 495 pos 12: '_hold == null || _drag == null': is not true.
flutter: Another exception was thrown: 'package:flutter/src/widgets/scrollable.dart': Failed assertion: line 495 pos 12: '_hold == null || _drag == null': is not true.
flutter: Another exception was thrown: 'package:flutter/src/widgets/scrollable.dart': Failed assertion: line 495 pos 12: '_hold == null || _drag == null': is not true.
flutter: Another exception was thrown: 'package:flutter/src/widgets/scrollable.dart': Failed assertion: line 495 pos 12: '_hold == null || _drag == null': is not true.
flutter: Another exception was thrown: 'package:flutter/src/widgets/scrollable.dart': Failed assertion: line 495 pos 12: '_hold == null || _drag == null': is not true.
flutter: Another exception was thrown: 'package:flutter/src/widgets/scrollable.dart': Failed assertion: line 495 pos 12: '_hold == null || _drag == null': is not true.
flutter: Another exception was thrown: 'package:flutter/src/widgets/scrollable.dart': Failed assertion: line 495 pos 12: '_hold == null || _drag == null': is not true.
flutter: Another exception was thrown: 'package:flutter/src/widgets/scrollable.dart': Failed assertion: line 495 pos 12: '_hold == null || _drag == null': is not true.
flutter: Another exception was thrown: 'package:flutter/src/widgets/scrollable.dart': Failed assertion: line 495 pos 12: '_hold == null || _drag == null': is not true.
flutter: Another exception was thrown: 'package:flutter/src/widgets/scrollable.dart': Failed assertion: line 501 pos 12: '_hold == null || _drag == null': is not true.

**Comment by xuelongqy** [comment]
目前EasyRefresh对NestedScrollView的兼容性不是很好，可能会有一些未知的问题
