### ISSUE TITLE
滑动时出现EasyRefreshPhysics.applyBoundaryConditions returned invalid overscroll value.

### ISSUE THREAD

**Issue by 5115191** [xuelongqy/flutter_easyrefresh#500]
使用嵌套

> extended.NestedScrollView

> >tabbar

> >tabbarview

> > >easyrefresh

> > > >SliverStaggeredGrid

滑动列表的时候会出现问题

════════ Exception caught by animation library ═════════════════════════════════════════════════════
The following assertion was thrown while notifying listeners for AnimationController:
EasyRefreshPhysics.applyBoundaryConditions returned invalid overscroll value.

The method was called to consider a change from 658.0656522059727 to 655.7894263747206, which is a delta of -2.3 units. However, it returned an overscroll of 26.7 units, which has a greater magnitude than the delta. The applyBoundaryConditions method is only supposed to reduce the possible range of movement, not increase it.
The scroll extents are 0.0 .. 629.0656522059727, and the viewport dimension is 650.6843477940273.
When the exception was thrown, this was the stack: 
#0      ScrollPosition.applyBoundaryConditions.<anonymous closure> (package:flutter/src/widgets/scroll_position.dart:477:9)
#1      ScrollPosition.applyBoundaryConditions (package:flutter/src/widgets/scroll_position.dart:489:6)
#2      ScrollPosition.setPixels (package:flutter/src/widgets/scroll_position.dart:259:33)
#3      BallisticScrollActivity.applyMoveTo (package:flutter/src/widgets/scroll_activity.dart:552:21)
#4      BallisticScrollActivity._tick (package:flutter/src/widgets/scroll_activity.dart:539:10)
...
The AnimationController notifying listeners was: AnimationController#94c27(▶ 655.789; for BallisticScrollActivity)

**Comment by xuelongqy** [comment]
v3已发布，也许问题得到解决。如果问题依然存在，请重新打开
