### ISSUE TITLE
不能触发下拉刷新的问题

### ISSUE THREAD

**Issue by ShuaiXiu** [xuelongqy/flutter_easyrefresh#502]
Refresh中的widget是Column，column中有一个跑马灯，使用ListView实现的，当添加跑马灯的时候就不能触发下拉刷新事件了

**Comment by alanFri** [comment]
我周五也碰到了这个问题，解决方案是在 ScrollNotificationListener.dart 文件中判断滑动的方向，当滑动为横向时，
_focusState = false;
_focus = true;
即可

**Comment by ShuaiXiu** [comment]
感谢大佬解惑，我目前处于学习阶段还不是很熟练，您的这种修改源码的方式是怎么导入库的，直接下载的源码放到项目里吗？




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年8月9日(星期一) 下午2:08
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [xuelongqy/flutter_easyrefresh] 不能触发下拉刷新的问题 (#502)





 
我周五也碰到了这个问题，解决方案是在 ScrollNotificationListener.dart 文件中判断滑动的方向，当滑动为横向时，
 _focusState = false;
 _focus = true;
 即可
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by alanFri** [comment]
源码导入工程，自己维护

**Comment by ShuaiXiu** [comment]
好的 感谢大佬




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年8月10日(星期二) 下午2:40
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [xuelongqy/flutter_easyrefresh] 不能触发下拉刷新的问题 (#502)





 
源码导入工程，自己维护
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by xuelongqy** [comment]
v3已发布，也许问题得到解决。如果问题依然存在，请重新打开
