### ISSUE TITLE
innerScrollPositionKeyBuilder 响应早于tabController的index改变

### ISSUE THREAD

**Issue by NSLogZfRee** [xuelongqy/flutter_easyrefresh#504]
NestedScrollView body使用tabbar和tabBarView传入tabController,  当tabBarView左右滚动切换时,  innerScrollPositionKeyBuilder的回调中tabController.index错误, tap的时候正确

**Comment by xuelongqy** [comment]
v3已发布，也许问题得到解决。如果问题依然存在，请重新打开
