### ISSUE TITLE
setState() or markNeedsBuild() called during build.

### ISSUE THREAD

**Issue by plumhly** [xuelongqy/flutter_easyrefresh#507]
数据没有到一屏自动刷新会出现这个问题。

 ══╡ EXCEPTION CAUGHT BY FLUTTER FRAMEWORK ╞═════════════════════════════════════════════════════════
flutter: The following assertion was thrown:
flutter: setState() or markNeedsBuild() called during build.
flutter: This EasyRefresh widget cannot be marked as needing to build because the framework is already in the
flutter: process of building widgets.  A widget can be marked as needing to be built during the build phase
flutter: only if one of its ancestors is currently building. This exception is allowed because the framework
flutter: builds parent widgets before children, which means a dirty descendant will always be built.
flutter: Otherwise, the framework might not visit this widget during this build phase.
flutter: The widget on which setState() or markNeedsBuild() was called was:
flutter:   EasyRefresh
flutter: The widget which was currently being built when the offending call was made was:
flutter:   LayoutBuilder
flutter:
flutter: When the exception was thrown, this was the stack:
flutter: #0      Element.markNeedsBuild.<anonymous closure> (package:flutter/src/widgets/framework.dart:4217:11)
flutter: #1      Element.markNeedsBuild (package:flutter/src/widgets/framework.dart:4232:6)
flutter: #2      State.setState (package:flutter/src/widgets/framework.dart:1108:15)
flutter: #3      _EasyRefreshState.initState.<anonymous closure> (package:flutter_easyrefresh/src/refresher.dart:282:9)
flutter: #4      ChangeNotifier.notifyListeners (package:flutter/src/foundation/change_notifier.dart:243:25)
flutter: #5      ValueNotifier.value= (package:flutter/src/foundation/change_notifier.dart:309:5)
flutter: #6      _EasyRefreshSliverRefreshControlState.transitionNextState.goToDone (package:flutter_easyrefresh/src/header/refresh_indicator.dart:726:29)
flutter: #7      _EasyRefreshSliverRefreshControlState.transitionNextState.goToFinish (package:flutter_easyrefresh/src/header/refresh_indicator.dart:737:17)
flutter: #8      _EasyRefreshSliverRefreshControlState.transitionNextState (package:flutter_easyrefresh/src/header/refresh_indicator.dart:831:33)
flutter: #9      _EasyRefreshSliverRefreshControlState.build.<anonymous closure> (package:flutter_easyrefresh/src/header/refresh_indicator.dart:882:26)
flutter: #10     _LayoutBuilderElement._layout.<anonymous closure> (package:flutter/src/widgets/layout_builder.dart:121:31)
flutter: #11     BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2535:19)
flutter: #12     _LayoutBuilderElement._layout (package:flutter/src/widgets/layout_builder.dart:118:12)
flutter: #13     RenderObject.invokeLayoutCallback.<anonymous closure> (package:flutter/src/rendering/object.dart:1889:59)
flutter: #14     PipelineOwner._enableMutationsToDirtySubtrees (package:flutter/src/rendering/object.dart:912:15)
flutter: #15     RenderObject.invokeLayoutCallback (package:flutter/src/rendering/object.dart:1889:14)
flutter: #16     RenderConstrainedLayoutBuilder.rebuildIfNecessary (package:flutter/src/widgets/layout_builder.dart:225:7)
flutter: #17     _RenderLayoutBuilder.performLayout (package:flutter/src/widgets/layout_builder.dart:360:5)
flutter: #18     RenderObject.layout (package:flutter/src/rendering/object.dart:1779:7)
flutter: #19     _RenderEasyRefreshSliverRefresh.performLayout (package:flutter_easyrefresh/src/header/refresh_indicator.dart:253:14)
flutter: #20     RenderObject.layout (package:flutter/src/rendering/object.dart:1779:7)
flutter: #21     _RenderEasyRefreshSliverRefresh.layout (package:flutter_easyrefresh/src/header/refresh_indicator.dart:178:13)
flutter: #22     RenderViewportBase.layoutChildSequence (package:flutter/src/rendering/viewport.dart:510:13)
flutter: #23     RenderViewport._attemptLayout (package:flutter/src/rendering/viewport.dart:1574:12)
flutter: #24     RenderViewport.performLayout (package:flutter/src/rendering/viewport.dart:1483:20)
flutter: #25     RenderObject._layoutWithoutResize (package:flutter/src/rendering/object.dart:1636:7)
flutter: #26     PipelineOwner.flushLayout (package:flutter/src/rendering/object.dart:881:18)
flutter: #27     RendererBinding.drawFrame (package:flutter/src/rendering/binding.dart:462:19)
flutter: #28     WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:876:13)
flutter: #29     RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:328:5)
flutter: #30     SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1144:15)
flutter: #31     SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1082:9)
flutter: #32     SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:998:5)
flutter: #36     _invoke (dart:ui/hooks.dart:163:10)
flutter: #37     PlatformDispatcher._drawFrame (dart:ui/platform_dispatcher.dart:259:5)
flutter: #38     _drawFrame (dart:ui/hooks.dart:126:31)
flutter: (elided 3 frames from dart:async)

**Comment by plumhly** [comment]
https://github.com/xuelongqy/flutter_easyrefresh/issues/405#issuecomment-744349095

**Comment by Jokemac** [comment]
我遇到了同样的问题, 使用自定的header会出现这个报错

**Comment by xuelongqy** [comment]
v3已发布，也许问题得到解决。如果问题依然存在，请重新打开
