### ISSUE TITLE
数据超过一屏内容，上拉不能出现footer内容

### ISSUE THREAD

**Issue by wlingf** [xuelongqy/flutter_easyrefresh#512]
在刷新数据时超过一屏显示且设置controller.finishLoad(noMore: true)时，此时无论怎么上拉都无法让footer内容显示出来，经debug查看,此时没有重新走footer build 方法去重新绘制内容

**Comment by OctMon** [comment]
我也遇到同样的问题

**Comment by xuelongqy** [comment]
v3已发布，也许问题得到解决。如果问题依然存在，请重新打开
