### ISSUE TITLE
使用 Tabar + TabBarView 嵌套 EasyRefresh.custom 显示空白

### ISSUE THREAD

**Issue by yiqulius** [xuelongqy/flutter_easyrefresh#513]
当我使用Tabar + TabBarView 嵌套 EasyRefresh.custom 时, 出现 Unhandled Exception: Null check operator used on a null value
![image](https://user-images.githubusercontent.com/32826579/133218572-73957fa4-0935-4087-ac28-9832d6867254.png)
![image](https://user-images.githubusercontent.com/32826579/133218645-7832bd5e-8f21-4604-8a2d-22bcfb2111d4.png)
![image](https://user-images.githubusercontent.com/32826579/133218984-45533469-c5ce-4c35-a11a-33c0186cd3d3.png)
![image](https://user-images.githubusercontent.com/32826579/133219064-76650327-dd2a-4c37-9dc9-2042384149ee.png)
我想实现下面的效果, 不知道支不支持?
![QQ图片20210914160227](https://user-images.githubusercontent.com/32826579/133219777-76002e01-c2dd-4d31-bc40-11e46d2c1392.jpg)

**Comment by yiqulius** [comment]
![image](https://user-images.githubusercontent.com/32826579/133237121-f311ff40-32a4-432b-93fe-89280c657970.png)
![image](https://user-images.githubusercontent.com/32826579/133237157-01048467-7343-47cf-b8c5-b2a5c0ff5712.png)
当我使用EasyRefresh显示正常, 但是内容无法更新
![image](https://user-images.githubusercontent.com/32826579/133359074-a5fef739-d3a4-4e3b-8dd7-844540d7e7f3.png)
setState方法修改内容没有效果

**Comment by xuelongqy** [comment]
v3已发布，也许问题得到解决。如果问题依然存在，请重新打开

**Comment by frankfancode** [comment]
@yiqulius 你好，空白问题是偶现还是必现
