### ISSUE TITLE
Exception caught by animation library

### ISSUE THREAD

**Issue by anchao-lu** [xuelongqy/flutter_easyrefresh#515]
版本 v2.2.1 仍然存在下面的问题，随机触发的
════════ Exception caught by animation library ═════════════════════════════════
The following assertion was thrown while notifying listeners for AnimationController:
EasyRefreshPhysics.applyBoundaryConditions returned invalid overscroll value.

The method was called to consider a change from 77.05522621990576 to 65.90870477447844, which is a delta of -11.1 units. However, it returned an overscroll of 65.9 units, which has a greater magnitude than the delta. The applyBoundaryConditions method is only supposed to reduce the possible range of movement, not increase it.
The scroll extents are 0.0 .. 0.0, and the viewport dimension is 836.0.
When the exception was thrown, this was the stack
#0      ScrollPosition.applyBoundaryConditions.<anonymous closure>
package:flutter/…/widgets/scroll_position.dart:480
#1      ScrollPosition.applyBoundaryConditions
package:flutter/…/widgets/scroll_position.dart:492
#2      ScrollPosition.setPixels
package:flutter/…/widgets/scroll_position.dart:262
#3      ScrollPositionWithSingleContext.setPixels
package:flutter/…/widgets/scroll_position_with_single_context.dart:82
#4      BallisticScrollActivity.applyMoveTo
package:flutter/…/widgets/scroll_activity.dart:566
#5      BallisticScrollActivity._tick
package:flutter/…/widgets/scroll_activity.dart:553
#6      AnimationLocalListenersMixin.notifyListeners
package:flutter/…/animation/listener_helpers.dart:155
#7      AnimationController._tick
package:flutter/…/animation/animation_controller.dart:829
#8      Ticker._tick
package:flutter/…/scheduler/ticker.dart:238
#9      SchedulerBinding._invokeFrameCallback
package:flutter/…/scheduler/binding.dart:1143
#10     SchedulerBinding.handleBeginFrame.<anonymous closure>
package:flutter/…/scheduler/binding.dart:1056
#11     _LinkedHashMapMixin.forEach (dart:collection-patch/compact_hash.dart:400:8)
#12     SchedulerBinding.handleBeginFrame
package:flutter/…/scheduler/binding.dart:1054
#13     SchedulerBinding._handleBeginFrame
package:flutter/…/scheduler/binding.dart:975
#17     _invoke1 (dart:ui/hooks.dart:185:10)
#18     PlatformDispatcher._beginFrame (dart:ui/platform_dispatcher.dart:248:5)
#19     _beginFrame (dart:ui/hooks.dart:116:31)
(elided 3 frames from dart:async)
The AnimationController notifying listeners was: AnimationController#816b1(▶ 65.909; for BallisticScrollActivity)
════════════════════════════════════════════════════════════════════════════════

**Comment by lan2000** [comment]
我也遇到这个问题。

**Comment by xuelongqy** [comment]
v3已发布，也许问题得到解决。如果问题依然存在，请重新打开

**Comment by dehypnosis** [comment]
still happen with 3.0.4

```
Another exception was thrown:
RangeMaintainingScrollPhysics.applyBoundaryConditions returned
invalid overscroll value.

Another exception was thrown:
RangeMaintainingScrollPhysics.applyBoundaryConditions returned
invalid overscroll value.

Another exception was thrown:
RangeMaintainingScrollPhysics.applyBoundaryConditions returned
invalid overscroll value.

Another exception was thrown:
RangeMaintainingScrollPhysics.applyBoundaryConditions returned
invalid overscroll value.

Another exception was thrown:
RangeMaintainingScrollPhysics.applyBoundaryConditions returned
invalid overscroll value.

Another exception was thrown:
RangeMaintainingScrollPhysics.applyBoundaryConditions returned
invalid overscroll value.

Another exception was thrown:
RangeMaintainingScrollPhysics.applyBoundaryConditions returned
invalid overscroll value.

Another exception was thrown:
RangeMaintainingScrollPhysics.applyBoundaryConditions returned
invalid overscroll value.

Another exception was thrown:
RangeMaintainingScrollPhysics.applyBoundaryConditions returned
invalid overscroll value.

Another exception was thrown:
RangeMaintainingScrollPhysics.applyBoundaryConditions returned
invalid overscroll value.

Another exception was thrown:
RangeMaintainingScrollPhysics.applyBoundaryConditions returned
invalid overscroll value.

Another exception was thrown:
RangeMaintainingScrollPhysics.applyBoundaryConditions returned
invalid overscroll value.

Another exception was thrown:
RangeMaintainingScrollPhysics.applyBoundaryConditions returned
invalid overscroll value.

Another exception was thrown:
RangeMaintainingScrollPhysics.applyBoundaryConditions returned
invalid overscroll value.

Another exception was thrown:
RangeMaintainingScrollPhysics.applyBoundaryConditions returned
invalid overscroll value.

Another exception was thrown:
RangeMaintainingScrollPhysics.applyBoundaryConditions returned
invalid overscroll value.

Another exception was thrown:
RangeMaintainingScrollPhysics.applyBoundaryConditions returned
invalid overscroll value.

Another exception was thrown:
RangeMaintainingScrollPhysics.applyBoundaryConditions returned
invalid overscroll value.

Another exception was thrown:
RangeMaintainingScrollPhysics.applyBoundaryConditions returned
invalid overscroll value.

Another exception was thrown:
RangeMaintainingScrollPhysics.applyBoundaryConditions returned
invalid overscroll value.

Another exception was thrown:
RangeMaintainingScrollPhysics.applyBoundaryConditions returned
invalid overscroll value.

Another exception was thrown:
RangeMaintainingScrollPhysics.applyBoundaryConditions returned
invalid overscroll value.
```

**Comment by xuelongqy** [comment]
> still happen with 3.0.4
> 
> ```
> Another exception was thrown:
> RangeMaintainingScrollPhysics.applyBoundaryConditions returned
> invalid overscroll value.
> 
> Another exception was thrown:
> RangeMaintainingScrollPhysics.applyBoundaryConditions returned
> invalid overscroll value.
> 
> Another exception was thrown:
> RangeMaintainingScrollPhysics.applyBoundaryConditions returned
> invalid overscroll value.
> 
> Another exception was thrown:
> RangeMaintainingScrollPhysics.applyBoundaryConditions returned
> invalid overscroll value.
> 
> Another exception was thrown:
> RangeMaintainingScrollPhysics.applyBoundaryConditions returned
> invalid overscroll value.
> 
> Another exception was thrown:
> RangeMaintainingScrollPhysics.applyBoundaryConditions returned
> invalid overscroll value.
> 
> Another exception was thrown:
> RangeMaintainingScrollPhysics.applyBoundaryConditions returned
> invalid overscroll value.
> 
> Another exception was thrown:
> RangeMaintainingScrollPhysics.applyBoundaryConditions returned
> invalid overscroll value.
> 
> Another exception was thrown:
> RangeMaintainingScrollPhysics.applyBoundaryConditions returned
> invalid overscroll value.
> 
> Another exception was thrown:
> RangeMaintainingScrollPhysics.applyBoundaryConditions returned
> invalid overscroll value.
> 
> Another exception was thrown:
> RangeMaintainingScrollPhysics.applyBoundaryConditions returned
> invalid overscroll value.
> 
> Another exception was thrown:
> RangeMaintainingScrollPhysics.applyBoundaryConditions returned
> invalid overscroll value.
> 
> Another exception was thrown:
> RangeMaintainingScrollPhysics.applyBoundaryConditions returned
> invalid overscroll value.
> 
> Another exception was thrown:
> RangeMaintainingScrollPhysics.applyBoundaryConditions returned
> invalid overscroll value.
> 
> Another exception was thrown:
> RangeMaintainingScrollPhysics.applyBoundaryConditions returned
> invalid overscroll value.
> 
> Another exception was thrown:
> RangeMaintainingScrollPhysics.applyBoundaryConditions returned
> invalid overscroll value.
> 
> Another exception was thrown:
> RangeMaintainingScrollPhysics.applyBoundaryConditions returned
> invalid overscroll value.
> 
> Another exception was thrown:
> RangeMaintainingScrollPhysics.applyBoundaryConditions returned
> invalid overscroll value.
> 
> Another exception was thrown:
> RangeMaintainingScrollPhysics.applyBoundaryConditions returned
> invalid overscroll value.
> 
> Another exception was thrown:
> RangeMaintainingScrollPhysics.applyBoundaryConditions returned
> invalid overscroll value.
> 
> Another exception was thrown:
> RangeMaintainingScrollPhysics.applyBoundaryConditions returned
> invalid overscroll value.
> 
> Another exception was thrown:
> RangeMaintainingScrollPhysics.applyBoundaryConditions returned
> invalid overscroll value.
> ```

can you give an example
