### ISSUE TITLE
使嵌套的 ListView 或者 ScrollView 的 keyboardDismissBehavior 属性失效

### ISSUE THREAD

**Issue by anchao-lu** [xuelongqy/flutter_easyrefresh#518]
比如想要滑动列表时隐藏键盘，嵌套在 flutter_easyrefresh 会失效

**Comment by soxft** [comment]
我在easy_fresh里面使用 listView.builder 不知道为什么报错 null safe相关的问题🥲

**Comment by soxft** [comment]
> 我在easy_fresh里面使用 listView.builder 不知道为什么报错 null safe相关的问题🥲

我服了，重载一下居然好了，debug半天

**Comment by anchao-lu** [comment]
已找到解决办法，如有相同需求可联系我
