### ISSUE TITLE
Null check operator used on a null value

### ISSUE THREAD

**Issue by 1244752609** [xuelongqy/flutter_easyrefresh#519]
我也遇到这个问题，看到2.2.1已经修复这个问题了，但是我这边还是出现了，而且只有ios有问题，Android没问题，最后发现有的页面没问题，一排查是跟其他插件冲突，就是keyboard_actions插件，这个页面用到了直接搜索，为了ios方便关闭键盘才添加的，后面无奈给他去掉了。

**Comment by BurkeDeng** [comment]
I also encountered it, please tell me the solution

**Comment by xuelongqy** [comment]
v3已发布，也许问题得到解决。如果问题依然存在，请重新打开

**Comment by BurkeDeng** [comment]
您好！我是柏源。您的邮件我已收到，我会尽快查看的，谢谢！
