### ISSUE TITLE
在Footer 的 enableInfiniteLoad 设置为 true 时，loadState 只返回一种状态，无法定制多种情况下的展示效果。

### ISSUE THREAD

**Issue by Tinaltt** [xuelongqy/flutter_easyrefresh#523]
在Footer 的 enableInfiniteLoad 设置为 true 时，loadState 只返回一种状态，无法定制多种情况下的展示效果。

版本信息  flutter_easyrefresh: 2.1.8

**Comment by xuelongqy** [comment]
v3已发布，也许问题得到解决。如果问题依然存在，请重新打开
