### ISSUE TITLE
无法在flutter web中拖拽listview和触发下拉刷新

### ISSUE THREAD

**Issue by turingking** [xuelongqy/flutter_easyrefresh#526]
1.首先确定是否为EasyRefresh导致：是，去掉就正常
2.详细描述问题现象：在flutter web中，使用 EasyRefresh 包裹 listview，无法使用鼠标拖拽滑动listview，也无法触发下拉刷新
3.提供有用的报错信息：没有报错
4.提供出现问题的代码示例
``` dart
 @override
  Widget build(BuildContext context) {
    return EasyRefresh(
      child: ListView.builder(
        itemBuilder: (context, index) {
          return ListTile(title: Text("$index"));
        },
      ),
      onRefresh: () async {},
      onLoad: () async {},
    );
  }
```

**Comment by laiiihz** [comment]
flutter 2.5+ 的默认行为就是这样的
https://flutter.cn/docs/release/breaking-changes/default-scroll-behavior-drag#description-of-change

**Comment by laiiihz** [comment]
这是[迁移指南](https://flutter.cn/docs/release/breaking-changes/default-scroll-behavior-drag#migration-guide)

**Comment by Dabbit-Chan** [comment]
Listview里加这两条：
shrinkWrap: true,
physics: NeverScrollableScrollPhysics(),
不然会冲突
