### ISSUE TITLE
希望可以直接设置noMore，而不通过finishLoad或者finishRefresh。

### ISSUE THREAD

**Issue by Akiraqvq** [xuelongqy/flutter_easyrefresh#527]
假设一个列表数据只有一页，首次进入加载即完成了所有数据的加载，此时footer的noMore应为true，但无法通过finishLoad对其进行设置。
若通过callLoad进行首次加载数据，虽然可以触发finishLoad将noMore设置为true，但是不必要的动画、不及时的数据加载会很影响体验。

**Comment by DeliriousLee** [comment]
+1

**Comment by xuelongqy** [comment]
v3已发布，请及时更新

**Comment by ericshi832** [comment]
> v3已发布，请及时更新

仍然有这个问题

**Comment by xuelongqy** [comment]
> > v3已发布，请及时更新
> 
> 仍然有这个问题

EasyRefresh.resetAfterRefresh设置为false
