### ISSUE TITLE
EasyRefresh + TabBarView + [ListView]嵌套如何下拉刷新

### ISSUE THREAD

**Issue by ChunPangWong** [xuelongqy/flutter_easyrefresh#529]
结构是Tabbar + TabBarView + 若干ListView。
需求要在外层下拉刷新，同时刷新若干ListView，所以在最外层嵌套了EasyRefresh。
 但是ListView好像拦截了下拉事件，无法触发EasyRefresh的onRefresh。

**Comment by wf1992** [comment]
大佬怎么改的？发出来看一下？

**Comment by wf1992** [comment]
@ChenPengHuang

**Comment by ChunPangWong** [comment]
自己改了官方RefreshIndicator的widget，把圈圈换成自己的widget了。挺容易改的。
