### ISSUE TITLE
建议将RefreshHeader和RefreshFooter中的finishDelay在子类中暴露出来

### ISSUE THREAD

**Issue by 312223105** [xuelongqy/flutter_easyrefresh#53]
已定义的各种样式，如ClassicsHeader和ClassicsFooter，并不能自定义动画延时，但其父类是有finishDelay在控制的，若要修改该属性，只能复制源码重新实现一个子类。

建议在子类的构造函数中增加finishDelay参数，并传递给父类。

**Comment by xuelongqy** [comment]
是的，因为不同的Header或者Footer可能需要不同的延时去完成动画。并不能满足所有人的需求，所以我的建议是，可以根据自己的需要去进行修改

**Comment by 312223105** [comment]
能否在下一个版本中更新？
