### ISSUE TITLE
关于加载数据重复的问题

### ISSUE THREAD

**Issue by AbeiOS** [xuelongqy/flutter_easyrefresh#532]
## 解决：在 _EasyRefreshSliverLoadControlState 私有类的 _infiniteLoad() 调用时，判断当前 loadState 是否为 inactive。若不是 inactive 则 修改 loadState 为 inactive；

这样是可以解决重复加载的问题，但是有没有更好的方式去解决这个问题？

**Comment by xuelongqy** [comment]
v3已发布，也许问题得到解决。如果问题依然存在，请重新打开
