### ISSUE TITLE
上滑翻页onload时，手指不松开,加载下一页数据，会无限触发footer的onload方法

### ISSUE THREAD

**Issue by Renqianbei** [xuelongqy/flutter_easyrefresh#535]
在出现footer触发刷新，在数据未返回前，手指不离开屏幕。
此时数据返回，更新页面后，会继续触发onload方法，list直接跳到了下一页的底部。

查看源码就是在onLoad结束后，footer一直超出了maxScroll，再次触发onLoad，无限循环导致的

**Comment by lsfern** [comment]
我也遇到了同样的问题。导致同一时间范围内请求了多次接口，返回了多张图片，内存直接爆涨

**Comment by xuelongqy** [comment]
v3已发布，也许问题得到解决。如果问题依然存在，请重新打开

**Comment by Renqianbei** [comment]
我已经解决了这个问题， 作者你的v3并没有修复

**Comment by Renqianbei** [comment]
> v3已发布，也许问题得到解决。如果问题依然存在，请重新打开

我看目前还没有修复，我这边已有解决方案，需要可以提供 （主要是系统ScrollPhysics.adjustPositionForNewDimensions问题）

**Comment by xuelongqy** [comment]
> > v3已发布，也许问题得到解决。如果问题依然存在，请重新打开
> 
> 我看目前还没有修复，我这边已有解决方案，需要可以提供 （主要是系统ScrollPhysics.adjustPositionForNewDimensions问题）

好的，我研究一下。你有好的解决方案，也欢迎贡献代码哦~

**Comment by Renqianbei** [comment]
好的👍
