### ISSUE TITLE
child 为 NestedScrollView 的时候，无法下拉刷新。 往下无法拉动。

### ISSUE THREAD

**Issue by Junesui** [xuelongqy/flutter_easyrefresh#536]
child 为 NestedScrollView 的时候，无法下拉刷新。 往下无法拉动。

**Comment by TigerYao** [comment]
我也遇到这个问题，请问怎么解决

**Comment by TigerYao** [comment]
> child 为 NestedScrollView 的时候，无法下拉刷新。 往下无法拉动。

有解决吗

**Comment by Junesui** [comment]
没有。除了自带刷新换了几个刷新插件都没解决

发自我的iPad

**Comment by xuelongqy** [comment]
v3已发布，也许问题得到解决。如果问题依然存在，请重新打开
