### ISSUE TITLE
列表共用一个EasyRefresh时，列表的偏移量会导致多次load

### ISSUE THREAD

**Issue by Boreals** [xuelongqy/flutter_easyrefresh#537]
![](https://tva1.sinaimg.cn/large/008i3skNgy1gz79n0uzt0j308s0glaah.jpg)
顶上的按钮切换的时候如果切换前的列表加载了第二页的数据，那么切换后的数据会触发第二页的load，目前是重置了列表偏移量解决的，能否通过置空数据来实现

**Comment by xuelongqy** [comment]
可以试试切换页面的时候，用控制器结束。v3已发布，请及时更新，如果问题依然存在，请重新开启
