### ISSUE TITLE
不满一屏如何禁用加载更多

### ISSUE THREAD

**Issue by git-maven** [xuelongqy/flutter_easyrefresh#538]
既然都不满一屏了，肯定没有更多了吧，应该默认要禁用

**Comment by demoYang** [comment]
mark

**Comment by xuelongqy** [comment]
如果有分页可以通过数量判断。提供一个思路，通过position.hasContentDimensions可以判断内容知否满一屏。参考"聊天页面"，也许能给你更多思路。v3已发布，请及时更新
