### ISSUE TITLE
reverse: true, 设置不了noMore的

### ISSUE THREAD

**Issue by justdoitgo** [xuelongqy/flutter_easyrefresh#539]
EasyRefresh.custom(
                          scrollController: _controller,
                          reverse: true,
                          footer: BYClassicalFooter(),
                          onLoad: () async {
                            await getListDate();
                          },
easyRefreshController.finishLoad(success: true, noMore: true);
设置没有更多数据不起作用~

**Comment by xuelongqy** [comment]
v3已发布，也许问题得到解决。如果问题依然存在，请重新打开
