### ISSUE TITLE
上下滚动的时候 出现错误

### ISSUE THREAD

**Issue by BadDeveloper2022** [xuelongqy/flutter_easyrefresh#541]
﻿======== Exception caught by gesture library =======================================================
The following assertion was thrown while routing a pointer event:
The position being added (Offset(221.8, 480.8)) has a smaller timestamp (12:08:50.329541) than its predecessor: _PointAtTime(Offset(221.8, 480.8) at 12:08:50.329542).

When the exception was thrown, this was the stack: 
#0      IOSScrollViewFlingVelocityTracker.addPosition.<anonymous closure> (package:flutter/src/gestures/velocity_tracker.dart:303:7)
#1      IOSScrollViewFlingVelocityTracker.addPosition (package:flutter/src/gestures/velocity_tracker.dart:307:6)
#2      DragGestureRecognizer.handleEvent (package:flutter/src/gestures/monodrag.dart:289:15)
#3      PointerRouter._dispatch (package:flutter/src/gestures/pointer_router.dart:94:12)
#4      PointerRouter._dispatchEventToRoutes.<anonymous closure> (package:flutter/src/gestures/pointer_router.dart:139:9)
#5      _LinkedHashMapMixin.forEach (dart:collection-patch/compact_hash.dart:539:8)
#6      PointerRouter._dispatchEventToRoutes (package:flutter/src/gestures/pointer_router.dart:137:18)
#7      PointerRouter.route (package:flutter/src/gestures/pointer_router.dart:123:7)
#8      GestureBinding.handleEvent (package:flutter/src/gestures/binding.dart:439:19)
#9      GestureBinding.dispatchEvent (package:flutter/src/gestures/binding.dart:419:22)
#10     RendererBinding.dispatchEvent (package:flutter/src/rendering/binding.dart:322:11)
#11     GestureBinding._handlePointerEventImmediately (package:flutter/src/gestures/binding.dart:374:7)
#12     PointerEventResampler._samplePointerPosition (package:flutter/src/gestures/resampler.dart:273:15)
#13     PointerEventResampler.sample (package:flutter/src/gestures/resampler.dart:307:7)
#14     _Resampler.sample (package:flutter/src/gestures/binding.dart:136:17)
#15     GestureBinding._handleSampleTimeChanged (package:flutter/src/gestures/binding.dart:468:20)
#16     _Resampler._onSampleTimeChanged (package:flutter/src/gestures/binding.dart:192:29)
#17     _Resampler.sample.<anonymous closure> (package:flutter/src/gestures/binding.dart:170:9)
#18     SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1144:15)
#19     SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1089:9)
#20     SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:995:5)
#24     _invoke (dart:ui/hooks.dart:151:10)
#25     PlatformDispatcher._drawFrame (dart:ui/platform_dispatcher.dart:308:5)
#26     _drawFrame (dart:ui/hooks.dart:115:31)
(elided 3 frames from dart:async)
====================================================================================================

﻿Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel unknown, 2.10.3, on macOS 12.3 21E230 darwin-x64, locale
    zh-Hans-CN)
[✓] Android toolchain - develop for Android devices (Android SDK version 32.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 13.3)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2021.1)
[✓] Connected device (2 available)
[✓] HTTP Host Availability

**Comment by xuelongqy** [comment]
v3已发布，也许问题得到解决。如果问题依然存在，请重新打开
