### ISSUE TITLE
EasyRefresh 如何嵌套Expanded？

### ISSUE THREAD

**Issue by zystudios** [xuelongqy/flutter_easyrefresh#542]
EasyRefresh(
                  child: Column(
                    children: [
                      ContainerA(),
                      Expanded(
                      SingleChildScrollView(
                        child:   ContainerB(),
                        )         
                      )
                    ],
                  ),
                ),

我的页面上下两个Container，上面ContainerA是固定的，需要下面的ContainerB 能够自适应页面高度，超过的时候可以滚动
不加EasyRefresh 一切正常，
但是这时候想整个页面下拉刷新，加了EasyRefresh会报错 无限高度，这个有什么好的解决办法？

**Comment by bilulanlv** [comment]
我也碰到了这个问题。ListView的高度无法确定。

**Comment by laiiihz** [comment]
里面的内容可以使用CustomScrollView实现

**Comment by yyy000112** [comment]
找到解决方法了吗？遇到pageview组件就不行了，无法确定高度

**Comment by xuelongqy** [comment]
看起来可以参考"聊天页面"的示例。v3已发布，请及时更新
