### ISSUE TITLE
嵌套问题.  最新版本 

### ISSUE THREAD

**Issue by 18363853135** [xuelongqy/flutter_easyrefresh#543]
Container(
        width: MediaQuery.of(context).size.width,
        height: MediaQuery.of(context).size.height,
        child:
            Column(
              children: [
                  
                Text("这不部分是不需要滚动刷新的"),
                EasyRefresh(child: child)
               
              ],
            )
）

**Comment by InTheClodus** [comment]
Expand 包裹就好

**Comment by xuelongqy** [comment]
布局问题哈。v3已发布，请及时更新
