### ISSUE TITLE
footer 无法消失 iPhone 12pro Max  ios15.4

### ISSUE THREAD

**Issue by 18363853135** [xuelongqy/flutter_easyrefresh#546]
<img width="288" alt="image" src="https://user-images.githubusercontent.com/16695187/166625653-f6eca014-3d14-4782-bb91-d0718a11e952.png">
底部无法消失

**Comment by 18363853135** [comment]
往期回复的两种方法，没有更多后： 1.去掉无限加载 2.将onLoad设置为null
上面的截图就是关闭了无线加载后 还是未完全消失
第二种方法onLoad设置为null可行
能否测试第一种方法
出现的场景 1.关闭无线加载 2.列表不足一屏可消失 ,超过一屏幕后footer还是能显示一半

**Comment by 18363853135** [comment]
<img width="310" alt="image" src="https://user-images.githubusercontent.com/16695187/166626582-99eeceee-429a-4d8f-8b2e-6f34f68ab834.png">
这只未关闭无线加载的场景，已调用
         _refreshController.finishLoad(success: true, noMore: true );

**Comment by yyy000112** [comment]
安卓也一样无法消失

**Comment by xuelongqy** [comment]
看起来像是启用无限滚动，但新数据的内容不够长的问题，如果没有更多，请设置为noMore。v3已发布，也许问题得到解决。如果问题依然存在，请重新打开。
