### ISSUE TITLE
下拉刷新有条白线，这个怎么处理，如图

### ISSUE THREAD

**Issue by pigheartCN** [xuelongqy/flutter_easyrefresh#547]
![image](https://user-images.githubusercontent.com/26181029/167253000-6a94fe17-2e60-4d83-a789-8d44222c40e5.png)
![image](https://user-images.githubusercontent.com/26181029/167253047-23e2ca8f-da37-4bcf-a1f3-36e544bb18cf.png)
![image](https://user-images.githubusercontent.com/26181029/167253058-bd66878c-f415-49a2-a11d-7295e5a0769b.png)

**Comment by xuelongqy** [comment]
这是Flutter的一直以来的问题。使用v3也许能解决你的问题，如果需要加背景颜色，可以参考"个人中心"的示例处理白线。原理是使用Stack越界1单位像素，并不做抗锯齿处理
