### ISSUE TITLE
Cannot able to pull to refresh in Flutter Macos

### ISSUE THREAD

**Issue by good-good-study** [xuelongqy/flutter_easyrefresh#549]
flutter build in macos and web ,  Flutter3 , Connot to pull to refresh and load more. 

<img width="734" alt="截屏2022-05-14 22 21 47" src="https://user-images.githubusercontent.com/20188392/168429816-8f2611d8-476e-442f-9da3-79b667846ba5.png">

**Comment by good-good-study** [comment]
flutter_easyrefresh: ^2.2.1

**Comment by wosika** [comment]
+1

**Comment by laiiihz** [comment]
please migrate your app with [default-scroll-behavior-drag](https://flutter.cn/docs/release/breaking-changes/default-scroll-behavior-drag#migration-guide).
I think desktop platform should provider a refresh button to refresh the content.  same issue #544

**Comment by xuelongqy** [comment]
v3 has been released, please update in time
