### ISSUE TITLE
Unhandled Exception: A ValueNotifier<double> was used after being disposed. Once you have called dispose() on a ValueNotifier<double>, it can no longer be used.

### ISSUE THREAD

**Issue by xieyuhai** [xuelongqy/flutter_easyrefresh#550]
[VERBOSE-2:ui_dart_state.cc(209)] Unhandled Exception: A ValueNotifier<double> was used after being disposed.
Once you have called dispose() on a ValueNotifier<double>, it can no longer be used.
#0      ChangeNotifier._debugAssertNotDisposed.<anonymous closure> (package:flutter/src/foundation/change_notifier.dart:114:9)
#1      ChangeNotifier._debugAssertNotDisposed (package:flutter/src/foundation/change_notifier.dart:120:6)
#2      ChangeNotifier.notifyListeners (package:flutter/src/foundation/change_notifier.dart:288:12)
#3      ValueNotifier.value= (package:flutter/src/foundation/change_notifier.dart:412:5)
#4      _RenderEasyRefreshSliverLoad.performLayout (package:flutter_easyrefresh/src/footer/load_indicator.dart:176:25)
#5      RenderObject.layout (package:flutter/src/rendering/object.dart:1887:7)
#6      RenderSliverEdgeInsetsPadding.performLayout (package:flutter/src/rendering/sliver_padding.dart:137:12)
#7      RenderSliverPadding.performLayout (package:flutter/src/rendering/sliver_padding.dart:371:11)

**Comment by xuelongqy** [comment]
v3 has been released, please update in time

**Comment by xieyuhai** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by xieyuhai** [comment]
thank you!
