### ISSUE TITLE
Please set controlFinishLoad to true, then use.

### ISSUE THREAD

**Issue by fireyy** [xuelongqy/flutter_easyrefresh#563]
https://github.com/xuelongqy/flutter_easy_refresh/blob/327578992ed17d197d18adb12cb5f2a098833447/lib/src/controller/controller.dart#L184

这里应该是 assert controlFinishLoad 吧

**Comment by xuelongqy** [comment]
非常感谢，将在下个版本修复

**Comment by xuelongqy** [comment]
v3.0.1已修复
