### ISSUE TITLE
在main.dart中设置EasyRefresh.defaultHeaderBuilder失效

### ISSUE THREAD

**Issue by jahnli** [xuelongqy/flutter_easyrefresh#564]
在main.dart中设置EasyRefresh.defaultHeaderBuilder失效，国际化不起作用

**Comment by jahnli** [comment]
void _configRefreshLocal() {
  EasyRefresh.defaultHeaderBuilder = () => ClassicHeader(
        dragText: 'Pull to refresh'.tr,
        armedText: 'Release ready'.tr,
        readyText: 'Refreshing...'.tr,
        processingText: 'Refreshing...'.tr,
        processedText: 'Succeeded'.tr,
        noMoreText: 'No more'.tr,
        failedText: 'Failed'.tr,
        messageText: 'Last updated at %T'.tr,
      );
  EasyRefresh.defaultFooterBuilder = () => ClassicFooter(
        dragText: 'Pull to load'.tr,
        armedText: 'Release ready'.tr,
        readyText: 'Loading...'.tr,
        processingText: 'Loading...'.tr,
        processedText: 'Succeeded'.tr,
        noMoreText: 'No more'.tr,
        failedText: 'Failed'.tr,
        messageText: 'Last updated at %T'.tr,
      );
}

**Comment by xuelongqy** [comment]
这是getx的哈，可以参考一下getx的国际化配置。但不局限国际化框架

**Comment by jahnli** [comment]
我用的也是gtex，main里面全局设置不生效，，只有单个header或者footer才行

**Comment by xuelongqy** [comment]
_configRefreshLocal被调用了吗？

**Comment by jahnli** [comment]
调用了

**Comment by jahnli** [comment]
依旧是不生效的

**Comment by xuelongqy** [comment]
示例没有问题哈，看起来不是EasyRefresh的问题。暂时帮不了你，可以通过加QQ群获取帮助。建议检查一下国际化的配置，希望你的问题能够及时解决

**Comment by zwind007** [comment]
这个问题有解决办法了吗？一样，全局设置不生效。

**Comment by zwind007** [comment]
> 这个问题有解决办法了吗？一样，全局设置不生效。

解决了，使用方法的问题，通过调试找出了原因，widget.header为空时才使用默认的_defaultHeader，注释掉列表组件里的header和footer就行了：
` EasyRefresh(
              controller: _.refreshController,
              // header: const ClassicHeader(clamping: false),
              // footer: const ClassicFooter(clamping: false),
              onRefresh: () => _.getRoomList(isRefresh: true),
              onLoad: () => _.getRoomList(isRefresh: false),
              child: CustomScrollView(...))`
`/// Use [EasyRefresh._defaultHeader] without [EasyRefresh.header].
  /// Use [NotRefreshHeader] when [EasyRefresh.onRefresh] is null.
  Header get _header {
    if (widget.onRefresh == null) {
      if (widget.notRefreshHeader != null) {
        return widget.notRefreshHeader!;
      } else {
        final h = widget.header ?? EasyRefresh._defaultHeader;
        return NotRefreshHeader(
          clamping: h.clamping,
          position: h.position,
          spring: h.spring,
          frictionFactor: h.frictionFactor,
        );
      }
    } else {
      Header h = widget.header ?? EasyRefresh._defaultHeader;
      if (_isRefreshOnStart) {
        h = widget.refreshOnStartHeader ?? h;
      }
      return h;
    }
  }`
