### ISSUE TITLE
Grid 不满一屏无法触发 onRefresh

### ISSUE THREAD

**Issue by moxc** [xuelongqy/flutter_easyrefresh#565]
在 example 中  nested_scroll_view.dart , _gridCount 改小以后可以复现。

**Comment by xuelongqy** [comment]
NestedScrollView的问题很多，如非必要，不建议结合NestedScrollView使用。后续看看有不有好的解决办法吧

**Comment by xuelongqy** [comment]
可参考这个[示例](https://github.com/xuelongqy/flutter_easy_refresh/blob/v3/example/lib/page/sample/tab_bar_view_page.dart)
