### ISSUE TITLE
flutter_easyrefresh: ^2.2.2 直接迁移到最新版本会报错

### ISSUE THREAD

**Issue by FLEasy** [xuelongqy/flutter_easyrefresh#566]
<img width="1352" alt="image" src="https://user-images.githubusercontent.com/15194292/178447803-ed344fb6-63c4-494f-84da-2b66008c2a1d.png">
直接迁移过来修改了报错的位置之后，会有这样的报错，是否有迁移的一些注意事项可以提供一下
'package:easy_refresh/src/indicator/indicator.dart': Failed assertion: line 369 pos 16: 'infiniteOffset == null || !clamping': Cannot scroll indefinitely when clamping.

**Comment by xuelongqy** [comment]
全新的架构哈，使用会不一样。但功能并不多，所以暂不提供迁文档。这个错误的意识是不能同时使用，很直面了哈。要么无限滚动，要么指示器悬浮
