### ISSUE TITLE
数据请求回来了，怎么结束下拉刷新或上拉加载

### ISSUE THREAD

**Issue by stoneUoU** [xuelongqy/flutter_easyrefresh#57]

**Comment by xuelongqy** [comment]
两种方式。1.使用方法异步内等待同步，可以自动结束；2.调用结束方法，你可以参考相关示例

**Comment by stoneUoU** [comment]
没找到结束方法，还有个问题：我配置这个noMoreText: "暂无更多数据",每次上拉加载完成后都会显示，其实数据库中还有好多数据

**Comment by xuelongqy** [comment]
如果 异步方法，没有使用await去等待异步请求，有可能出现这个问题。异步中再使用异步，EasyRefresh无法获取方法的结束时机是不准确的
