### ISSUE TITLE
How to remove the default footer?

### ISSUE THREAD

**Issue by sedbytes** [xuelongqy/flutter_easyrefresh#573]
Is it possible to use `EasyRefresh` without specifying a footer at all?

Currently, If we set the `footer` param to `null`. It falls back to the default `ClassicFooter` which is undesirable in my case.

**Comment by xuelongqy** [comment]
Try onLoad: null?

**Comment by xuelongqy** [comment]
BuilderFooter => returen SizedBox();

**Comment by sedbytes** [comment]
> Try onLoad: null?

This worked, thanks. I thought `onLoad` is the same as `onRefresh` 😅
