### ISSUE TITLE
flutter sdk 2.8.1 抛出错误 Theme.of(context).textTheme.titleMedium,

### ISSUE THREAD

**Issue by StellanFan** [xuelongqy/flutter_easyrefresh#577]
`/F:/flutter%20Sdk/2.8.1/.pub-cache/hosted/pub.flutter-io.cn/easy_refresh-3.0.2+2/lib/src/styles/classic/classic_indicator.dart:358:66: Error: The getter 'titleMedium' isn't defined for the class 'TextTheme'.
 - 'TextTheme' is from 'package:flutter/src/material/text_theme.dart' ('/F:/flutter%20Sdk/2.8.1/packages/flutter/lib/src/material/text_theme.dart').
Try correcting the name to the name of an existing getter, or defining a getter or field named 'titleMedium'.
          style: widget.textStyle ?? Theme.of(context).textTheme.titleMedium,
                                                                                           ^^^^^^^^^^^
/F:/flutter%20Sdk/2.8.1/.pub-cache/hosted/pub.flutter-io.cn/easy_refresh-3.0.2+2/lib/src/styles/cupertino/cupertino_indicator.dart:111:13: Error: No named parameter with the name 'color'.
            color: widget.foregroundColor,
            ^^^^^
/F:/flutter%20Sdk/2.8.1/packages/flutter/lib/src/cupertino/activity_indicator.dart:44:9: Context: Found this candidate, but the arguments don't match.
  const CupertinoActivityIndicator.partiallyRevealed({
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
/F:/flutter%20Sdk/2.8.1/.pub-cache/hosted/pub.flutter-io.cn/easy_refresh-3.0.2+2/lib/src/styles/cupertino/cupertino_indicator.dart:121:11: Error: No named parameter with the name 'color'.
          color: widget.foregroundColor,
          ^^^^^
/F:/flutter%20Sdk/2.8.1/packages/flutter/lib/src/cupertino/activity_indicator.dart:28:9: Context: Found this candidate, but the arguments don't match.
  const CupertinoActivityIndicator({
        ^^^^^^^^^^^^^^^^^^^^^^^^^^
/F:/flutter%20Sdk/2.8.1/.pub-cache/hosted/pub.flutter-io.cn/easy_refresh-3.0.2+2/lib/src/styles/cupertino/cupertino_indicator.dart:128:11: Error: No named parameter with the name 'color'.
          color: widget.foregroundColor,
          ^^^^^
/F:/flutter%20Sdk/2.8.1/packages/flutter/lib/src/cupertino/activity_indicator.dart:28:9: Context: Found this candidate, but the arguments don't match.
  const CupertinoActivityIndicator({
        ^^^^^^^^^^^^^^^^^^^^^^^^^^
`

**Comment by StellanFan** [comment]
`
import 'package:easy_refresh/easy_refresh.dart';
import 'package:flutter/material.dart';

class Refresh extends StatefulWidget {
  const Refresh({Key? key}) : super(key: key);

  @override
  State<Refresh> createState() => _RefreshState();
}

class _RefreshState extends State<Refresh> {
  late EasyRefreshController _controller;

  @override
  void initState() {
    super.initState();
    _controller = EasyRefreshController(
      controlFinishRefresh: true,
      controlFinishLoad: true,
    );
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: const Text('下拉刷新'),
        centerTitle: true,
      ),
      body: Container(
        color: const Color(0xffededed),
        padding: const EdgeInsets.symmetric(horizontal: 15),
        child: ListView.builder(
          itemBuilder: (BuildContext context, int index) {
            return _item(index);
          },
          itemCount: 15,
        ),
      ),
    );
  }

  Widget _item(int index) {
    return Container(
      width: double.infinity,
      height: 150,
      margin: const EdgeInsets.only(top: 10),
      decoration: BoxDecoration(
        color: Colors.white,
        borderRadius: BorderRadius.circular(8),
      ),
      alignment: Alignment.center,
      child: Text('这是第${index + 1}个item'),
    );
  }
}






















`

**Comment by xuelongqy** [comment]
运行example需要Flutter3.0及以上
