### ISSUE TITLE
FooterLocator滑动时消失了

### ISSUE THREAD

**Issue by git-maven** [xuelongqy/flutter_easyrefresh#584]
EasyRefresh(
        controller: _controller,
        refreshOnStart: true,
        footer: ClassicFooter(
          position: IndicatorPosition.locator,
          dragText: 'Pull to load'.tr,
          armedText: 'Release ready'.tr,
          readyText: 'Loading...'.tr,
          processingText: 'Loading...'.tr,
          processedText: 'Succeeded'.tr,
          noMoreText: 'No more'.tr,
          failedText: 'Failed'.tr,
          messageText: 'Last updated at %T'.tr,
        ),
        refreshOnStartHeader: BuilderHeader(
          triggerOffset: 70,
          clamping: true,
          position: IndicatorPosition.above,
          processedDuration: Duration.zero,
          builder: (ctx, state) {
            if (state.mode == IndicatorMode.inactive ||
                state.mode == IndicatorMode.done) {
              return const SizedBox();
            }
            return Container(
              padding: const EdgeInsets.only(bottom: 100),
              width: double.infinity,
              height: state.viewportDimension,
              alignment: Alignment.center,
              child: SpinKitFadingCube(
                size: 24,
                color: themeData.colorScheme.primary,
              ),
            );
          },
        ),
        onRefresh: () async {
          await Future.delayed(const Duration(seconds: 2));
          if (!mounted) {
            return;
          }
          setState(() {
            _count = 2;
          });
          _controller.finishRefresh();
          _controller.resetFooter();
        },
        onLoad: () async {
          await Future.delayed(const Duration(seconds: 2));
          // if (!mounted) {
          //   return;
          // }
          // setState(() {
          //   _count += 10;
          // });
          _controller.finishLoad(IndicatorResult.noMore);
        },
        child: CustomScrollView(
          slivers: [
            SliverList(
              delegate: SliverChildBuilderDelegate(
                (context, index) {
                  return const SkeletonItem();
                },
                childCount: _count,
              ),
            ),
            FooterLocator.sliver()
          ],
        ),
      ),

当控制器是IndicatorResult.noMore状态时候, 页面list只有2个元素没有铺满屏幕, 这时候就上下滑动listview导致footer会消失, 本人版本还是2.10.5, 使用了footer的clamping会爆红

**Comment by xuelongqy** [comment]
建议看一下Api文档，示例代码还有报错信息中的提示

**Comment by git-maven** [comment]
https://user-images.githubusercontent.com/45022397/183025083-7fc8bbc9-14be-40b3-aa3d-30e251332b42.mp4



> 建议看一下Api文档，示例代码还有报错信息中的提示

看了你的api文档, 试过了很多属性, 还是无法解决这个效果, 请问Footer就是这样设计的嘛, 如何跟着listview滑动不消失呢?

**Comment by seho-dev** [comment]
我是一个column的widget, 用这个组件, 也是出现了同样的问题, nomore不会常驻, 会消失
