### ISSUE TITLE
上拉加载的时候，Succeeded提示不会自动消失

### ISSUE THREAD

**Issue by geniushuix** [xuelongqy/flutter_easyrefresh#585]
Flutter 3.0.1 
easy_refresh: ^3.0.4+1

![WI87V1( 1TP{34(N )EZHZ0](https://user-images.githubusercontent.com/5145971/183240366-f34dd9cc-c6a3-4f1a-bc00-636526b6de65.png)

**Comment by geniushuix** [comment]
补充：我发现这(footer )本来就不会消失，为什么为出现上面的重叠现象，是因为我的 itemBuilder 下面的widget没有指定高度，指定固定的高度就不会出现这种情况了

但是我的 widget 的高度是不固定的，也不太容易确定高度（类似于微博的feed）

请问这有解决办法么？或者是下面这个 footer 不显示

**Comment by geniushuix** [comment]
补充： 用了 NotLoadFooter ，footer 不显示了，但效果不太理想

**Comment by xuelongqy** [comment]
试试FooterLocator？
