### ISSUE TITLE
数据不足时，每次上拉加载都需要往上滚动一下

### ISSUE THREAD

**Issue by jahnli** [xuelongqy/flutter_easyrefresh#588]
onRefresh: () async {
                  controller.updateCcurrentIssuePageIndex(1);
                  await controller.getIssueList();
                  controller.refreshController.finishRefresh();
                  controller.refreshController.resetFooter();
                },
                onLoad: () async {
                  if (controller.pdaIssueListData.list!.length < controller.pdaIssueListData.total!) {
                    controller.updateCcurrentIssuePageIndex(controller.currentIssuePageIndex + 1);
                  }
   
                  await controller.getIssueList();
                  controller.refreshController.finishLoad(
                    controller.pdaIssueListData.list!.length >= controller.pdaIssueListData.total!
                        ? IndicatorResult.noMore
                        : IndicatorResult.success,
                  );
                },

**Comment by jahnli** [comment]
https://user-images.githubusercontent.com/20943608/183430731-1a30db86-6a0c-4dd2-b564-d4012000a1a4.mp4

**Comment by jahnli** [comment]
数据不足时，每次上拉加载都需要往上滚动一下才可以
https://user-images.githubusercontent.com/20943608/183439380-02523b62-6e2a-4457-998f-7d8afe9a1622.mp4

**Comment by jahnli** [comment]
数据不足时，每次上拉加载都需要往上滚动一下才可以
https://user-images.githubusercontent.com/20943608/183439604-fe1fa702-1908-49da-803f-e20aa5c03548.mp4

**Comment by jahnli** [comment]
数据不足时，每次上拉加载都需要往上滚动一下才可以

https://user-images.githubusercontent.com/20943608/183439732-c0217008-edb2-4d1a-93e7-e1d9bee41336.mp4

**Comment by DaoCaGit** [comment]
我也遇到了这个问题

**Comment by cipchk** [comment]
同样遇到类似的情况 @xuelongqy

**Comment by xuelongqy** [comment]
主分支已经可以了哈，还没发版。如果需要可以直接github方式导入

**Comment by xuelongqy** [comment]
v3.0.4+3 已解决

**Comment by LiWenHui96** [comment]
@xuelongqy 你好，v3.0.4+3 使用了 `SpringDescription`，而 Flutter 2.10.5找不到这个类，无法继续使用了。

**Comment by xuelongqy** [comment]
> @xuelongqy 你好，v3.0.4+3 使用了 `SpringDescription`，而 Flutter 2.10.5找不到这个类，无法继续使用了。

试试v3.0.4+4呢？

**Comment by LiWenHui96** [comment]
@xuelongqy 可以正常使用了。
