### ISSUE TITLE
可以出一个C#版本么

### ISSUE THREAD

**Issue by xuexirong** [xuelongqy/flutter_easyrefresh#589]
现在元宇宙开发很火，很多原生app里面用到unity 3d开发，unity官方出了个uiwidgets插件，是用flutter的方式搭建类原生的页面，他们用c#把flutter重写了一遍，但是他们还没有专门的下拉上拉加载组件，这个需要第三方开发者自己写，就跟咱们现在的easy_refresh一样，或者把现有的第三方翻译成c#，然后直接就能用了。他们现在翻译了flutter 1.x ，现在正在迁移flutter 3.0 ，他们官方技术说预计两个月完成
https://github.com/Unity-Technologies/com.unity.uiwidgets

**Comment by xuelongqy** [comment]
工作量挺大的，目前没有这个计划。如果你感兴趣，何尝不试一试移植呢？
