### ISSUE TITLE
Using with Stream based ListView

### ISSUE THREAD

**Issue by Purus** [xuelongqy/flutter_easyrefresh#59]
Can you please help on using EasyRefresh with a StreamBuilder?

I am fetching data from Firebase using Streams and when I add elements to the ListView, the entire data is duplicated in the view.

Please share the best way to work with Stream data.

**Comment by Purus** [comment]
Any help on this? Is this repo still active?

**Comment by xuelongqy** [comment]
v2 has been refactored
