### ISSUE TITLE
下拉松手之后的处理疑问

### ISSUE THREAD

**Issue by HaijunWei** [xuelongqy/flutter_easyrefresh#593]
下拉超过触发距离，松手之后进入IndicatorMode.ready状态，滚到出发距离的点才回触发onRefresh事件，这样的体验感觉会有一些延迟。
如果加载状态显示的是一个占位图页面，松手大约100毫米后，才能看到占位页面，体验特别不好。

下拉如果超过触发距离，有没方式能设置松手之后直接进入`IndicatorMode.processing`状态呢？

**Comment by xuelongqy** [comment]
可以在ready时就显示哈

**Comment by xuelongqy** [comment]
可以在ready时就显示哈

**Comment by xuelongqy** [comment]
v3.2.0 添加 triggerWhenRelease
