### ISSUE TITLE
下拉时渲染问题

### ISSUE THREAD

**Issue by 309791679** [xuelongqy/flutter_easyrefresh#594]
![e985002aaa75eeb33f6d4f2c052e401](https://user-images.githubusercontent.com/26238458/183853309-1a02bade-7dac-4814-9d59-148353876541.jpg)
![ef8906fe7b6221b3234acdc665982fd](https://user-images.githubusercontent.com/26238458/183853940-6eea8948-bdd1-4255-8121-62185930ecab.jpg)
![40d866bf31298b4926ad43f54551f7e](https://user-images.githubusercontent.com/26238458/183854022-724efda3-985d-4e08-9ca2-e93e5cd8f319.jpg)

当第一次下拉结束时继续下拉就很容易出现这个问题

**Comment by xuelongqy** [comment]
因为状态没有回到inactive？还是说重影的问题？

**Comment by 309791679** [comment]
> 因为状态没有回到inactive？还是说重影的问题？

貌似只有英文才会出现，简单复现就是，当第一次下拉刚刚结束是继续缓慢下拉（两个手指交替下拉），就会出现

**Comment by 309791679** [comment]
> 因为状态没有回到inactive？还是说重影的问题？

#598 帮忙看看这个，影响有点大

现在这个问题我觉得是重影,感觉就是渲染太频繁了

**Comment by xuelongqy** [comment]
我认为EasyRefresh不会导致这样的问题。请确保跟设备是否有关，或者提供详细的信息以及复现代码，你可以随时重新打开此issue。
