### ISSUE TITLE
运行不了 报错

### ISSUE THREAD

**Issue by jack-laowang** [xuelongqy/flutter_easyrefresh#596]
package identifier or launch activity not found.
Please check /Users/halvie/Desktop/flutter_easy_refresh/example/android/app/src/main/AndroidManifest.xml for errors.
No application found for TargetPlatform.android_arm64.
Is your project missing an android/app/src/main/AndroidManifest.xml?
Consider running "flutter create ." to create one.

**Comment by xuelongqy** [comment]
？？？

**Comment by MinchinWang** [comment]
![WechatIMG1696](https://user-images.githubusercontent.com/3407244/184293908-c0415efc-aac6-49ad-96f1-82ffb0274d21.jpeg)
运行main.dart 然后报错，项目运行不了

**Comment by jack-laowang** [comment]
请问下 哪里看最新版本是多少？我看^2.2.2 跟源码版本不一样

**Comment by xuelongqy** [comment]
v3就是最新版本，示例用Flutter3.0编译
