### ISSUE TITLE
列表子项减少后列表跳动

### ISSUE THREAD

**Issue by 309791679** [xuelongqy/flutter_easyrefresh#598]
https://user-images.githubusercontent.com/26238458/184324941-f212a4fa-99a5-491d-bc8e-3169db35431c.mp4
当我在列表最后，删除子项会造成高度变化，按道理说和上拉事件没关系，但会造成这个列表跳动
@xuelongqy

**Comment by 309791679** [comment]
easy_refresh: ^3.0.4+2

**Comment by 309791679** [comment]
@xuelongqy 这个问题能解决不？

**Comment by xuelongqy** [comment]
最新版本应该不在有这个问题
