### ISSUE TITLE
[功能建议] 在 onRefresh 为 null 时，能否禁止下拉滑动？

### ISSUE THREAD

**Issue by linzux** [xuelongqy/flutter_easyrefresh#599]
该功能在 `ListView` 或者 `GridView` 时，可以通过自定义 `ScrollView` 实现

如果碰到 `CustomScrollView` 时，要求使用 `EasyRefresh.builder` 方法，则无法实现自定义的需求。

是否有类似需求的计划呢？

**Comment by xuelongqy** [comment]
notRefreshHeader

**Comment by Junesui** [comment]
> notRefreshHeader

notRefreshHeader 只是没有了头部，但是列表还是可以往下拉的
