### ISSUE TITLE
Getx中使用GetView组装的widget，finishLoad 无法触发noMore情况

### ISSUE THREAD

**Issue by EvanJin** [xuelongqy/flutter_easyrefresh#601]
【理想情况】load more完成触发
![image](https://user-images.githubusercontent.com/1031636/184589433-e75a86ad-e087-4675-8bc8-efb87996f6e9.png)
【使用场景】无法触发noMore结果

【使用版本】v3.0.4+2

  代码使用场景：配合getx使用
【EasyRefresh封装在使用GetView的Widget中】
![image](https://user-images.githubusercontent.com/1031636/184589601-0b9fa71b-912c-4e7c-8712-1a7f57732041.png)

【EasyRefreshController 在 GetController中初始化】
![image](https://user-images.githubusercontent.com/1031636/184589678-b0ac69bd-346f-4f0c-989d-7747f5456410.png)

【断点发现 EashRefreshController 在初始化完成后，发现其中的_state是null】
![image](https://user-images.githubusercontent.com/1031636/184590015-c7c86691-d482-49bf-a9bd-c94c11c9dce9.png)

【result已经是noMore，但是_state为null，导致没有触发更新】
![image](https://user-images.githubusercontent.com/1031636/184591099-0363258b-9072-47aa-bffd-26a96c9e2fba.png)

**Comment by EvanJin** [comment]
已找到原因，关闭

**Comment by ZM0709** [comment]
我也碰见一样问题了，是什么原因能告知一下吗？

**Comment by xyhuangjia** [comment]
> 已找到原因，关闭

大佬怎么解决问题的？get controller 加上tagid？
