### ISSUE TITLE
与Stack组合使用时报错!debugNeedsLayout is not true

### ISSUE THREAD

**Issue by Jambooo** [xuelongqy/flutter_easyrefresh#605]
当我将其放在stack内或与stack同级时，页面渲染会报错!debugNeedsLayout is not true，想请教下您知道是什么原因吗？

![image](https://user-images.githubusercontent.com/30616157/185381898-f250a7ca-713d-4bb6-be0b-cbf50e5caf31.png)
![image](https://user-images.githubusercontent.com/30616157/185382844-42b1fa12-82c7-48d6-bc67-0f0baf4f8730.png)

![image](https://user-images.githubusercontent.com/30616157/185382338-3554ee2a-e6fa-441c-bf64-e4cd0ed0384f.png)

**Comment by Jambooo** [comment]
或者这样看更加直观一些
![image](https://user-images.githubusercontent.com/30616157/185383467-a4a85700-5bfe-48ee-8f93-f18122ceccc3.png)

**Comment by xuelongqy** [comment]
应该是布局问题哈，Stack需要约束，Positioned作为第一项没有明确的大小约束

**Comment by Jambooo** [comment]
确实是我布局问题，给大佬递茶
