### ISSUE TITLE
关于设置disable切换后，onLoad无法正常执行问题

### ISSUE THREAD

**Issue by Jambooo** [xuelongqy/flutter_easyrefresh#608]
参考的ClassicFooter的example写法，当我数据不足一页时，设置disable为true，当我重新获取数据，并设置为false时，onLoad内函数未执行
![image](https://user-images.githubusercontent.com/30616157/186297954-f540ae46-69dc-4cd6-9ca9-a7be160b799d.png)
![image](https://user-images.githubusercontent.com/30616157/186298271-3553f7e8-c52d-4c32-9a0b-53d1240f34ee.png)
![image](https://user-images.githubusercontent.com/30616157/186298323-9b713464-9a19-49e2-8a59-c41a04a5a916.png)

**Comment by Jambooo** [comment]
这是_footerProperties
![image](https://user-images.githubusercontent.com/30616157/186298450-f29e794c-ef6f-4e3b-88fa-5b9c47b8566f.png)
![image](https://user-images.githubusercontent.com/30616157/186298478-b5586c5f-218d-48d9-af46-04e758ea98bf.png)

**Comment by EgoisteEnvie** [comment]
https://github.com/xuelongqy/flutter_easy_refresh/blob/9b9f5ac89e8d21165c65dacd73588395c97a1a8a/lib/src/notifier/indicator_notifier.dart#L535-L539
修改成
```dart
    if (_task == null) {
      if (_mode != IndicatorMode.inactive) {
        _mode = IndicatorMode.inactive;
      }
      return;
    }
```
Debug 发现没有 task 的时候 依旧执行了更新模式代码 导致 Mode 执行成为 armed 状态 无法执行 _onTask 任务

**Comment by xuelongqy** [comment]
3.2.1 已解决
