### ISSUE TITLE
能否在播放完成刷新过渡动画的过程的同时刷新列表

### ISSUE THREAD

**Issue by kidozh** [xuelongqy/flutter_easyrefresh#613]
如标题，我发现新版本的easy_refresh并不像老版本，在执行刷新完成动画的时候就能渲染加载的列表。而是必须等header完全收进去之后才开始渲染列表，但是实际上我在finishRefresh之前已经setState表明列表变更了。

这个虽然不是什么大问题，但是会有一点显得加载比较拖沓，我觉得老版本同时进行的动画挺好的，不太会有顿挫感。

**Comment by xuelongqy** [comment]
应该是可以的吧？
