### ISSUE TITLE
在Easy_refresh 里面有一个横向的listviw，当横向listview滑动到最 左或者最右的时候回触发refresh，或者onload

### ISSUE THREAD

**Issue by imlhk** [xuelongqy/flutter_easyrefresh#615]
[](url)
![image](https://user-images.githubusercontent.com/95897056/187617523-12301219-e9db-48df-9171-70f3fb548b8d.png)
![image](https://user-images.githubusercontent.com/95897056/187617581-4e354100-15c7-4b56-a2dd-7d950148ed73.png)

**Comment by xuelongqy** [comment]
readme中提到的嵌套和作用域
