### ISSUE TITLE
每次加载更多的时候，会将可见区域展示的项目全部build一次

### ISSUE THREAD

**Issue by longren610** [xuelongqy/flutter_easyrefresh#624]
如题！
如果可见区域正好有视频，下拉加载更多的时候，会很明显的重载一次。求指导，如何才能避免已经渲染的项被重载？

https://user-images.githubusercontent.com/26690413/192974919-2c2c56e7-0ae7-4ea7-8f5a-e598191d2999.mp4

**Comment by xuelongqy** [comment]
我感觉这是列表数据变化，所以列表会重建。你应该解决的是列表重建，列表项重构优化。所以问题不是出现在加载操作
