### ISSUE TITLE
和datatable2 出现左拉刷新

### ISSUE THREAD

**Issue by zyk-miao** [xuelongqy/flutter_easyrefresh#625]
主要代码是这样
`
 EasyRefresh(
          onRefresh: _getList,
          // child: SingleChildScrollView(
            child: DataTable2(
              columns: const [
                DataColumn2(label: Text("联系人"),size: ColumnSize.L),
                DataColumn2(label: Text("电话"),size: ColumnSize.L),
              ],
              rows: List<DataRow>.generate(list.length, (index) {
                return DataRow(
                    onSelectChanged: (selected) {
                      setState(() {
                        list[index].selected = selected!;
                      });
                    },
                    selected: list[index].selected,
                    cells: [
                      DataCell(
                        ListTile(
                            title: Text(
                          list[index].booker!,
                        )),
                      ),
                      DataCell(
                        ListTile(
                            title: Text(
                          list[index].phone!,
                        )),
                      )
                    ]);
              }),
            ),
          // ),
        )
`
![图片](https://user-images.githubusercontent.com/45023244/194909093-6e6f1389-2be3-4881-82b2-67e7c6010e9e.png)

**Comment by xuelongqy** [comment]
作用域问题，请查看README中相关说明

**Comment by iOSyan** [comment]
请问这个问题你是怎么解决的呀？我也遇到了。。 @zyk-miao

**Comment by zyk-miao** [comment]
> 

我没有正面解决 最终我没用datatable2
