### ISSUE TITLE
滚动导致AppBar变色

### ISSUE THREAD

**Issue by sfyblack** [xuelongqy/flutter_easyrefresh#632]
滚动时列表时发现AppBar会变成带一些透明度的主题色，想问下这个怎么去掉。
官方的示例也有这个问题，下划的时候AppBar会变成主题色
https://xuelongqy.github.io/flutter_easy_refresh/#/style/classic

* 未滚动时
![未滚动时](https://user-images.githubusercontent.com/58662366/198973611-45031d22-35c3-4a9d-a019-a91af014e766.png)
* 滚动时
![滚动时](https://user-images.githubusercontent.com/58662366/198973612-b59a7f0d-9b59-4e93-8e3a-a18882be20c6.png)

**Comment by xuelongqy** [comment]
Material3 了解一下
