### ISSUE TITLE
请问能判断当前状态是否刷新中吗 

### ISSUE THREAD

**Issue by lixp185** [xuelongqy/flutter_easyrefresh#635]
请问能判断当前状态是否刷新中吗

**Comment by xuelongqy** [comment]
目前可以监听指示器的状态。后续我会加在Controller中，会更方便

**Comment by lixp185** [comment]
👌

**Comment by zhuwei** [comment]
@xuelongqy 不好意思，怎么监听指示器？

**Comment by xuelongqy** [comment]
v3.2.0， EasyRefreshController 添加 headerState, footerState

**Comment by lixp185** [comment]
这是一封自动回复邮件。已经收到您的来信，我会尽快回复。
