### ISSUE TITLE
如果嵌套的Listview的第一个item是横向滚动的列表时会有两个刷新

### ISSUE THREAD

**Issue by WFCN** [xuelongqy/flutter_easyrefresh#636]
页面布局

    EasyRefresh(
                  controller: state.refreshController,
                  onRefresh: () async {
                    logic.onRefresh();
                  },
                  onLoad: state.disableLoad
                      ? null
                      : () async {
                          logic.onLoad();
                        },
                  child: _buildList(logic.state))

    Widget _buildList(HomeAttentionState state) {
    return ListView.builder(
      itemCount: state.dataList.length,
      itemBuilder: (context, index) {
        return _buildItem(state.dataList[index]);
      },
    );
  }

第一个item 的布局

    SingleChildScrollView(
        scrollDirection: Axis.horizontal,
        child: Row(
          crossAxisAlignment: CrossAxisAlignment.start,
          children: _buildLectureList(list),
        ),
      )

**Comment by WFCN** [comment]
不好意思  使用builder好了

**Comment by chenjiangmin** [comment]
遇到同样的问题。 谢谢你。  
用EasyRefresh.builder 解决了。

**Comment by superAndroidMan** [comment]
+1 thanks

**Comment by ZhuSky** [comment]
+1 thanks
