### ISSUE TITLE
3.0.4+3/lib/src/easy_refresh.dart:87:9:报错

### ISSUE THREAD

**Issue by CoderWeiLee** [xuelongqy/flutter_easyrefresh#638]
Error: Type 'SpringDescription' not found.
  final SpringDescription? spring;
        ^^^^^^^^^^^^^^^^^

**Comment by xuelongqy** [comment]
3.0.4+2没问题是吧？Flutter版本是2.10？

**Comment by A1314** [comment]
设备iPhone14.7.1 flutterSDK3.0.5  3.0.4+2试过没问题，但是+3缺失文件SpringDescription

**Comment by xuelongqy** [comment]
试试v3.0.4+4呢？
