### ISSUE TITLE
footer总是在底部不消失

### ISSUE THREAD

**Issue by Young1006** [xuelongqy/flutter_easyrefresh#641]
上拉加载时footer位置不对且不消失
https://user-images.githubusercontent.com/25003571/201893950-ce0e6bcd-dfb5-4c51-9abd-2f64a17caf42.png

return const ClassicFooter(
      key: _footerKey,
      dragText: '上拉加载更多',
      armedText: '加载中...',
      readyText: '加载中...',
      processingText: '加载中...',
      processedText: '加载完成',
      noMoreText: '没有更多了',
      failedText: '加载失败',
      messageText: '最后更新于 %T',
      // safeArea: false,
      // infiniteOffset: null,
      // showMessage: false,
      // showText: false
    );

**Comment by xuelongqy** [comment]
使用FooterLocator
