### ISSUE TITLE
用在ExtendedNestedScrollView上下拉刷新时会报错

### ISSUE THREAD

**Issue by iOSyan** [xuelongqy/flutter_easyrefresh#646]
直接运行demo中tab_bar_view_page，下拉刷新结束后报错 Unhandled Exception: type '_NestedScrollMetrics' is not a subtype of type 'ScrollPosition' in type cast

**Comment by AWarmHug** [comment]
请问一下，你那边会出现刷新一个页面，其他页面也同时刷新的情况吗

**Comment by LiWenHui96** [comment]
> 请问一下，你那一边会出现刷新的一个页面，其他页面也同时刷新的情况吗

使用 `ExtendedNestedScrollView` 解决这个问题

**Comment by lvyandev** [comment]
使用原生的CustomScrollView也会出现这个问题

**Comment by FrankyLee-dev** [comment]
使用ClassicHeader不会有这个错，使用MaterialHeader时会出现。

**Comment by lvyandev** [comment]
> 使用ClassicHeader不会有这个错，使用MaterialHeader时会出现。

就是用的classicHeader
<img width="628" alt="image" src="https://user-images.githubusercontent.com/18045999/206964301-fc3fc55d-3725-4032-b4cd-7473eabab785.png">

**Comment by gujintao1900** [comment]
参考官方类似问题 https://github.com/flutter/flutter/pull/48457/commits/2e3e2c3488f4b83d2b734a58d0f2e28179132fd3 的处理

也许需要 easy_refresh 把 `_position as ScrollPosition` 改成 `_position` 直接用 `ScrollMetrics` 
<img width="1061" alt="image" src="https://user-images.githubusercontent.com/48408513/210994366-ddf9322e-5ede-4f2d-815a-20f6bfdfe56e.png">

![image](https://user-images.githubusercontent.com/48408513/210994828-4d03e815-05c6-4d57-b332-38dcb598df7e.png)

**Comment by gujintao1900** [comment]
使用官方demo 也一样报错 
https://github.com/xuelongqy/flutter_easy_refresh/blob/v3/example/lib/page/sample/tab_bar_view_page.dart

**Comment by WangJiaJun8922** [comment]
遇到同样问题 `Unhandled Exception: type '_NestedScrollMetrics' is not a subtype of type 'ScrollPosition' in type cast`
直接复制官方demo 一样报错。

换成下面的版本 好像就没有问题:
```
  easy_refresh: 3.0.3
  extended_nested_scroll_view: ^5.1.3
```

**Comment by xuelongqy** [comment]
3.3.0+1已修复
