### ISSUE TITLE
垂直滚动的ListView上面加了一个水平的ListView，再给垂直的ListView加上easy_refresh之后，水平的也给自动加上easy_refresh了

### ISSUE THREAD

**Issue by LambGe** [xuelongqy/flutter_easyrefresh#647]
垂直滚动的ListView上面加了一个水平的ListView，再给垂直的ListView加上easy_refresh之后，水平的也给自动加上easy_refresh了，这种情况该怎么解决(我只是想给垂直的ListView加刷新视图，不想给里面的水平滚动的ListView加)

**Comment by xuelongqy** [comment]
看readme的作用区域 使用builder
