### ISSUE TITLE
ios的刷新问题

### ISSUE THREAD

**Issue by zp-techie** [xuelongqy/flutter_easyrefresh#649]
场景：列表上面有个搜索框，等列表上请求到所有数据后，在搜索框输入文字点软键盘上的搜索按钮，我是调用的control.refresh()，安卓没有问题，但是ios不能回调到refresh组件的onRefresh()方法

**Comment by xuelongqy** [comment]
有简单的复现代码片段吗？

**Comment by xuelongqy** [comment]
我无法定位你的问题，如果你后续还遇到这个问题。请附上简单的复现案例，并重新开启此issue
