### ISSUE TITLE
有没有开关控制，是否启用下拉或者上拉

### ISSUE THREAD

**Issue by lyx0224** [xuelongqy/flutter_easyrefresh#656]
版本：2.2.1
业务场景：只需要下拉刷新不需要分页，如果设置？

**Comment by xuelongqy** [comment]
提问前请看注释，看以前的issue。onRefresh和onLoad设置为null即可(https://github.com/xuelongqy/flutter_easy_refresh/issues/653)

**Comment by lyx0224** [comment]
> 提问前请看注释，看以前的issue。onRefresh和onLoad设置为null即可(#653)

❤️
