### ISSUE TITLE
Add Android-like scroll physics

### ISSUE THREAD

**Issue by Pwuts** [xuelongqy/flutter_easyrefresh#660]
The current [`_ERScrollPhysics`](https://github.com/xuelongqy/flutter_easy_refresh/blob/v3/lib/src/physics/scroll_physics.dart) is based on `BouncingScrollPhysics`, which is iOS-like behavior. For Android however, it is a bit strange, and I have not been able to figure out how to implement Android-like scroll behavior that works with this library.

Could you please add Android-like scroll physics as well?

**Comment by xuelongqy** [comment]
Use BouncingScrollPhysics because that's how EasyRefresh works. It is necessary to control the scrolling of the list and display the indicator. In the next version, you can set maxOverOffset and triggerOffset to the same value to limit the maximum overscroll offset.

**Comment by Pwuts** [comment]
I noticed that the physics for bouncing back after overscroll are also applied to the indicator in `drag` mode, so I think I understand what you mean. I'm looking forward to the new features you're mentioning!

**Comment by xuelongqy** [comment]
v3.2.0 add maxOverOffse

**Comment by xuelongqy** [comment]
Boundary scrolling behavior can use ScrollBehavior, or set EasyRefresh.defaultScrollBehaviorBuilder. I think this should be what you need, EasyRefresh will remove the boundary scrolling behavior by default, because it will affect the indicator style.

**Comment by Pwuts** [comment]
I tried using those, but could not figure out how, as they aren't mentioned in the documentation. There are examples, but they are pretty complex, as is the library's source, so unfortunately I could not figure it out from those either.

**Comment by xuelongqy** [comment]
> I tried using those, but could not figure out how, as they aren't mentioned in the documentation. There are examples, but they are pretty complex, as is the library's source, so unfortunately I could not figure it out from those either.

You need to implement ScrollBehavior.buildOverscrollIndicator.

**Comment by xuelongqy** [comment]
If the issue has not been resolved, please reopen.
