### ISSUE TITLE
Demo中TabBarView在Android滑动有回弹问题

### ISSUE THREAD

**Issue by Leheih** [xuelongqy/flutter_easyrefresh#663]
Demo中的expandedHeight我改成了420，其他代码没变。
悬停在顶部之后，下拉时候会有回弹，具体效果见下方视频，iOS没这个问题，是否可以优化。

https://user-images.githubusercontent.com/17791894/210504014-a0b685bc-c9f1-4867-b2e9-d84782ce5ac6.mov

**Comment by xuelongqy** [comment]
请确定是否与Flutter版本有关

**Comment by Leheih** [comment]
好的，好的。目前我Flutter是3.3.9版本，easy_refresh: 3.2.0+1，后面我切换其他版本测试下，谢谢！

**Comment by Leheih** [comment]
尝试切换到Flutter 3.3.0、3.3.9、3.3.10都能复现这个问题。

**Comment by xuelongqy** [comment]
我这边真机Android12没有问题。你有时间的话，试试真机呢，或者切换模拟器的Android版本试试看

**Comment by Leheih** [comment]
https://github.com/fluttercandies/extended_nested_scroll_view/issues/116# 应该是这个原因

**Comment by xuelongqy** [comment]
3.3.1和最新的extended_nested_scroll_view，还有这个问题么？

**Comment by Leheih** [comment]
extended_nested_scroll_view没有处理这个精度问题。
目前我也是把remainingDelta > 0.0改成remainingDelta > precisionErrorTolerance来处理的。
