### ISSUE TITLE
使用ExtendedNestedScrollView，当clamping为ture时报错

### ISSUE THREAD

**Issue by zenganiu** [xuelongqy/flutter_easyrefresh#671]
使用ExtendedNestedScrollView，当clamping为ture时报错，'_NestedScrollMetrics' is not a subtype of type 'ScrollPosition' in type cast
在indicator_notifier文件中_resetBallistic()实现里，ExtendedNestedScrollView里的_position为_NestedScrollMetrics，不是ScrollPosition子类
`    if (clamping && !userOffsetNotifier.value) {
      // Sucks. When clamping, the position will not change after the task is completed.
      // Temporary solution like this, there is a better way to replace.
      double pixels = position.pixels;
      const tiny = 0.001;
      pixels -= tiny;
      (_position as ScrollPosition).jumpTo(pixels);
    }`

**Comment by xuelongqy** [comment]
3.3.0+1已修复
