### ISSUE TITLE
关于IndicatorMode 事件回调疑问

### ISSUE THREAD

**Issue by 309791679** [xuelongqy/flutter_easyrefresh#674]
在实际使用中我发现事件执行状态分别是” IndicatorMode.drag、 IndicatorMode.armed、 IndicatorMode.inactive“

但ui模型中显示了4个状态”IndicatorMode.ready“这个并没有在回调中

就出现我只能可以通过”pullIconBuilder“设置{drag、armed、processed}三个状态的图标, 却没法设置 readyText 文字显示时的图标

dragText:"快了继续拉",armedText: "松手查看全部",readyText:"1正在更新中...",processedText:"更新完成",

**Comment by 309791679** [comment]
@xuelongqy ,我用的版本是最新的 easy_refresh: ^3.3.0+1

调用代码
```
 pullIconBuilder:(BuildContext context, IndicatorState state, double animation){print(state.mode);},

```
整个事件
![image](https://user-images.githubusercontent.com/26238458/216762752-3468c18f-3381-40d1-b0df-1b8a608d4745.png)

**Comment by xuelongqy** [comment]
v3分支最新的代码，你看是对你有帮助

**Comment by xuelongqy** [comment]
状态已添加。如果还有问题，请重新开启此issue
