### ISSUE TITLE
刷新组件出现位置不对

### ISSUE THREAD

**Issue by MyNameIsSkyFly** [xuelongqy/flutter_easyrefresh#675]
在CustomScrollView 有部分横向滚动widget 
然后下拉刷新的时候  刷新组件会从左侧出来
这个怎么解决

**Comment by xuelongqy** [comment]
怎么回事？README第一点特别标注，同一个问题问了很多遍了，之前的issue就能看到，提问前麻烦看文档找相似的issue。这些话不是怼你，是希望开发者们，改掉这些毛病，大家共同进步
