### ISSUE TITLE
ListView 嵌套 GridView 导致刷新出问题

### ISSUE THREAD

**Issue by tang5011235** [xuelongqy/flutter_easyrefresh#677]
return ListView.builder(itemBuilder: (_,__){
        return GridView.count(
          shrinkWrap: true,
          crossAxisCount: 4,
          physics: NeverScrollableScrollPhysics(),
          children: [
            Container(
              color: Colors.blue,
            ),
            Container(
              color: Colors.red,
            ),
            Container(
              color: Colors.green,
            ),
            Container(
              color: Colors.red,
            ),
            Container(
              color: Colors.red,
            ),
          ],
        );
      },itemCount: 10,);

**Comment by xuelongqy** [comment]
请提供详细信息，并重新开启此issue
