### ISSUE TITLE
六同学，你是不是撤回了pub版本？

### ISSUE THREAD

**Issue by qcks** [xuelongqy/flutter_easyrefresh#684]
依赖3.3.0好好的组件，今天打开Demo居然不默认刷新了

**Comment by qcks** [comment]
refreshOnStart: true,确认是打开的

**Comment by qcks** [comment]
之前空数据时显示默认图片，现在子组件必须是ScrollView了，年轻人不讲码德啊
![8ab367dc5aa262d411ecdbabeb4369dc](https://user-images.githubusercontent.com/21257035/220051130-cd5926d1-542b-43c9-bd08-1f4ef9c0f4c0.gif)

**Comment by xuelongqy** [comment]
？？？
