### ISSUE TITLE
EasyRefresh + ExtendedNestedScrollView + TabView 联动问题

### ISSUE THREAD

**Issue by EsZhangHome** [xuelongqy/flutter_easyrefresh#686]
博主你好～
        我这边使用了最新的插件库，按着demo 的样式编写了代码，我使用了EasyRefresh + ExtendedNestedScrollView + TabView，但是当我下滑的时候出现了联动问题，当我下滑刷新，顶部出现了刷新区域，但是同时TabView 的页面也出现了一块区域，我看案例demo中共用了physics ，我尝试不使用一个，发现无法下拉刷新了，这个问题困扰有什么解决建议？
![image](https://user-images.githubusercontent.com/33644433/221067740-c65b7508-9d95-46c0-8655-3f6026e18e0a.png)

**Comment by xuelongqy** [comment]
clamping设置为true试试看

**Comment by xuelongqy** [comment]
这个组合会存在一些目前没有解决的问题，建议少使用，最好和设计沟通一下其他UI方案。可以查看以前的issue，这个问题是讨论最多的

**Comment by EsZhangHome** [comment]
> clamping设置为true试试看
这个设置哪个控件的 clamping ？

**Comment by EsZhangHome** [comment]
> 这个组合会存在一些目前没有解决的问题，建议少使用，最好和设计沟通一下其他UI方案。可以查看以前的issue，这个问题是讨论最多的

**Comment by xuelongqy** [comment]
Header里面 参考示例的写法

**Comment by EsZhangHome** [comment]
> Header里面 参考示例的写法
可以的，我自定义header 的时候把这个属性给舍弃掉了，现在可以了，感谢博主，这个组合只有你的demo能实现，完美～

**Comment by shinedlc** [comment]
> 这个组合会存在一些目前没有解决的问题，建议少使用，最好和设计沟通一下其他UI方案。可以查看以前的issue，这个问题是讨论最多的

perfect，5102年了，找了好大一圈，就这个框架最佳实现了。。。EasyRefresh + ExtendedNestedScrollView + TabView + ListView/SingleScrollView共用了physics解决整个页面滚动问题。
