### ISSUE TITLE
能否提供一个参数，用于设定 header、footer 的状态？

### ISSUE THREAD

**Issue by lihanst** [xuelongqy/flutter_easyrefresh#687]
我需要使用 refreshController 来设置 footer 能否加载更多，我现在是在 build 方法中判断并进行调用。我无法在 onLoad 方法里直接进行调用，因为我的数据流是单向的，调用 loadMore action 不会有返回告知我加载结果。

更符合声明式编程的方式是直接 rebuild，并传入对应的状态。

**Comment by xuelongqy** [comment]
EasyRefreshController.finishLoad(IndicatorResult.noMore) ?

**Comment by xuelongqy** [comment]
如果后续还遇到此问题，请重新开启此issue
