### ISSUE TITLE
The secondary page can't respond to any GestureDetector

### ISSUE THREAD

**Issue by 826327700** [xuelongqy/flutter_easyrefresh#688]
The secondary page can't respond to any GestureDetector. 
Is it not supported GestureDetector ？ or is there a problem with my code？

**Comment by xuelongqy** [comment]
Indeed, I also found this problem. When the secondary page occupies a full screen, the gesture will fail. I’m not sure yet what caused this problem.

**Comment by xuelongqy** [comment]
Related to (https://github.com/xuelongqy/flutter_easy_refresh/pull/714/commits/f7e12a65a9f3c85f753edbfdb6df9f910bd2555c)

**Comment by xuelongqy** [comment]
3.3.1+2 fixed
