### ISSUE TITLE
下拉刷新 header  回不去啊

### ISSUE THREAD

**Issue by zhanglongjiang** [xuelongqy/flutter_easyrefresh#694]
![Simulator Screen Shot - iPhone 14 Pro - 2023-03-08 at 09 53 14](https://user-images.githubusercontent.com/17929221/223598922-53a6ad2d-f58c-4e84-b209-6e4a90d733a3.png)

**Comment by xuelongqy** [comment]
请详细看一下demo，再来提问吧，老哥。而且，你这样提问我怎么帮你

**Comment by gaozongy** [comment]
有同样的问题，布局EasyRefresh -》 CustomScrollView
