### ISSUE TITLE
V3.3.1 onLoad会触发2次以上

### ISSUE THREAD

**Issue by wengxianxun** [xuelongqy/flutter_easyrefresh#695]
如图，配合getx使用，上拉刷新会触发多次。<img width="1482" alt="image" src="https://user-images.githubusercontent.com/831898/224635393-9485ce71-db1f-4bf0-9a2a-301ae954bd17.png">

**Comment by xuelongqy** [comment]
所以，是GetX的问题？还是EasyRefresh的问题？又或者是你本身的代码问题？？这样描述我帮不了你，请提供一个完整的可复现代码示例，重开此issue，谢谢。
