### ISSUE TITLE
现象级的bug，很影响用户操作，发生在嵌套的scrollView情景下。

### ISSUE THREAD

**Issue by ShiChenZhi** [xuelongqy/flutter_easyrefresh#697]
例如ListView嵌套ListView，而刷新主体加在第一层的ListView，子ListView已经禁用了滑动手势等操作。当切换tab后，会不断的在控制台打印触发日志，而且拦截了事件。只要点击屏幕或者拖动一下，就能阻止（不停的）触发事件，而后就能正常操作了。

**Comment by ShiChenZhi** [comment]
当再次切换tab时，又会出现这种情况，如此反复。

**Comment by xuelongqy** [comment]
请看Readme第一点
