### ISSUE TITLE
Collapsing Toolbar

### ISSUE THREAD

**Issue by taliptako** [xuelongqy/flutter_easyrefresh#7]
Hello,
Thank you I really like this package. I tried adding TabBar to your Sliver example [https://github.com/xuelongqy/flutter_easyrefresh/blob/master/example/lib/page/sliver_page.dart](https://github.com/xuelongqy/flutter_easyrefresh/blob/master/example/lib/page/sliver_page.dart)
but when its collapse TabBar also collapsing how can i use this package with SliverAppBar and TabBar both for this i need to use NestedScrollView but i dont know if this package works well with it ?

**Comment by xuelongqy** [comment]
NestedScrollView is not currently supported, but you can use CustomScrollView. Because the NestedScrollView is also internally implemented using CustomScrollView, the same effect can be achieved.
```dart
// This is the implementation of NestedScrollView
List<Widget> _buildSlivers(BuildContext context, ScrollController innerController, bool bodyIsScrolled) {
	final List<Widget> slivers = <Widget>[];
	slivers.addAll(headerSliverBuilder(context, bodyIsScrolled));
	slivers.add(SliverFillRemaining(
	  child: PrimaryScrollController(
		controller: innerController,
		child: body,
	  ),
	));
	return slivers;
}
...
_NestedScrollViewCustomScrollView(
	scrollDirection: widget.scrollDirection,
	reverse: widget.reverse,
	physics: widget.physics != null
		? widget.physics.applyTo(const ClampingScrollPhysics())
		: const ClampingScrollPhysics(),
	controller: _coordinator._outerController,
	slivers: widget._buildSlivers(
	  context,
	  _coordinator._innerController,
	  _lastHasScrolledBody,
	),
	handle: _absorberHandle,
);
...
class _NestedScrollViewCustomScrollView extends CustomScrollView
...
```
NestedScrollView just converts all Widgets into slivers of CustomScrollView

**Comment by taliptako** [comment]
Okay thanks

**Comment by xuelongqy** [comment]
1.2.4 has been able to support NestedScrollView, you can refer to the example [NestedScrollViewPage](https://github.com/xuelongqy/flutter_easyrefresh/blob/master/example/lib/page/sample/nested_scroll_view_page.dart)
