### ISSUE TITLE
列表中有输入框的刷新问题

### ISSUE THREAD

**Issue by 865102930** [xuelongqy/flutter_easyrefresh#703]
当列表中有输入框时,列表默认上下滑动,拖动输入框左右移动能触发左右界面面刷新

 Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBarWidget(title: 'tab_1'.tr,automaticallyImplyLeading: false),
      body: Container(
        color: Colors.red,
        child: EasyRefresh(onRefresh: () {},child: ListView.builder(itemBuilder: (BuildContext context, int index) {
          return Container(
            width: 200,
            height: 100,
            child: TextField(

            ),
          );
        })),
      ),
    );
  }

https://user-images.githubusercontent.com/18364926/230751463-6d85d5da-295c-46ad-baef-3a276b0506ca.mp4

**Comment by 865102930** [comment]
解决了,只能用EasyRefresh.build方法设置physics

**Comment by OneMoreJack** [comment]
你好，我也遇到相同的问题了。
请问你是通过 `EasyRefresh.builder` 解决的？可以再具体点吗？

**Comment by OneMoreJack** [comment]
解决了，可以设置下 TextField 的 scrollPhysics

```dart
TextField(
        /// ...
        scrollPhysics: const ClampingScrollPhysics(),
)
```
