### ISSUE TITLE
3.x 版本如何设置滑动到顶部添加回弹效果

### ISSUE THREAD

**Issue by galen-5** [xuelongqy/flutter_easyrefresh#706]
2.x 版本快速滑动到顶部有回弹效果。 

3.x 版本如何设置画的到顶部添加回弹效果呢？

`scrollBehaviorBuilder: (physics) => ERScrollBehavior(BouncingScrollPhysics()),`
确实有回弹了，但是下拉刷新的功能就没有了。

默认的physics是 `class _ERScrollPhysics extends BouncingScrollPhysics `
设计的时候就考虑到了支持弹簧效果，但是没有生效。

**Comment by xuelongqy** [comment]
试试hitOver = true

**Comment by nxhung1610** [comment]
I use this but not working

> try hitOver = true

any update for this one

**Comment by xuelongqy** [comment]
> I use this but not working
> 
> > try hitOver = true
> 
> any update for this one

If it is clamping, it will not take effect
