### ISSUE TITLE
3.3.1x1版本，flutter 3.10.1版本

### ISSUE THREAD

**Issue by kevin-lemon** [xuelongqy/flutter_easyrefresh#709]
![image](https://user-images.githubusercontent.com/20926872/233072764-0b077000-ed2c-491a-be70-e644c6921590.png)
以上代码，当我使用加载更多时，添加多个item，超出屏幕高度时，底部loading无法关闭。

**Comment by xuelongqy** [comment]
可以试试FooterLocator，列表嵌入的方式

**Comment by xuelongqy** [comment]
Flutter3.10.0 正式版，还有这个问题么

**Comment by kevin-lemon** [comment]
> Flutter3.10.0 正式版，还有这个问题么

暂时没尝试了，更换了插件

**Comment by xuelongqy** [comment]
如果后续问题还存在，请重新开启此issue
