### ISSUE TITLE
Crash when plugin is on a view that that does not initialize completely but is then disposed

### ISSUE THREAD

**Issue by pgulegin** [xuelongqy/flutter_easyrefresh#71]
Please refer to this project: https://github.com/pgulegin/flutter_easyrefresh

Run the application, follow the instructions and it will show the crash.

Basically, I have an application that has a tab bar controller with different views.
If the refresher is on one of those pages, but that page is never actually opened, the refresher will crash with this error:

Launching lib/main.dart on iPhone Xs Max in debug mode...
Xcode build done.                                            9.8s
flutter: ══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
flutter: The following assertion was thrown while finalizing the widget tree:
flutter: ClassicsHeaderState#3d4d9(tickers: tracking 2 tickers) was disposed with an active Ticker.
flutter: ClassicsHeaderState created a Ticker via its TickerProviderStateMixin, but at the time dispose() was
flutter: called on the mixin, that Ticker was still active. All Tickers must be disposed before calling
flutter: super.dispose(). Tickers used by AnimationControllers should be disposed by calling dispose() on the
flutter: AnimationController itself. Otherwise, the ticker will leak.
flutter: The offending ticker was: _WidgetTicker(created by ClassicsHeaderState#3d4d9(lifecycle state:
flutter: created, tickers: tracking 0 tickers))
flutter: The stack trace when the _WidgetTicker was actually created was:
flutter: #0      new Ticker.<anonymous closure> 
flutter: #1      new Ticker 
flutter: #2      new _WidgetTicker 
flutter: #3      _ClassicsHeaderState&RefreshHeaderState&TickerProviderStateMixin.createTicker 
flutter: #4      new AnimationController 
flutter: #5      ClassicsHeaderState.initState
flutter: #6      StatefulElement._firstBuild 
flutter: #7      ComponentElement.mount 
flutter: #8      Element.inflateWidget 
flutter: #9      MultiChildRenderObjectElement.mount 
flutter: #10     Element.inflateWidget 
flutter: #11     MultiChildRenderObjectElement.mount 
flutter: #12     Element.inflateWidget 
flutter: #13     Element.updateChild 
flutter: #14     ComponentElement.performRebuild 
flutter: #15     Element.rebuild 
flutter: #16     ComponentElement._firstBuild 
flutter: #17     ComponentElement.mount 
flutter: #18     Element.inflateWidget 
flutter: #19     Element.updateChild 
flutter: #20     ComponentElement.performRebuild 
flutter: #21     Element.rebuild 
flutter: #22     ComponentElement._firstBuild 
flutter: #23     StatefulElement._firstBuild 
flutter: #24     ComponentElement.mount 
flutter: #25     Element.inflateWidget 
flutter: #26     Element.updateChild 
flutter: #27     ComponentElement.performRebuild 
flutter: #28     Element.rebuild 
flutter: #29     ComponentElement._firstBuild 
flutter: #30     ComponentElement.mount 
flutter: #31     Element.inflateWidget 
flutter: #32     Element.updateChild 
flutter: #33     ComponentElement.performRebuild 
flutter: #34     Element.rebuild 
flutter: #35     ComponentElement._firstBuild 
flutter: #36     ComponentElement.mount 
flutter: #37     Element.inflateWidget 
flutter: #38     Element.updateChild 
flutter: #39     SingleChildRenderObjectElement.mount 
flutter: #40     Element.inflateWidget 
flutter: #41     Element.updateChild 
flutter: #42     ComponentElement.performRebuild 
flutter: #43     Element.rebuild 
flutter: #44     ComponentElement._firstBuild 
flutter: #45     ComponentElement.mount 
flutter: #46     Element.inflateWidget 
flutter: #47     Element.updateChild 
flutter: #48     SingleChildRenderObjectElement.mount 
flutter: #49     Element.inflateWidget 
flutter: #50     Element.updateChild 
flutter: #51     ComponentElement.performRebuild 
flutter: #52     Element.rebuild 
flutter: #53     ComponentElement._firstBuild 
flutter: #54     ComponentElement.mount 
flutter: #55     Element.inflateWidget 
flutter: #56     Element.updateChild 
flutter: #57     ComponentElement.performRebuild 
flutter: #58     Element.rebuild 
flutter: #59     ComponentElement._firstBuild 
flutter: #60     ComponentElement.mount 
flutter: #61     Element.inflateWidget 
flutter: #62     Element.updateChild 
flutter: #63     ComponentElement.performRebuild 
flutter: #64     Element.rebuild 
flutter: #65     ComponentElement._firstBuild 
flutter: #66     ComponentElement.mount 
flutter: #67     ParentDataElement.mount 
flutter: #68     Element.inflateWidget 
flutter: #69     MultiChildRenderObjectElement.mount 
flutter: #70     Element.inflateWidget 
flutter: #71     Element.updateChild 
flutter: #72     ComponentElement.performRebuild 
flutter: #73     Element.rebuild 
flutter: #74     ComponentElement._firstBuild 
flutter: #75     StatefulElement._firstBuild 
flutter: #76     ComponentElement.mount 
flutter: #77     Element.inflateWidget 
flutter: #78     Element.updateChild 
flutter: #79     ComponentElement.performRebuild 
flutter: #80     Element.rebuild 
flutter: #81     ComponentElement._firstBuild 
flutter: #82     ComponentElement.mount 
flutter: #83     Element.inflateWidget 
flutter: #84     Element.updateChild 
flutter: #85     ComponentElement.performRebuild 
flutter: #86     Element.rebuild 
flutter: #87     ComponentElement._firstBuild 
flutter: #88     StatefulElement._firstBuild 
flutter: #89     ComponentElement.mount 
flutter: #90     Element.inflateWidget 
flutter: #91     Element.updateChild 
flutter: #92     SingleChildRenderObjectElement.mount 
flutter: #93     Element.inflateWidget 
flutter: #94     Element.updateChild 
flutter: #95     ComponentElement.performRebuild 
flutter: #96     Element.rebuild 
flutter: #97     ComponentElement._firstBuild 
flutter: #98     ComponentElement.mount 
flutter: #99     Element.inflateWidget 
flutter: #100    Element.updateChild 
flutter: #101    SingleChildRenderObjectElement.mount 
flutter: #102    Element.inflateWidget 
flutter: #103    Element.updateChild 
flutter: #104    ComponentElement.performRebuild 
flutter: #105    Element.rebuild 
flutter: #106    ComponentElement._firstBuild 
flutter: #107    StatefulElement._firstBuild 
flutter: #108    ComponentElement.mount 
flutter: #109    Element.inflateWidget 
flutter: #110    Element.updateChild 
flutter: #111    ComponentElement.performRebuild 
flutter: #112    Element.rebuild 
flutter: #113    ComponentElement._firstBuild 
flutter: #114    StatefulElement._firstBuild 
flutter: #115    ComponentElement.mount 
flutter: #116    Element.inflateWidget 
flutter: #117    Element.updateChild 
flutter: #118    ComponentElement.performRebuild 
flutter: #119    Element.rebuild 
flutter: #120    ComponentElement._firstBuild 
flutter: #121    ComponentElement.mount 
flutter: #122    Element.inflateWidget 
flutter: #123    Element.updateChild 
flutter: #124    ComponentElement.performRebuild 
flutter: #125    Element.rebuild 
flutter: #126    ComponentElement._firstBuild 
flutter: #127    ComponentElement.mount 
flutter: #128    Element.inflateWidget 
flutter: #129    Element.updateChild 
flutter: #130    ComponentElement.performRebuild 
flutter: #131    Element.rebuild 
flutter: #132    ComponentElement._firstBuild 
flutter: #133    StatefulElement._firstBuild 
flutter: #134    ComponentElement.mount 
flutter: #135    Element.inflateWidget 
flutter: #136    Element.updateChild 
flutter: #137    ComponentElement.performRebuild 
flutter: #138    Element.rebuild 
flutter: #139    ComponentElement._firstBuild 
flutter: #140    StatefulElement._firstBuild 
flutter: #141    ComponentElement.mount 
flutter: #142    Element.inflateWidget 
flutter: #143    Element.updateChild 
flutter: #144    ComponentElement.performRebuild 
flutter: #145    Element.rebuild 
flutter: #146    ComponentElement._firstBuild 
flutter: #147    ComponentElement.mount 
flutter: #148    Element.inflateWidget 
flutter: #149    Element.updateChild 
flutter: #150    SingleChildRenderObjectElement.mount 
flutter: #151    Element.inflateWidget 
flutter: #152    MultiChildRenderObjectElement.mount 
flutter: #153    Element.inflateWidget 
flutter: #154    Element.updateChild 
flutter: #155    ComponentElement.performRebuild 
flutter: #156    Element.rebuild 
flutter: #157    ComponentElement._firstBuild 
flutter: #158    ComponentElement.mount 
flutter: #159    Element.inflateWidget 
flutter: #160    Element.updateChild 
flutter: #161    ComponentElement.performRebuild 
flutter: #162    Element.rebuild 
flutter: #163    ComponentElement._firstBuild 
flutter: #164    ComponentElement.mount 
flutter: #165    Element.inflateWidget 
flutter: #166    Element.updateChild 
flutter: #167    ComponentElement.performRebuild 
flutter: #168    Element.rebuild 
flutter: #169    ComponentElement._firstBuild 
flutter: #170    ComponentElement.mount 
flutter: #171    ParentDataElement.mount 
flutter: #172    Element.inflateWidget 
flutter: #173    MultiChildRenderObjectElement.mount 
flutter: #174    Element.inflateWidget 
flutter: #175    Element.updateChild 
flutter: #176    ComponentElement.performRebuild 
flutter: #177    Element.rebuild 
flutter: #178    ComponentElement._firstBuild 
flutter: #179    StatefulElement._firstBuild 
flutter: #180    ComponentElement.mount 
flutter: #181    Element.inflateWidget 
flutter: #182    Element.updateChild 
flutter: #183    ComponentElement.performRebuild 
flutter: #184    Element.rebuild 
flutter: #185    ComponentElement._firstBuild 
flutter: #186    ComponentElement.mount 
flutter: #187    Element.inflateWidget 
flutter: #188    Element.updateChild 
flutter: #189    ComponentElement.performRebuild 
flutter: #190    Element.rebuild 
flutter: #191    ComponentElement._firstBuild 
flutter: #192    StatefulElement._firstBuild 
flutter: #193    ComponentElement.mount 
flutter: #194    Element.inflateWidget 
flutter: #195    Element.updateChild 
flutter: #196    SingleChildRenderObjectElement.mount 
flutter: #197    Element.inflateWidget 
flutter: #198    Element.updateChild 
flutter: #199    ComponentElement.performRebuild 
flutter: #200    Element.rebuild 
flutter: #201    ComponentElement._firstBuild 
flutter: #202    ComponentElement.mount 
flutter: #203    Element.inflateWidget 
flutter: #204    Element.updateChild 
flutter: #205    SingleChildRenderObjectElement.mount 
flutter: #206    Element.inflateWidget 
flutter: #207    Element.updateChild 
flutter: #208    ComponentElement.performRebuild 
flutter: #209    Element.rebuild 
flutter: #210    ComponentElement._firstBuild 
flutter: #211    StatefulElement._firstBuild 
flutter: #212    ComponentElement.mount 
flutter: #213    Element.inflateWidget 
flutter: #214    Element.updateChild 
flutter: #215    ComponentElement.performRebuild 
flutter: #216    Element.rebuild 
flutter: #217    ComponentElement._firstBuild 
flutter: #218    StatefulElement._firstBuild 
flutter: #219    ComponentElement.mount 
flutter: #220    Element.inflateWidget 
flutter: #221    Element.updateChild 
flutter: #222    ComponentElement.performRebuild 
flutter: #223    Element.rebuild 
flutter: #224    ComponentElement._firstBuild 
flutter: #225    ComponentElement.mount 
flutter: #226    Element.inflateWidget 
flutter: #227    Element.updateChild 
flutter: #228    ComponentElement.performRebuild 
flutter: #229    Element.rebuild 
flutter: #230    ComponentElement._firstBuild 
flutter: #231    ComponentElement.mount 
flutter: #232    Element.inflateWidget 
flutter: #233    Element.updateChild 
flutter: #234    ComponentElement.performRebuild 
flutter: #235    Element.rebuild 
flutter: #236    ComponentElement._firstBuild 
flutter: #237    StatefulElement._firstBuild 
flutter: #238    ComponentElement.mount 
flutter: #239    Element.inflateWidget 
flutter: #240    Element.updateChild 
flutter: #241    ComponentElement.performRebuild 
flutter: #242    Element.rebuild 
flutter: #243    ComponentElement._firstBuild 
flutter: #244    StatefulElement._firstBuild 
flutter: #245    ComponentElement.mount 
flutter: #246    Element.inflateWidget 
flutter: #247    Element.updateChild 
flutter: #248    ComponentElement.performRebuild 
flutter: #249    Element.rebuild 
flutter: #250    ComponentElement._firstBuild 
flutter: #251    StatefulElement._firstBuild 
flutter: #252    ComponentElement.mount 
flutter: #253    Element.inflateWidget 
flutter: #254    Element.updateChild 
flutter: #255    SingleChildRenderObjectElement.mount 
flutter: #256    Element.inflateWidget 
flutter: #257    Element.updateChild 
flutter: #258    ComponentElement.performRebuild 
flutter: #259    Element.rebuild 
flutter: #260    ComponentElement._firstBuild 
flutter: #261    ComponentElement.mount 
flutter: #262    Element.inflateWidget 
flutter: #263    Element.updateChild 
flutter: #264    SingleChildRenderObjectElement.mount 
flutter: #265    Element.inflateWidget 
flutter: #266    Element.updateChild 
flutter: #267    SingleChildRenderObjectElement.mount 
flutter: #268    Element.inflateWidget 
flutter: #269    MultiChildRenderObjectElement.mount 
flutter: #270    Element.inflateWidget 
flutter: #271    Element.updateChild 
flutter: #272    ComponentElement.performRebuild 
flutter: #273    Element.rebuild 
flutter: #274    ComponentElement._firstBuild 
flutter: #275    StatefulElement._firstBuild 
flutter: #276    ComponentElement.mount 
flutter: #277    Element.inflateWidget 
flutter: #278    Element.updateChild 
flutter: #279    SingleChildRenderObjectElement.mount 
flutter: #280    Element.inflateWidget 
flutter: #281    Element.updateChild 
flutter: #282    ComponentElement.performRebuild 
flutter: #283    Element.rebuild 
flutter: #284    ComponentElement._firstBuild 
flutter: #285    StatefulElement._firstBuild 
flutter: #286    ComponentElement.mount 
flutter: #287    Element.inflateWidget 
flutter: #288    Element.updateChild 
flutter: #289    SingleChildRenderObjectElement.mount 
flutter: #290    Element.inflateWidget 
flutter: #291    Element.updateChild 
flutter: #292    ComponentElement.performRebuild 
flutter: #293    Element.rebuild 
flutter: #294    ComponentElement._firstBuild 
flutter: #295    StatefulElement._firstBuild 
flutter: #296    ComponentElement.mount 
flutter: #297    Element.inflateWidget 
flutter: #298    Element.updateChild 
flutter: #299    SingleChildRenderObjectElement.mount 
flutter: #300    Element.inflateWidget 
flutter: #301    Element.updateChild 
flutter: #302    ComponentElement.performRebuild 
flutter: #303    Element.rebuild 
flutter: #304    ComponentElement._firstBuild 
flutter: #305    StatefulElement._firstBuild 
flutter: #306    ComponentElement.mount 
flutter: #307    Element.inflateWidget 
flutter: #308    Element.updateChild 
flutter: #309    ComponentElement.performRebuild 
flutter: #310    Element.rebuild 
flutter: #311    ComponentElement._firstBuild 
flutter: #312    ComponentElement.mount 
flutter: #313    Element.inflateWidget 
flutter: #314    Element.updateChild 
flutter: #315    ComponentElement.performRebuild 
flutter: #316    Element.rebuild 
flutter: #317    ComponentElement._firstBuild 
flutter: #318    StatefulElement._firstBuild 
flutter: #319    ComponentElement.mount 
flutter: #320    Element.inflateWidget 
flutter: #321    Element.updateChild 
flutter: #322    SingleChildRenderObjectElement.mount 
flutter: #323    Element.inflateWidget 
flutter: #324    Element.updateChild 
flutter: #325    ComponentElement.performRebuild 
flutter: #326    Element.rebuild 
flutter: #327    ComponentElement._firstBuild 
flutter: #328    ComponentElement.mount 
flutter: #329    Element.inflateWidget 
flutter: #330    Element.updateChild 
flutter: #331    SingleChildRenderObjectElement.mount 
flutter: #332    Element.inflateWidget 
flutter: #333    Element.updateChild 
flutter: #334    ComponentElement.performRebuild 
flutter: #335    Element.rebuild 
flutter: #336    ComponentElement._firstBuild 
flutter: #337    StatefulElement._firstBuild 
flutter: #338    ComponentElement.mount 
flutter: #339    Element.inflateWidget 
flutter: #340    Element.updateChild 
flutter: #341    ComponentElement.performRebuild 
flutter: #342    Element.rebuild 
flutter: #343    ComponentElement._firstBuild 
flutter: #344    ComponentElement.mount 
flutter: #345    Element.inflateWidget 
flutter: #346    Element.updateChild 
flutter: #347    SingleChildRenderObjectElement.mount 
flutter: #348    Element.inflateWidget 
flutter: #349    Element.updateChild 
flutter: #350    ComponentElement.performRebuild 
flutter: #351    Element.rebuild 
flutter: #352    ComponentElement._firstBuild 
flutter: #353    ComponentElement.mount 
flutter: #354    Element.inflateWidget 
flutter: #355    Element.updateChild 
flutter: #356    ComponentElement.performRebuild 
flutter: #357    Element.rebuild 
flutter: #358    ComponentElement._firstBuild 
flutter: #359    StatefulElement._firstBuild 
flutter: #360    ComponentElement.mount 
flutter: #361    Element.inflateWidget 
flutter: #362    Element.updateChild 
flutter: #363    ComponentElement.performRebuild 
flutter: #364    Element.rebuild 
flutter: #365    ComponentElement._firstBuild 
flutter: #366    StatefulElement._firstBuild 
flutter: #367    ComponentElement.mount 
flutter: #368    Element.inflateWidget 
flutter: #369    Element.updateChild 
flutter: #370    RenderObjectElement.updateChildren 
flutter: #371    MultiChildRenderObjectElement.update 
flutter: #372    Element.updateChild 
flutter: #373    _TheatreElement.update 
flutter: #374    Element.updateChild 
flutter: #375    ComponentElement.performRebuild 
flutter: #376    Element.rebuild 
flutter: #377    StatefulElement.update 
flutter: #378    Element.updateChild 
flutter: #379    ComponentElement.performRebuild 
flutter: #380    Element.rebuild 
flutter: #381    ProxyElement.update 
flutter: #382    Element.updateChild 
flutter: #383    SingleChildRenderObjectElement.update 
flutter: #384    Element.updateChild 
flutter: #385    ComponentElement.performRebuild 
flutter: #386    Element.rebuild 
flutter: #387    StatefulElement.update 
flutter: #388    Element.updateChild 
flutter: #389    SingleChildRenderObjectElement.update 
flutter: #390    Element.updateChild 
flutter: #391    SingleChildRenderObjectElement.update 
flutter: #392    Element.updateChild 
flutter: #393    ComponentElement.performRebuild 
flutter: #394    Element.rebuild 
flutter: #395    BuildOwner.buildScope 
flutter: #396    _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding&RendererBinding&WidgetsBinding.drawFrame 
flutter: #397    _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding&RendererBinding._handlePersistentFrameCallback 
flutter: #398    _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._invokeFrameCallback 
flutter: #399    _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding.handleDrawFrame 
flutter: #400    _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._handleDrawFrame 
flutter: #404    _invoke (dart:ui/hooks.dart:189:10)
flutter: #405    _drawFrame (dart:ui/hooks.dart:162:3)
flutter: (elided 3 frames from package dart:async)
flutter:
flutter: When the exception was thrown, this was the stack:
flutter: #0      _ClassicsHeaderState&RefreshHeaderState&TickerProviderStateMixin.dispose.<anonymous closure> 
flutter: #1      _ClassicsHeaderState&RefreshHeaderState&TickerProviderStateMixin.dispose 
flutter: #2      ClassicsHeaderState.dispose
flutter: #3      StatefulElement.unmount 
flutter: #4      _InactiveElements._unmount 
flutter: #5      _InactiveElements._unmount.<anonymous closure> 
flutter: #6      MultiChildRenderObjectElement.visitChildren 
flutter: #7      _InactiveElements._unmount 
flutter: #8      _InactiveElements._unmount.<anonymous closure> 
flutter: #9      MultiChildRenderObjectElement.visitChildren 
flutter: #10     _InactiveElements._unmount 
flutter: #11     _InactiveElements._unmount.<anonymous closure> 
flutter: #12     ComponentElement.visitChildren 
flutter: #13     _InactiveElements._unmount 
flutter: #14     _InactiveElements._unmount.<anonymous closure> 
flutter: #15     ComponentElement.visitChildren 
flutter: #16     _InactiveElements._unmount 
flutter: #17     _InactiveElements._unmount.<anonymous closure> 
flutter: #18     ComponentElement.visitChildren 
flutter: #19     _InactiveElements._unmount 
flutter: #20     _InactiveElements._unmount.<anonymous closure> 
flutter: #21     ComponentElement.visitChildren 
flutter: #22     _InactiveElements._unmount 
flutter: #23     _InactiveElements._unmount.<anonymous closure> 
flutter: #24     SingleChildRenderObjectElement.visitChildren 
flutter: #25     _InactiveElements._unmount 
flutter: #26     _InactiveElements._unmount.<anonymous closure> 
flutter: #27     ComponentElement.visitChildren 
flutter: #28     _InactiveElements._unmount 
flutter: #29     _InactiveElements._unmount.<anonymous closure> 
flutter: #30     SingleChildRenderObjectElement.visitChildren 
flutter: #31     _InactiveElements._unmount 
flutter: #32     _InactiveElements._unmount.<anonymous closure> 
flutter: #33     ComponentElement.visitChildren 
flutter: #34     _InactiveElements._unmount 
flutter: #35     _InactiveElements._unmount.<anonymous closure> 
flutter: #36     ComponentElement.visitChildren 
flutter: #37     _InactiveElements._unmount 
flutter: #38     _InactiveElements._unmount.<anonymous closure> 
flutter: #39     ComponentElement.visitChildren 
flutter: #40     _InactiveElements._unmount 
flutter: #41     _InactiveElements._unmount.<anonymous closure> 
flutter: #42     MultiChildRenderObjectElement.visitChildren 
flutter: #43     _InactiveElements._unmount 
flutter: #44     _InactiveElements._unmount.<anonymous closure> 
flutter: #45     ComponentElement.visitChildren 
flutter: #46     _InactiveElements._unmount 
flutter: #47     _InactiveElements._unmount.<anonymous closure> 
flutter: #48     ComponentElement.visitChildren 
flutter: #49     _InactiveElements._unmount 
flutter: #50     _InactiveElements._unmount.<anonymous closure> 
flutter: #51     ComponentElement.visitChildren 
flutter: #52     _InactiveElements._unmount 
flutter: #53     _InactiveElements._unmount.<anonymous closure> 
flutter: #54     SingleChildRenderObjectElement.visitChildren 
flutter: #55     _InactiveElements._unmount 
flutter: #56     _InactiveElements._unmount.<anonymous closure> 
flutter: #57     ComponentElement.visitChildren 
flutter: #58     _InactiveElements._unmount 
flutter: #59     _InactiveElements._unmount.<anonymous closure> 
flutter: #60     SingleChildRenderObjectElement.visitChildren 
flutter: #61     _InactiveElements._unmount 
flutter: #62     _InactiveElements._unmount.<anonymous closure> 
flutter: #63     ComponentElement.visitChildren 
flutter: #64     _InactiveElements._unmount 
flutter: #65     _InactiveElements._unmount.<anonymous closure> 
flutter: #66     ComponentElement.visitChildren 
flutter: #67     _InactiveElements._unmount 
flutter: #68     _InactiveElements._unmount.<anonymous closure> 
flutter: #69     ComponentElement.visitChildren 
flutter: #70     _InactiveElements._unmount 
flutter: #71     _InactiveElements._unmount.<anonymous closure> 
flutter: #72     ComponentElement.visitChildren 
flutter: #73     _InactiveElements._unmount 
flutter: #74     _InactiveElements._unmount.<anonymous closure> 
flutter: #75     ComponentElement.visitChildren 
flutter: #76     _InactiveElements._unmount 
flutter: #77     _InactiveElements._unmount.<anonymous closure> 
flutter: #78     ComponentElement.visitChildren 
flutter: #79     _InactiveElements._unmount 
flutter: #80     _InactiveElements._unmount.<anonymous closure> 
flutter: #81     ComponentElement.visitChildren 
flutter: #82     _InactiveElements._unmount 
flutter: #83     _InactiveElements._unmount.<anonymous closure> 
flutter: #84     SingleChildRenderObjectElement.visitChildren 
flutter: #85     _InactiveElements._unmount 
flutter: #86     _InactiveElements._unmount.<anonymous closure> 
flutter: #87     MultiChildRenderObjectElement.visitChildren 
flutter: #88     _InactiveElements._unmount 
flutter: #89     _InactiveElements._unmount.<anonymous closure> 
flutter: #90     ComponentElement.visitChildren 
flutter: #91     _InactiveElements._unmount 
flutter: #92     _InactiveElements._unmount.<anonymous closure> 
flutter: #93     ComponentElement.visitChildren 
flutter: #94     _InactiveElements._unmount 
flutter: #95     _InactiveElements._unmount.<anonymous closure> 
flutter: #96     ComponentElement.visitChildren 
flutter: #97     _InactiveElements._unmount 
flutter: #98     _InactiveElements._unmount.<anonymous closure> 
flutter: #99     MultiChildRenderObjectElement.visitChildren 
flutter: #100    _InactiveElements._unmount 
flutter: #101    _InactiveElements._unmount.<anonymous closure> 
flutter: #102    ComponentElement.visitChildren 
flutter: #103    _InactiveElements._unmount 
flutter: #104    _InactiveElements._unmount.<anonymous closure> 
flutter: #105    ComponentElement.visitChildren 
flutter: #106    _InactiveElements._unmount 
flutter: #107    _InactiveElements._unmount.<anonymous closure> 
flutter: #108    ComponentElement.visitChildren 
flutter: #109    _InactiveElements._unmount 
flutter: #110    _InactiveElements._unmount.<anonymous closure> 
flutter: #111    SingleChildRenderObjectElement.visitChildren 
flutter: #112    _InactiveElements._unmount 
flutter: #113    _InactiveElements._unmount.<anonymous closure> 
flutter: #114    ComponentElement.visitChildren 
flutter: #115    _InactiveElements._unmount 
flutter: #116    _InactiveElements._unmount.<anonymous closure> 
flutter: #117    SingleChildRenderObjectElement.visitChildren 
flutter: #118    _InactiveElements._unmount 
flutter: #119    _InactiveElements._unmount.<anonymous closure> 
flutter: #120    ComponentElement.visitChildren 
flutter: #121    _InactiveElements._unmount 
flutter: #122    _InactiveElements._unmount.<anonymous closure> 
flutter: #123    ComponentElement.visitChildren 
flutter: #124    _InactiveElements._unmount 
flutter: #125    _InactiveElements._unmount.<anonymous closure> 
flutter: #126    ComponentElement.visitChildren 
flutter: #127    _InactiveElements._unmount 
flutter: #128    _InactiveElements._unmount.<anonymous closure> 
flutter: #129    ComponentElement.visitChildren 
flutter: #130    _InactiveElements._unmount 
flutter: #131    _InactiveElements._unmount.<anonymous closure> 
flutter: #132    ComponentElement.visitChildren 
flutter: #133    _InactiveElements._unmount 
flutter: #134    _InactiveElements._unmount.<anonymous closure> 
flutter: #135    ComponentElement.visitChildren 
flutter: #136    _InactiveElements._unmount 
flutter: #137    _InactiveElements._unmount.<anonymous closure> 
flutter: #138    ComponentElement.visitChildren 
flutter: #139    _InactiveElements._unmount 
flutter: #140    _InactiveElements._unmount.<anonymous closure> 
flutter: #141    SingleChildRenderObjectElement.visitChildren 
flutter: #142    _InactiveElements._unmount 
flutter: #143    _InactiveElements._unmount.<anonymous closure> 
flutter: #144    ComponentElement.visitChildren 
flutter: #145    _InactiveElements._unmount 
flutter: #146    _InactiveElements._unmount.<anonymous closure> 
flutter: #147    SingleChildRenderObjectElement.visitChildren 
flutter: #148    _InactiveElements._unmount 
flutter: #149    _InactiveElements._unmount.<anonymous closure> 
flutter: #150    SingleChildRenderObjectElement.visitChildren 
flutter: #151    _InactiveElements._unmount 
flutter: #152    _InactiveElements._unmount.<anonymous closure> 
flutter: #153    MultiChildRenderObjectElement.visitChildren 
flutter: #154    _InactiveElements._unmount 
flutter: #155    _InactiveElements._unmount.<anonymous closure> 
flutter: #156    ComponentElement.visitChildren 
flutter: #157    _InactiveElements._unmount 
flutter: #158    _InactiveElements._unmount.<anonymous closure> 
flutter: #159    SingleChildRenderObjectElement.visitChildren 
flutter: #160    _InactiveElements._unmount 
flutter: #161    _InactiveElements._unmount.<anonymous closure> 
flutter: #162    ComponentElement.visitChildren 
flutter: #163    _InactiveElements._unmount 
flutter: #164    _InactiveElements._unmount.<anonymous closure> 
flutter: #165    SingleChildRenderObjectElement.visitChildren 
flutter: #166    _InactiveElements._unmount 
flutter: #167    _InactiveElements._unmount.<anonymous closure> 
flutter: #168    ComponentElement.visitChildren 
flutter: #169    _InactiveElements._unmount 
flutter: #170    _InactiveElements._unmount.<anonymous closure> 
flutter: #171    SingleChildRenderObjectElement.visitChildren 
flutter: #172    _InactiveElements._unmount 
flutter: #173    _InactiveElements._unmount.<anonymous closure> 
flutter: #174    ComponentElement.visitChildren 
flutter: #175    _InactiveElements._unmount 
flutter: #176    _InactiveElements._unmount.<anonymous closure> 
flutter: #177    ComponentElement.visitChildren 
flutter: #178    _InactiveElements._unmount 
flutter: #179    _InactiveElements._unmount.<anonymous closure> 
flutter: #180    ComponentElement.visitChildren 
flutter: #181    _InactiveElements._unmount 
flutter: #182    _InactiveElements._unmount.<anonymous closure> 
flutter: #183    SingleChildRenderObjectElement.visitChildren 
flutter: #184    _InactiveElements._unmount 
flutter: #185    _InactiveElements._unmount.<anonymous closure> 
flutter: #186    ComponentElement.visitChildren 
flutter: #187    _InactiveElements._unmount 
flutter: #188    _InactiveElements._unmount.<anonymous closure> 
flutter: #189    SingleChildRenderObjectElement.visitChildren 
flutter: #190    _InactiveElements._unmount 
flutter: #191    _InactiveElements._unmount.<anonymous closure> 
flutter: #192    ComponentElement.visitChildren 
flutter: #193    _InactiveElements._unmount 
flutter: #194    _InactiveElements._unmount.<anonymous closure> 
flutter: #195    ComponentElement.visitChildren 
flutter: #196    _InactiveElements._unmount 
flutter: #197    _InactiveElements._unmount.<anonymous closure> 
flutter: #198    SingleChildRenderObjectElement.visitChildren 
flutter: #199    _InactiveElements._unmount 
flutter: #200    _InactiveElements._unmount.<anonymous closure> 
flutter: #201    ComponentElement.visitChildren 
flutter: #202    _InactiveElements._unmount 
flutter: #203    _InactiveElements._unmount.<anonymous closure> 
flutter: #204    ComponentElement.visitChildren 
flutter: #205    _InactiveElements._unmount 
flutter: #206    _InactiveElements._unmount.<anonymous closure> 
flutter: #207    ComponentElement.visitChildren 
flutter: #208    _InactiveElements._unmount 
flutter: #209    ListIterable.forEach (dart:_internal/iterable.dart:39:13)
flutter: #210    _InactiveElements._unmountAll 
flutter: #211    BuildOwner.finalizeTree.<anonymous closure> 
flutter: #212    BuildOwner.lockState 
flutter: #213    BuildOwner.finalizeTree 
flutter: #214    _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding&RendererBinding&WidgetsBinding.drawFrame 
flutter: #215    _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding&RendererBinding._handlePersistentFrameCallback 
flutter: #216    _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._invokeFrameCallback 
flutter: #217    _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding.handleDrawFrame 
flutter: #218    _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._handleDrawFrame 
flutter: #222    _invoke (dart:ui/hooks.dart:189:10)
flutter: #223    _drawFrame (dart:ui/hooks.dart:162:3)
flutter: (elided 3 frames from package dart:async)
flutter: ════════════════════════════════════════════════════════════════════════════════════════════════════

**Comment by PayneJay** [comment]
我是和TabBar结合使用。跨三四个Tab切换会出现这个问题，在dispose中也调用controller.dispose()了，问题依然存在
`@override
  void dispose() {
    //先调用controller.dispose释放了动画资源，再调用super
    _controller?.dispose();
    super.dispose();
  }`

**Comment by xuelongqy** [comment]
Fixed in v2
