### ISSUE TITLE
v2版本升级到v3好难用

### ISSUE THREAD

**Issue by ixinrun** [xuelongqy/flutter_easyrefresh#712]
1. 空视图不容易添加
2. 上拉加载更多，没有数据时不会回弹
3. 上拉加载更多只能加载一次
4. api使用有点不清晰

**Comment by xuelongqy** [comment]
哈哈哈，看来就差我帮你手写代码了

**Comment by xuelongqy** [comment]
如果你需要文档，你可以在这里看[API reference](https://pub.dev/documentation/easy_refresh/latest/easy_refresh/easy_refresh-library.html)。上述的所有问题都能得到解决
