### ISSUE TITLE
如何由程序触发刷新

### ISSUE THREAD

**Issue by mostcute** [xuelongqy/flutter_easyrefresh#715]
有时候有一些组件联动操作，某操作发生后触发一次刷新动画，如何由代码触发刷新动画

**Comment by mostcute** [comment]
仔细看了看例子

使用` _controller.callRefresh();`即可

打扰了

**Comment by zhuwei** [comment]
有问题，如果刚刚加载完，但动画在结束的过程中调用_controller.callRefresh();将没有任何作用
