### ISSUE TITLE
[enhancement] trigger onLoad automatically when scroll is in bottom without extra hold gesture

### ISSUE THREAD

**Issue by sed1ka** [xuelongqy/flutter_easyrefresh#716]
The package is awesome,
I just realized that in order to trigger `onLoad` the user has to do an additional scroll gesture (hold + scroll). I think for the user experience it would be nice if the `onLoad` could be triggered automatically when the scroll position is already at the bottom (with the condition that the `Footer `is also shown automatically without any additional gestures). hope there is an option for this in the future

or maybe I missed something for this option? because I've been diving in the code examples but couldn't figure out how

**Comment by xuelongqy** [comment]
Try setting the infiniteOffset parameter of the indicator, maybe it can help you

**Comment by sed1ka** [comment]
Set the infiniteOffset parameters and set the infiniteHitOver to false is the solution
