### ISSUE TITLE
 The method 'updateHeight' was called on null.

### ISSUE THREAD

**Issue by lionoggo** [xuelongqy/flutter_easyrefresh#72]
NoSuchMethodError: The method 'updateHeight' was called on null.

Receiver: null

Tried calling: updateHeight(15.837440000000003)

#0 Object.noSuchMethod (dart:core/runtime/libobject_patch.dart:50)

#1 EasyRefreshState._setTopItemHeight.
(package:flutter_easyrefresh/src/refresher.dart:748)

#2 State.setState (package:flutter/src/widgets/framework.dart:1130)

#3 EasyRefreshState._setTopItemHeight (package:flutter_easyrefresh/src/refresher.dart:745)

#4 EasyRefreshState.initState.
. (package:flutter_easyrefresh/src/refresher.dart:450)

#5 State.setState (package:flutter/src/widgets/framework.dart:1130)

#6 EasyRefreshState.initState.
(package:flutter_easyrefresh/src/refresher.dart:440)

**Comment by xuelongqy** [comment]
v2 has been refactored
