### ISSUE TITLE
使用CustomScrollView进行指示器定位时候，出现覆盖指示器的情况

### ISSUE THREAD

**Issue by xiaoyao20084321** [xuelongqy/flutter_easyrefresh#723]
<img width="229" alt="image" src="https://github.com/xuelongqy/flutter_easy_refresh/assets/10344550/2cf9cd4c-aaa1-4030-9162-bc0feecc10a5">
<img width="517" alt="image" src="https://github.com/xuelongqy/flutter_easy_refresh/assets/10344550/0d0e27a2-2342-4897-8300-31c91548f3a2">
使用CupertinoSliverNavigationBar也会出现
<img width="286" alt="image" src="https://github.com/xuelongqy/flutter_easy_refresh/assets/10344550/971cf2e8-1f35-454f-99f2-119769d274f4">
<img width="651" alt="image" src="https://github.com/xuelongqy/flutter_easy_refresh/assets/10344550/2f143334-70cf-4cdd-81ec-8a03b6b1af29">

**Comment by xuelongqy** [comment]
试试设置一下header的safeArea

**Comment by xuelongqy** [comment]
可以参考这个示例 [CupertinoPage](https://github.com/xuelongqy/flutter_easy_refresh/blob/v3/example/lib/page/style/cupertino_page.dart)
