### ISSUE TITLE
I want to call onLoad in advance so that the next page is already loaded when the user scrolls to the bottom.

### ISSUE THREAD

**Issue by limdp99** [xuelongqy/flutter_easyrefresh#729]
When the scroll is not at the very bottom but around 60-70% scrolled, I want to call onLoad in advance so that the next page is already loaded when the user scrolls to the bottom.

I have tried changing various parameters of CupertinoFooter, but it doesn't work. 
What part should I refer to in order to implement this?

Thank you!

**Comment by xuelongqy** [comment]
set infiniteOffset
