### ISSUE TITLE
帧数低至30fps，性能差

### ISSUE THREAD

**Issue by zhuxiujia** [xuelongqy/flutter_easyrefresh#73]
帧数低至30fps，性能差
可以打开android studio 或者idea，右下角performance 窗口，当下拉刷新时，帧数非常低，差不多30fps
而且当前页面里面只有一个Text()控件，并不复杂，希望作者看到可以优化下控件的性能 以免卡顿

**Comment by Lizhooh** [comment]
@zhuxiujia 你电脑卡吧，试试发布版本 + 真机。

**Comment by zhuxiujia** [comment]
> @zhuxiujia 你电脑卡吧，试试发布版本 + 真机。

电脑i7 +16G内存+ 500G固态+gtx1080ti，配置不低
真机是在iphone8上侦测的，idea有监控窗口里面显示的
