### ISSUE TITLE
onLoad behavior like OnRefresh 

### ISSUE THREAD

**Issue by WMOH-DEV** [xuelongqy/flutter_easyrefresh#734]
Hello,

I need to use EasyRefresh in my project to enable navigation between elements (books). I am using onRefresh to navigate to the previous element page, and onLoad to navigate to the next element page.

The onRefresh functionality works very well, and everything is okay. However, the onLoad behavior is not as desired. After scrolling down, the onLoad event triggers immediately. I want it to behave just like the onRefresh: ClassicHeader, when you reach the bottom and drag up and if released, it triggers the action; otherwise, it does nothing.

the header set to classicheader
the footer set to classicfooter

Can you please help me configure the onLoad behavior to achieve the desired functionality?

**Comment by xuelongqy** [comment]
Set Footer.infiniteOffset = null

**Comment by yfming93** [comment]
> Set Footer.infiniteOffset = null

3Q. It`s work well for me .
