### ISSUE TITLE
easyrefresh 不触发动画的刷新方法（首次进入页面是希望不出现下拉刷新动画）

### ISSUE THREAD

**Issue by shang1219178163** [xuelongqy/flutter_easyrefresh#736]
如题；希望可以在  EasyRefreshController 方法调用中加一个参数，关闭或者打开动画

**Comment by xuelongqy** [comment]
参考示例。将首次刷新的Header设置为clamping，然后构建空视图就行了

**Comment by shang1219178163** [comment]
您好，我希望的是首屏（次）加载没有动画，但是之后加载动画还是要的。

**Comment by shang1219178163** [comment]
> 参考示例。将首次刷新的Header设置为clamping，然后构建空视图就行了


您好，我希望的是首屏（次）加载没有动画，但是之后加载动画还是要的。
