### ISSUE TITLE
在手机上要下拉很大的距离才能触发刷新，超过2个条目高度才能触发

### ISSUE THREAD

**Issue by junixapp** [xuelongqy/flutter_easyrefresh#742]
![310df66632534934a331ff97fdb92ff2](https://github.com/xuelongqy/flutter_easy_refresh/assets/4426715/ea008b2b-52aa-4d98-a018-5dba57719a49)
![f8788e69e96e9443680542deca8967b3](https://github.com/xuelongqy/flutter_easy_refresh/assets/4426715/d855ccb2-c15c-45d1-a454-655277c3c6bc)
demo下拉一小段距离就可以触发刷新，我在手机上要下拉很大的距离才能触发刷新，超过2个条目高度才能触发，没有设置任何属性。
版本：easy_refresh: ^3.3.2+1
代码如下:
```
EasyRefresh(
      onRefresh: () async {
        await loadData();
      }, child:Obx(() => ListView.separated(padding:EdgeInsets.zero,
          itemBuilder: (context, index){
            return createItem(context, item);
          }, separatorBuilder: (context, index)=> SizedBox(height: 0.w,),
          itemCount: userAssetController.list.length)))
```

**Comment by xuelongqy** [comment]
在指示器去掉safeArea，设置为false
