### ISSUE TITLE
v3 版本的refreshOnStart=true 无效 

### ISSUE THREAD

**Issue by fanwei33** [xuelongqy/flutter_easyrefresh#743]
使用官方项目examples下的tabbarview代码，设置refreshOnStart = true 不生效。尝试增加ScrollController，自动加载数据会一直停留
加载状态上。
![image](https://github.com/xuelongqy/flutter_easy_refresh/assets/120299492/9a02e2d7-50cf-468b-9d51-6c66df1afe3c)

**Comment by xuelongqy** [comment]
暂时无解，跟上一个issue一样。链接至https://github.com/xuelongqy/flutter_easy_refresh/issues/741
