### ISSUE TITLE
Demo都是单个文件的，能不能basic 模式的多个文件（每个Tab单独一个页面）来写一个?

### ISSUE THREAD

**Issue by BadDeveloper2022** [xuelongqy/flutter_easyrefresh#744]
Demo都是单个文件的，能不能basic 模式的多个文件（每个Tab单独一个页面）来写一个?
新手求教....physics 值不知道怎么传过去，还有onRefresh 怎么通知对应的页面
万分感谢

**Comment by BadDeveloper2022** [comment]
@xuelongqy

**Comment by BadDeveloper2022** [comment]
意思就是：tab_bar_view_page.dart 怎么拆分多个页面，每个Tabbar对应的页面单独一个文件，这样全部写在一个文件里面逻辑有点复杂，维护难了。
一个刷新，多个Tab

**Comment by xuelongqy** [comment]
我觉得你需要提升一下Flutter的基础知识。这里不是课堂，我也没有这个义务
