### ISSUE TITLE
SliverAppBar问题

### ISSUE THREAD

**Issue by bianning** [xuelongqy/flutter_easyrefresh#748]
请问使用NestedScrollView嵌套滚动时，为什么刷新控件是覆盖在SliverAppBar上方出现的，而不是把SliveAppbar顶下去，如果想要顶下去应该怎么做

**Comment by xuelongqy** [comment]
请参考示例。但不建议使用这种方式，Flutter中的嵌套滚动不能很好的支持下拉刷新，会有很多坑。建议修改设计方案
