### ISSUE TITLE
大佬，你好，咨询一个刷新的问题，请进来看一下，谢谢你

### ISSUE THREAD

**Issue by WangYiOS** [xuelongqy/flutter_easyrefresh#749]
目前我用的是 flutter_easyrefresh: ^2.2.1 版本，

在使用咱们库刷新的时候，一旦出现加载错误，就一直loading，这个列表就无法上拉加载更多了，

需要退出界面，从新初始化刷新库，才能正常使用咱的刷新库，

我该怎么做，才能在当前界面，继续使用刷新库，

希望你看到能解答我一下，给我点思路，谢谢大佬，

祝你度过快乐的一天

**Comment by xuelongqy** [comment]
这个版本不维护了，建议升级到v3哈
