### ISSUE TITLE
下拉加载时，footer让其一直存在

### ISSUE THREAD

**Issue by zhaoyanga** [xuelongqy/flutter_easyrefresh#751]
下拉加载时，松开手后，footer的内容会消失不见，想让footer一直存在，加载成功or失败后再消失

**Comment by xuelongqy** [comment]
看看示例有没有要的效果呢。没想错的话应该是无限滚动吧？

**Comment by zhaoyanga** [comment]
不是，是松开手后让footer一直存在，现在是松手后，footer直接不见了

**Comment by xuelongqy** [comment]
设置Footer的clamping为true？

**Comment by xuelongqy** [comment]
如果问题未解决，请留言并重新开启此issue
