### ISSUE TITLE
首次进入页面自动下拉, 然后顶部刷新区域一片空白, 无法回弹

### ISSUE THREAD

**Issue by dazeGitHub** [xuelongqy/flutter_easyrefresh#753]
<img width="289" alt="Snipaste_2023-08-30_13-21-12" src="https://github.com/xuelongqy/flutter_easy_refresh/assets/17785036/75848d4c-22d9-4a92-8f75-a5f3a5fdff37">

class RecommendController extends GetxController {
  @override
  void onReady() {
    super.onReady();
    Log.i("TAG RecommendController onReady() callRefresh()");
    Future.delayed(
      const Duration(milliseconds: 1200), () => easyRefreshController.callRefresh()
    );
  }
}

即使请求完数据这么干也没用 : 
    Future.delayed(
        const Duration(milliseconds: 500), () {
          easyRefreshController.finishRefresh();
          easyRefreshController.resetFooter();
        }
    );

我真服了，那个 pull_to_refresh 抛异常, 这个 easy_refresh 下拉回不去

**Comment by xuelongqy** [comment]
你不看示例，遇到报错怪谁。
