### ISSUE TITLE
关于easy_refresh刷新

### ISSUE THREAD

**Issue by ZhongYu5** [xuelongqy/flutter_easyrefresh#759]
EasyRefresh(
                      refreshOnStart: true,
                      onRefresh: () {
                        getData();
                      },
                      onLoad: () {
                        getData(isloadMore: true);
                      },
                      controller: _controller,
                      child: listView()))；
HttpUtils.post(
      url,
      '',
      dataMap,
      success: (data) async {
        if (data['result_code'] ==
            ((JhStorageUtils.getString('role_sign')!.contains('sale') &&
                    titleSelect == '0')
                ? '200'
                : '200')) {
          setState(() {
            dataList = data['data'];
          });
        } else {
          SmartDialog.showToast(data['msg']);
        }

        if (isloadMore) {
          _controller.finishLoad();
        } else {
          _controller.finishRefresh();
        }
      },
      fail: (code, msg) {
        _controller.finishRefresh();
        if (isloadMore) {
          _controller.finishLoad();
        }
        _controller.resetHeader();
      },
请求结束之后header顶部不回自动回收，留部分空白，请问是什么问题导致的

**Comment by xuelongqy** [comment]
请参考示例。如果有明确的bug，请提供详细信息，重新开启这个issue
