### ISSUE TITLE
与flutter_swiper_view 一起使用的时候，左右滑动会出现下拉的内容 

### ISSUE THREAD

**Issue by Jackfinal** [xuelongqy/flutter_easyrefresh#761]
<img width="442" alt="image" src="https://github.com/xuelongqy/flutter_easy_refresh/assets/15246879/71b2ba1f-8ab3-48c3-9ae5-c71217eb6c10">

左右滑动会出现这个，

`flutter 3.13.1`
`easy_refresh 3.3.2+1`

**Comment by xuelongqy** [comment]
Readme第一条，使用过程中有问题时。建议先阅读文档以及搜索历史issues
