### ISSUE TITLE
flutter_easy_refresh + get 遇到问题

### ISSUE THREAD

**Issue by emodeqidao** [xuelongqy/flutter_easyrefresh#763]
作者你好：
A页面使用了 刷新 EasyRefresh ， 也设置了refreshController ，跟着跳转到第二个页面 ，第三个页面，在第三个页面调用 Get.offAllNamed(/A页面)【删除所有以前的路由并转到新路由】。 这个时候A页面的EasyRefresh 的header  下来刷新是回不去的。求解
附带demo https://github.com/emodeqidao/testdemo

flutter: 3.13.4

easy_refresh: 3.3.2+1
get: 4.6.6

**Comment by HiUSB** [comment]
你应该重写RootpageView的controller，并加上tag。
```
class RootpageView extends GetView<RootpageController> {
  RootpageView({Key? key}) : super(key: key);

  @override
  final controller = Get.put(RootpageController(), tag: UniqueKey().toString());

...

```

**Comment by emodeqidao** [comment]
> 你应该重写RootpageView的controller，并加上tag。
> 
> ```
> class RootpageView extends GetView<RootpageController> {
>   RootpageView({Key? key}) : super(key: key);
> 
>   @override
>   final controller = Get.put(RootpageController(), tag: UniqueKey().toString());
> 
> ...
> ```

谢谢
