### ISSUE TITLE
可以给Header增加 padding 属性么？

### ISSUE THREAD

**Issue by M2dL1fe** [xuelongqy/flutter_easyrefresh#764]
当包裹的CustomScrollView里面有SliverPersistentHeader悬浮的时候，刷新中的时候，会造成悬浮header和刷新header重合，通过增加triggerOffset会增加额外的底部padding

<img width="231" alt="image" src="https://github.com/xuelongqy/flutter_easy_refresh/assets/8074125/5aa43f75-9d13-4e56-a742-7d1b8d957b5e">

**Comment by xuelongqy** [comment]
不能，但是你可以自定义Header。建议先自己尝试寻找解决方案，如果实在无法解决，请提供复现案例。维护项目不易，也没有帮忙解决开发问题的义务，希望理解
