### ISSUE TITLE
数据较少，底部区域该怎么去除 如图

### ISSUE THREAD

**Issue by Slhaos7373** [xuelongqy/flutter_easyrefresh#768]
![EA884C4BD151983D78C78FFA52CE9B60](https://github.com/xuelongqy/flutter_easy_refresh/assets/48637489/705a2f79-8c8d-47df-ac94-31d3c12af1f0)

**Comment by xuelongqy** [comment]
请先扩散思维自行研究，如不能解决问题。请提供详细说明和相关案例，并重新开启此issue
