### ISSUE TITLE
Null check operator used on a null value

### ISSUE THREAD

**Issue by zhongzf1** [xuelongqy/flutter_easyrefresh#774]
indicator_notifier.dart in IndicatorNotifier._canProcess at line 277 within easy_refresh
indicator_notifier.dart in IndicatorNotifier.callTask at line 433 within easy_refresh
easy_refresh.dart in _EasyRefreshState._callRefresh at line 476 within easy_refresh
easy_refresh.dart in _EasyRefreshState.initState.<fn>.<fn> at line 338 within easy_refresh
Called from: binding.dart in SchedulerBinding._invokeFrameCallback within flutter

我看了源码，发现_EasyRefreshState.initState里，_callRefresh的调用是在addPostFrameCallback的监听里面调用的，假如这个监听在_EasyRefreshState销毁之后才回调，那么_callRefresh里面的_canProcess => _onCanProcess!.call()就会因为_onCanProcess为空，导致出现Null check operator used on a null value的报错

**Comment by xuelongqy** [comment]
3.3.2+4 已解决
