### ISSUE TITLE
onrefresh数据不足

### ISSUE THREAD

**Issue by wpzym1125** [xuelongqy/flutter_easyrefresh#776]
当onrefresh请求下来的数据不足的时候，现在我要再加载一下，当controller.finishLoad(IndicatorResult.noMore);的时候才会显示没有更多数据，controller.finishRefresh(IndicatorResult.noMore);不行
我要怎么样才能在首页数据不足的时候底下直接显示没有更多数据不让加载？

**Comment by xuelongqy** [comment]
你刷新的时候没有更多数据。试试调用controller.finishLoad(IndicatorResult.noMore)呢？refresh是header，load是footer

**Comment by xuelongqy** [comment]
controller.finishRefresh后，添加以下
```
WidgetsBinding.instance.addPostFrameCallback((timeStamp) {
  _controller.finishLoad(IndicatorResult.noMore, true);
});
```
