### ISSUE TITLE
macos 触控板无法双指滚动，只能按住拖动

### ISSUE THREAD

**Issue by LuoGuoXin** [xuelongqy/flutter_easyrefresh#777]
如果我用 easyRefresh 包裹一层 listview，在手机端正常，web 端也是正常的。但是我在 macos 端，触控板双指滚动，是没有反应的，你的 demo 我也试过了，也是不正常的。

**Comment by xuelongqy** [comment]
你试试github v3最新的代码呢。之前改过，没发版本，不知道能不能起作用

**Comment by LuoGuoXin** [comment]
> 你试试github v3最新的代码呢。之前改过，没发版本，不知道能不能起作用

easy_refresh: ^3.3.2. 我是用这个版本的，怎么用最新的代码呢？

**Comment by xuelongqy** [comment]
```
easy_refresh:
    git:
      url: git://github.com/xuelongqy/flutter_easy_refresh.git
```

**Comment by LuoGuoXin** [comment]
> ```
> easy_refresh:
>     git:
>       url: git://github.com/xuelongqy/flutter_easy_refresh.git
> ```

我直接用你项目最新代码，跑起来，是可以的。麻烦大佬推一个版本吧，我更新一下。

**Comment by xuelongqy** [comment]
你先暂时这样用吧。我有时间了发个版本，到时候给你留言

**Comment by xuelongqy** [comment]
3.3.2+2已发布

**Comment by Ssiswent** [comment]
最新的发布版本和v3分支的版本都还是存在这个问题哇，请问大佬有办法吗，感谢
