### ISSUE TITLE
alwaysscrollablescrollphysics capable?

### ISSUE THREAD

**Issue by ejlevin1** [xuelongqy/flutter_easyrefresh#778]
I'm running into an issue with getting the easy_refresh to work when the list of items doesn't extend beyond the viewport.  I've fixed this in the past with using alwaysscrollablescrollphysics which then allow for the pull-to-refresh capability.  Is there something similar with the east_refresh package?

**Comment by xuelongqy** [comment]
In east_refresh package you don't need AlwaysScrollableScrollPhysics
