### ISSUE TITLE
AlwaysScrollable?

### ISSUE THREAD

**Issue by ejlevin1** [xuelongqy/flutter_easyrefresh#779]
Is there an example or reference on how to allow EasyRefresh.builder() to enable AlwaysScrollablePhysics?  When the list items don't extend beyond the viewport, I can't drag and expose the heads and footer.

**Comment by xuelongqy** [comment]
You can set the clamping and hitOver parameters of the indicator to achieve the effect.

**Comment by xuelongqy** [comment]
If this problem persists, please reopen
