### ISSUE TITLE
demo 无法运行

### ISSUE THREAD

**Issue by DavidMGT** [xuelongqy/flutter_easyrefresh#78]
ompiler message:
lib/footer/space_footer.dart:48:7: Error: The non-abstract class 'SpaceFooterState' is missing implementations for these members:
 - FlareController.isActive
Try to either
 - provide an implementation,
 - inherit an implementation from a superclass or mixin,
 - mark the class as abstract, or
 - provide a 'noSuchMethod' implementation.

class SpaceFooterState extends RefreshFooterState<SpaceFooter>
      ^^^^^^^^^^^^^^^^
file:///Users/mac/.pub-cache/hosted/pub.flutter-io.cn/flare_flutter-1.5.0/lib/flare_controller.dart:26:23: Context: 'FlareController.isActive' is defined here.
  ValueNotifier<bool> isActive = ValueNotifier<bool>(true);
                      ^^^^^^^^
lib/header/space_header.dart:48:7: Error: The non-abstract class 'SpaceHeaderState' is missing implementations for these members:
 - FlareController.isActive
Try to either
 - provide an implementation,
 - inherit an implementation from a superclass or mixin,
 - mark the class as abstract, or
 - provide a 'noSuchMethod' implementation.

class SpaceHeaderState extends RefreshHeaderState<SpaceHeader>
      ^^^^^^^^^^^^^^^^
file:///Users/mac/.pub-cache/hosted/pub.flutter-io.cn/flare_flutter-1.5.0/lib/flare_controller.dart:26:23: Context: 'FlareController.isActive' is defined here.
  ValueNotifier<bool> isActive = ValueNotifier<bool>(true);
                      ^^^^^^^^
Compiler failed on /Users/mac/flutter_prj/flutter_easyrefresh-master/example/lib/main.dart
Finished with error: Gradle task assembleDebug failed with exit code 1

**Comment by xuelongqy** [comment]
这应该是flare更新导致的

**Comment by tagerjump** [comment]
modifying "implements FlareController" to" with FlareController" in space_header.dart and space_footer.dart will solve this.
深藏功与名

**Comment by zinwalin** [comment]
> modifying "implements FlareController" to" with FlareController" in space_header.dart and space_footer.dart will solve this.
> 深藏功与名

顺颂鲁棒。
