### ISSUE TITLE
TabBarView下拉刷新位置

### ISSUE THREAD

**Issue by smallooo** [xuelongqy/flutter_easyrefresh#780]
下拉刷新位置怎么放在TabBar下面啊？  像NestedScrollView的刷新位置一样。 （ NestedScrollView没有办法左右滑动，苹果手机测试）

**Comment by xuelongqy** [comment]
在Flutter中正常做法做不到，不可兼得。闲鱼做到了，但不清楚具体做法

**Comment by smallooo** [comment]
感谢🙏
