### ISSUE TITLE
listview嵌套gridview时，第一次下拉刷新不回弹

### ISSUE THREAD

**Issue by laterdayi** [xuelongqy/flutter_easyrefresh#783]

**Comment by xuelongqy** [comment]
README第一条，试试看呢？

**Comment by laterdayi** [comment]
![image](https://github.com/xuelongqy/flutter_easy_refresh/assets/122137647/485eda32-5645-41df-8a05-b1e146692b95)

使用这种也会有这个问题，当listview嵌套gridview时

**Comment by laterdayi** [comment]
```
if (controller.flowTypeList.isNotEmpty)
```

那些按钮是经过接口刷新之后返回的

**Comment by xuelongqy** [comment]
你的布局感觉不合理，官方不推荐随意使用shrinkWrap，尝试使用CustomScrollView。基础知识自己尝试哈，issue不负责教学。建议找到确切问题，再提问回复，或者加群交流
