### ISSUE TITLE
GridView进入页面首次自动刷新动画不显示，直到刷新成功才显示回弹动画。 ListView 是正常的

### ISSUE THREAD

**Issue by TrueloveSomeGIRl** [xuelongqy/flutter_easyrefresh#784]
![image](https://github.com/xuelongqy/flutter_easy_refresh/assets/25426589/c11b7fc2-a12e-4a5b-9fb0-3180534cedf1)

**Comment by xuelongqy** [comment]
去掉shrinkWrap？

**Comment by TrueloveSomeGIRl** [comment]
> 去掉shrinkWrap？

可行 解决了 3q
