### ISSUE TITLE
Footer怎样不占用布局

### ISSUE THREAD

**Issue by MyNameIsShort** [xuelongqy/flutter_easyrefresh#786]
能否有属性可以隐藏Footer布局或者设置高度为0，只触发上拉加载

**Comment by xuelongqy** [comment]
你可以试试自定义Footer，设置很小指示器高度和触发高度，组件使用SizedBox。应该可以达到效果，推荐使用无限加载触发距离，在快要到底部的时候即可加载数据

**Comment by xuelongqy** [comment]
如果问题依然存在，请重新开启此issue
