### ISSUE TITLE
refreshOnStart设置为true时首次加载只有动画onRefresh不回调

### ISSUE THREAD

**Issue by Misutesu** [xuelongqy/flutter_easyrefresh#789]
问题：

- `refreshOnStart`设置为`true`时首次加载只有动画`onRefresh`不回调
- 手动刷新时`onRefresh`是正常执行的
- `EasyRefreshController`的`finishRefresh`方法也无法停止首次加载的动画
- 一开始我认为是我自己其他代码影响了框架，但是我已经剔除了几乎所有业务代码问题依旧
- 执行项目`example`中的`refresh_on_start_page.dart`这个界面是没问题的`onRefresh`能正常触发
- Flutter版本是`3.16.5`，easy_refresh版本是`^3.3.3+1`

以下是我的测试代码
```
class MessagePage extends StatefulWidget {
  const MessagePage({super.key});

  @override
  State<MessagePage> createState() => _MessagePageState();
}

class _MessagePageState extends State<MessagePage> {
  late EasyRefreshController _refreshController;

  @override
  void initState() {
    super.initState();
    _refreshController = EasyRefreshController(
      controlFinishRefresh: true,
      controlFinishLoad: true,
    );
  }

  @override
  void dispose() {
    _refreshController.dispose();
    super.dispose();
  }

  @override
  Widget build(BuildContext context) {
    return EasyRefresh(
      controller: _refreshController,
      refreshOnStart: true,
      onRefresh: () async {
        //未执行
        print("on refresh");
        await Future.delayed(const Duration(seconds: 2));
        if (!mounted) {
          return;
        }
        _refreshController.finishRefresh();
        _refreshController.resetFooter();
      },
      child: ListView(children: const [
        Text("123"),
        Text("123"),
        Text("123"),
        Text("123"),
        Text("123"),
        Text("123"),
        Text("123"),
        Text("123"),
        Text("123"),
        Text("123"),
      ]),
    );
  }
}
```

**Comment by xuelongqy** [comment]
这个代码测试没有问题呢

**Comment by Misutesu** [comment]
> 这个代码测试没有问题呢

麻烦试试这个代码能不能复现呢？我这次是在本项目的`example`里运行的

我在`onRefresh`方法里加了一个`Snackbar`打印，这是运行的录屏

现在具体的现象是：

- 初次加载不会回调`onRefresh`
- 初次加载会一直持续直到有上下滑动的触摸事件
- 初次加载持续时下拉会触发`onRefresh`
- 初次加载上拉会直接结束动画不触发`onRefresh`
- 刷新Header设置为`MaterialHeader`不会出现问题

https://github.com/xuelongqy/flutter_easy_refresh/assets/20251580/814ca3e1-c39f-42bd-bfcb-0ee0b832caaa

```
import 'package:easy_refresh/easy_refresh.dart';
import 'package:flutter/material.dart';

main() {
  runApp(const TestPage());
}

class TestPage extends StatefulWidget {
  const TestPage({super.key});

  @override
  State<TestPage> createState() => _TestPageState();
}

class _TestPageState extends State<TestPage> {
  final _scaffoldKey = GlobalKey<ScaffoldState>();
  late EasyRefreshController _refreshController;

  @override
  void initState() {
    super.initState();
    _refreshController = EasyRefreshController(
      controlFinishRefresh: true,
      controlFinishLoad: true,
    );
  }

  @override
  void dispose() {
    _refreshController.dispose();
    super.dispose();
  }

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: Scaffold(
        key: _scaffoldKey,
        body: EasyRefresh(
          controller: _refreshController,
          refreshOnStart: true,
          onRefresh: () async {
            print("on refresh");
            ScaffoldMessenger.of(_scaffoldKey.currentContext!)
                .showSnackBar(const SnackBar(content: Text("On Refresh")));
            await Future.delayed(const Duration(seconds: 2));
            if (!mounted) {
              return;
            }
            _refreshController.finishRefresh();
            _refreshController.resetFooter();
          },
          child: ListView(children: const [
            Text("123"),
            Text("123"),
            Text("123"),
            Text("123"),
            Text("123"),
            Text("123"),
            Text("123"),
            Text("123"),
            Text("123"),
            Text("123"),
          ]),
        ),
      ),
    );
  }
}

```

**Comment by xuelongqy** [comment]
我没用真机测。是不是只有启动App就刷新会出现这种情况？

**Comment by Misutesu** [comment]
不是的，用`Navigator`跳转到有问题的界面也会有这个问题，我用的是雷电模拟器测试的

**Comment by Misutesu** [comment]
刚才我测试了一下，只有雷电模拟器会有这个问题，AS的安卓模拟器和真机是正常的

雷电模拟器是Android9

没问题的真机是小米13Ultra Android14和AS自带的Android14模拟器

我明天再详细测试一下如果只在雷电模拟器上有问题的话那就不用管了

**Comment by PlusWong** [comment]
我这边也发现了这个问题，具体代码如下：
```@override
  Widget build(BuildContext context) {
    return Scaffold(
//设置这个appBar为null，即可复现该问题
      appBar: null,
      body: EasyRefresh(
        refreshOnStart: true,
        onRefresh: () async {
          debugPrint("on refresh");
          await Future.delayed(const Duration(seconds: 2));
        },
        onLoad: () async {
          debugPrint("on load");
          await Future.delayed(const Duration(seconds: 2));
        },
        child: CustomScrollView(
          slivers: [
            SliverList.builder(
                itemCount: 20,
                itemBuilder: (context, index) {
                  return Text("$index");
                })
          ],
        ),
      ),
    );
  }```

**Comment by xuelongqy** [comment]
> 我这边也发现了这个问题，具体代码如下：
> 
> ```
>   Widget build(BuildContext context) {
>     return Scaffold(
> //设置这个appBar为null，即可复现该问题
>       appBar: null,
>       body: EasyRefresh(
>         refreshOnStart: true,
>         onRefresh: () async {
>           debugPrint("on refresh");
>           await Future.delayed(const Duration(seconds: 2));
>         },
>         onLoad: () async {
>           debugPrint("on load");
>           await Future.delayed(const Duration(seconds: 2));
>         },
>         child: CustomScrollView(
>           slivers: [
>             SliverList.builder(
>                 itemCount: 20,
>                 itemBuilder: (context, index) {
>                   return Text("$index");
>                 })
>           ],
>         ),
>       ),
>     );
>   }```
> ```

真机吗？

**Comment by PlusWong** [comment]
> > 我这边也发现了这个问题，具体代码如下：
> > ```
> >   Widget build(BuildContext context) {
> >     return Scaffold(
> > //设置这个appBar为null，即可复现该问题
> >       appBar: null,
> >       body: EasyRefresh(
> >         refreshOnStart: true,
> >         onRefresh: () async {
> >           debugPrint("on refresh");
> >           await Future.delayed(const Duration(seconds: 2));
> >         },
> >         onLoad: () async {
> >           debugPrint("on load");
> >           await Future.delayed(const Duration(seconds: 2));
> >         },
> >         child: CustomScrollView(
> >           slivers: [
> >             SliverList.builder(
> >                 itemCount: 20,
> >                 itemBuilder: (context, index) {
> >                   return Text("$index");
> >                 })
> >           ],
> >         ),
> >       ),
> >     );
> >   }```
> > ```
> 
> 真机吗？

是的，iPhone13、三星S22都会出现

**Comment by saviourdog** [comment]
3.3.2没问题,升级到最新版确实有这个问题

**Comment by xuelongqy** [comment]
可以试试github最新的代码是否修复。我没有复现设备，所以只是理论猜测

**Comment by xuelongqy** [comment]
3.3.4已尝试修复，如还有问题，请重新开启此issue
