### ISSUE TITLE
during refreshing,chang tabview index,Display is abnormal,

### ISSUE THREAD

**Issue by steven-gao** [xuelongqy/flutter_easyrefresh#790]
Flutter :3.13.1
flutter_easy_refresh:^3.3.3+1

please help me!

https://github.com/xuelongqy/flutter_easy_refresh/assets/4360916/94bf9b88-6198-4743-938a-7a9199412038

**Comment by xuelongqy** [comment]
可以试试局部状态更新呢，而不是更新整个页面，setState的作用域。有需要请提供复现案例

**Comment by steven-gao** [comment]
> 可以试试局部状态更新呢，而不是更新整个页面，setState的作用域。有需要请提供复现案例

我的商户数据和交易数据是在一个pageview里面的两个页面。没有刷新整个页面啊，麻烦您能讲下怎么操作才属于整个页面更新呢？

**Comment by steven-gao** [comment]
> 可以试试局部状态更新呢，而不是更新整个页面，setState的作用域。有需要请提供复现案例

复现案例需要我把真实数据全部替换成测试数据，我尽量明天晚上之前发出来。

**Comment by steven-gao** [comment]
这个问题是在pageview 切换页面的时候卡主的。现在我不用它了。所以就没这个问题了。多谢。我先关掉了
