### ISSUE TITLE
ClassicFooter的safeArea属性不起作用

### ISSUE THREAD

**Issue by YaKun-SH** [xuelongqy/flutter_easyrefresh#791]
EasyRefresh.builder的childBuilder是一个ListView，数据量大超过一屏safeArea=true属性没问题，如果数据量小，正好一屏的时候safeArea=true属性就不起作用了，底部安全距离为0，列表最后一条数据就会被BottomNavigationBar遮盖
设备：真机测试，苹果手机

**Comment by xuelongqy** [comment]
你可以试试在用MediaQuery包裹EasyRefresh，手动添加安全距离

**Comment by xuelongqy** [comment]
如不能解决，请提供复现案例

**Comment by xuelongqy** [comment]
如果还有问题，请重新开启此issue
