### ISSUE TITLE
刷新的组件里面存在一个定时器循环滚动组件，影响下拉刷新，下拉的时候下拉刷新不会响应

### ISSUE THREAD

**Issue by AlmostSir777** [xuelongqy/flutter_easyrefresh#794]
![image](https://github.com/xuelongqy/flutter_easy_refresh/assets/16682438/04006958-9fce-4726-be82-c8c342e4bad4)

**Comment by xuelongqy** [comment]
你可以使用EasrRefreshController控制刷新。触发刷新的条件，需要模拟用户对屏幕进行了滑动，所以只是滚动列表不会触发

**Comment by AlmostSir777** [comment]
3q，我用了另外一种方法，当scroll偏移量为负的时候，关闭滚动列表滚动，到时候有问题就用你这终极手段
