### ISSUE TITLE
如何在让一个Container()能下拉刷新？

### ISSUE THREAD

**Issue by SheepYang1993** [xuelongqy/flutter_easyrefresh#795]
想要让一个Container()填满界面，并且能下拉刷新。

看过其他issues，说需要套Scollable才能下拉。

但是如果在Container外面套一层SingleChildScrollView，那Container就不能填满布局了。

**Comment by xuelongqy** [comment]
看样式吧。跟着定义就行，state里面会有指示器的高度

**Comment by SheepYang1993** [comment]
已解决，使用CustomScrollView+SliverFillRemaining
