### ISSUE TITLE
请问如何运行项目？

### ISSUE THREAD

**Issue by ylmyg** [xuelongqy/flutter_easyrefresh#798]
你好，我用我本地的版本gradle，一直提示 
	A problem occurred configuring root project 'android'.
> Could not resolve all files for configuration ':classpath'.
   > Could not download gson-2.8.6.jar (com.google.code.gson:gson:2.8.6)
      > Could not get resource 'https://maven.aliyun.com/repository/public/com/google/code/gson/gson/2.8.6/gson-2.8.6.jar'.
         > Could not HEAD 'https://maven.aliyun.com/repository/public/com/google/code/gson/gson/2.8.6/gson-2.8.6.jar'.
            > Connect to 127.0.0.1:7890 [/127.0.0.1] failed: Connection refused: connect
Exception in thread "main" java.net.ConnectException: Connection refused: connect
不知道如何解决，请问有什么办法能解么

**Comment by xuelongqy** [comment]
老哥，你这明显是网络问题
