### ISSUE TITLE
每次上拉加载结束后总会显示No More

### ISSUE THREAD

**Issue by ppjjzz** [xuelongqy/flutter_easyrefresh#8]
我明明已经往数组里加东西里还是会显示No More。
希望有个属性可以控制要不要显示No More。
希望能提供个属性配置让我上拉加载结束后直接渲染不需要再弹提示

**Comment by xuelongqy** [comment]
请浏览常见问题，也许你能找到答案

**Comment by xuelongqy** [comment]
如果你不需要提示，请自行修改Footer或者使用其他的Footer样式

**Comment by ppjjzz** [comment]
可我用的是ListView.builder啊，也有指定itemCount，还是会出现没有更多的问题

**Comment by xuelongqy** [comment]
你看看常见问题的第四条，如果还有问题，请加QQ群或者等待下一个版本，可以手动控制加载结束
