### ISSUE TITLE
列表被截断

### ISSUE THREAD

**Issue by disburden** [xuelongqy/flutter_easyrefresh#803]
我列表的结构是SingleChildScrollView+Column,然后外面再套一层EasyRefresh
```dart
return SingleChildScrollView(
      child: Column(
        mainAxisSize: MainAxisSize.max ,
        children: <Widget>[
          ...WDList.listMapWithIndex(_redeems, (index, _redeem) {
            return _buildRedeemItem(index, _redeem);
          }),
          Padding(padding: EdgeInsets.only(top: 16.h)),
        ],
      ),
    );
```

然后我发现记录比较少,不满一屏的时候,下拉时列表会被截断,如图
ps:换成ListView就不会有问题,我只是想了解一下这个是什么情况.避免以后踩坑.
![ddd](https://github.com/xuelongqy/flutter_easy_refresh/assets/1391188/03019d35-d051-4b6e-9b9d-4964caac7c5c)

**Comment by xuelongqy** [comment]
首先这不是坑，是基础知识哈。SingleChildScrollView会计算子组件的高度作为真实高度，类似shrinkWrap: true，这会让列表性能下降。如果你非要用SingleChildScrollView，加上clipBehavior: Clip.none，这样就不会截断了

**Comment by disburden** [comment]
刚才试了一下开始以为不行,后来多试了几次才发现原来SingleChildScrollView和EasyRefresh两个组件要同时设置这个属性才有效,谢谢解答!

另外问一下,因为我初学时不断使用Column,遇到需要滚动就习惯性的加个SingleChildScrollView来解决,这种方式是不是比ListView效率低很多,我有很多需要滚动的页面都是这么弄的,是不是要全部换成ListView?
