### ISSUE TITLE
EasyRefresh下拉刷新有延迟

### ISSUE THREAD

**Issue by Zipper-Code** [xuelongqy/flutter_easyrefresh#815]
当我手动下拉刷新时，发现会延迟300左右的毫秒才会执行onRefresh方法，但是动画已经早就开始了，有遇到的朋友吗

**Comment by xuelongqy** [comment]
这是为了适配部分动画，分阶段显示。你可以设置Header的triggerWhenRelease为ture，立马触发刷新
