### ISSUE TITLE
3.3.5 onLoad 无法触发

### ISSUE THREAD

**Issue by M2dL1fe** [xuelongqy/flutter_easyrefresh#818]
![image](https://github.com/xuelongqy/flutter_easy_refresh/assets/8074125/82135efe-b91e-47ff-9f79-9f59bdab8cee)
isMore默认状态是false，即一开始的时候onLoad 是传的null,后面刷新了数据了，给onLoad传递方法，就无法唤起加载更多事件了，回退到3.3.2就没这个问题了

**Comment by M2dL1fe** [comment]
3.3.4 也没此问题，此问题仅在3.3.5出现

**Comment by xuelongqy** [comment]
3.3.5+1已修复
