### ISSUE TITLE
V3版本如何关闭无限刷新

### ISSUE THREAD

**Issue by Marco-Ryus** [xuelongqy/flutter_easyrefresh#819]
请问V3版本如何关闭无限刷新，之前footer中的参数不见了，现在example也无法加载

**Comment by xuelongqy** [comment]
infiniteOffset参数为null关闭。使用3.3.5+1版本

**Comment by Marco-Ryus** [comment]
可以了，非常感谢。另外现在碰到一个问题是需要较快速度滑动才可触发上拉加载的回弹效果，请问大佬知道怎么修改可以让使用者以较慢速度也可触发回弹效果吗

**Comment by xuelongqy** [comment]
可以设置指示器中的滚动和弹簧系数。看看能不能达到你想要的效果
