### ISSUE TITLE
NestedScrollView下多个tabview共享一个ScrollController导致下拉刷新同时执行多个tab页

### ISSUE THREAD

**Issue by xmc123456** [xuelongqy/flutter_easyrefresh#82]

**Comment by daniuwo** [comment]
请问 你在多个TabView之间切换 能保持页面状态吗？如果能怎么实现的

**Comment by xmc123456** [comment]
tabview保持状态
	1.State with AutomaticKeepAliveClientMixin
	2.@override
  	   bool get wantKeepAlive => true;
	3.super.build(context);
	4.super(key: Key("curr_page"));

按官方说的方式添加以上配置，不过在快速间隔切换tab时候还是不能保持页面状态：例如：tab1  tab3  tab2会导致tab2状态丢失刷新了页面

**Comment by elileo1** [comment]
一个tab下列表滚动 其它tab列表也跟着滚动

**Comment by 0-php** [comment]
@elileo1  我也遇到这个问题了

**Comment by zinwalin** [comment]
因为多个tab列表共用同一个controller的原因吧?
