### ISSUE TITLE
最新版本 嵌套CustomScrollView 用Sliver家族 下拉加载到noMore时， noMore文案显示几秒后会消失，重新滑动渲染才会出现

### ISSUE THREAD

**Issue by Jesen-H** [xuelongqy/flutter_easyrefresh#823]
第一张是加载结束，没有更多
https://github.com/xuelongqy/flutter_easy_refresh/assets/34497038/40338473-3955-4bb8-a72d-e44350fb53bf
第二张是等待一会消失的 
https://github.com/xuelongqy/flutter_easy_refresh/assets/34497038/d80d71f7-b2f7-465c-913b-23e292a997ef

**Comment by Jesen-H** [comment]
https://github.com/xuelongqy/flutter_easy_refresh/assets/34497038/d63d5041-3988-409a-8304-c690abb56080

**Comment by xuelongqy** [comment]
可以给一个可以运行的复现案例吗？我目前定位不了问题

**Comment by ShareZore** [comment]
> 可以给一个可以运行的复现案例吗？我目前定位不了问题

随便写个listview， item是一个轮播图，当noMore出现时，滑动轮播图，noMore时隐时现

**Comment by xuelongqy** [comment]
> > 可以给一个可以运行的复现案例吗？我目前定位不了问题
> 
> 随便写个listview， item是一个轮播图，当noMore出现时，滑动轮播图，noMore时隐时现

用EasyRefresh.builder试试呢？

**Comment by ShareZore** [comment]
> > > 可以给一个可以运行的复现案例吗？我目前定位不了问题
> > 
> > 
> > 随便写个listview， item是一个轮播图，当noMore出现时，滑动轮播图，noMore时隐时现
> 
> 用EasyRefresh.builder试试呢？

nice, 完美解决了

**Comment by xuelongqy** [comment]
看起来问题得到了解决
