### ISSUE TITLE
laggy scroll when scroll up only (ios/android)

### ISSUE THREAD

**Issue by heshesh2010** [xuelongqy/flutter_easyrefresh#824]
Hi , 

I'm using easy refresh last version , but I notice that when I scroll down it's smooth and great , but when just try to scroll up again I see my widgets in list view gets some lag and shown again , this behavior only occurs when I applied easy refresh , but other refreshable  plugins was working

**Comment by xuelongqy** [comment]
Please reopen this issue after adding sample code.
