### ISSUE TITLE
使用组件报错Error: A non-null value must be returned since the return type 'Widget' doesn't allow null

### ISSUE THREAD

**Issue by xupengku123** [xuelongqy/flutter_easyrefresh#825]
用的https://gitee.com/openharmony-sig/flutter_flutter 支持鸿蒙的flutter SDK。
接入后使用组件报错。
原因是我是用的flutter SDK的TargetPlatform枚举里多了一个ohos
![image](https://github.com/xuelongqy/flutter_easy_refresh/assets/17425158/283dce5c-dd15-443a-95e4-d9fda5aea3e5)
导致buildScrollbar方法有可能fanh返回空
这里能做个兼容给个默认返回吗

**Comment by xuelongqy** [comment]
你暂时可以自己实现一下ScrollBehavior，然后设置EasyRefresh.defaultScrollBehaviorBuilder。下个版本会做兼容处理

**Comment by xuelongqy** [comment]
3.4.0已修复

**Comment by shihuatao** [comment]
![WeChat96a92c7671ede26a144dcd4afb37077a](https://github.com/user-attachments/assets/8b626899-fd28-4005-aaf8-162a18e216a0)


用的https://gitee.com/openharmony-sig/flutter_flutter 支持鸿蒙的flutter SDK。
