### ISSUE TITLE
Error: The getter 'subtitle1' isn't defined for the class 'TextTheme'

### ISSUE THREAD

**Issue by hasimyerlikaya** [xuelongqy/flutter_easyrefresh#827]
Hi,

I cant build my project after Flutter 3.22.0 update.

This is the error message;

`Error (Xcode): ../../../../../../.pub-cache/hosted/pub.dev/easy_refresh-3.3.5+1/lib/src/styles/classic/classic_indicator.dart:359:66: Error: The getter 'subtitle1' isn't defined for the class 'TextTheme'.`

**Comment by xuelongqy** [comment]
Use 3.4.0
