### ISSUE TITLE
ExtendedNestedScrollView+EasyRefresh 自动刷新无效的问题。

### ISSUE THREAD

**Issue by do-one-thing-to-well** [xuelongqy/flutter_easyrefresh#833]
#### 前言：  
在提这个`Issue`之前我查看了之前小伙伴提及到的`ExtendedNestedScrollView`和本库相关的问题。总结如下：  
1. 如果使用`ExtendedNestedScrollView`+`EasyRefresh`，如何实现自动刷新？
    解答： 应声明一个`ScrollController`，并在`EasyRefresh`内的滑动列表指定该`ScrollController`对象，并在适当时候调用`easyRefreshController.callRefresh(scrollController: scrollController);`可实现自动刷新，经验证，确实可以做到自动刷新。但是这个时候`ExtendedNestedScrollView`已经无法实现嵌套滑动的效果。 [参考该Issue](https://github.com/xuelongqy/flutter_easy_refresh/issues/616#issue-1359722685)

目前我遇到的问题就是使用`ExtendedNestedScrollView`+`EasyRefresh`的时候，无法触发自动刷新，
- 一旦加上`ScrollController`，`ExtendedNestedScrollView`的特性就会消失。
- 如果去掉`ScrollController`，则又无法实现自动刷新。

我试着仅在最外层`ExtendedNestedScrollView`中指定`ScrollController`，调用`easyRefreshController.callRefresh(scrollController: scrollController);`无反应。  

PS: 当然，我也试着在不同位置添加`ScrollController`，还是不行。。。

请问作者，现在是否有合适的解决方案呢？

**Comment by xuelongqy** [comment]
目前涉及到NestedScrollView的问题，都是无解的。

**Comment by do-one-thing-to-well** [comment]
好吧，感谢解答。

**Comment by Rosario9527** [comment]
同样的问题，试了好多，都没有解决，大佬，求解决办法。

**Comment by chikang** [comment]
> 同样的问题，试了好多，都没有解决，大佬，求解决办法。

你解决了吗
