### ISSUE TITLE
Easy Refresh 判断是否正在刷新中的办法

### ISSUE THREAD

**Issue by do-one-thing-to-well** [xuelongqy/flutter_easyrefresh#834]
我使用了`refreshController.headerState?.mode==IndicatorMode.done`来判断是否正在刷新中，但是通过验证感觉方式不正确，我在Demo中没有找到相关的判断方式，请问正确的判断是否正在刷新中的方法是？

**Comment by xuelongqy** [comment]
每个状态的作用，在这里有详细的描述。[https://pub.dev/documentation/easy_refresh/latest/easy_refresh/IndicatorMode.html](https://pub.dev/documentation/easy_refresh/latest/easy_refresh/IndicatorMode.html)
