### ISSUE TITLE
当列表内容不铺满整个屏幕时，footer没有在内容的下方展示，而是要向下拖拽一下才看到

### ISSUE THREAD

**Issue by wubaibin** [xuelongqy/flutter_easyrefresh#840]
<img width="476" alt="image" src="https://github.com/xuelongqy/flutter_easy_refresh/assets/30898947/68fa966d-5157-43a7-81bf-f5a472d66929">
<img width="486" alt="image" src="https://github.com/xuelongqy/flutter_easy_refresh/assets/30898947/fc370203-4c99-42c0-9aba-3cfefd2dcadf">

**Comment by xuelongqy** [comment]
使用IndicatorPosition.locator、infiniteOffset不为null即可
```dart
const ClassicFooter(
  position: IndicatorPosition.locator,
  infiniteOffset: 10,
)
```
```
child: CustomScrollView(
  slivers: [
    SliverList(...),
    const FooterLocator.sliver(),
  ],
)
```

**Comment by wubaibin** [comment]
设置了position: IndicatorPosition.locator和infiniteOffset: 10 完全不展示了

**Comment by Ziven-n** [comment]
> 设置了position: IndicatorPosition.locator和infiniteOffset: 10 完全不展示了

有解决方案吗
