### ISSUE TITLE
有没有大佬能做一个与 `flutter_riverpod` 集成的插件，把 `refreshController` 集成到 `riverpod` 里

### ISSUE THREAD

**Issue by Pluto1219** [xuelongqy/flutter_easyrefresh#841]
有没有大佬能做一个与 `flutter_riverpod` 集成的插件，把 `refreshController` 集成到 `riverpod` 里，从而更方便地控制 `controller`。比如可以通过 `provider.refreshController.callRefresh()` 来调用刷新功能。

**Comment by xuelongqy** [comment]
请自行实验，举一反三

**Comment by Pluto1219** [comment]
> 请自行实验，举一反三

你说得对，从 easy_refresh 推出时我就开始用了。如今 riverpod 越来越流行，如果 easy_refresh 能提供一个集成 riverpod 的示例，那么它无疑会成为首选的下拉刷新控件，超越 custom_refresh_indicator 指日可待。我希望 easy_refresh 能成为 pub.dev 上下拉刷新的第一选择。
@xuelongqy

**Comment by xuelongqy** [comment]
这个后续将考虑在EasyPaging上集成
