### ISSUE TITLE
/easy_refresh/lib/src/behavior/scroll_behavior.dart  ，这个方法建议添加一个默认值，不然跑纯血鸿蒙，会报错，因为没有case TargetPlatform.ohos:的判断

### ISSUE THREAD

**Issue by xiongzhaoxu** [xuelongqy/flutter_easyrefresh#842]
/easy_refresh/lib/src/behavior/scroll_behavior.dart  ，这个方法建议添加一个默认值，不然跑纯血鸿蒙，会报错，因为没有case TargetPlatform.ohos:的判断

`
@override
  Widget buildScrollbar(
      BuildContext context, Widget child, ScrollableDetails details) {
    switch (getPlatform(context)) {
      case TargetPlatform.linux:
      case TargetPlatform.macOS:
      case TargetPlatform.windows:
        assert(details.controller != null);
        return Scrollbar(
          controller: details.controller,
          child: child,
        );
      case TargetPlatform.android:
      case TargetPlatform.fuchsia:
      case TargetPlatform.iOS:
        return child;
    }
  }

`

`  
@override
  Widget buildScrollbar(
      BuildContext context, Widget child, ScrollableDetails details) {
    switch (getPlatform(context)) {
      case TargetPlatform.linux:
      case TargetPlatform.macOS:
      case TargetPlatform.windows:
        assert(details.controller != null);
        return Scrollbar(
          controller: details.controller,
          child: child,
        );
      case TargetPlatform.android:
      case TargetPlatform.fuchsia:
      case TargetPlatform.iOS:
        return child;
    }
    // 添加一个默认返回值，以确保所有可能情况都返回一个 Widget。
    return child;
  }

`

还有还有，就是这个问题了啦：https://github.com/xuelongqy/flutter_easy_refresh/issues/832

希望大佬的空帮更新一波

**Comment by xuelongqy** [comment]
默认不再支持Flutter3.7哈。请查看之前的issue，有相关方法。等后面鸿蒙Flutter那边版本提升后，就支持了

**Comment by xiongzhaoxu** [comment]
> 默认不再支持Flutter3.7哈。请查看之前的issue，有相关方法。等后面鸿蒙Flutter那边版本提升后，就支持了

好的，好的

**Comment by xuelongqy** [comment]
ScrollBehavior可以自己实现，然后设置默认的ScrollBehavior。尽量复制原有代码或者继承覆盖方法进行修改

**Comment by xiongzhaoxu** [comment]
> ScrollBehavior可以自己实现，然后设置默认的ScrollBehavior。尽量复制原有代码或者继承覆盖方法进行修改

目前使用源码修改添加的ohos的判断已经可以满足项目需求了，期待后面的鸿蒙升级了，感谢大佬回复
