### ISSUE TITLE
ListView里面套ListView，手动执行 refreshController.callRefresh() 失效 

### ISSUE THREAD

**Issue by M2dL1fe** [xuelongqy/flutter_easyrefresh#844]
里面的ListView足够长的时候，ios和android都有此问题，去掉里面的ListView就没此问题

https://github.com/xuelongqy/flutter_easy_refresh/assets/8074125/46ae40c0-fab3-4515-b596-298536a1784c

**Comment by M2dL1fe** [comment]
可以明显的看到，下拉刷新的那个 圈 ，没有跑到位，就回去了
下面是里面包的 ListView
![image](https://github.com/xuelongqy/flutter_easy_refresh/assets/8074125/6a6a4743-c1d8-4394-94d7-f548c1563bbc)

**Comment by xuelongqy** [comment]
README第一条，作用域问题

**Comment by M2dL1fe** [comment]
下拉刷新的列表是 通过 EasyRefresh.builder 构造 ，使用了里面的 physics
