### ISSUE TITLE
demo中的TabBarVIew事例，使用controller控制foot的状态

### ISSUE THREAD

**Issue by KaiLiDev** [xuelongqy/flutter_easyrefresh#850]
demo中的TabBarVIew事例，如果使用controller控制foot的状态，只能自己根据切换的tab去单独维护吗？所有的Tabbar是公用一个Footer吗？

**Comment by xuelongqy** [comment]
我觉得这个在你使用的时候，特别是代码上的Widget层级关系就能够知道具体的原理，本身是一个EasyRefresh去控制的，所以不会有多个footer。如果需要区分开，每个列表单独使用EasyRefresh。如果你想用一个Header就建议使用TabBarVIew事例的方式，用controller去主动控制，切换的时候打断既可

**Comment by KaiLiDev** [comment]
好的 感谢大佬
