### ISSUE TITLE
如何调整footer的高度

### ISSUE THREAD

**Issue by islinjj** [xuelongqy/flutter_easyrefresh#858]

**Comment by islinjj** [comment]
是取消了footer 的padding属性了吗 https://github.com/xuelongqy/flutter_easy_refresh/issues/332

**Comment by xuelongqy** [comment]
目前是自带安全区域，调整高度请看footer参数。如未解决问题，请提供复现案例后重开此issue

**Comment by jiakh9465** [comment]
safeArea: false,
 ListView.builder(
                                physics: scrollPhysics,
                                padding: EdgeInsets.zero, //ListView默认底部有padding，取消掉
                                itemCount: controller.list.length,
