### ISSUE TITLE
easyrefresh嵌套NestedScrollView时为了实现同时能下拉刷新和吸顶效果导致运行崩溃

### ISSUE THREAD

**Issue by ahtrun** [xuelongqy/flutter_easyrefresh#87]
一直提示The following assertion was thrown during performResize():
Vertical viewport was given unbounded height.
Viewports expand in the scrolling direction to fill their container.In this case, a vertical
viewport was given an unlimited amount of vertical space in which to expand. This situation
typically happens when a scrollable widget is nested inside another scrollable widget.
If this widget is always nested in a scrollable widget there is no need to use a viewport because
there will always be enough vertical space for the children. In this case, consider using a Column
instead. Otherwise, consider using the "shrinkWrap" property (or a ShrinkWrappingViewport) to size
the height of the viewport to the sum of the heights of its children.
以上错误，当把easyrefresh换成RefreshIndicator之后又一切正常了，请问到底哪里有问题？

**Comment by rainedAllNight** [comment]
我是Column中使用EasyRefresh也报了同样的错误.

```
 return Column(
              children: <Widget>[
                Expanded(
                    child: EasyRefresh(
                      key: _easyRefreshKey,
                      child: HomeListView(shapshot.data),
                      onRefresh: () async {
                        bloc.fetchHomeData();
                      }),
                    flex: 6),
                Expanded(child: HomeBottomBar(), flex: 1)
              ],
            );
```

**Comment by ushang000** [comment]
把ListView.builder用Expanded包裹起来，就好了，我遇到的问题是不报错，但刷新跟NestedScrollView有冲突，滑动顶部不隐藏了

**Comment by zhouxianjun** [comment]
请教一下，如何把NestedScrollView与EasyRefresh关联在一起？
EasyRefresh作为NestedScrollView的SliverAppBar中的flexibleSpace（需要下拉刷新功能）。
然后NestedScrollView的body为listview，在NestedScrollView下拉到顶部的时候，怎么触发EasyRefresh的下拉效果？
@ahtrun @xuelongqy

**Comment by cqtangrenjie** [comment]
> 把ListView.builder用Expanded包裹起来，就好了，我遇到的问题是不报错，但刷新跟NestedScrollView有冲突，滑动顶部不隐藏了

我目前是嵌套后 listview顶部有个20的padding， 根据 注释说明，使用MediaQuery 这个来嵌套，然后就出现这个错误了，添加Expanded 也是报这个错

**Comment by Airoyee** [comment]
大佬怎么解决的，我现在是EasyRefresh 2.0.0 嵌套NestscrollView，里面有一个吸顶想过的tabbar和tabbarView，在最外层嵌套之后直接崩溃@zhouxianjun

**Comment by huangying1111** [comment]
> 把ListView.builder用Expanded包裹起来，就好了，我遇到的问题是不报错，但刷新跟NestedScrollView有冲突，滑动顶部不隐藏了

请问解决这个问题了吗 我也遇到了

**Comment by peakerWu** [comment]
> 大佬怎么解决的，我现在是EasyRefresh 2.0.0 嵌套NestscrollView，里面有一个吸顶想过的tabbar和tabbarView，在最外层嵌套之后直接崩溃@zhouxianjun

你的有解决吗？我也是 EasyRefresh 嵌套NestscrollView 一直报错

**Comment by xuelongqy** [comment]
> > 大佬怎么解决的，我现在是EasyRefresh 2.0.0 嵌套NestscrollView，里面有一个吸顶想过的tabbar和tabbarView，在最外层嵌套之后直接崩溃@zhouxianjun
> 
> 你的有解决吗？我也是 EasyRefresh 嵌套NestscrollView 一直报错

请参考示例

**Comment by peakerWu** [comment]
> > > 大佬怎么解决的，我现在是EasyRefresh 2.0.0 嵌套NestscrollView，里面有一个吸顶想过的tabbar和tabbarView，在最外层嵌套之后直接崩溃@zhouxianjun
> > 
> > 
> > 你的有解决吗？我也是 EasyRefresh 嵌套NestscrollView 一直报错
> 
> 请参考示例

下面是我原来的结构，
nestscrollview 
     tabbar
     tabbarview
          easyrefresh
