### ISSUE TITLE
flutter 3.24.5 ：_ClassicIndicatorState#1d0ad(tickers: tracking 1 ticker) was disposed with an active Ticker.

### ISSUE THREAD

**Issue by yanmingLiu** [xuelongqy/flutter_easyrefresh#877]
easy_refresh: ^3.4.0

Flutter 3.24.5 • channel stable • https://github.com/flutter/flutter.git
Framework • revision dec2ee5c1f (3 weeks ago) • 2024-11-13 11:13:06 -0800
Engine • revision a18df97ca5
Tools • Dart 3.5.4 • DevTools 2.37.3

错误日志：

════════ Exception caught by widgets library ═══════════════════════════════════
The following assertion was thrown while finalizing the widget tree:
_ClassicIndicatorState#1d0ad(tickers: tracking 1 ticker) was disposed with an active Ticker.
_ClassicIndicatorState created a Ticker via its TickerProviderStateMixin, but at the time dispose() was called on the mixin, that Ticker was still active. All Tickers must be disposed before calling super.dispose().
Tickers used by AnimationControllers should be disposed by calling dispose() on the AnimationController itself. Otherwise, the ticker will leak.
The offending ticker was: _WidgetTicker(created by _ClassicIndicatorState#1d0ad)
The stack trace when the _WidgetTicker was actually created was:
#0      new Ticker.<anonymous closure> (package:flutter/src/scheduler/ticker.dart:74:40)
ticker.dart:74
#1      new Ticker (package:flutter/src/scheduler/ticker.dart:76:6)
ticker.dart:76
#2      new _WidgetTicker (package:flutter/src/widgets/ticker_provider.dart)
#3      TickerProviderStateMixin.createTicker (package:flutter/src/widgets/ticker_provider.dart:291:34)
ticker_provider.dart:291
#4      new AnimationController (package:flutter/src/animation/animation_controller.dart:267:21)
animation_controller.dart:267
#5      _ClassicIndicatorState.initState (package:easy_refresh/src/styles/classic/classic_indicator.dart:195:32)
classic_indicator.dart:195
#6      StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:5748:55)
framework.dart:5748
#7      ComponentElement.mount (package:flutter/src/widgets/framework.dart:5593:5)
framework.dart:5593

**Comment by KiddoV** [comment]
I have the same error when using `EasyRefresh `in a `TabBarView`.
@yanmingLiu you closed the issue. How did you revolved this?
