### ISSUE TITLE
与fish_redux结合，loadmore更多数据后，listview自动滚到顶部。

### ISSUE THREAD

**Issue by juggist** [xuelongqy/flutter_easyrefresh#89]
首先感谢作者开源了这么一个大家常用的刷新库。
下面是我使用easyrefresh + listview +fish_redux 出现的一个问题。
1.只使用easyrefresh+listview，都是理想的效果。如果再加入fish_redux，使用loadMore,数据是正常的。就是listview的显示出现问题了（正常情况应该是lsitview滑动状态不动，listview后面自动添加新的item），listview会自动滚到顶部，就好像重置了数据源一样。
2.只使用fish_redux+listview，通过按钮手动新增数据，数据正常的，listview的显示也是正常的。

麻烦作者帮忙看下，谢谢了。

**Comment by MMMzq** [comment]
> 首先感谢作者开源了这么一个大家常用的刷新库。
> 下面是我使用easyrefresh + listview +fish_redux 出现的一个问题。
> 1.只使用easyrefresh+listview，都是理想的效果。如果再加入fish_redux，使用loadMore,数据是正常的。就是listview的显示出现问题了（正常情况应该是lsitview滑动状态不动，listview后面自动添加新的item），listview会自动滚到顶部，就好像重置了数据源一样。
> 2.只使用fish_redux+listview，通过按钮手动新增数据，数据正常的，listview的显示也是正常的。
> 
> 麻烦作者帮忙看下，谢谢了。
请检查controller是不是每次都是用了新的controller

**Comment by juggist** [comment]
> > 首先感谢作者开源了这么一个大家常用的刷新库。
> > 下面是我使用easyrefresh + listview +fish_redux 出现的一个问题。
> > 1.只使用easyrefresh+listview，都是理想的效果。如果再加入fish_redux，使用loadMore,数据是正常的。就是listview的显示出现问题了（正常情况应该是lsitview滑动状态不动，listview后面自动添加新的item），listview会自动滚到顶部，就好像重置了数据源一样。
> > 2.只使用fish_redux+listview，通过按钮手动新增数据，数据正常的，listview的显示也是正常的。
> > 麻烦作者帮忙看下，谢谢了。
> 
> 请检查controller是不是每次都是用了新的controller

没有更新controller。单纯的新增数据，也会导致listview立刻恢复到顶部，没有回滚到顶部的动画。

**Comment by MMMzq** [comment]
> > > 首先感谢作者开源了这么一个大家常用的刷新库。
> > > 下面是我使用easyrefresh + listview +fish_redux 出现的一个问题。
> > > 1.只使用easyrefresh+listview，都是理想的效果。如果再加入fish_redux，使用loadMore,数据是正常的。就是listview的显示出现问题了（正常情况应该是lsitview滑动状态不动，listview后面自动添加新的item），listview会自动滚到顶部，就好像重置了数据源一样。
> > > 2.只使用fish_redux+listview，通过按钮手动新增数据，数据正常的，listview的显示也是正常的。
> > > 麻烦作者帮忙看下，谢谢了。
> > 
> > 
> > 请检查controller是不是每次都是用了新的controller
> 
> 没有更新controller。单纯的新增数据，也会导致listview立刻恢复到顶部，没有回滚到顶部的动画。

你看看你的controller new的过程是不是再buildView里写的

**Comment by juggist** [comment]
> > > > 首先感谢作者开源了这么一个大家常用的刷新库。
> > > > 下面是我使用easyrefresh + listview +fish_redux 出现的一个问题。
> > > > 1.只使用easyrefresh+listview，都是理想的效果。如果再加入fish_redux，使用loadMore,数据是正常的。就是listview的显示出现问题了（正常情况应该是lsitview滑动状态不动，listview后面自动添加新的item），listview会自动滚到顶部，就好像重置了数据源一样。
> > > > 2.只使用fish_redux+listview，通过按钮手动新增数据，数据正常的，listview的显示也是正常的。
> > > > 麻烦作者帮忙看下，谢谢了。
> > > 
> > > 
> > > 请检查controller是不是每次都是用了新的controller
> > 
> > 
> > 没有更新controller。单纯的新增数据，也会导致listview立刻恢复到顶部，没有回滚到顶部的动画。
> 
> 你看看你的controller new的过程是不是再buildView里写的

很抱歉，又过了好久才回复你。
我实在不确定哪里出了问题。
能不能麻烦你抽空用fish-redux，easyrefresh写一份上拉加载更多的demo，非常感谢你。

**Comment by cqtangrenjie** [comment]
> > > > > 首先感谢作者开源了这么一个大家常用的刷新库。
> > > > > 下面是我使用easyrefresh + listview +fish_redux 出现的一个问题。
> > > > > 1.只使用easyrefresh+listview，都是理想的效果。如果再加入fish_redux，使用loadMore,数据是正常的。就是listview的显示出现问题了（正常情况应该是lsitview滑动状态不动，listview后面自动添加新的item），listview会自动滚到顶部，就好像重置了数据源一样。
> > > > > 2.只使用fish_redux+listview，通过按钮手动新增数据，数据正常的，listview的显示也是正常的。
> > > > > 麻烦作者帮忙看下，谢谢了。
> > > > 
> > > > 
> > > > 请检查controller是不是每次都是用了新的controller
> > > 
> > > 
> > > 没有更新controller。单纯的新增数据，也会导致listview立刻恢复到顶部，没有回滚到顶部的动画。
> > 
> > 
> > 你看看你的controller new的过程是不是再buildView里写的
> 
> 很抱歉，又过了好久才回复你。
> 我实在不确定哪里出了问题。
> 能不能麻烦你抽空用fish-redux，easyrefresh写一份上拉加载更多的demo，非常感谢你。

我是用的easyrefresh + gridview +fish_redux  倒是没出现你说的问题

**Comment by xuelongqy** [comment]
v2已重构
