### ISSUE TITLE
Flare Animation

### ISSUE THREAD

**Issue by taliptako** [xuelongqy/flutter_easyrefresh#9]
Can we make refresh animations work with Flare ?
Like in this example
https://github.com/2d-inc/Flare-Flutter/tree/master/example/space_reload

**Comment by xuelongqy** [comment]
Yes, you can refer to the EasyRefresh documentation. [Custom Header and Footer](https://github.com/xuelongqy/flutter_easyrefresh/blob/master/art/md/en/CUSTOM_HEADER_FOOTER.md)

**Comment by xuelongqy** [comment]
But I am very interested, I am willing to give it a try.

**Comment by xuelongqy** [comment]
Already done, you can refer to the example. [SpacePage](https://github.com/xuelongqy/flutter_easyrefresh/blob/master/example/lib/page/style/space_page.dart)

**Comment by taliptako** [comment]
Wow thats amazing! Thank you.
