### ISSUE TITLE
下拉刷新，上拉加载功能有的时候失效，往上往下都手势都没反应

### ISSUE THREAD

**Issue by a272312970** [xuelongqy/flutter_easyrefresh#91]
我现在用的是TabBarView，然后每个widget的state with AutomaticKeepAliveClientMixin的方式做的，但是有概率出现下拉刷新和上拉加载功能失效的情况，我使用的机型是小米6X，查看源码发现能不能下拉刷新或者上拉加载是由_isRefresh控制的，为true则return，每次下拉刷新或者上拉加载完成闲置状态的时候把值都赋为false，但是我打log发现有的时候下拉刷新完值并没有置为false，才导致上述问题的出现

**Comment by xmc123456** [comment]
我也出现过类似情况，偶现列表卡死不仅不能下拉刷新，连滚动都不能滚动（小米mix），希望作者帮看一下哈

**Comment by flappygod** [comment]
同样的情况，跟进源码调试发现_scrollPhysics此时一直为_neverScrollableScrollPhysics，所以无法上拉下拉了，苹果IOS。

**Comment by diaotongt** [comment]
我写的东西以及demo有时候也会出现这个问题。

**Comment by xuelongqy** [comment]
v2已重构
