### ISSUE TITLE
加载更多的时候为什么每次都会出现没有更多数据 

### ISSUE THREAD

**Issue by huangqiang325** [xuelongqy/flutter_easyrefresh#92]
我是在loadMore里去请求数据   然后请求到了数据setState   为什么每次都会出现没有更多数据(什么时候会触发没有更多数据）  还有就是能不能像安卓原生的smartRefresh一样 主动去取消加载更多的状态

**Comment by xuelongqy** [comment]
这个问题，请参考常见问题
