### ISSUE TITLE
error

### ISSUE THREAD

**Issue by sunguotao** [xuelongqy/flutter_easyrefresh#95]
1023:18: Error: The argument type 'Int32List' can't be assigned to the parameter type 'Uint16List'.
 - 'Int32List' is from 'dart:typed_data'.
 - 'Uint16List' is from 'dart:typed_data'.
Try changing the type of the parameter, or casting the argument to 'Uint16List'.
        indices: _indices, textureCoordinates: _uvBuffer);
                 ^
Compiler failed on /Users/sunguotao/Desktop/FlutterPro/flutter_easyrefresh/example/lib/main.dart

FAILURE: Build failed with an exception.

* Where:
Script '/Users/sunguotao/Desktop/AndroidDev/flutter/packages/flutter_tools/gradle/flutter.gradle' line: 648

* What went wrong:
Execution failed for task ':app:compileflutterBuildDebugandroid-arm64'.
> Process 'command '/Users/sunguotao/Desktop/AndroidDev/flutter/bin/flutter'' finished with non-zero exit value 1

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 10s
Finished with error: Gradle task assembleDebug failed with exit code 1

**Comment by xuelongqy** [comment]
V2 has been refactored
